apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream-install.yaml
  - system-resources.yaml
patches:
  - path: patches/namespace.yaml
    target:
      group: ""
      version: v1
      kind: Namespace
      name: astronomer-delivery-system
  - path: patches/source-controller.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: source-controller
  - path: patches/kustomize-controller.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: kustomize-controller
  - path: patches/helm-controller.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: helm-controller
  - path: patches/crd-controller-role.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: crd-controller-astronomer-delivery-system
  - path: patches/crd-controller-binding.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: crd-controller-astronomer-delivery-system
  - path: patches/delete-allow-egress.yaml
  - path: patches/delete-allow-scraping.yaml
  - path: patches/delete-allow-webhooks.yaml
  - path: patches/delete-flux-edit.yaml
  - path: patches/delete-flux-view.yaml
  - path: patches/delete-critical-pods-quota.yaml
images:
  - name: ghcr.io/fluxcd/source-controller
    digest: sha256:6a6693172589f8ff26123a231d5fa6ceb194a6efb4dc647cdf057c959f76a2e3
  - name: ghcr.io/fluxcd/kustomize-controller
    digest: sha256:2ebeaa341da77d52b6abbbba5efcee0450d47f8b42f0e6f33b08f9020262d606
  - name: ghcr.io/fluxcd/helm-controller
    digest: sha256:0d52fff5c4d476277b8fcb6beb9041e269adb5db943fe69f5a806ea0c92b1511
