// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anomaly_baselines.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAnomalyBaselines = `-- name: CountAnomalyBaselines :one
SELECT count(*) FROM anomaly_baselines
`

func (q *Queries) CountAnomalyBaselines(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAnomalyBaselines)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnomalyBaseline = `-- name: GetAnomalyBaseline :one
SELECT id, cluster_id, metric_name, window_seconds, sample_count, mean, stddev,
       min_value, max_value, p50, p95, p99, last_value, last_value_at,
       recent_samples, updated_at
FROM anomaly_baselines
WHERE cluster_id = $1 AND metric_name = $2 AND window_seconds = $3
`

type GetAnomalyBaselineParams struct {
	ClusterID     uuid.UUID `json:"cluster_id"`
	MetricName    string    `json:"metric_name"`
	WindowSeconds int32     `json:"window_seconds"`
}

func (q *Queries) GetAnomalyBaseline(ctx context.Context, arg GetAnomalyBaselineParams) (AnomalyBaseline, error) {
	row := q.db.QueryRow(ctx, getAnomalyBaseline, arg.ClusterID, arg.MetricName, arg.WindowSeconds)
	var i AnomalyBaseline
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.MetricName,
		&i.WindowSeconds,
		&i.SampleCount,
		&i.Mean,
		&i.Stddev,
		&i.MinValue,
		&i.MaxValue,
		&i.P50,
		&i.P95,
		&i.P99,
		&i.LastValue,
		&i.LastValueAt,
		&i.RecentSamples,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnomalyBaselineByID = `-- name: GetAnomalyBaselineByID :one
SELECT id, cluster_id, metric_name, window_seconds, sample_count, mean, stddev,
       min_value, max_value, p50, p95, p99, last_value, last_value_at,
       recent_samples, updated_at
FROM anomaly_baselines
WHERE id = $1
`

func (q *Queries) GetAnomalyBaselineByID(ctx context.Context, id uuid.UUID) (AnomalyBaseline, error) {
	row := q.db.QueryRow(ctx, getAnomalyBaselineByID, id)
	var i AnomalyBaseline
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.MetricName,
		&i.WindowSeconds,
		&i.SampleCount,
		&i.Mean,
		&i.Stddev,
		&i.MinValue,
		&i.MaxValue,
		&i.P50,
		&i.P95,
		&i.P99,
		&i.LastValue,
		&i.LastValueAt,
		&i.RecentSamples,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnomalyBaselines = `-- name: ListAnomalyBaselines :many

SELECT id, cluster_id, metric_name, window_seconds, sample_count, mean, stddev,
       min_value, max_value, p50, p95, p99, last_value, last_value_at,
       recent_samples, updated_at
FROM anomaly_baselines
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListAnomalyBaselinesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Migration 072 — rolling-window baselines for "deviation from
// baseline" alert rules. Queries here are mirrored in the
// hand-authored shim at internal/db/sqlc/anomaly_baselines_ext.sql.go
// so the build keeps passing on agent worktrees where the sqlc CLI
// is occasionally not available.
func (q *Queries) ListAnomalyBaselines(ctx context.Context, arg ListAnomalyBaselinesParams) ([]AnomalyBaseline, error) {
	rows, err := q.db.Query(ctx, listAnomalyBaselines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnomalyBaseline{}
	for rows.Next() {
		var i AnomalyBaseline
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.MetricName,
			&i.WindowSeconds,
			&i.SampleCount,
			&i.Mean,
			&i.Stddev,
			&i.MinValue,
			&i.MaxValue,
			&i.P50,
			&i.P95,
			&i.P99,
			&i.LastValue,
			&i.LastValueAt,
			&i.RecentSamples,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnomalyBaselinesByCluster = `-- name: ListAnomalyBaselinesByCluster :many
SELECT id, cluster_id, metric_name, window_seconds, sample_count, mean, stddev,
       min_value, max_value, p50, p95, p99, last_value, last_value_at,
       recent_samples, updated_at
FROM anomaly_baselines
WHERE cluster_id = $1
ORDER BY metric_name ASC
`

func (q *Queries) ListAnomalyBaselinesByCluster(ctx context.Context, clusterID uuid.UUID) ([]AnomalyBaseline, error) {
	rows, err := q.db.Query(ctx, listAnomalyBaselinesByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnomalyBaseline{}
	for rows.Next() {
		var i AnomalyBaseline
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.MetricName,
			&i.WindowSeconds,
			&i.SampleCount,
			&i.Mean,
			&i.Stddev,
			&i.MinValue,
			&i.MaxValue,
			&i.P50,
			&i.P95,
			&i.P99,
			&i.LastValue,
			&i.LastValueAt,
			&i.RecentSamples,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnomalyBaseline = `-- name: UpsertAnomalyBaseline :one
INSERT INTO anomaly_baselines (
    cluster_id, metric_name, window_seconds, sample_count, mean, stddev,
    min_value, max_value, p50, p95, p99, last_value, last_value_at,
    recent_samples, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, now()
)
ON CONFLICT (cluster_id, metric_name, window_seconds) DO UPDATE SET
    sample_count   = EXCLUDED.sample_count,
    mean           = EXCLUDED.mean,
    stddev         = EXCLUDED.stddev,
    min_value      = EXCLUDED.min_value,
    max_value      = EXCLUDED.max_value,
    p50            = EXCLUDED.p50,
    p95            = EXCLUDED.p95,
    p99            = EXCLUDED.p99,
    last_value     = EXCLUDED.last_value,
    last_value_at  = EXCLUDED.last_value_at,
    recent_samples = EXCLUDED.recent_samples,
    updated_at     = now()
RETURNING id, cluster_id, metric_name, window_seconds, sample_count, mean, stddev,
          min_value, max_value, p50, p95, p99, last_value, last_value_at,
          recent_samples, updated_at
`

type UpsertAnomalyBaselineParams struct {
	ClusterID     uuid.UUID          `json:"cluster_id"`
	MetricName    string             `json:"metric_name"`
	WindowSeconds int32              `json:"window_seconds"`
	SampleCount   int32              `json:"sample_count"`
	Mean          float64            `json:"mean"`
	Stddev        float64            `json:"stddev"`
	MinValue      float64            `json:"min_value"`
	MaxValue      float64            `json:"max_value"`
	P50           float64            `json:"p50"`
	P95           float64            `json:"p95"`
	P99           float64            `json:"p99"`
	LastValue     float64            `json:"last_value"`
	LastValueAt   pgtype.Timestamptz `json:"last_value_at"`
	RecentSamples json.RawMessage    `json:"recent_samples"`
}

func (q *Queries) UpsertAnomalyBaseline(ctx context.Context, arg UpsertAnomalyBaselineParams) (AnomalyBaseline, error) {
	row := q.db.QueryRow(ctx, upsertAnomalyBaseline,
		arg.ClusterID,
		arg.MetricName,
		arg.WindowSeconds,
		arg.SampleCount,
		arg.Mean,
		arg.Stddev,
		arg.MinValue,
		arg.MaxValue,
		arg.P50,
		arg.P95,
		arg.P99,
		arg.LastValue,
		arg.LastValueAt,
		arg.RecentSamples,
	)
	var i AnomalyBaseline
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.MetricName,
		&i.WindowSeconds,
		&i.SampleCount,
		&i.Mean,
		&i.Stddev,
		&i.MinValue,
		&i.MaxValue,
		&i.P50,
		&i.P95,
		&i.P99,
		&i.LastValue,
		&i.LastValueAt,
		&i.RecentSamples,
		&i.UpdatedAt,
	)
	return i, err
}
