// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apiserver_allowlists.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteApiserverAllowlistSnapshotsOlderThan = `-- name: DeleteApiserverAllowlistSnapshotsOlderThan :exec
DELETE FROM apiserver_allowlist_snapshots
WHERE captured_at < $1
`

// 90-day retention sweep — drop rows older than the given cutoff.
func (q *Queries) DeleteApiserverAllowlistSnapshotsOlderThan(ctx context.Context, capturedAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteApiserverAllowlistSnapshotsOlderThan, capturedAt)
	return err
}

const getApiserverAllowlistByClusterID = `-- name: GetApiserverAllowlistByClusterID :one

SELECT cluster_id, cidrs, mode, detected_provider, last_reconciled_at,
       sync_status, last_error, effective_cidrs, created_at, updated_at
FROM apiserver_allowlists
WHERE cluster_id = $1
`

// Apiserver allow-list CRUD (migration 070).
//
// Hand-edited SQL for the apiserver_allowlists + apiserver_allowlist_
// snapshots tables. The sqlc generator produces a thin Go shim with
// type-safe arguments around these queries.
func (q *Queries) GetApiserverAllowlistByClusterID(ctx context.Context, clusterID uuid.UUID) (ApiserverAllowlist, error) {
	row := q.db.QueryRow(ctx, getApiserverAllowlistByClusterID, clusterID)
	var i ApiserverAllowlist
	err := row.Scan(
		&i.ClusterID,
		&i.Cidrs,
		&i.Mode,
		&i.DetectedProvider,
		&i.LastReconciledAt,
		&i.SyncStatus,
		&i.LastError,
		&i.EffectiveCidrs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertApiserverAllowlistSnapshot = `-- name: InsertApiserverAllowlistSnapshot :one

INSERT INTO apiserver_allowlist_snapshots (
    cluster_id, effective_cidrs, desired_cidrs, drift
) VALUES ($1, $2, $3, $4)
RETURNING id, cluster_id, captured_at, effective_cidrs, desired_cidrs, drift
`

type InsertApiserverAllowlistSnapshotParams struct {
	ClusterID      uuid.UUID       `json:"cluster_id"`
	EffectiveCidrs json.RawMessage `json:"effective_cidrs"`
	DesiredCidrs   json.RawMessage `json:"desired_cidrs"`
	Drift          bool            `json:"drift"`
}

// Snapshots ------------------------------------------------------------
func (q *Queries) InsertApiserverAllowlistSnapshot(ctx context.Context, arg InsertApiserverAllowlistSnapshotParams) (ApiserverAllowlistSnapshot, error) {
	row := q.db.QueryRow(ctx, insertApiserverAllowlistSnapshot,
		arg.ClusterID,
		arg.EffectiveCidrs,
		arg.DesiredCidrs,
		arg.Drift,
	)
	var i ApiserverAllowlistSnapshot
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.CapturedAt,
		&i.EffectiveCidrs,
		&i.DesiredCidrs,
		&i.Drift,
	)
	return i, err
}

const listActiveApiserverAllowlists = `-- name: ListActiveApiserverAllowlists :many
SELECT cluster_id, cidrs, mode, detected_provider, last_reconciled_at,
       sync_status, last_error, effective_cidrs, created_at, updated_at
FROM apiserver_allowlists
WHERE mode != 'disabled'
ORDER BY cluster_id
`

// "active" == mode != 'disabled' — the rows the reconciler walks every tick.
func (q *Queries) ListActiveApiserverAllowlists(ctx context.Context) ([]ApiserverAllowlist, error) {
	rows, err := q.db.Query(ctx, listActiveApiserverAllowlists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiserverAllowlist{}
	for rows.Next() {
		var i ApiserverAllowlist
		if err := rows.Scan(
			&i.ClusterID,
			&i.Cidrs,
			&i.Mode,
			&i.DetectedProvider,
			&i.LastReconciledAt,
			&i.SyncStatus,
			&i.LastError,
			&i.EffectiveCidrs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiserverAllowlistSnapshots = `-- name: ListApiserverAllowlistSnapshots :many
SELECT id, cluster_id, captured_at, effective_cidrs, desired_cidrs, drift
FROM apiserver_allowlist_snapshots
WHERE cluster_id = $1
ORDER BY captured_at DESC
LIMIT $2 OFFSET $3
`

type ListApiserverAllowlistSnapshotsParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListApiserverAllowlistSnapshots(ctx context.Context, arg ListApiserverAllowlistSnapshotsParams) ([]ApiserverAllowlistSnapshot, error) {
	rows, err := q.db.Query(ctx, listApiserverAllowlistSnapshots, arg.ClusterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiserverAllowlistSnapshot{}
	for rows.Next() {
		var i ApiserverAllowlistSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.CapturedAt,
			&i.EffectiveCidrs,
			&i.DesiredCidrs,
			&i.Drift,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiserverAllowlistReconcileState = `-- name: UpdateApiserverAllowlistReconcileState :exec
UPDATE apiserver_allowlists
SET detected_provider  = $2,
    sync_status        = $3,
    last_error         = $4,
    effective_cidrs    = $5,
    last_reconciled_at = now(),
    updated_at         = now()
WHERE cluster_id = $1
`

type UpdateApiserverAllowlistReconcileStateParams struct {
	ClusterID        uuid.UUID       `json:"cluster_id"`
	DetectedProvider string          `json:"detected_provider"`
	SyncStatus       string          `json:"sync_status"`
	LastError        string          `json:"last_error"`
	EffectiveCidrs   json.RawMessage `json:"effective_cidrs"`
}

// Stamps the per-tick outcome — provider, sync_status, last_error,
// effective_cidrs snapshot, last_reconciled_at. Called by the reconciler.
func (q *Queries) UpdateApiserverAllowlistReconcileState(ctx context.Context, arg UpdateApiserverAllowlistReconcileStateParams) error {
	_, err := q.db.Exec(ctx, updateApiserverAllowlistReconcileState,
		arg.ClusterID,
		arg.DetectedProvider,
		arg.SyncStatus,
		arg.LastError,
		arg.EffectiveCidrs,
	)
	return err
}

const upsertApiserverAllowlist = `-- name: UpsertApiserverAllowlist :one
INSERT INTO apiserver_allowlists (
    cluster_id, cidrs, mode
) VALUES ($1, $2, $3)
ON CONFLICT (cluster_id) DO UPDATE SET
    cidrs      = EXCLUDED.cidrs,
    mode       = EXCLUDED.mode,
    updated_at = now()
RETURNING cluster_id, cidrs, mode, detected_provider, last_reconciled_at,
          sync_status, last_error, effective_cidrs, created_at, updated_at
`

type UpsertApiserverAllowlistParams struct {
	ClusterID uuid.UUID       `json:"cluster_id"`
	Cidrs     json.RawMessage `json:"cidrs"`
	Mode      string          `json:"mode"`
}

func (q *Queries) UpsertApiserverAllowlist(ctx context.Context, arg UpsertApiserverAllowlistParams) (ApiserverAllowlist, error) {
	row := q.db.QueryRow(ctx, upsertApiserverAllowlist, arg.ClusterID, arg.Cidrs, arg.Mode)
	var i ApiserverAllowlist
	err := row.Scan(
		&i.ClusterID,
		&i.Cidrs,
		&i.Mode,
		&i.DetectedProvider,
		&i.LastReconciledAt,
		&i.SyncStatus,
		&i.LastError,
		&i.EffectiveCidrs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
