// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: argocd.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAppsByInstance = `-- name: CountAppsByInstance :one
SELECT count(*) FROM argocd_applications WHERE argocd_instance_id = $1
`

func (q *Queries) CountAppsByInstance(ctx context.Context, argocdInstanceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAppsByInstance, argocdInstanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArgoCDApplications = `-- name: CountArgoCDApplications :one
SELECT count(*) FROM argocd_applications
`

func (q *Queries) CountArgoCDApplications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArgoCDApplications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArgoCDApplicationsBySyncHealth = `-- name: CountArgoCDApplicationsBySyncHealth :many
SELECT
    COALESCE(NULLIF(sync_status, ''), 'Unknown')::text AS sync_status,
    COALESCE(NULLIF(health_status, ''), 'Unknown')::text AS health_status,
    count(*)::bigint AS app_count
FROM argocd_applications
GROUP BY 1, 2
ORDER BY 1, 2
`

type CountArgoCDApplicationsBySyncHealthRow struct {
	SyncStatus   string `json:"sync_status"`
	HealthStatus string `json:"health_status"`
	AppCount     int64  `json:"app_count"`
}

func (q *Queries) CountArgoCDApplicationsBySyncHealth(ctx context.Context) ([]CountArgoCDApplicationsBySyncHealthRow, error) {
	rows, err := q.db.Query(ctx, countArgoCDApplicationsBySyncHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountArgoCDApplicationsBySyncHealthRow{}
	for rows.Next() {
		var i CountArgoCDApplicationsBySyncHealthRow
		if err := rows.Scan(&i.SyncStatus, &i.HealthStatus, &i.AppCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countArgoCDInstances = `-- name: CountArgoCDInstances :one
SELECT count(*) FROM argocd_instances
`

func (q *Queries) CountArgoCDInstances(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArgoCDInstances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArgoCDInstance = `-- name: CreateArgoCDInstance :one
INSERT INTO argocd_instances (name, cluster_id, api_url, auth_token_encrypted, verify_ssl)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, cluster_id, api_url, auth_token_encrypted, verify_ssl, is_healthy, last_sync, created_at, updated_at
`

type CreateArgoCDInstanceParams struct {
	Name               string    `json:"name"`
	ClusterID          uuid.UUID `json:"cluster_id"`
	ApiUrl             string    `json:"api_url"`
	AuthTokenEncrypted string    `json:"auth_token_encrypted"`
	VerifySsl          bool      `json:"verify_ssl"`
}

func (q *Queries) CreateArgoCDInstance(ctx context.Context, arg CreateArgoCDInstanceParams) (ArgocdInstance, error) {
	row := q.db.QueryRow(ctx, createArgoCDInstance,
		arg.Name,
		arg.ClusterID,
		arg.ApiUrl,
		arg.AuthTokenEncrypted,
		arg.VerifySsl,
	)
	var i ArgocdInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClusterID,
		&i.ApiUrl,
		&i.AuthTokenEncrypted,
		&i.VerifySsl,
		&i.IsHealthy,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createArgoCDManagedCluster = `-- name: CreateArgoCDManagedCluster :one

INSERT INTO argocd_managed_clusters (argocd_instance_id, cluster_id, cluster_secret_name, server_url, labels)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (argocd_instance_id, cluster_id) DO UPDATE SET
    cluster_secret_name = EXCLUDED.cluster_secret_name,
    server_url = EXCLUDED.server_url,
    labels = EXCLUDED.labels,
    updated_at = now()
RETURNING id, argocd_instance_id, cluster_id, cluster_secret_name, server_url, labels, created_at, updated_at
`

type CreateArgoCDManagedClusterParams struct {
	ArgocdInstanceID  uuid.UUID       `json:"argocd_instance_id"`
	ClusterID         uuid.UUID       `json:"cluster_id"`
	ClusterSecretName string          `json:"cluster_secret_name"`
	ServerUrl         string          `json:"server_url"`
	Labels            json.RawMessage `json:"labels"`
}

// ArgoCD Managed Clusters (Phase B1)
// Index of which of OUR clusters have been registered into each upstream
// ArgoCD instance. The upstream truth lives in the ArgoCD cluster Secret in
// the argocd namespace; this table makes list/unregister cheap and gives the
// ApplicationSet UI something to label-target.
func (q *Queries) CreateArgoCDManagedCluster(ctx context.Context, arg CreateArgoCDManagedClusterParams) (ArgocdManagedCluster, error) {
	row := q.db.QueryRow(ctx, createArgoCDManagedCluster,
		arg.ArgocdInstanceID,
		arg.ClusterID,
		arg.ClusterSecretName,
		arg.ServerUrl,
		arg.Labels,
	)
	var i ArgocdManagedCluster
	err := row.Scan(
		&i.ID,
		&i.ArgocdInstanceID,
		&i.ClusterID,
		&i.ClusterSecretName,
		&i.ServerUrl,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArgoCDClusterProxyTokensByCluster = `-- name: DeleteArgoCDClusterProxyTokensByCluster :execrows
DELETE FROM argocd_cluster_proxy_tokens WHERE cluster_id = $1
`

func (q *Queries) DeleteArgoCDClusterProxyTokensByCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArgoCDClusterProxyTokensByCluster, clusterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteArgoCDInstance = `-- name: DeleteArgoCDInstance :exec
DELETE FROM argocd_instances WHERE id = $1
`

func (q *Queries) DeleteArgoCDInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArgoCDInstance, id)
	return err
}

const deleteArgoCDManagedCluster = `-- name: DeleteArgoCDManagedCluster :exec
DELETE FROM argocd_managed_clusters WHERE argocd_instance_id = $1 AND cluster_id = $2
`

type DeleteArgoCDManagedClusterParams struct {
	ArgocdInstanceID uuid.UUID `json:"argocd_instance_id"`
	ClusterID        uuid.UUID `json:"cluster_id"`
}

func (q *Queries) DeleteArgoCDManagedCluster(ctx context.Context, arg DeleteArgoCDManagedClusterParams) error {
	_, err := q.db.Exec(ctx, deleteArgoCDManagedCluster, arg.ArgocdInstanceID, arg.ClusterID)
	return err
}

const deleteArgoCDManagedClustersByCluster = `-- name: DeleteArgoCDManagedClustersByCluster :execrows
DELETE FROM argocd_managed_clusters WHERE cluster_id = $1
`

// Bulk-delete every (instance, cluster) mapping for one cluster. Used by
// the decommission worker to drop local rows after a cluster is tombstoned.
// Upstream Argo cluster Secrets (the actual k8s resource in each Argo
// namespace) need a separate unregister flow; the orphans are surfaced via
// the cluster.decommission.argocd_secret_orphan audit row.
func (q *Queries) DeleteArgoCDManagedClustersByCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArgoCDManagedClustersByCluster, clusterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveArgoCDClusterProxyTokenByClusterID = `-- name: GetActiveArgoCDClusterProxyTokenByClusterID :one

SELECT id, cluster_id, purpose, token_hash, token_prefix, token_encrypted, expires_at, last_used_at, is_revoked, created_at, updated_at FROM argocd_cluster_proxy_tokens
WHERE cluster_id = $1
  AND purpose = 'argocd_cluster_proxy'
  AND is_revoked = false
  AND (expires_at IS NULL OR expires_at > now())
`

// ArgoCD cluster-proxy service tokens. These are not user API tokens:
// they are cluster-scoped machine identities used only by built-in ArgoCD
// to reach an adopted cluster through Astronomer's tunnel-backed proxy.
func (q *Queries) GetActiveArgoCDClusterProxyTokenByClusterID(ctx context.Context, clusterID uuid.UUID) (ArgocdClusterProxyToken, error) {
	row := q.db.QueryRow(ctx, getActiveArgoCDClusterProxyTokenByClusterID, clusterID)
	var i ArgocdClusterProxyToken
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Purpose,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.TokenEncrypted,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArgoCDApplicationByID = `-- name: GetArgoCDApplicationByID :one

SELECT id, argocd_instance_id, name, project, repo_url, path, target_revision, destination_cluster, destination_namespace, sync_status, health_status, resource_created_count, resource_changed_count, resource_pruned_count, last_synced, created_at, updated_at, upstream_uid, application_namespace FROM argocd_applications WHERE id = $1
`

// ArgoCD Applications
func (q *Queries) GetArgoCDApplicationByID(ctx context.Context, id uuid.UUID) (ArgocdApplication, error) {
	row := q.db.QueryRow(ctx, getArgoCDApplicationByID, id)
	var i ArgocdApplication
	err := row.Scan(
		&i.ID,
		&i.ArgocdInstanceID,
		&i.Name,
		&i.Project,
		&i.RepoUrl,
		&i.Path,
		&i.TargetRevision,
		&i.DestinationCluster,
		&i.DestinationNamespace,
		&i.SyncStatus,
		&i.HealthStatus,
		&i.ResourceCreatedCount,
		&i.ResourceChangedCount,
		&i.ResourcePrunedCount,
		&i.LastSynced,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpstreamUid,
		&i.ApplicationNamespace,
	)
	return i, err
}

const getArgoCDApplicationByName = `-- name: GetArgoCDApplicationByName :one
SELECT id, argocd_instance_id, name, project, repo_url, path, target_revision, destination_cluster, destination_namespace, sync_status, health_status, resource_created_count, resource_changed_count, resource_pruned_count, last_synced, created_at, updated_at, upstream_uid, application_namespace FROM argocd_applications WHERE argocd_instance_id = $1 AND name = $2
`

type GetArgoCDApplicationByNameParams struct {
	ArgocdInstanceID uuid.UUID `json:"argocd_instance_id"`
	Name             string    `json:"name"`
}

func (q *Queries) GetArgoCDApplicationByName(ctx context.Context, arg GetArgoCDApplicationByNameParams) (ArgocdApplication, error) {
	row := q.db.QueryRow(ctx, getArgoCDApplicationByName, arg.ArgocdInstanceID, arg.Name)
	var i ArgocdApplication
	err := row.Scan(
		&i.ID,
		&i.ArgocdInstanceID,
		&i.Name,
		&i.Project,
		&i.RepoUrl,
		&i.Path,
		&i.TargetRevision,
		&i.DestinationCluster,
		&i.DestinationNamespace,
		&i.SyncStatus,
		&i.HealthStatus,
		&i.ResourceCreatedCount,
		&i.ResourceChangedCount,
		&i.ResourcePrunedCount,
		&i.LastSynced,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpstreamUid,
		&i.ApplicationNamespace,
	)
	return i, err
}

const getArgoCDClusterProxyTokenByHash = `-- name: GetArgoCDClusterProxyTokenByHash :one
SELECT id, cluster_id, purpose, token_hash, token_prefix, token_encrypted, expires_at, last_used_at, is_revoked, created_at, updated_at FROM argocd_cluster_proxy_tokens
WHERE token_hash = $1
  AND purpose = 'argocd_cluster_proxy'
  AND is_revoked = false
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetArgoCDClusterProxyTokenByHash(ctx context.Context, tokenHash string) (ArgocdClusterProxyToken, error) {
	row := q.db.QueryRow(ctx, getArgoCDClusterProxyTokenByHash, tokenHash)
	var i ArgocdClusterProxyToken
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Purpose,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.TokenEncrypted,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArgoCDInstanceByID = `-- name: GetArgoCDInstanceByID :one

SELECT id, name, cluster_id, api_url, auth_token_encrypted, verify_ssl, is_healthy, last_sync, created_at, updated_at FROM argocd_instances WHERE id = $1
`

// ArgoCD Instances
func (q *Queries) GetArgoCDInstanceByID(ctx context.Context, id uuid.UUID) (ArgocdInstance, error) {
	row := q.db.QueryRow(ctx, getArgoCDInstanceByID, id)
	var i ArgocdInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClusterID,
		&i.ApiUrl,
		&i.AuthTokenEncrypted,
		&i.VerifySsl,
		&i.IsHealthy,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArgoCDInstanceByName = `-- name: GetArgoCDInstanceByName :one
SELECT id, name, cluster_id, api_url, auth_token_encrypted, verify_ssl, is_healthy, last_sync, created_at, updated_at FROM argocd_instances WHERE name = $1
`

func (q *Queries) GetArgoCDInstanceByName(ctx context.Context, name string) (ArgocdInstance, error) {
	row := q.db.QueryRow(ctx, getArgoCDInstanceByName, name)
	var i ArgocdInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClusterID,
		&i.ApiUrl,
		&i.AuthTokenEncrypted,
		&i.VerifySsl,
		&i.IsHealthy,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArgoCDManagedCluster = `-- name: GetArgoCDManagedCluster :one
SELECT id, argocd_instance_id, cluster_id, cluster_secret_name, server_url, labels, created_at, updated_at FROM argocd_managed_clusters WHERE argocd_instance_id = $1 AND cluster_id = $2
`

type GetArgoCDManagedClusterParams struct {
	ArgocdInstanceID uuid.UUID `json:"argocd_instance_id"`
	ClusterID        uuid.UUID `json:"cluster_id"`
}

func (q *Queries) GetArgoCDManagedCluster(ctx context.Context, arg GetArgoCDManagedClusterParams) (ArgocdManagedCluster, error) {
	row := q.db.QueryRow(ctx, getArgoCDManagedCluster, arg.ArgocdInstanceID, arg.ClusterID)
	var i ArgocdManagedCluster
	err := row.Scan(
		&i.ID,
		&i.ArgocdInstanceID,
		&i.ClusterID,
		&i.ClusterSecretName,
		&i.ServerUrl,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppsByInstance = `-- name: ListAppsByInstance :many
SELECT id, argocd_instance_id, name, project, repo_url, path, target_revision, destination_cluster, destination_namespace, sync_status, health_status, resource_created_count, resource_changed_count, resource_pruned_count, last_synced, created_at, updated_at, upstream_uid, application_namespace FROM argocd_applications WHERE argocd_instance_id = $1 ORDER BY name ASC LIMIT $2 OFFSET $3
`

type ListAppsByInstanceParams struct {
	ArgocdInstanceID uuid.UUID `json:"argocd_instance_id"`
	Limit            int32     `json:"limit"`
	Offset           int32     `json:"offset"`
}

func (q *Queries) ListAppsByInstance(ctx context.Context, arg ListAppsByInstanceParams) ([]ArgocdApplication, error) {
	rows, err := q.db.Query(ctx, listAppsByInstance, arg.ArgocdInstanceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArgocdApplication{}
	for rows.Next() {
		var i ArgocdApplication
		if err := rows.Scan(
			&i.ID,
			&i.ArgocdInstanceID,
			&i.Name,
			&i.Project,
			&i.RepoUrl,
			&i.Path,
			&i.TargetRevision,
			&i.DestinationCluster,
			&i.DestinationNamespace,
			&i.SyncStatus,
			&i.HealthStatus,
			&i.ResourceCreatedCount,
			&i.ResourceChangedCount,
			&i.ResourcePrunedCount,
			&i.LastSynced,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpstreamUid,
			&i.ApplicationNamespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArgoCDApplications = `-- name: ListArgoCDApplications :many
SELECT id, argocd_instance_id, name, project, repo_url, path, target_revision, destination_cluster, destination_namespace, sync_status, health_status, resource_created_count, resource_changed_count, resource_pruned_count, last_synced, created_at, updated_at, upstream_uid, application_namespace FROM argocd_applications ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListArgoCDApplicationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArgoCDApplications(ctx context.Context, arg ListArgoCDApplicationsParams) ([]ArgocdApplication, error) {
	rows, err := q.db.Query(ctx, listArgoCDApplications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArgocdApplication{}
	for rows.Next() {
		var i ArgocdApplication
		if err := rows.Scan(
			&i.ID,
			&i.ArgocdInstanceID,
			&i.Name,
			&i.Project,
			&i.RepoUrl,
			&i.Path,
			&i.TargetRevision,
			&i.DestinationCluster,
			&i.DestinationNamespace,
			&i.SyncStatus,
			&i.HealthStatus,
			&i.ResourceCreatedCount,
			&i.ResourceChangedCount,
			&i.ResourcePrunedCount,
			&i.LastSynced,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpstreamUid,
			&i.ApplicationNamespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArgoCDApplicationsByManagedClusterTargets = `-- name: ListArgoCDApplicationsByManagedClusterTargets :many
SELECT id, argocd_instance_id, name, project, repo_url, path, target_revision, destination_cluster, destination_namespace, sync_status, health_status, resource_created_count, resource_changed_count, resource_pruned_count, last_synced, created_at, updated_at, upstream_uid, application_namespace FROM argocd_applications
WHERE argocd_instance_id = ANY($1::uuid[])
  AND destination_cluster = ANY($2::text[])
ORDER BY name ASC
`

type ListArgoCDApplicationsByManagedClusterTargetsParams struct {
	ArgocdInstanceIds   []uuid.UUID `json:"argocd_instance_ids"`
	DestinationClusters []string    `json:"destination_clusters"`
}

func (q *Queries) ListArgoCDApplicationsByManagedClusterTargets(ctx context.Context, arg ListArgoCDApplicationsByManagedClusterTargetsParams) ([]ArgocdApplication, error) {
	rows, err := q.db.Query(ctx, listArgoCDApplicationsByManagedClusterTargets, arg.ArgocdInstanceIds, arg.DestinationClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArgocdApplication{}
	for rows.Next() {
		var i ArgocdApplication
		if err := rows.Scan(
			&i.ID,
			&i.ArgocdInstanceID,
			&i.Name,
			&i.Project,
			&i.RepoUrl,
			&i.Path,
			&i.TargetRevision,
			&i.DestinationCluster,
			&i.DestinationNamespace,
			&i.SyncStatus,
			&i.HealthStatus,
			&i.ResourceCreatedCount,
			&i.ResourceChangedCount,
			&i.ResourcePrunedCount,
			&i.LastSynced,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpstreamUid,
			&i.ApplicationNamespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArgoCDInstances = `-- name: ListArgoCDInstances :many
SELECT id, name, cluster_id, api_url, auth_token_encrypted, verify_ssl, is_healthy, last_sync, created_at, updated_at FROM argocd_instances ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListArgoCDInstancesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArgoCDInstances(ctx context.Context, arg ListArgoCDInstancesParams) ([]ArgocdInstance, error) {
	rows, err := q.db.Query(ctx, listArgoCDInstances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArgocdInstance{}
	for rows.Next() {
		var i ArgocdInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClusterID,
			&i.ApiUrl,
			&i.AuthTokenEncrypted,
			&i.VerifySsl,
			&i.IsHealthy,
			&i.LastSync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArgoCDManagedClusters = `-- name: ListArgoCDManagedClusters :many
SELECT amc.id, amc.argocd_instance_id, amc.cluster_id, amc.cluster_secret_name, amc.server_url, amc.labels, amc.created_at, amc.updated_at FROM argocd_managed_clusters amc
JOIN clusters cl ON cl.id = amc.cluster_id
WHERE amc.argocd_instance_id = $1 AND cl.decommissioned_at IS NULL
ORDER BY amc.created_at ASC
`

// Only registrations whose backing cluster still exists and is NOT
// decommissioned. Decommission deletes these rows, but this INNER JOIN keeps a
// tombstoned/deleted-cluster registration from ever surfacing (in the clusters
// tab, the orphan-app report's valid-target set, or the registration refresh)
// if a row is ever left behind.
func (q *Queries) ListArgoCDManagedClusters(ctx context.Context, argocdInstanceID uuid.UUID) ([]ArgocdManagedCluster, error) {
	rows, err := q.db.Query(ctx, listArgoCDManagedClusters, argocdInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArgocdManagedCluster{}
	for rows.Next() {
		var i ArgocdManagedCluster
		if err := rows.Scan(
			&i.ID,
			&i.ArgocdInstanceID,
			&i.ClusterID,
			&i.ClusterSecretName,
			&i.ServerUrl,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArgoCDManagedClustersByCluster = `-- name: ListArgoCDManagedClustersByCluster :many
SELECT id, argocd_instance_id, cluster_id, cluster_secret_name, server_url, labels, created_at, updated_at FROM argocd_managed_clusters WHERE cluster_id = $1 ORDER BY created_at ASC
`

// Reverse index of the above: every ArgoCD instance into which a given
// Astronomer cluster is registered. Used by the
// "argocd:refresh_managed_cluster_labels" worker task to re-stamp the
// astronomer.io/label-* keys on every relevant cluster Secret after a
// clusters.labels mutation.
func (q *Queries) ListArgoCDManagedClustersByCluster(ctx context.Context, clusterID uuid.UUID) ([]ArgocdManagedCluster, error) {
	rows, err := q.db.Query(ctx, listArgoCDManagedClustersByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArgocdManagedCluster{}
	for rows.Next() {
		var i ArgocdManagedCluster
		if err := rows.Scan(
			&i.ID,
			&i.ArgocdInstanceID,
			&i.ClusterID,
			&i.ClusterSecretName,
			&i.ServerUrl,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArgoCDManagedClustersByClusterIDs = `-- name: ListArgoCDManagedClustersByClusterIDs :many
SELECT id, argocd_instance_id, cluster_id, cluster_secret_name, server_url, labels, created_at, updated_at FROM argocd_managed_clusters
WHERE cluster_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

// Batched form of ListArgoCDManagedClustersByCluster for the clusters-list
// dashboard: one round-trip for a whole page of clusters instead of one query
// per cluster (the ArgoCD N+1). Rows are grouped by cluster_id in Go; the
// created_at ordering keeps each cluster's per-row order identical to the
// single-cluster query.
func (q *Queries) ListArgoCDManagedClustersByClusterIDs(ctx context.Context, clusterIds []uuid.UUID) ([]ArgocdManagedCluster, error) {
	rows, err := q.db.Query(ctx, listArgoCDManagedClustersByClusterIDs, clusterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArgocdManagedCluster{}
	for rows.Next() {
		var i ArgocdManagedCluster
		if err := rows.Scan(
			&i.ID,
			&i.ArgocdInstanceID,
			&i.ClusterID,
			&i.ClusterSecretName,
			&i.ServerUrl,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByCluster = `-- name: ListInstancesByCluster :many
SELECT id, name, cluster_id, api_url, auth_token_encrypted, verify_ssl, is_healthy, last_sync, created_at, updated_at FROM argocd_instances WHERE cluster_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListInstancesByClusterParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListInstancesByCluster(ctx context.Context, arg ListInstancesByClusterParams) ([]ArgocdInstance, error) {
	rows, err := q.db.Query(ctx, listInstancesByCluster, arg.ClusterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArgocdInstance{}
	for rows.Next() {
		var i ArgocdInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClusterID,
			&i.ApiUrl,
			&i.AuthTokenEncrypted,
			&i.VerifySsl,
			&i.IsHealthy,
			&i.LastSync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchArgoCDClusterProxyToken = `-- name: TouchArgoCDClusterProxyToken :exec
UPDATE argocd_cluster_proxy_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchArgoCDClusterProxyToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchArgoCDClusterProxyToken, id)
	return err
}

const updateArgoCDApplication = `-- name: UpdateArgoCDApplication :one
UPDATE argocd_applications SET
    project = $2,
    repo_url = $3,
    path = $4,
    target_revision = $5,
    destination_cluster = $6,
    destination_namespace = $7,
    sync_status = $8,
    health_status = $9,
    resource_created_count = $10,
    resource_changed_count = $11,
    resource_pruned_count = $12,
    last_synced = $13
WHERE id = $1
RETURNING id, argocd_instance_id, name, project, repo_url, path, target_revision, destination_cluster, destination_namespace, sync_status, health_status, resource_created_count, resource_changed_count, resource_pruned_count, last_synced, created_at, updated_at, upstream_uid, application_namespace
`

type UpdateArgoCDApplicationParams struct {
	ID                   uuid.UUID          `json:"id"`
	Project              string             `json:"project"`
	RepoUrl              string             `json:"repo_url"`
	Path                 string             `json:"path"`
	TargetRevision       string             `json:"target_revision"`
	DestinationCluster   string             `json:"destination_cluster"`
	DestinationNamespace string             `json:"destination_namespace"`
	SyncStatus           string             `json:"sync_status"`
	HealthStatus         string             `json:"health_status"`
	ResourceCreatedCount int32              `json:"resource_created_count"`
	ResourceChangedCount int32              `json:"resource_changed_count"`
	ResourcePrunedCount  int32              `json:"resource_pruned_count"`
	LastSynced           pgtype.Timestamptz `json:"last_synced"`
}

func (q *Queries) UpdateArgoCDApplication(ctx context.Context, arg UpdateArgoCDApplicationParams) (ArgocdApplication, error) {
	row := q.db.QueryRow(ctx, updateArgoCDApplication,
		arg.ID,
		arg.Project,
		arg.RepoUrl,
		arg.Path,
		arg.TargetRevision,
		arg.DestinationCluster,
		arg.DestinationNamespace,
		arg.SyncStatus,
		arg.HealthStatus,
		arg.ResourceCreatedCount,
		arg.ResourceChangedCount,
		arg.ResourcePrunedCount,
		arg.LastSynced,
	)
	var i ArgocdApplication
	err := row.Scan(
		&i.ID,
		&i.ArgocdInstanceID,
		&i.Name,
		&i.Project,
		&i.RepoUrl,
		&i.Path,
		&i.TargetRevision,
		&i.DestinationCluster,
		&i.DestinationNamespace,
		&i.SyncStatus,
		&i.HealthStatus,
		&i.ResourceCreatedCount,
		&i.ResourceChangedCount,
		&i.ResourcePrunedCount,
		&i.LastSynced,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpstreamUid,
		&i.ApplicationNamespace,
	)
	return i, err
}

const updateArgoCDInstance = `-- name: UpdateArgoCDInstance :one
UPDATE argocd_instances SET
    name = $2,
    api_url = $3,
    auth_token_encrypted = $4,
    verify_ssl = $5
WHERE id = $1
RETURNING id, name, cluster_id, api_url, auth_token_encrypted, verify_ssl, is_healthy, last_sync, created_at, updated_at
`

type UpdateArgoCDInstanceParams struct {
	ID                 uuid.UUID `json:"id"`
	Name               string    `json:"name"`
	ApiUrl             string    `json:"api_url"`
	AuthTokenEncrypted string    `json:"auth_token_encrypted"`
	VerifySsl          bool      `json:"verify_ssl"`
}

func (q *Queries) UpdateArgoCDInstance(ctx context.Context, arg UpdateArgoCDInstanceParams) (ArgocdInstance, error) {
	row := q.db.QueryRow(ctx, updateArgoCDInstance,
		arg.ID,
		arg.Name,
		arg.ApiUrl,
		arg.AuthTokenEncrypted,
		arg.VerifySsl,
	)
	var i ArgocdInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClusterID,
		&i.ApiUrl,
		&i.AuthTokenEncrypted,
		&i.VerifySsl,
		&i.IsHealthy,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArgoCDInstanceHealth = `-- name: UpdateArgoCDInstanceHealth :exec
UPDATE argocd_instances SET is_healthy = $2, last_sync = now() WHERE id = $1
`

type UpdateArgoCDInstanceHealthParams struct {
	ID        uuid.UUID `json:"id"`
	IsHealthy bool      `json:"is_healthy"`
}

func (q *Queries) UpdateArgoCDInstanceHealth(ctx context.Context, arg UpdateArgoCDInstanceHealthParams) error {
	_, err := q.db.Exec(ctx, updateArgoCDInstanceHealth, arg.ID, arg.IsHealthy)
	return err
}

const updateArgoCDManagedClusterLabels = `-- name: UpdateArgoCDManagedClusterLabels :one
UPDATE argocd_managed_clusters
SET labels = $3, updated_at = now()
WHERE argocd_instance_id = $1 AND cluster_id = $2
RETURNING id, argocd_instance_id, cluster_id, cluster_secret_name, server_url, labels, created_at, updated_at
`

type UpdateArgoCDManagedClusterLabelsParams struct {
	ArgocdInstanceID uuid.UUID       `json:"argocd_instance_id"`
	ClusterID        uuid.UUID       `json:"cluster_id"`
	Labels           json.RawMessage `json:"labels"`
}

func (q *Queries) UpdateArgoCDManagedClusterLabels(ctx context.Context, arg UpdateArgoCDManagedClusterLabelsParams) (ArgocdManagedCluster, error) {
	row := q.db.QueryRow(ctx, updateArgoCDManagedClusterLabels, arg.ArgocdInstanceID, arg.ClusterID, arg.Labels)
	var i ArgocdManagedCluster
	err := row.Scan(
		&i.ID,
		&i.ArgocdInstanceID,
		&i.ClusterID,
		&i.ClusterSecretName,
		&i.ServerUrl,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertArgoCDClusterProxyToken = `-- name: UpsertArgoCDClusterProxyToken :one
INSERT INTO argocd_cluster_proxy_tokens
    (cluster_id, token_hash, token_prefix, token_encrypted, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (cluster_id, purpose) DO UPDATE SET
    token_hash = EXCLUDED.token_hash,
    token_prefix = EXCLUDED.token_prefix,
    token_encrypted = EXCLUDED.token_encrypted,
    expires_at = EXCLUDED.expires_at,
    is_revoked = false,
    updated_at = now()
RETURNING id, cluster_id, purpose, token_hash, token_prefix, token_encrypted, expires_at, last_used_at, is_revoked, created_at, updated_at
`

type UpsertArgoCDClusterProxyTokenParams struct {
	ClusterID      uuid.UUID          `json:"cluster_id"`
	TokenHash      string             `json:"token_hash"`
	TokenPrefix    string             `json:"token_prefix"`
	TokenEncrypted string             `json:"token_encrypted"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertArgoCDClusterProxyToken(ctx context.Context, arg UpsertArgoCDClusterProxyTokenParams) (ArgocdClusterProxyToken, error) {
	row := q.db.QueryRow(ctx, upsertArgoCDClusterProxyToken,
		arg.ClusterID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.TokenEncrypted,
		arg.ExpiresAt,
	)
	var i ArgocdClusterProxyToken
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Purpose,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.TokenEncrypted,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDiscoveredArgoCDApplication = `-- name: UpsertDiscoveredArgoCDApplication :one
INSERT INTO argocd_applications (
    argocd_instance_id,
    name,
    upstream_uid,
    application_namespace,
    project,
    repo_url,
    path,
    target_revision,
    destination_cluster,
    destination_namespace,
    sync_status,
    health_status,
    resource_created_count,
    resource_changed_count,
    resource_pruned_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (argocd_instance_id, name) DO UPDATE SET
    upstream_uid = EXCLUDED.upstream_uid,
    application_namespace = EXCLUDED.application_namespace,
    project = EXCLUDED.project,
    repo_url = EXCLUDED.repo_url,
    path = EXCLUDED.path,
    target_revision = EXCLUDED.target_revision,
    destination_cluster = EXCLUDED.destination_cluster,
    destination_namespace = EXCLUDED.destination_namespace,
    sync_status = CASE
        WHEN argocd_applications.upstream_uid = '' THEN EXCLUDED.sync_status
        ELSE argocd_applications.sync_status
    END,
    health_status = CASE
        WHEN argocd_applications.upstream_uid = '' THEN EXCLUDED.health_status
        ELSE argocd_applications.health_status
    END,
    resource_created_count = CASE
        WHEN argocd_applications.upstream_uid = '' THEN EXCLUDED.resource_created_count
        ELSE argocd_applications.resource_created_count
    END,
    resource_changed_count = CASE
        WHEN argocd_applications.upstream_uid = '' THEN EXCLUDED.resource_changed_count
        ELSE argocd_applications.resource_changed_count
    END,
    resource_pruned_count = CASE
        WHEN argocd_applications.upstream_uid = '' THEN EXCLUDED.resource_pruned_count
        ELSE argocd_applications.resource_pruned_count
    END,
    updated_at = now()
WHERE argocd_applications.upstream_uid = ''
   OR argocd_applications.upstream_uid = EXCLUDED.upstream_uid
RETURNING id, argocd_instance_id, name, project, repo_url, path, target_revision, destination_cluster, destination_namespace, sync_status, health_status, resource_created_count, resource_changed_count, resource_pruned_count, last_synced, created_at, updated_at, upstream_uid, application_namespace
`

type UpsertDiscoveredArgoCDApplicationParams struct {
	ArgocdInstanceID     uuid.UUID `json:"argocd_instance_id"`
	Name                 string    `json:"name"`
	UpstreamUid          string    `json:"upstream_uid"`
	ApplicationNamespace string    `json:"application_namespace"`
	Project              string    `json:"project"`
	RepoUrl              string    `json:"repo_url"`
	Path                 string    `json:"path"`
	TargetRevision       string    `json:"target_revision"`
	DestinationCluster   string    `json:"destination_cluster"`
	DestinationNamespace string    `json:"destination_namespace"`
	SyncStatus           string    `json:"sync_status"`
	HealthStatus         string    `json:"health_status"`
	ResourceCreatedCount int32     `json:"resource_created_count"`
	ResourceChangedCount int32     `json:"resource_changed_count"`
	ResourcePrunedCount  int32     `json:"resource_pruned_count"`
}

// A single statement is the transaction boundary for concurrent discovery.
// The stable local ID is preserved on conflict so already-audited operation
// targets never drift. Discovery refreshes only bounded reference metadata;
// last-good status, resource counts and last_synced are intentionally not
// clobbered when another server replica won the insert race.
func (q *Queries) UpsertDiscoveredArgoCDApplication(ctx context.Context, arg UpsertDiscoveredArgoCDApplicationParams) (ArgocdApplication, error) {
	row := q.db.QueryRow(ctx, upsertDiscoveredArgoCDApplication,
		arg.ArgocdInstanceID,
		arg.Name,
		arg.UpstreamUid,
		arg.ApplicationNamespace,
		arg.Project,
		arg.RepoUrl,
		arg.Path,
		arg.TargetRevision,
		arg.DestinationCluster,
		arg.DestinationNamespace,
		arg.SyncStatus,
		arg.HealthStatus,
		arg.ResourceCreatedCount,
		arg.ResourceChangedCount,
		arg.ResourcePrunedCount,
	)
	var i ArgocdApplication
	err := row.Scan(
		&i.ID,
		&i.ArgocdInstanceID,
		&i.Name,
		&i.Project,
		&i.RepoUrl,
		&i.Path,
		&i.TargetRevision,
		&i.DestinationCluster,
		&i.DestinationNamespace,
		&i.SyncStatus,
		&i.HealthStatus,
		&i.ResourceCreatedCount,
		&i.ResourceChangedCount,
		&i.ResourcePrunedCount,
		&i.LastSynced,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpstreamUid,
		&i.ApplicationNamespace,
	)
	return i, err
}
