// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAPITokens = `-- name: CountAPITokens :one
SELECT count(*) FROM api_tokens
`

func (q *Queries) CountAPITokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAPITokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSSOConfigurations = `-- name: CountSSOConfigurations :one
SELECT count(*) FROM sso_configurations
`

func (q *Queries) CountSSOConfigurations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSSOConfigurations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTokensByUser = `-- name: CountTokensByUser :one
SELECT count(*) FROM api_tokens WHERE user_id = $1 AND is_revoked = false
`

func (q *Queries) CountTokensByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, prefix, expires_at, scopes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at
`

type CreateAPITokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	Prefix    string             `json:"prefix"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Scopes    json.RawMessage    `json:"scopes"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSSOConfiguration = `-- name: CreateSSOConfiguration :one
INSERT INTO sso_configurations (provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at
`

type CreateSSOConfigurationParams struct {
	Provider              string          `json:"provider"`
	IsEnabled             bool            `json:"is_enabled"`
	DisplayName           string          `json:"display_name"`
	Config                json.RawMessage `json:"config"`
	ClientID              string          `json:"client_id"`
	ClientSecretEncrypted string          `json:"client_secret_encrypted"`
	AllowedOrganizations  json.RawMessage `json:"allowed_organizations"`
	AllowedDomains        json.RawMessage `json:"allowed_domains"`
	AutoCreateUsers       bool            `json:"auto_create_users"`
	DefaultGlobalRoleID   pgtype.UUID     `json:"default_global_role_id"`
}

func (q *Queries) CreateSSOConfiguration(ctx context.Context, arg CreateSSOConfigurationParams) (SsoConfiguration, error) {
	row := q.db.QueryRow(ctx, createSSOConfiguration,
		arg.Provider,
		arg.IsEnabled,
		arg.DisplayName,
		arg.Config,
		arg.ClientID,
		arg.ClientSecretEncrypted,
		arg.AllowedOrganizations,
		arg.AllowedDomains,
		arg.AutoCreateUsers,
		arg.DefaultGlobalRoleID,
	)
	var i SsoConfiguration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const deleteSSOConfiguration = `-- name: DeleteSSOConfiguration :exec
DELETE FROM sso_configurations WHERE id = $1
`

func (q *Queries) DeleteSSOConfiguration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSOConfiguration, id)
	return err
}

const getAPITokenByID = `-- name: GetAPITokenByID :one

SELECT id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at FROM api_tokens WHERE id = $1
`

// API Tokens
func (q *Queries) GetAPITokenByID(ctx context.Context, id uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnabledSSOProviders = `-- name: GetEnabledSSOProviders :many
SELECT id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at FROM sso_configurations WHERE is_enabled = true ORDER BY provider ASC
`

func (q *Queries) GetEnabledSSOProviders(ctx context.Context) ([]SsoConfiguration, error) {
	rows, err := q.db.Query(ctx, getEnabledSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoConfiguration{}
	for rows.Next() {
		var i SsoConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.IsEnabled,
			&i.DisplayName,
			&i.Config,
			&i.ClientID,
			&i.ClientSecretEncrypted,
			&i.AllowedOrganizations,
			&i.AllowedDomains,
			&i.AutoCreateUsers,
			&i.DefaultGlobalRoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSSOConfigurationByID = `-- name: GetSSOConfigurationByID :one

SELECT id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at FROM sso_configurations WHERE id = $1
`

// SSO Configurations
func (q *Queries) GetSSOConfigurationByID(ctx context.Context, id uuid.UUID) (SsoConfiguration, error) {
	row := q.db.QueryRow(ctx, getSSOConfigurationByID, id)
	var i SsoConfiguration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOConfigurationByProvider = `-- name: GetSSOConfigurationByProvider :one
SELECT id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at FROM sso_configurations WHERE provider = $1
`

func (q *Queries) GetSSOConfigurationByProvider(ctx context.Context, provider string) (SsoConfiguration, error) {
	row := q.db.QueryRow(ctx, getSSOConfigurationByProvider, provider)
	var i SsoConfiguration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at FROM api_tokens WHERE token_hash = $1 AND is_revoked = false
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at FROM api_tokens ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAPITokensParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAPITokens(ctx context.Context, arg ListAPITokensParams) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.IsRevoked,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTokensByUser = `-- name: ListAllTokensByUser :many
SELECT id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAllTokensByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListAllTokensByUser(ctx context.Context, arg ListAllTokensByUserParams) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAllTokensByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.IsRevoked,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSOConfigurations = `-- name: ListSSOConfigurations :many
SELECT id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at FROM sso_configurations ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListSSOConfigurationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSSOConfigurations(ctx context.Context, arg ListSSOConfigurationsParams) ([]SsoConfiguration, error) {
	rows, err := q.db.Query(ctx, listSSOConfigurations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoConfiguration{}
	for rows.Next() {
		var i SsoConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.IsEnabled,
			&i.DisplayName,
			&i.Config,
			&i.ClientID,
			&i.ClientSecretEncrypted,
			&i.AllowedOrganizations,
			&i.AllowedDomains,
			&i.AutoCreateUsers,
			&i.DefaultGlobalRoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at FROM api_tokens WHERE user_id = $1 AND is_revoked = false ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTokensByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTokensByUser(ctx context.Context, arg ListTokensByUserParams) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.IsRevoked,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens SET is_revoked = true WHERE id = $1
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, id)
	return err
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastUsed, id)
	return err
}

const updateSSOConfiguration = `-- name: UpdateSSOConfiguration :one
UPDATE sso_configurations SET
    is_enabled = $2,
    display_name = $3,
    config = $4,
    client_id = $5,
    client_secret_encrypted = $6,
    allowed_organizations = $7,
    allowed_domains = $8,
    auto_create_users = $9,
    default_global_role_id = $10
WHERE id = $1
RETURNING id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at
`

type UpdateSSOConfigurationParams struct {
	ID                    uuid.UUID       `json:"id"`
	IsEnabled             bool            `json:"is_enabled"`
	DisplayName           string          `json:"display_name"`
	Config                json.RawMessage `json:"config"`
	ClientID              string          `json:"client_id"`
	ClientSecretEncrypted string          `json:"client_secret_encrypted"`
	AllowedOrganizations  json.RawMessage `json:"allowed_organizations"`
	AllowedDomains        json.RawMessage `json:"allowed_domains"`
	AutoCreateUsers       bool            `json:"auto_create_users"`
	DefaultGlobalRoleID   pgtype.UUID     `json:"default_global_role_id"`
}

func (q *Queries) UpdateSSOConfiguration(ctx context.Context, arg UpdateSSOConfigurationParams) (SsoConfiguration, error) {
	row := q.db.QueryRow(ctx, updateSSOConfiguration,
		arg.ID,
		arg.IsEnabled,
		arg.DisplayName,
		arg.Config,
		arg.ClientID,
		arg.ClientSecretEncrypted,
		arg.AllowedOrganizations,
		arg.AllowedDomains,
		arg.AutoCreateUsers,
		arg.DefaultGlobalRoleID,
	)
	var i SsoConfiguration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
