// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUnmigratedSSORows = `-- name: CountActiveUnmigratedSSORows :one
SELECT count(*) FROM sso_configurations
WHERE is_enabled = true AND migrated_to_dex_at IS NULL
`

// Drives the startup-time deprecation warning (migration 045). Counts
// enabled sso_configurations rows that have NOT been stamped as migrated
// to dex_connectors — i.e. rows the operator added AFTER cutover. When > 0
// we log a warn-level line at boot so the drift is visible without burying
// the migration story.
func (q *Queries) CountActiveUnmigratedSSORows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUnmigratedSSORows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTokensByUser = `-- name: CountTokensByUser :one
SELECT count(*) FROM api_tokens WHERE user_id = $1 AND is_revoked = false
`

func (q *Queries) CountTokensByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, prefix, expires_at, scopes, allowed_cidrs)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at, allowed_cidrs, last_seen_remote_ip
`

type CreateAPITokenParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	TokenHash    string             `json:"token_hash"`
	Prefix       string             `json:"prefix"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Scopes       json.RawMessage    `json:"scopes"`
	AllowedCidrs string             `json:"allowed_cidrs"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
		arg.Scopes,
		arg.AllowedCidrs,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowedCidrs,
		&i.LastSeenRemoteIp,
	)
	return i, err
}

const createSSOConfiguration = `-- name: CreateSSOConfiguration :one
INSERT INTO sso_configurations (provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at, migrated_to_dex_at
`

type CreateSSOConfigurationParams struct {
	Provider              string          `json:"provider"`
	IsEnabled             bool            `json:"is_enabled"`
	DisplayName           string          `json:"display_name"`
	Config                json.RawMessage `json:"config"`
	ClientID              string          `json:"client_id"`
	ClientSecretEncrypted string          `json:"client_secret_encrypted"`
	AllowedOrganizations  json.RawMessage `json:"allowed_organizations"`
	AllowedDomains        json.RawMessage `json:"allowed_domains"`
	AutoCreateUsers       bool            `json:"auto_create_users"`
	DefaultGlobalRoleID   pgtype.UUID     `json:"default_global_role_id"`
}

func (q *Queries) CreateSSOConfiguration(ctx context.Context, arg CreateSSOConfigurationParams) (SsoConfiguration, error) {
	row := q.db.QueryRow(ctx, createSSOConfiguration,
		arg.Provider,
		arg.IsEnabled,
		arg.DisplayName,
		arg.Config,
		arg.ClientID,
		arg.ClientSecretEncrypted,
		arg.AllowedOrganizations,
		arg.AllowedDomains,
		arg.AutoCreateUsers,
		arg.DefaultGlobalRoleID,
	)
	var i SsoConfiguration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MigratedToDexAt,
	)
	return i, err
}

const deleteSSOConfiguration = `-- name: DeleteSSOConfiguration :exec
DELETE FROM sso_configurations WHERE id = $1
`

func (q *Queries) DeleteSSOConfiguration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSOConfiguration, id)
	return err
}

const enableDexSSOForGeneration = `-- name: EnableDexSSOForGeneration :one
WITH dex_lock AS MATERIALIZED (SELECT pg_advisory_xact_lock(742193440558879931)), current_generation AS MATERIALIZED (
    SELECT 1
    FROM dex_settings AS settings
    WHERE settings.id = '00000000-0000-0000-0000-000000000001'::uuid
      AND settings.runtime_generation = $1
      AND settings.runtime_applied_generation = $1
      AND settings.runtime_phase IN ('fresh','cutover')
      AND EXISTS(SELECT 1 FROM dex_lock)
	FOR UPDATE OF settings
), enabled AS (
INSERT INTO sso_configurations (
    provider, is_enabled, display_name, config, client_id,
    client_secret_encrypted, allowed_organizations, allowed_domains,
    auto_create_users
)
SELECT
    'dex', true, $2, $3, $4,
    $5, '[]'::jsonb, '[]'::jsonb, true
FROM current_generation
ON CONFLICT (provider) DO UPDATE SET
    is_enabled = true,
    display_name = EXCLUDED.display_name,
    config = EXCLUDED.config,
    client_id = EXCLUDED.client_id,
    client_secret_encrypted = EXCLUDED.client_secret_encrypted
WHERE EXISTS (SELECT 1 FROM current_generation)
RETURNING id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at, migrated_to_dex_at
), cleared AS (
 UPDATE dex_settings SET saga_previous_sso_enabled=false,updated_at=now()
 WHERE id='00000000-0000-0000-0000-000000000001'::uuid
 AND runtime_generation=$1 AND EXISTS(SELECT 1 FROM enabled) RETURNING 1
)
SELECT enabled.id, enabled.provider, enabled.is_enabled, enabled.display_name, enabled.config, enabled.client_id, enabled.client_secret_encrypted, enabled.allowed_organizations, enabled.allowed_domains, enabled.auto_create_users, enabled.default_global_role_id, enabled.created_at, enabled.updated_at, enabled.migrated_to_dex_at FROM enabled WHERE (SELECT count(*) FROM cleared)>0
`

type EnableDexSSOForGenerationParams struct {
	RuntimeGeneration     int64           `json:"runtime_generation"`
	DisplayName           string          `json:"display_name"`
	Config                json.RawMessage `json:"config"`
	ClientID              string          `json:"client_id"`
	ClientSecretEncrypted string          `json:"client_secret_encrypted"`
}

type EnableDexSSOForGenerationRow struct {
	ID                    uuid.UUID          `json:"id"`
	Provider              string             `json:"provider"`
	IsEnabled             bool               `json:"is_enabled"`
	DisplayName           string             `json:"display_name"`
	Config                json.RawMessage    `json:"config"`
	ClientID              string             `json:"client_id"`
	ClientSecretEncrypted string             `json:"client_secret_encrypted"`
	AllowedOrganizations  json.RawMessage    `json:"allowed_organizations"`
	AllowedDomains        json.RawMessage    `json:"allowed_domains"`
	AutoCreateUsers       bool               `json:"auto_create_users"`
	DefaultGlobalRoleID   pgtype.UUID        `json:"default_global_role_id"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	MigratedToDexAt       pgtype.Timestamptz `json:"migrated_to_dex_at"`
}

// The generation predicate is evaluated in the same statement that enables
// the provider. A stale reconcile can therefore never win a check-then-write
// race against a newer settings/register mutation.
func (q *Queries) EnableDexSSOForGeneration(ctx context.Context, arg EnableDexSSOForGenerationParams) (EnableDexSSOForGenerationRow, error) {
	row := q.db.QueryRow(ctx, enableDexSSOForGeneration,
		arg.RuntimeGeneration,
		arg.DisplayName,
		arg.Config,
		arg.ClientID,
		arg.ClientSecretEncrypted,
	)
	var i EnableDexSSOForGenerationRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MigratedToDexAt,
	)
	return i, err
}

const getAPITokenByID = `-- name: GetAPITokenByID :one

SELECT id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at, allowed_cidrs, last_seen_remote_ip FROM api_tokens WHERE id = $1
`

// API Tokens
func (q *Queries) GetAPITokenByID(ctx context.Context, id uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowedCidrs,
		&i.LastSeenRemoteIp,
	)
	return i, err
}

const getEnabledSSOProviders = `-- name: GetEnabledSSOProviders :many
SELECT id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at, migrated_to_dex_at FROM sso_configurations WHERE is_enabled = true ORDER BY provider ASC
`

func (q *Queries) GetEnabledSSOProviders(ctx context.Context) ([]SsoConfiguration, error) {
	rows, err := q.db.Query(ctx, getEnabledSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoConfiguration{}
	for rows.Next() {
		var i SsoConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.IsEnabled,
			&i.DisplayName,
			&i.Config,
			&i.ClientID,
			&i.ClientSecretEncrypted,
			&i.AllowedOrganizations,
			&i.AllowedDomains,
			&i.AutoCreateUsers,
			&i.DefaultGlobalRoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MigratedToDexAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSSOConfigurationByID = `-- name: GetSSOConfigurationByID :one

SELECT id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at, migrated_to_dex_at FROM sso_configurations WHERE id = $1
`

// SSO Configurations
func (q *Queries) GetSSOConfigurationByID(ctx context.Context, id uuid.UUID) (SsoConfiguration, error) {
	row := q.db.QueryRow(ctx, getSSOConfigurationByID, id)
	var i SsoConfiguration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MigratedToDexAt,
	)
	return i, err
}

const getSSOConfigurationByProvider = `-- name: GetSSOConfigurationByProvider :one
SELECT id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at, migrated_to_dex_at FROM sso_configurations WHERE provider = $1
`

func (q *Queries) GetSSOConfigurationByProvider(ctx context.Context, provider string) (SsoConfiguration, error) {
	row := q.db.QueryRow(ctx, getSSOConfigurationByProvider, provider)
	var i SsoConfiguration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MigratedToDexAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at, allowed_cidrs, last_seen_remote_ip FROM api_tokens WHERE token_hash = $1 AND is_revoked = false
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowedCidrs,
		&i.LastSeenRemoteIp,
	)
	return i, err
}

const incrementFailedLoginCount = `-- name: IncrementFailedLoginCount :exec

UPDATE users
SET failed_login_count = failed_login_count + 1,
    failed_login_at    = $2,
    updated_at         = now()
WHERE id = $1
`

type IncrementFailedLoginCountParams struct {
	ID            uuid.UUID          `json:"id"`
	FailedLoginAt pgtype.Timestamptz `json:"failed_login_at"`
}

// Account lockout (NIST 800-53 AC-7).
//
// The Login handler increments on every bcrypt miss, locks the account
// when the running count exceeds the chart-tuned threshold, and resets
// on a successful auth. Auto-unlock is implicit: a locked_until in the
// past behaves like "not locked".
func (q *Queries) IncrementFailedLoginCount(ctx context.Context, arg IncrementFailedLoginCountParams) error {
	_, err := q.db.Exec(ctx, incrementFailedLoginCount, arg.ID, arg.FailedLoginAt)
	return err
}

const invalidateAllTokens = `-- name: InvalidateAllTokens :exec
UPDATE users
SET tokens_invalidated_at = $2,
    updated_at            = now()
WHERE id = $1
`

type InvalidateAllTokensParams struct {
	ID                  uuid.UUID          `json:"id"`
	TokensInvalidatedAt pgtype.Timestamptz `json:"tokens_invalidated_at"`
}

func (q *Queries) InvalidateAllTokens(ctx context.Context, arg InvalidateAllTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateAllTokens, arg.ID, arg.TokensInvalidatedAt)
	return err
}

const isJWTRevoked = `-- name: IsJWTRevoked :one
SELECT EXISTS (SELECT 1 FROM jwt_revocations WHERE jti = $1) AS revoked
`

func (q *Queries) IsJWTRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isJWTRevoked, jti)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const listSSOConfigurations = `-- name: ListSSOConfigurations :many
SELECT id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at, migrated_to_dex_at FROM sso_configurations ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListSSOConfigurationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSSOConfigurations(ctx context.Context, arg ListSSOConfigurationsParams) ([]SsoConfiguration, error) {
	rows, err := q.db.Query(ctx, listSSOConfigurations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoConfiguration{}
	for rows.Next() {
		var i SsoConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.IsEnabled,
			&i.DisplayName,
			&i.Config,
			&i.ClientID,
			&i.ClientSecretEncrypted,
			&i.AllowedOrganizations,
			&i.AllowedDomains,
			&i.AutoCreateUsers,
			&i.DefaultGlobalRoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MigratedToDexAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT id, user_id, name, token_hash, prefix, expires_at, last_used_at, is_revoked, scopes, created_at, updated_at, allowed_cidrs, last_seen_remote_ip FROM api_tokens WHERE user_id = $1 AND is_revoked = false ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTokensByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTokensByUser(ctx context.Context, arg ListTokensByUserParams) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.IsRevoked,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AllowedCidrs,
			&i.LastSeenRemoteIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
UPDATE users
SET locked_until  = $2,
    locked_reason = $3,
    updated_at    = now()
WHERE id = $1
`

type LockUserParams struct {
	ID           uuid.UUID          `json:"id"`
	LockedUntil  pgtype.Timestamptz `json:"locked_until"`
	LockedReason string             `json:"locked_reason"`
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil, arg.LockedReason)
	return err
}

const purgeExpiredJWTRevocations = `-- name: PurgeExpiredJWTRevocations :execrows
DELETE FROM jwt_revocations WHERE expires_at < now()
`

// Called by the nightly retention worker so the deny list doesn't grow
// without bound. Returning the rowcount lets the worker emit it as a
// metric.
func (q *Queries) PurgeExpiredJWTRevocations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredJWTRevocations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetFailedLoginCount = `-- name: ResetFailedLoginCount :exec
UPDATE users
SET failed_login_count = 0,
    failed_login_at    = NULL,
    locked_until       = NULL,
    locked_reason      = '',
    updated_at         = now()
WHERE id = $1
`

// Called on a successful login. Also clears any expired lock so the next
// failed-attempt cycle starts from a clean state.
func (q *Queries) ResetFailedLoginCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLoginCount, id)
	return err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens SET is_revoked = true WHERE id = $1
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, id)
	return err
}

const revokeJWT = `-- name: RevokeJWT :exec

INSERT INTO jwt_revocations (jti, user_id, expires_at, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (jti) DO NOTHING
`

type RevokeJWTParams struct {
	Jti       string    `json:"jti"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Reason    string    `json:"reason"`
}

// JWT session revocation.
//
// Two layers:
//  1. Per-JTI deny list. Used by Logout. ON CONFLICT lets the same JTI
//     be submitted multiple times (idempotent).
//  2. Per-user `tokens_invalidated_at` cutoff. Used by admin force-
//     logout to invalidate ALL active tokens for a user without having
//     to enumerate them — the JWT validator rejects any token whose
//     iat predates the cutoff.
func (q *Queries) RevokeJWT(ctx context.Context, arg RevokeJWTParams) error {
	_, err := q.db.Exec(ctx, revokeJWT,
		arg.Jti,
		arg.UserID,
		arg.ExpiresAt,
		arg.Reason,
	)
	return err
}

const unlockUser = `-- name: UnlockUser :exec
UPDATE users
SET failed_login_count = 0,
    failed_login_at    = NULL,
    locked_until       = NULL,
    locked_reason      = '',
    updated_at         = now()
WHERE id = $1
`

func (q *Queries) UnlockUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlockUser, id)
	return err
}

const updateAPITokenLastSeenIP = `-- name: UpdateAPITokenLastSeenIP :exec
UPDATE api_tokens SET last_seen_remote_ip = $2 WHERE id = $1
`

type UpdateAPITokenLastSeenIPParams struct {
	ID               uuid.UUID `json:"id"`
	LastSeenRemoteIp string    `json:"last_seen_remote_ip"`
}

// Best-effort stamp written from the auth middleware on every successful
// API-token request. The handler ignores write errors — this column is
// informational (operator UI / forensic review) and must NEVER cause a
// 5xx on the request path.
func (q *Queries) UpdateAPITokenLastSeenIP(ctx context.Context, arg UpdateAPITokenLastSeenIPParams) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastSeenIP, arg.ID, arg.LastSeenRemoteIp)
	return err
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastUsed, id)
	return err
}

const updateSSOConfiguration = `-- name: UpdateSSOConfiguration :one
UPDATE sso_configurations SET
    is_enabled = $2,
    display_name = $3,
    config = $4,
    client_id = $5,
    client_secret_encrypted = $6,
    allowed_organizations = $7,
    allowed_domains = $8,
    auto_create_users = $9,
    default_global_role_id = $10
WHERE id = $1
RETURNING id, provider, is_enabled, display_name, config, client_id, client_secret_encrypted, allowed_organizations, allowed_domains, auto_create_users, default_global_role_id, created_at, updated_at, migrated_to_dex_at
`

type UpdateSSOConfigurationParams struct {
	ID                    uuid.UUID       `json:"id"`
	IsEnabled             bool            `json:"is_enabled"`
	DisplayName           string          `json:"display_name"`
	Config                json.RawMessage `json:"config"`
	ClientID              string          `json:"client_id"`
	ClientSecretEncrypted string          `json:"client_secret_encrypted"`
	AllowedOrganizations  json.RawMessage `json:"allowed_organizations"`
	AllowedDomains        json.RawMessage `json:"allowed_domains"`
	AutoCreateUsers       bool            `json:"auto_create_users"`
	DefaultGlobalRoleID   pgtype.UUID     `json:"default_global_role_id"`
}

func (q *Queries) UpdateSSOConfiguration(ctx context.Context, arg UpdateSSOConfigurationParams) (SsoConfiguration, error) {
	row := q.db.QueryRow(ctx, updateSSOConfiguration,
		arg.ID,
		arg.IsEnabled,
		arg.DisplayName,
		arg.Config,
		arg.ClientID,
		arg.ClientSecretEncrypted,
		arg.AllowedOrganizations,
		arg.AllowedDomains,
		arg.AutoCreateUsers,
		arg.DefaultGlobalRoleID,
	)
	var i SsoConfiguration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.IsEnabled,
		&i.DisplayName,
		&i.Config,
		&i.ClientID,
		&i.ClientSecretEncrypted,
		&i.AllowedOrganizations,
		&i.AllowedDomains,
		&i.AutoCreateUsers,
		&i.DefaultGlobalRoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MigratedToDexAt,
	)
	return i, err
}
