// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_blessed.sql

package sqlc

import (
	"context"
)

const countBlessedCharts = `-- name: CountBlessedCharts :one
SELECT count(*) FROM catalog_blessed_charts
`

func (q *Queries) CountBlessedCharts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBlessedCharts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlessedChart = `-- name: CreateBlessedChart :exec
INSERT INTO catalog_blessed_charts
    (repo_url, chart_name, display_name, description, category, icon_url, mgmt_safe, version_policy, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateBlessedChartParams struct {
	RepoUrl       string `json:"repo_url"`
	ChartName     string `json:"chart_name"`
	DisplayName   string `json:"display_name"`
	Description   string `json:"description"`
	Category      string `json:"category"`
	IconUrl       string `json:"icon_url"`
	MgmtSafe      bool   `json:"mgmt_safe"`
	VersionPolicy string `json:"version_policy"`
	Source        string `json:"source"`
}

func (q *Queries) CreateBlessedChart(ctx context.Context, arg CreateBlessedChartParams) error {
	_, err := q.db.Exec(ctx, createBlessedChart,
		arg.RepoUrl,
		arg.ChartName,
		arg.DisplayName,
		arg.Description,
		arg.Category,
		arg.IconUrl,
		arg.MgmtSafe,
		arg.VersionPolicy,
		arg.Source,
	)
	return err
}

const deleteBlessedChartsBySource = `-- name: DeleteBlessedChartsBySource :exec
DELETE FROM catalog_blessed_charts WHERE source = $1
`

func (q *Queries) DeleteBlessedChartsBySource(ctx context.Context, source string) error {
	_, err := q.db.Exec(ctx, deleteBlessedChartsBySource, source)
	return err
}

const getBlessedChart = `-- name: GetBlessedChart :one
SELECT id, repo_url, chart_name, display_name, description, category, icon_url, mgmt_safe, version_policy, source, created_at, updated_at FROM catalog_blessed_charts WHERE repo_url = $1 AND chart_name = $2
`

type GetBlessedChartParams struct {
	RepoUrl   string `json:"repo_url"`
	ChartName string `json:"chart_name"`
}

func (q *Queries) GetBlessedChart(ctx context.Context, arg GetBlessedChartParams) (CatalogBlessedChart, error) {
	row := q.db.QueryRow(ctx, getBlessedChart, arg.RepoUrl, arg.ChartName)
	var i CatalogBlessedChart
	err := row.Scan(
		&i.ID,
		&i.RepoUrl,
		&i.ChartName,
		&i.DisplayName,
		&i.Description,
		&i.Category,
		&i.IconUrl,
		&i.MgmtSafe,
		&i.VersionPolicy,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlessedCharts = `-- name: ListBlessedCharts :many
SELECT id, repo_url, chart_name, display_name, description, category, icon_url, mgmt_safe, version_policy, source, created_at, updated_at FROM catalog_blessed_charts ORDER BY category ASC, chart_name ASC
`

func (q *Queries) ListBlessedCharts(ctx context.Context) ([]CatalogBlessedChart, error) {
	rows, err := q.db.Query(ctx, listBlessedCharts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogBlessedChart{}
	for rows.Next() {
		var i CatalogBlessedChart
		if err := rows.Scan(
			&i.ID,
			&i.RepoUrl,
			&i.ChartName,
			&i.DisplayName,
			&i.Description,
			&i.Category,
			&i.IconUrl,
			&i.MgmtSafe,
			&i.VersionPolicy,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDefaultHelmRepository = `-- name: UpsertDefaultHelmRepository :exec

INSERT INTO helm_repositories (name, url, repo_type, description, is_default, enabled)
VALUES ($1, $2, 'helm', $3, true, true)
ON CONFLICT (name) DO UPDATE SET
    url = EXCLUDED.url,
    description = EXCLUDED.description,
    is_default = true,
    updated_at = now()
`

type UpsertDefaultHelmRepositoryParams struct {
	Name        string `json:"name"`
	Url         string `json:"url"`
	Description string `json:"description"`
}

// Blessed-chart catalog overlays (sourced from astronomer-catalog/catalog.yaml).
// Seed/refresh a platform-default repo. On conflict we update the URL/description
// and re-assert is_default, but deliberately leave `enabled` alone so an operator
// who disabled a default repo keeps it disabled across reconciles.
func (q *Queries) UpsertDefaultHelmRepository(ctx context.Context, arg UpsertDefaultHelmRepositoryParams) error {
	_, err := q.db.Exec(ctx, upsertDefaultHelmRepository, arg.Name, arg.Url, arg.Description)
	return err
}
