// Migration 050 — multi-registry-per-cluster CRUD, hand-authored sqlc shim.
//
// The legacy GetClusterRegistryConfig / UpsertClusterRegistryConfig /
// DeleteClusterRegistryConfig in clusters.sql.go target the table by
// cluster_id under the assumption of one row per cluster — kept for
// back-compat with the existing PUT /clusters/{id}/registry/ route. This
// file holds the row-id-based CRUD the new admin-UX endpoints
// (POST /clusters/{cluster_id}/registries/, …) use, plus a `:many` lister
// per cluster and a global lister for the periodic drift sweep.
//
// File suffix `_ext` is intentional: the canonical sqlc-CLI output for the
// clusters query group is internal/db/sqlc/clusters.sql.go. That file is
// auto-regenerated by repo tooling, which can clobber hand additions.
// Putting these new queries in a separate file keeps them out of the
// regeneration target so the multi-registry handler keeps building across
// successive sqlc-generate runs.

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const clusterRegistryConfigSelectColumns = `id, cluster_id, private_registry_url, registry_username, registry_password, insecure, ca_bundle, created_at, updated_at, namespaces, inject_default_sa, secret_name, last_applied_at, last_apply_error`

func scanClusterRegistryConfigRow(row interface {
	Scan(dest ...any) error
}) (ClusterRegistryConfig, error) {
	var i ClusterRegistryConfig
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.PrivateRegistryUrl,
		&i.RegistryUsername,
		&i.RegistryPassword,
		&i.Insecure,
		&i.CaBundle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Namespaces,
		&i.InjectDefaultSa,
		&i.SecretName,
		&i.LastAppliedAt,
		&i.LastApplyError,
	)
	return i, err
}

const listClusterRegistryConfigs = `-- name: ListClusterRegistryConfigs :many
SELECT ` + clusterRegistryConfigSelectColumns + `
FROM cluster_registry_configs
WHERE cluster_id = $1
ORDER BY created_at ASC`

func (q *Queries) ListClusterRegistryConfigs(ctx context.Context, clusterID uuid.UUID) ([]ClusterRegistryConfig, error) {
	rows, err := q.db.Query(ctx, listClusterRegistryConfigs, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClusterRegistryConfig{}
	for rows.Next() {
		i, err := scanClusterRegistryConfigRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllClusterRegistryConfigs = `-- name: ListAllClusterRegistryConfigs :many
SELECT ` + clusterRegistryConfigSelectColumns + `
FROM cluster_registry_configs
ORDER BY cluster_id, created_at ASC`

func (q *Queries) ListAllClusterRegistryConfigs(ctx context.Context) ([]ClusterRegistryConfig, error) {
	rows, err := q.db.Query(ctx, listAllClusterRegistryConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClusterRegistryConfig{}
	for rows.Next() {
		i, err := scanClusterRegistryConfigRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClusterRegistryConfigByID = `-- name: GetClusterRegistryConfigByID :one
SELECT ` + clusterRegistryConfigSelectColumns + `
FROM cluster_registry_configs WHERE id = $1`

func (q *Queries) GetClusterRegistryConfigByID(ctx context.Context, id uuid.UUID) (ClusterRegistryConfig, error) {
	row := q.db.QueryRow(ctx, getClusterRegistryConfigByID, id)
	return scanClusterRegistryConfigRow(row)
}

const createClusterRegistryConfig = `-- name: CreateClusterRegistryConfig :one
INSERT INTO cluster_registry_configs (
    cluster_id,
    private_registry_url,
    registry_username,
    registry_password,
    insecure,
    ca_bundle,
    namespaces,
    inject_default_sa,
    secret_name
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING ` + clusterRegistryConfigSelectColumns

type CreateClusterRegistryConfigParams struct {
	ClusterID          uuid.UUID       `json:"cluster_id"`
	PrivateRegistryUrl string          `json:"private_registry_url"`
	RegistryUsername   string          `json:"registry_username"`
	RegistryPassword   string          `json:"registry_password"`
	Insecure           bool            `json:"insecure"`
	CaBundle           string          `json:"ca_bundle"`
	Namespaces         json.RawMessage `json:"namespaces"`
	InjectDefaultSa    bool            `json:"inject_default_sa"`
	SecretName         string          `json:"secret_name"`
}

func (q *Queries) CreateClusterRegistryConfig(ctx context.Context, arg CreateClusterRegistryConfigParams) (ClusterRegistryConfig, error) {
	row := q.db.QueryRow(ctx, createClusterRegistryConfig,
		arg.ClusterID,
		arg.PrivateRegistryUrl,
		arg.RegistryUsername,
		arg.RegistryPassword,
		arg.Insecure,
		arg.CaBundle,
		arg.Namespaces,
		arg.InjectDefaultSa,
		arg.SecretName,
	)
	return scanClusterRegistryConfigRow(row)
}

const updateClusterRegistryConfig = `-- name: UpdateClusterRegistryConfig :one
UPDATE cluster_registry_configs SET
    private_registry_url = $2,
    registry_username    = $3,
    registry_password    = $4,
    insecure             = $5,
    ca_bundle            = $6,
    namespaces           = $7,
    inject_default_sa    = $8,
    secret_name          = $9,
    updated_at           = now()
WHERE id = $1
RETURNING ` + clusterRegistryConfigSelectColumns

type UpdateClusterRegistryConfigParams struct {
	ID                 uuid.UUID       `json:"id"`
	PrivateRegistryUrl string          `json:"private_registry_url"`
	RegistryUsername   string          `json:"registry_username"`
	RegistryPassword   string          `json:"registry_password"`
	Insecure           bool            `json:"insecure"`
	CaBundle           string          `json:"ca_bundle"`
	Namespaces         json.RawMessage `json:"namespaces"`
	InjectDefaultSa    bool            `json:"inject_default_sa"`
	SecretName         string          `json:"secret_name"`
}

func (q *Queries) UpdateClusterRegistryConfig(ctx context.Context, arg UpdateClusterRegistryConfigParams) (ClusterRegistryConfig, error) {
	row := q.db.QueryRow(ctx, updateClusterRegistryConfig,
		arg.ID,
		arg.PrivateRegistryUrl,
		arg.RegistryUsername,
		arg.RegistryPassword,
		arg.Insecure,
		arg.CaBundle,
		arg.Namespaces,
		arg.InjectDefaultSa,
		arg.SecretName,
	)
	return scanClusterRegistryConfigRow(row)
}

const deleteClusterRegistryConfigByID = `-- name: DeleteClusterRegistryConfigByID :exec
DELETE FROM cluster_registry_configs WHERE id = $1`

func (q *Queries) DeleteClusterRegistryConfigByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClusterRegistryConfigByID, id)
	return err
}

const markClusterRegistryApplied = `-- name: MarkClusterRegistryApplied :exec
UPDATE cluster_registry_configs SET
    last_applied_at  = now(),
    last_apply_error = ''
WHERE id = $1`

func (q *Queries) MarkClusterRegistryApplied(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markClusterRegistryApplied, id)
	return err
}

const markClusterRegistryApplyError = `-- name: MarkClusterRegistryApplyError :exec
UPDATE cluster_registry_configs SET
    last_apply_error = $2
WHERE id = $1`

type MarkClusterRegistryApplyErrorParams struct {
	ID             uuid.UUID `json:"id"`
	LastApplyError string    `json:"last_apply_error"`
}

func (q *Queries) MarkClusterRegistryApplyError(ctx context.Context, arg MarkClusterRegistryApplyErrorParams) error {
	_, err := q.db.Exec(ctx, markClusterRegistryApplyError, arg.ID, arg.LastApplyError)
	return err
}
