// Hand-rolled compliance-export queries. Kept in the sqlc package
// alongside the generated code (mirrors audit_v1_manual.go) so the
// compliance handler can read these via the same *sqlc.Queries the rest
// of the platform uses.
//
// These queries are NOT generated by `sqlc generate` — the sqlc-CLI
// isn't part of the local Makefile path, so the file format the
// generator emits is replicated by hand. Each query carries the
// `:many` / `:one` annotation a future regen could pick up.
//
// Why hand-rolled:
//
//  1. ListAuditLogV1ForRange streams across the partitioned audit_log
//     table by ASC time order — the existing ListAuditLogV1 query
//     sorts DESC and paginates by LIMIT/OFFSET (fine for a UI, awful
//     for an export of millions of rows). The compliance writer
//     pages in ASC chunks keyed on (created_at, id) so the data set
//     stays consistent under concurrent inserts.
//
//  2. ListAllRoleBindingsWithRoleNames is the all-users variant of
//     the existing ListUserBindingsWithRoles. Mirrors that query's
//     shape exactly so callers can switch between "for one user" and
//     "for everyone" without rewriting the row scanner.
//
//  3. ListAPITokensForCompliance projects the `allowed_cidrs` and
//     `last_seen_remote_ip` columns added in migration 044. The
//     ApiToken sqlc model is stale (those columns aren't in the
//     generated struct yet); rather than block on a sqlc regen this
//     query selects directly into a compliance-specific row type.
package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// ── audit_log range query for the export streamer ────────────────────────

// ListAuditLogV1ForRangeParams scopes a streamed audit-log read. The
// page key is (created_at, id) ascending; AfterCreatedAt + AfterID
// are exclusive — pass the previous page's last row to advance. On
// the first page pass `from` for AfterCreatedAt and uuid.Nil for AfterID.
type ListAuditLogV1ForRangeParams struct {
	From           time.Time `json:"from"`
	To             time.Time `json:"to"`
	AfterCreatedAt time.Time `json:"after_created_at"`
	AfterID        uuid.UUID `json:"after_id"`
	Limit          int32     `json:"limit"`
}

// listAuditLogV1ForRange streams rows in ASC time order so the
// compliance writer can page through millions of entries without
// triggering OFFSET-induced re-scans on the partitioned table. The
// (created_at, id) tuple comparison is the standard keyset-pagination
// pattern; PostgreSQL evaluates it row-wise against the natural
// partitioning + index order.
const listAuditLogV1ForRange = `
SELECT id, created_at, schema_version, source, correlation_id, user_id,
       actor_auth_method, action, resource_type, resource_id,
       resource_name, http_method, path, status_code, duration_ms,
       request_id, ip_address, user_agent, detail
FROM audit_log
WHERE created_at >= $1
  AND created_at <  $2
  AND (created_at, id) > ($3, $4)
ORDER BY created_at ASC, id ASC
LIMIT $5
`

// ListAuditLogV1ForRange returns up to Limit rows from the closed-open
// range [From, To), strictly after (AfterCreatedAt, AfterID). The
// compliance streamer calls this in a loop until the returned slice is
// shorter than Limit.
func (q *Queries) ListAuditLogV1ForRange(ctx context.Context, arg ListAuditLogV1ForRangeParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogV1ForRange,
		arg.From, arg.To, arg.AfterCreatedAt, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SchemaVersion,
			&i.Source,
			&i.CorrelationID,
			&i.UserID,
			&i.ActorAuthMethod,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.HttpMethod,
			&i.Path,
			&i.StatusCode,
			&i.DurationMs,
			&i.RequestID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

const countAuditLogV1ForRange = `
SELECT count(*) FROM audit_log
WHERE created_at >= $1 AND created_at < $2
`

// CountAuditLogV1ForRange is the size estimate the compliance handler
// uses to decide between the inline streaming path and the async
// task path. Over ~100K rows the streaming path takes long enough that
// an HTTP request is the wrong transport.
func (q *Queries) CountAuditLogV1ForRange(ctx context.Context, from, to time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogV1ForRange, from, to)
	var n int64
	err := row.Scan(&n)
	return n, err
}

// ── all-users RBAC snapshot ───────────────────────────────────────────────

// ListAllRoleBindingsWithRoleNamesRow mirrors ListUserBindingsWithRolesRow
// but adds the binding's user_id + group + source. The compliance
// snapshot lists every binding across the platform — both the per-user
// rows (UserID.Valid==true) and the per-group rows (UserID.Valid==false,
// Group populated). Source is the migration-042 column distinguishing
// 'manual' from 'group_sync'.
type ListAllRoleBindingsWithRoleNamesRow struct {
	Scope     string      `json:"scope"`
	BindingID uuid.UUID   `json:"binding_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Group     string      `json:"group"`
	RoleID    uuid.UUID   `json:"role_id"`
	RoleName  string      `json:"role_name"`
	ClusterID pgtype.UUID `json:"cluster_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Source    string      `json:"source"`
	CreatedAt time.Time   `json:"created_at"`
}

const listAllRoleBindingsWithRoleNames = `
SELECT
    'global'::text                  AS scope,
    gb.id                           AS binding_id,
    gb.user_id                      AS user_id,
    gb."group"                      AS "group",
    gb.role_id                      AS role_id,
    gr.name                         AS role_name,
    NULL::uuid                      AS cluster_id,
    NULL::uuid                      AS project_id,
    COALESCE(gb.source, 'manual')   AS source,
    gb.created_at                   AS created_at
FROM global_role_bindings gb
JOIN global_roles gr ON gr.id = gb.role_id
UNION ALL
SELECT
    'cluster'::text                 AS scope,
    cb.id                           AS binding_id,
    cb.user_id                      AS user_id,
    cb."group"                      AS "group",
    cb.role_id                      AS role_id,
    cr.name                         AS role_name,
    cb.cluster_id                   AS cluster_id,
    NULL::uuid                      AS project_id,
    COALESCE(cb.source, 'manual')   AS source,
    cb.created_at                   AS created_at
FROM cluster_role_bindings cb
JOIN cluster_roles cr ON cr.id = cb.role_id
UNION ALL
SELECT
    'project'::text                 AS scope,
    pb.id                           AS binding_id,
    pb.user_id                      AS user_id,
    pb."group"                      AS "group",
    pb.role_id                      AS role_id,
    pr.name                         AS role_name,
    NULL::uuid                      AS cluster_id,
    pb.project_id                   AS project_id,
    COALESCE(pb.source, 'manual')   AS source,
    pb.created_at                   AS created_at
FROM project_role_bindings pb
JOIN project_roles pr ON pr.id = pb.role_id
ORDER BY scope ASC, created_at ASC
`

// ListAllRoleBindingsWithRoleNames is the export-scope analogue of
// ListUserBindingsWithRoles — it returns every binding across the
// three RBAC tables joined to its role name, with the 'manual' vs
// 'group_sync' source discriminator from migration 042.
func (q *Queries) ListAllRoleBindingsWithRoleNames(ctx context.Context) ([]ListAllRoleBindingsWithRoleNamesRow, error) {
	rows, err := q.db.Query(ctx, listAllRoleBindingsWithRoleNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []ListAllRoleBindingsWithRoleNamesRow{}
	for rows.Next() {
		var i ListAllRoleBindingsWithRoleNamesRow
		if err := rows.Scan(
			&i.Scope,
			&i.BindingID,
			&i.UserID,
			&i.Group,
			&i.RoleID,
			&i.RoleName,
			&i.ClusterID,
			&i.ProjectID,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// ── compliance projects projection ────────────────────────────────────────

// ComplianceProjectRow is the projection the policy-snapshot.json writer
// reads. It carries exactly the policy-relevant fields — no
// `namespaces` / `limit_range` / heartbeat columns the operator
// dashboard cares about but auditors don't.
type ComplianceProjectRow struct {
	ID                       uuid.UUID `json:"id"`
	Name                     string    `json:"name"`
	DisplayName              string    `json:"display_name"`
	ClusterID                uuid.UUID `json:"cluster_id"`
	PodSecurityProfile       string    `json:"pod_security_profile"`
	NetworkPolicyMode        string    `json:"network_policy_mode"`
	ResourceQuotaCpuLimit    string    `json:"resource_quota_cpu_limit"`
	ResourceQuotaMemoryLimit string    `json:"resource_quota_memory_limit"`
	ResourceQuotaPodCount    int32     `json:"resource_quota_pod_count"`
	CreatedAt                time.Time `json:"created_at"`
}

const listAllProjectsForCompliance = `
SELECT id, name, display_name, cluster_id,
       pod_security_profile, network_policy_mode,
       resource_quota_cpu_limit, resource_quota_memory_limit,
       resource_quota_pod_count, created_at
FROM projects
ORDER BY created_at ASC
`

// ListAllProjectsForCompliance returns every project with just the
// policy fields the compliance bundle needs. Distinct from
// ListProjects (which returns the full row + namespaces JSONB) to keep
// the export read cheap when there are thousands of projects.
func (q *Queries) ListAllProjectsForCompliance(ctx context.Context) ([]ComplianceProjectRow, error) {
	rows, err := q.db.Query(ctx, listAllProjectsForCompliance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []ComplianceProjectRow{}
	for rows.Next() {
		var i ComplianceProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.ClusterID,
			&i.PodSecurityProfile,
			&i.NetworkPolicyMode,
			&i.ResourceQuotaCpuLimit,
			&i.ResourceQuotaMemoryLimit,
			&i.ResourceQuotaPodCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// ── all-users API token projection ────────────────────────────────────────

// ComplianceAPITokenRow projects API token rows with the migration-044
// columns (allowed_cidrs, last_seen_remote_ip). The generated ApiToken
// model is stale (those columns aren't there yet); this struct
// includes them. Token hash is intentionally omitted — the compliance
// bundle MUST NOT include any decrypted-or-decryptable secret material,
// and a bcrypt-style hash counts as "decryptable enough" under SOC 2
// CC6.7 (defense-in-depth — even hashed credentials are subject to
// offline cracking attempts).
type ComplianceAPITokenRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Username         string             `json:"username"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	Prefix           string             `json:"prefix"`
	Scopes           json.RawMessage    `json:"scopes"`
	AllowedCIDRs     string             `json:"allowed_cidrs"`
	LastSeenRemoteIP string             `json:"last_seen_remote_ip"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	IsRevoked        bool               `json:"is_revoked"`
	CreatedAt        time.Time          `json:"created_at"`
}

// listAPITokensForCompliance LEFT-JOINs users so the export carries
// the human-readable identity columns instead of just the UUID. The
// LEFT JOIN tolerates a deleted user where the token row is still
// present (ON DELETE CASCADE normally kills it, but defensive — a
// migration could change the FK behaviour later).
const listAPITokensForCompliance = `
SELECT t.id, t.user_id, COALESCE(u.username, ''), COALESCE(u.email, ''),
       t.name, t.prefix, t.scopes,
       t.allowed_cidrs, t.last_seen_remote_ip,
       t.expires_at, t.last_used_at, t.is_revoked, t.created_at
FROM api_tokens t
LEFT JOIN users u ON u.id = t.user_id
ORDER BY t.created_at ASC
`

// ListAPITokensForCompliance returns every API token row with user
// identity joined in and the hash + raw secret material stripped. The
// `WHERE is_revoked = false` filter is deliberately NOT applied —
// auditors need the historical record of issued credentials, including
// revoked ones, so they can trace incident response.
func (q *Queries) ListAPITokensForCompliance(ctx context.Context) ([]ComplianceAPITokenRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensForCompliance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []ComplianceAPITokenRow{}
	for rows.Next() {
		var i ComplianceAPITokenRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Name,
			&i.Prefix,
			&i.Scopes,
			&i.AllowedCIDRs,
			&i.LastSeenRemoteIP,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.IsRevoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}
