// Hand-rolled compliance-baselines queries (migration 064).
//
// Sprint 17 introduces the four-preset compliance baselines feature.
// Kept in the sqlc package alongside the generated code (same pattern
// as compliance_manual.go / audit_v1_manual.go / quotas.sql.go) so the
// baselines handler + the internal/compliance apply engine can read
// these via the same *sqlc.Queries the rest of the platform uses.
//
// These queries are NOT generated by `sqlc generate` — the sqlc CLI
// isn't part of the local Makefile path (one pre-existing query in
// compliance.sql fails the upstream parser) so the file format the
// generator emits is replicated by hand. Each query carries the
// `:many` / `:one` / `:exec` annotation a future regen could pick up.
package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// ── baseline registry CRUD ────────────────────────────────────────────

const listComplianceBaselines = `-- name: ListComplianceBaselines :many
SELECT id, slug, name, description, version, spec, enabled, created_at, updated_at
FROM compliance_baselines
ORDER BY slug ASC
`

// ListComplianceBaselines returns every baseline row sorted by slug.
// Used by the GET /admin/compliance-baselines/ handler which then
// joins each row with the in-code Registry() to surface the canonical
// spec.
func (q *Queries) ListComplianceBaselines(ctx context.Context) ([]ComplianceBaseline, error) {
	rows, err := q.db.Query(ctx, listComplianceBaselines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []ComplianceBaseline{}
	for rows.Next() {
		var i ComplianceBaseline
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Spec,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

const getComplianceBaseline = `-- name: GetComplianceBaseline :one
SELECT id, slug, name, description, version, spec, enabled, created_at, updated_at
FROM compliance_baselines
WHERE id = $1
`

// GetComplianceBaseline returns one baseline by UUID. Returns
// pgx.ErrNoRows when the slug isn't seeded — handlers translate that
// to a 404.
func (q *Queries) GetComplianceBaseline(ctx context.Context, id uuid.UUID) (ComplianceBaseline, error) {
	row := q.db.QueryRow(ctx, getComplianceBaseline, id)
	var i ComplianceBaseline
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Spec,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplianceBaselineBySlug = `-- name: GetComplianceBaselineBySlug :one
SELECT id, slug, name, description, version, spec, enabled, created_at, updated_at
FROM compliance_baselines
WHERE slug = $1
`

// GetComplianceBaselineBySlug looks a baseline up by its stable slug.
// Used in tests + when reconciling the seeded rows against the
// in-code Registry().
func (q *Queries) GetComplianceBaselineBySlug(ctx context.Context, slug string) (ComplianceBaseline, error) {
	row := q.db.QueryRow(ctx, getComplianceBaselineBySlug, slug)
	var i ComplianceBaseline
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Spec,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ── applications history ──────────────────────────────────────────────

const createComplianceBaselineApplication = `-- name: CreateComplianceBaselineApplication :one
INSERT INTO compliance_baseline_applications (
    baseline_id, previous_state, applied_by, notes, status
) VALUES ($1, $2, $3, $4, 'applied')
RETURNING id, baseline_id, previous_state, applied_by, applied_at, status, reverted_at, reverted_by, notes
`

// CreateComplianceBaselineApplicationParams: applied_at + status come
// from defaults; the caller supplies baseline_id, the captured
// previous_state JSON, the actor user_id (nullable for system-actor
// future use), and operator-supplied notes ("".empty is legal).
type CreateComplianceBaselineApplicationParams struct {
	BaselineID    uuid.UUID       `json:"baseline_id"`
	PreviousState json.RawMessage `json:"previous_state"`
	AppliedBy     pgtype.UUID     `json:"applied_by"`
	Notes         string          `json:"notes"`
}

// CreateComplianceBaselineApplication records one "Apply" event.
// MUST be called inside the same tx as the baseline writes so a
// partial-apply rollback also rolls back the application row.
func (q *Queries) CreateComplianceBaselineApplication(ctx context.Context, arg CreateComplianceBaselineApplicationParams) (ComplianceBaselineApplication, error) {
	row := q.db.QueryRow(ctx, createComplianceBaselineApplication,
		arg.BaselineID,
		arg.PreviousState,
		arg.AppliedBy,
		arg.Notes,
	)
	var i ComplianceBaselineApplication
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.PreviousState,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.Status,
		&i.RevertedAt,
		&i.RevertedBy,
		&i.Notes,
	)
	return i, err
}

const listComplianceBaselineApplications = `-- name: ListComplianceBaselineApplications :many
SELECT id, baseline_id, previous_state, applied_by, applied_at, status, reverted_at, reverted_by, notes
FROM compliance_baseline_applications
ORDER BY applied_at DESC
LIMIT $1
`

// ListComplianceBaselineApplications returns the most-recent N apply
// events. Bounded by limit so the history endpoint doesn't accidentally
// stream thousands of rows; the UI pages via the operator-supplied
// limit query param.
func (q *Queries) ListComplianceBaselineApplications(ctx context.Context, limit int32) ([]ComplianceBaselineApplication, error) {
	rows, err := q.db.Query(ctx, listComplianceBaselineApplications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []ComplianceBaselineApplication{}
	for rows.Next() {
		var i ComplianceBaselineApplication
		if err := rows.Scan(
			&i.ID,
			&i.BaselineID,
			&i.PreviousState,
			&i.AppliedBy,
			&i.AppliedAt,
			&i.Status,
			&i.RevertedAt,
			&i.RevertedBy,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

const getComplianceBaselineApplication = `-- name: GetComplianceBaselineApplication :one
SELECT id, baseline_id, previous_state, applied_by, applied_at, status, reverted_at, reverted_by, notes
FROM compliance_baseline_applications
WHERE id = $1
`

// GetComplianceBaselineApplication fetches one application by ID.
// Used by Revert to load the previous_state snapshot.
func (q *Queries) GetComplianceBaselineApplication(ctx context.Context, id uuid.UUID) (ComplianceBaselineApplication, error) {
	row := q.db.QueryRow(ctx, getComplianceBaselineApplication, id)
	var i ComplianceBaselineApplication
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.PreviousState,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.Status,
		&i.RevertedAt,
		&i.RevertedBy,
		&i.Notes,
	)
	return i, err
}

const getActiveComplianceBaselineApplication = `-- name: GetActiveComplianceBaselineApplication :one
SELECT id, baseline_id, previous_state, applied_by, applied_at, status, reverted_at, reverted_by, notes
FROM compliance_baseline_applications
WHERE status = 'applied'
ORDER BY applied_at DESC
LIMIT 1
`

// GetActiveComplianceBaselineApplication returns the single most-recent
// row whose status is 'applied'. Pgx returns ErrNoRows when no baseline
// has ever been applied — handler renders that as `{"active": null}`.
func (q *Queries) GetActiveComplianceBaselineApplication(ctx context.Context) (ComplianceBaselineApplication, error) {
	row := q.db.QueryRow(ctx, getActiveComplianceBaselineApplication)
	var i ComplianceBaselineApplication
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.PreviousState,
		&i.AppliedBy,
		&i.AppliedAt,
		&i.Status,
		&i.RevertedAt,
		&i.RevertedBy,
		&i.Notes,
	)
	return i, err
}

const markComplianceBaselineApplicationReverted = `-- name: MarkComplianceBaselineApplicationReverted :exec
UPDATE compliance_baseline_applications
SET status = 'reverted',
    reverted_at = now(),
    reverted_by = $2
WHERE id = $1
  AND status = 'applied'
`

// MarkComplianceBaselineApplicationRevertedParams: id is the
// application row to revert; reverted_by is the operator UUID (may be
// NULL for system reverts in some future use case).
type MarkComplianceBaselineApplicationRevertedParams struct {
	ID         uuid.UUID   `json:"id"`
	RevertedBy pgtype.UUID `json:"reverted_by"`
}

// MarkComplianceBaselineApplicationReverted flips the status of an
// applied row to reverted. The `AND status = 'applied'` guards
// against double-revert — calling this twice is a no-op rather than an
// error. The internal/compliance.Revert engine wraps this with the
// state-restore writes in a single tx.
func (q *Queries) MarkComplianceBaselineApplicationReverted(ctx context.Context, arg MarkComplianceBaselineApplicationRevertedParams) error {
	_, err := q.db.Exec(ctx, markComplianceBaselineApplicationReverted, arg.ID, arg.RevertedBy)
	return err
}
