// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dex_operations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDexOperation = `-- name: ClaimDexOperation :one
UPDATE dex_operations
SET status = 'running', phase = 'reconciling', attempt_count = attempt_count + 1,
    locked_until = $1, error_code = '', updated_at = now()
WHERE id = $2
  AND (status IN ('pending', 'retrying') OR (status = 'running' AND locked_until <= now()))
RETURNING id, action, target_id, runtime_generation, idempotency_scope, idempotency_key, request_digest, payload_encrypted, status, phase, attempt_count, locked_until, error_code, created_by, completed_at, created_at, updated_at
`

type ClaimDexOperationParams struct {
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) ClaimDexOperation(ctx context.Context, arg ClaimDexOperationParams) (DexOperation, error) {
	row := q.db.QueryRow(ctx, claimDexOperation, arg.LockedUntil, arg.ID)
	var i DexOperation
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetID,
		&i.RuntimeGeneration,
		&i.IdempotencyScope,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PayloadEncrypted,
		&i.Status,
		&i.Phase,
		&i.AttemptCount,
		&i.LockedUntil,
		&i.ErrorCode,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDexOperation = `-- name: GetDexOperation :one
SELECT id, action, target_id, runtime_generation, idempotency_scope, idempotency_key, request_digest, payload_encrypted, status, phase, attempt_count, locked_until, error_code, created_by, completed_at, created_at, updated_at FROM dex_operations WHERE id = $1
`

func (q *Queries) GetDexOperation(ctx context.Context, id uuid.UUID) (DexOperation, error) {
	row := q.db.QueryRow(ctx, getDexOperation, id)
	var i DexOperation
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetID,
		&i.RuntimeGeneration,
		&i.IdempotencyScope,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PayloadEncrypted,
		&i.Status,
		&i.Phase,
		&i.AttemptCount,
		&i.LockedUntil,
		&i.ErrorCode,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDexOperationFailed = `-- name: MarkDexOperationFailed :exec
UPDATE dex_operations
SET status = 'failed', phase = 'completed', locked_until = NULL,
    error_code = $1, completed_at = COALESCE(completed_at, now()), updated_at = now()
WHERE id = $2 AND status = 'running'
`

type MarkDexOperationFailedParams struct {
	ErrorCode string    `json:"error_code"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) MarkDexOperationFailed(ctx context.Context, arg MarkDexOperationFailedParams) error {
	_, err := q.db.Exec(ctx, markDexOperationFailed, arg.ErrorCode, arg.ID)
	return err
}

const markDexOperationRetrying = `-- name: MarkDexOperationRetrying :exec
UPDATE dex_operations
SET status = 'retrying', locked_until = NULL, error_code = $1, updated_at = now()
WHERE id = $2 AND status = 'running'
`

type MarkDexOperationRetryingParams struct {
	ErrorCode string    `json:"error_code"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) MarkDexOperationRetrying(ctx context.Context, arg MarkDexOperationRetryingParams) error {
	_, err := q.db.Exec(ctx, markDexOperationRetrying, arg.ErrorCode, arg.ID)
	return err
}

const markDexOperationSucceeded = `-- name: MarkDexOperationSucceeded :exec
UPDATE dex_operations
SET status = 'succeeded', phase = 'completed', locked_until = NULL,
    error_code = '', completed_at = COALESCE(completed_at, now()), updated_at = now()
WHERE id = $1 AND status = 'running'
`

func (q *Queries) MarkDexOperationSucceeded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDexOperationSucceeded, id)
	return err
}

const queueDexOperation = `-- name: QueueDexOperation :one
WITH operation AS (
    UPDATE dex_operations
    SET runtime_generation = $1, updated_at = now()
    WHERE dex_operations.id = $2 AND dex_operations.status = 'pending'
    RETURNING id, action, target_id, runtime_generation, idempotency_scope, idempotency_key, request_digest, payload_encrypted, status, phase, attempt_count, locked_until, error_code, created_by, completed_at, created_at, updated_at
), queued AS (
    INSERT INTO task_outbox (
        dedupe_key, task_type, payload, queue_name, max_retry,
        timeout_seconds, unique_seconds, max_delivery_attempts, next_attempt_at
    )
    SELECT 'dex-operation:' || id::text, 'dex:apply_operation',
           convert_to(jsonb_build_object('operation_id', id::text)::text, 'UTF8'),
           'tunnel', 8, 120, 1800, 20, now()
    FROM operation
    ON CONFLICT (dedupe_key) WHERE dedupe_key IS NOT NULL DO NOTHING
    RETURNING id
)
SELECT operation.id, operation.action, operation.target_id, operation.runtime_generation, operation.idempotency_scope, operation.idempotency_key, operation.request_digest, operation.payload_encrypted, operation.status, operation.phase, operation.attempt_count, operation.locked_until, operation.error_code, operation.created_by, operation.completed_at, operation.created_at, operation.updated_at FROM operation CROSS JOIN queued
`

type QueueDexOperationParams struct {
	RuntimeGeneration int64     `json:"runtime_generation"`
	ID                uuid.UUID `json:"id"`
}

type QueueDexOperationRow struct {
	ID                uuid.UUID          `json:"id"`
	Action            string             `json:"action"`
	TargetID          uuid.UUID          `json:"target_id"`
	RuntimeGeneration int64              `json:"runtime_generation"`
	IdempotencyScope  string             `json:"idempotency_scope"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestDigest     string             `json:"request_digest"`
	PayloadEncrypted  string             `json:"payload_encrypted"`
	Status            string             `json:"status"`
	Phase             string             `json:"phase"`
	AttemptCount      int32              `json:"attempt_count"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	ErrorCode         string             `json:"error_code"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

func (q *Queries) QueueDexOperation(ctx context.Context, arg QueueDexOperationParams) (QueueDexOperationRow, error) {
	row := q.db.QueryRow(ctx, queueDexOperation, arg.RuntimeGeneration, arg.ID)
	var i QueueDexOperationRow
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetID,
		&i.RuntimeGeneration,
		&i.IdempotencyScope,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PayloadEncrypted,
		&i.Status,
		&i.Phase,
		&i.AttemptCount,
		&i.LockedUntil,
		&i.ErrorCode,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recoverDexOperationOutbox = `-- name: RecoverDexOperationOutbox :execrows
UPDATE task_outbox outbox
SET status = 'pending', attempt_count = 0, next_attempt_at = now(),
    locked_until = NULL, delivered_at = NULL, last_error = '', updated_at = now()
FROM dex_operations operation
WHERE outbox.dedupe_key = 'dex-operation:' || operation.id::text
  AND outbox.status = 'delivered'
  AND (
      (operation.status IN ('pending', 'retrying') AND operation.updated_at <= $1)
      OR (operation.status = 'running' AND operation.locked_until <= now())
  )
`

func (q *Queries) RecoverDexOperationOutbox(ctx context.Context, staleBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, recoverDexOperationOutbox, staleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveDexOperation = `-- name: ReserveDexOperation :one
INSERT INTO dex_operations (
    id, action, target_id, idempotency_scope, idempotency_key,
    request_digest, payload_encrypted, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8
)
ON CONFLICT (idempotency_scope, idempotency_key) DO UPDATE
SET idempotency_key = dex_operations.idempotency_key
WHERE dex_operations.id = EXCLUDED.id
  AND dex_operations.action = EXCLUDED.action
  AND dex_operations.target_id = EXCLUDED.target_id
  AND dex_operations.request_digest = EXCLUDED.request_digest
RETURNING dex_operations.id, dex_operations.action, dex_operations.target_id, dex_operations.runtime_generation, dex_operations.idempotency_scope, dex_operations.idempotency_key, dex_operations.request_digest, dex_operations.payload_encrypted, dex_operations.status, dex_operations.phase, dex_operations.attempt_count, dex_operations.locked_until, dex_operations.error_code, dex_operations.created_by, dex_operations.completed_at, dex_operations.created_at, dex_operations.updated_at, (xmax = 0) AS created
`

type ReserveDexOperationParams struct {
	ID               uuid.UUID `json:"id"`
	Action           string    `json:"action"`
	TargetID         uuid.UUID `json:"target_id"`
	IdempotencyScope string    `json:"idempotency_scope"`
	IdempotencyKey   string    `json:"idempotency_key"`
	RequestDigest    string    `json:"request_digest"`
	PayloadEncrypted string    `json:"payload_encrypted"`
	CreatedBy        uuid.UUID `json:"created_by"`
}

type ReserveDexOperationRow struct {
	ID                uuid.UUID          `json:"id"`
	Action            string             `json:"action"`
	TargetID          uuid.UUID          `json:"target_id"`
	RuntimeGeneration int64              `json:"runtime_generation"`
	IdempotencyScope  string             `json:"idempotency_scope"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestDigest     string             `json:"request_digest"`
	PayloadEncrypted  string             `json:"payload_encrypted"`
	Status            string             `json:"status"`
	Phase             string             `json:"phase"`
	AttemptCount      int32              `json:"attempt_count"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	ErrorCode         string             `json:"error_code"`
	CreatedBy         uuid.UUID          `json:"created_by"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	Created           bool               `json:"created"`
}

func (q *Queries) ReserveDexOperation(ctx context.Context, arg ReserveDexOperationParams) (ReserveDexOperationRow, error) {
	row := q.db.QueryRow(ctx, reserveDexOperation,
		arg.ID,
		arg.Action,
		arg.TargetID,
		arg.IdempotencyScope,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.PayloadEncrypted,
		arg.CreatedBy,
	)
	var i ReserveDexOperationRow
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetID,
		&i.RuntimeGeneration,
		&i.IdempotencyScope,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PayloadEncrypted,
		&i.Status,
		&i.Phase,
		&i.AttemptCount,
		&i.LockedUntil,
		&i.ErrorCode,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}

const setDexOperationPhase = `-- name: SetDexOperationPhase :exec
UPDATE dex_operations SET phase = $1, updated_at = now()
WHERE id = $2 AND status = 'running'
`

type SetDexOperationPhaseParams struct {
	Phase string    `json:"phase"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) SetDexOperationPhase(ctx context.Context, arg SetDexOperationPhaseParams) error {
	_, err := q.db.Exec(ctx, setDexOperationPhase, arg.Phase, arg.ID)
	return err
}
