// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_principals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimExternalPrincipal = `-- name: ClaimExternalPrincipal :one
WITH claimed AS (
    UPDATE external_principals ep
    SET linked_at = COALESCE(ep.linked_at, now()),
        email = $1,
        username = $2,
        display_name = $3
    FROM dex_connectors dc
    WHERE dc.id = ep.connector_id
      AND dc.name = $4
      AND ep.subject = $5
    RETURNING ep.user_id
)
SELECT users.id, users.email, users.username, users.first_name, users.last_name, users.password, users.is_active, users.is_staff, users.is_superuser, users.last_login, users.date_joined, users.created_at, users.updated_at, users.must_change_password, users.failed_login_count, users.failed_login_at, users.locked_until, users.locked_reason, users.tokens_invalidated_at, users.quota_plan, users.quota_overrides, users.is_service
FROM users
JOIN claimed ON claimed.user_id = users.id
`

type ClaimExternalPrincipalParams struct {
	PrincipalEmail       string `json:"principal_email"`
	PrincipalUsername    string `json:"principal_username"`
	PrincipalDisplayName string `json:"principal_display_name"`
	TargetConnectorName  string `json:"target_connector_name"`
	TargetSubject        string `json:"target_subject"`
}

func (q *Queries) ClaimExternalPrincipal(ctx context.Context, arg ClaimExternalPrincipalParams) (User, error) {
	row := q.db.QueryRow(ctx, claimExternalPrincipal,
		arg.PrincipalEmail,
		arg.PrincipalUsername,
		arg.PrincipalDisplayName,
		arg.TargetConnectorName,
		arg.TargetSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.IsActive,
		&i.IsStaff,
		&i.IsSuperuser,
		&i.LastLogin,
		&i.DateJoined,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.FailedLoginAt,
		&i.LockedUntil,
		&i.LockedReason,
		&i.TokensInvalidatedAt,
		&i.QuotaPlan,
		&i.QuotaOverrides,
		&i.IsService,
	)
	return i, err
}

const materializeExternalPrincipal = `-- name: MaterializeExternalPrincipal :one
WITH existing_principal AS MATERIALIZED (
    SELECT ep.user_id
    FROM external_principals ep
    WHERE ep.connector_id = $1
      AND ep.subject = $2
), upserted_user AS (
    INSERT INTO users (
        email, username, first_name, last_name, password,
        is_active, is_staff, is_superuser
    )
    SELECT
        $3, $4, $5,
        $6, '!', true, false, false
    WHERE NOT EXISTS (SELECT 1 FROM existing_principal)
    ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
    RETURNING id
), target_user AS MATERIALIZED (
    SELECT user_id AS id FROM existing_principal
    UNION ALL
    SELECT id FROM upserted_user
    LIMIT 1
), materialized AS (
    INSERT INTO external_principals (
        connector_id, subject, email, username, display_name, user_id
    )
    SELECT
        $1, $2, $3,
        $7, $8, target_user.id
    FROM target_user
    ON CONFLICT (connector_id, subject) DO UPDATE SET
        email = EXCLUDED.email,
        username = EXCLUDED.username,
        display_name = EXCLUDED.display_name
    RETURNING id, connector_id, subject, email, username, display_name, user_id, linked_at, created_at, updated_at
)
SELECT id, connector_id, subject, email, username, display_name, user_id, linked_at, created_at, updated_at FROM materialized
`

type MaterializeExternalPrincipalParams struct {
	TargetConnectorID    uuid.UUID `json:"target_connector_id"`
	TargetSubject        string    `json:"target_subject"`
	PrincipalEmail       string    `json:"principal_email"`
	LocalUsername        string    `json:"local_username"`
	PrincipalFirstName   string    `json:"principal_first_name"`
	PrincipalLastName    string    `json:"principal_last_name"`
	ExternalUsername     string    `json:"external_username"`
	PrincipalDisplayName string    `json:"principal_display_name"`
}

type MaterializeExternalPrincipalRow struct {
	ID          uuid.UUID          `json:"id"`
	ConnectorID uuid.UUID          `json:"connector_id"`
	Subject     string             `json:"subject"`
	Email       string             `json:"email"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	UserID      uuid.UUID          `json:"user_id"`
	LinkedAt    pgtype.Timestamptz `json:"linked_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (q *Queries) MaterializeExternalPrincipal(ctx context.Context, arg MaterializeExternalPrincipalParams) (MaterializeExternalPrincipalRow, error) {
	row := q.db.QueryRow(ctx, materializeExternalPrincipal,
		arg.TargetConnectorID,
		arg.TargetSubject,
		arg.PrincipalEmail,
		arg.LocalUsername,
		arg.PrincipalFirstName,
		arg.PrincipalLastName,
		arg.ExternalUsername,
		arg.PrincipalDisplayName,
	)
	var i MaterializeExternalPrincipalRow
	err := row.Scan(
		&i.ID,
		&i.ConnectorID,
		&i.Subject,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.UserID,
		&i.LinkedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchPrincipalUsers = `-- name: SearchPrincipalUsers :many
SELECT
    u.id AS user_id,
    u.email,
    u.username,
    u.first_name,
    u.last_name,
    u.last_login,
    CASE WHEN ep.id IS NULL THEN ''::text ELSE ep.id::text END AS external_principal_id,
    CASE WHEN ep.connector_id IS NULL THEN ''::text ELSE ep.connector_id::text END AS connector_id,
    coalesce(dc.name, '') AS connector_name,
    coalesce(dc.type, '') AS connector_type,
    coalesce(ep.subject, '') AS subject,
    CASE WHEN ep.id IS NOT NULL AND ep.linked_at IS NULL THEN true ELSE false END AS pending
FROM users u
LEFT JOIN LATERAL (
    SELECT candidate.id, candidate.connector_id, candidate.subject, candidate.email, candidate.username, candidate.display_name, candidate.user_id, candidate.linked_at, candidate.created_at, candidate.updated_at
    FROM external_principals candidate
    WHERE candidate.user_id = u.id
    ORDER BY candidate.linked_at NULLS FIRST, candidate.created_at ASC
    LIMIT 1
) ep ON true
LEFT JOIN dex_connectors dc ON dc.id = ep.connector_id
WHERE u.is_service = false
  AND u.is_active = true
  AND lower(
    coalesce(u.username, '') || ' ' ||
    coalesce(u.email, '') || ' ' ||
    coalesce(u.first_name, '') || ' ' ||
    coalesce(u.last_name, '')
  ) LIKE '%' || lower($1) || '%'
ORDER BY
    CASE
        WHEN lower(u.username) = lower($1) THEN 0
        WHEN lower(u.email) = lower($1) THEN 1
        ELSE 2
    END,
    u.created_at DESC,
    u.id DESC
LIMIT $2
`

type SearchPrincipalUsersParams struct {
	Search      string `json:"search"`
	ResultLimit int32  `json:"result_limit"`
}

type SearchPrincipalUsersRow struct {
	UserID              uuid.UUID          `json:"user_id"`
	Email               string             `json:"email"`
	Username            string             `json:"username"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	LastLogin           pgtype.Timestamptz `json:"last_login"`
	ExternalPrincipalID string             `json:"external_principal_id"`
	ConnectorID         string             `json:"connector_id"`
	ConnectorName       string             `json:"connector_name"`
	ConnectorType       string             `json:"connector_type"`
	Subject             string             `json:"subject"`
	Pending             bool               `json:"pending"`
}

func (q *Queries) SearchPrincipalUsers(ctx context.Context, arg SearchPrincipalUsersParams) ([]SearchPrincipalUsersRow, error) {
	rows, err := q.db.Query(ctx, searchPrincipalUsers, arg.Search, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPrincipalUsersRow{}
	for rows.Next() {
		var i SearchPrincipalUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.LastLogin,
			&i.ExternalPrincipalID,
			&i.ConnectorID,
			&i.ConnectorName,
			&i.ConnectorType,
			&i.Subject,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
