// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitops_registration.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGitOpsRegisteredClustersBySource = `-- name: CountGitOpsRegisteredClustersBySource :one
SELECT COUNT(*) FROM gitops_registered_clusters WHERE source_id = $1
`

func (q *Queries) CountGitOpsRegisteredClustersBySource(ctx context.Context, sourceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGitOpsRegisteredClustersBySource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGitOpsTombstonedBySource = `-- name: CountGitOpsTombstonedBySource :one
SELECT COUNT(*) FROM gitops_registered_clusters
WHERE source_id = $1 AND status = 'tombstoned'
`

func (q *Queries) CountGitOpsTombstonedBySource(ctx context.Context, sourceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGitOpsTombstonedBySource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGitOpsSource = `-- name: CreateGitOpsSource :one
INSERT INTO gitops_registration_sources (
    name, repo_url, branch, path_prefix, auth_mode, auth_encrypted,
    sync_mode, sync_interval_seconds, on_delete, enabled, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, repo_url, branch, path_prefix, auth_mode, auth_encrypted,
          sync_mode, sync_interval_seconds, on_delete,
          last_synced_at, last_synced_sha, last_error, enabled,
          created_by, created_at, updated_at
`

type CreateGitOpsSourceParams struct {
	Name                string      `json:"name"`
	RepoUrl             string      `json:"repo_url"`
	Branch              string      `json:"branch"`
	PathPrefix          string      `json:"path_prefix"`
	AuthMode            string      `json:"auth_mode"`
	AuthEncrypted       string      `json:"auth_encrypted"`
	SyncMode            string      `json:"sync_mode"`
	SyncIntervalSeconds int32       `json:"sync_interval_seconds"`
	OnDelete            string      `json:"on_delete"`
	Enabled             bool        `json:"enabled"`
	CreatedBy           pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateGitOpsSource(ctx context.Context, arg CreateGitOpsSourceParams) (GitopsRegistrationSource, error) {
	row := q.db.QueryRow(ctx, createGitOpsSource,
		arg.Name,
		arg.RepoUrl,
		arg.Branch,
		arg.PathPrefix,
		arg.AuthMode,
		arg.AuthEncrypted,
		arg.SyncMode,
		arg.SyncIntervalSeconds,
		arg.OnDelete,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i GitopsRegistrationSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.PathPrefix,
		&i.AuthMode,
		&i.AuthEncrypted,
		&i.SyncMode,
		&i.SyncIntervalSeconds,
		&i.OnDelete,
		&i.LastSyncedAt,
		&i.LastSyncedSha,
		&i.LastError,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitOpsRegisteredCluster = `-- name: DeleteGitOpsRegisteredCluster :exec
DELETE FROM gitops_registered_clusters WHERE cluster_id = $1
`

func (q *Queries) DeleteGitOpsRegisteredCluster(ctx context.Context, clusterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitOpsRegisteredCluster, clusterID)
	return err
}

const deleteGitOpsSource = `-- name: DeleteGitOpsSource :exec
DELETE FROM gitops_registration_sources WHERE id = $1
`

func (q *Queries) DeleteGitOpsSource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitOpsSource, id)
	return err
}

const getGitOpsSource = `-- name: GetGitOpsSource :one
SELECT id, name, repo_url, branch, path_prefix, auth_mode, auth_encrypted,
       sync_mode, sync_interval_seconds, on_delete,
       last_synced_at, last_synced_sha, last_error, enabled,
       created_by, created_at, updated_at
FROM gitops_registration_sources
WHERE id = $1
`

func (q *Queries) GetGitOpsSource(ctx context.Context, id uuid.UUID) (GitopsRegistrationSource, error) {
	row := q.db.QueryRow(ctx, getGitOpsSource, id)
	var i GitopsRegistrationSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.PathPrefix,
		&i.AuthMode,
		&i.AuthEncrypted,
		&i.SyncMode,
		&i.SyncIntervalSeconds,
		&i.OnDelete,
		&i.LastSyncedAt,
		&i.LastSyncedSha,
		&i.LastError,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitOpsSourceByName = `-- name: GetGitOpsSourceByName :one
SELECT id, name, repo_url, branch, path_prefix, auth_mode, auth_encrypted,
       sync_mode, sync_interval_seconds, on_delete,
       last_synced_at, last_synced_sha, last_error, enabled,
       created_by, created_at, updated_at
FROM gitops_registration_sources
WHERE name = $1
`

func (q *Queries) GetGitOpsSourceByName(ctx context.Context, name string) (GitopsRegistrationSource, error) {
	row := q.db.QueryRow(ctx, getGitOpsSourceByName, name)
	var i GitopsRegistrationSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.PathPrefix,
		&i.AuthMode,
		&i.AuthEncrypted,
		&i.SyncMode,
		&i.SyncIntervalSeconds,
		&i.OnDelete,
		&i.LastSyncedAt,
		&i.LastSyncedSha,
		&i.LastError,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledGitOpsSources = `-- name: ListEnabledGitOpsSources :many
SELECT id, name, repo_url, branch, path_prefix, auth_mode, auth_encrypted,
       sync_mode, sync_interval_seconds, on_delete,
       last_synced_at, last_synced_sha, last_error, enabled,
       created_by, created_at, updated_at
FROM gitops_registration_sources
WHERE enabled = true
ORDER BY name ASC
`

func (q *Queries) ListEnabledGitOpsSources(ctx context.Context) ([]GitopsRegistrationSource, error) {
	rows, err := q.db.Query(ctx, listEnabledGitOpsSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitopsRegistrationSource{}
	for rows.Next() {
		var i GitopsRegistrationSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.Branch,
			&i.PathPrefix,
			&i.AuthMode,
			&i.AuthEncrypted,
			&i.SyncMode,
			&i.SyncIntervalSeconds,
			&i.OnDelete,
			&i.LastSyncedAt,
			&i.LastSyncedSha,
			&i.LastError,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredTombstones = `-- name: ListExpiredTombstones :many
SELECT cluster_id, source_id, repo_path, last_yaml_sha, last_applied_at,
       status, tombstoned_at, created_at, updated_at
FROM gitops_registered_clusters
WHERE status = 'tombstoned'
  AND tombstoned_at IS NOT NULL
  AND tombstoned_at <= $1
ORDER BY tombstoned_at ASC
`

// The reaper pulls rows that have been tombstoned for longer than the
// grace window (24h by default — passed in as the parameter so tests
// can shrink it). The partial index idx_gitops_tombstoned_clusters
// keeps this scan cheap as the table grows.
func (q *Queries) ListExpiredTombstones(ctx context.Context, tombstonedAt pgtype.Timestamptz) ([]GitopsRegisteredCluster, error) {
	rows, err := q.db.Query(ctx, listExpiredTombstones, tombstonedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitopsRegisteredCluster{}
	for rows.Next() {
		var i GitopsRegisteredCluster
		if err := rows.Scan(
			&i.ClusterID,
			&i.SourceID,
			&i.RepoPath,
			&i.LastYamlSha,
			&i.LastAppliedAt,
			&i.Status,
			&i.TombstonedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitOpsRegisteredClustersBySource = `-- name: ListGitOpsRegisteredClustersBySource :many

SELECT cluster_id, source_id, repo_path, last_yaml_sha, last_applied_at,
       status, tombstoned_at, created_at, updated_at
FROM gitops_registered_clusters
WHERE source_id = $1
ORDER BY repo_path ASC
`

// Registered clusters --------------------------------------------------
func (q *Queries) ListGitOpsRegisteredClustersBySource(ctx context.Context, sourceID uuid.UUID) ([]GitopsRegisteredCluster, error) {
	rows, err := q.db.Query(ctx, listGitOpsRegisteredClustersBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitopsRegisteredCluster{}
	for rows.Next() {
		var i GitopsRegisteredCluster
		if err := rows.Scan(
			&i.ClusterID,
			&i.SourceID,
			&i.RepoPath,
			&i.LastYamlSha,
			&i.LastAppliedAt,
			&i.Status,
			&i.TombstonedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitOpsSources = `-- name: ListGitOpsSources :many

SELECT id, name, repo_url, branch, path_prefix, auth_mode, auth_encrypted,
       sync_mode, sync_interval_seconds, on_delete,
       last_synced_at, last_synced_sha, last_error, enabled,
       created_by, created_at, updated_at
FROM gitops_registration_sources
ORDER BY name ASC
`

// GitOps cluster registration sources + tracked clusters (migration 060).
//
// The sync worker pulls ListEnabledGitOpsSources every 60s, fetches each
// repo, walks the YAML files, and reconciles via UpsertGitOpsRegistered
// + StampGitOpsSourceSync. The reaper sweeps tombstoned rows older than
// the 24h grace via ListExpiredTombstones, enqueueing
// cluster:decommission for each. The handler tier owns CRUD over the
// sources themselves and the per-source /clusters/ + /preview/ readers.
func (q *Queries) ListGitOpsSources(ctx context.Context) ([]GitopsRegistrationSource, error) {
	rows, err := q.db.Query(ctx, listGitOpsSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitopsRegistrationSource{}
	for rows.Next() {
		var i GitopsRegistrationSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.Branch,
			&i.PathPrefix,
			&i.AuthMode,
			&i.AuthEncrypted,
			&i.SyncMode,
			&i.SyncIntervalSeconds,
			&i.OnDelete,
			&i.LastSyncedAt,
			&i.LastSyncedSha,
			&i.LastError,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stampGitOpsSourceError = `-- name: StampGitOpsSourceError :exec
UPDATE gitops_registration_sources
SET last_error = $2,
    updated_at = now()
WHERE id = $1
`

type StampGitOpsSourceErrorParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

// Stamped on a hard sync failure (clone error, walk error, etc).
func (q *Queries) StampGitOpsSourceError(ctx context.Context, arg StampGitOpsSourceErrorParams) error {
	_, err := q.db.Exec(ctx, stampGitOpsSourceError, arg.ID, arg.LastError)
	return err
}

const stampGitOpsSourceSync = `-- name: StampGitOpsSourceSync :exec
UPDATE gitops_registration_sources
SET last_synced_at  = $2,
    last_synced_sha = $3,
    last_error      = '',
    updated_at      = now()
WHERE id = $1
`

type StampGitOpsSourceSyncParams struct {
	ID            uuid.UUID          `json:"id"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	LastSyncedSha string             `json:"last_synced_sha"`
}

// Called by the sync worker after every successful tick. Clearing
// last_error on success is intentional — partial failures during a tick
// leave last_error stamped via StampGitOpsSourceError.
func (q *Queries) StampGitOpsSourceSync(ctx context.Context, arg StampGitOpsSourceSyncParams) error {
	_, err := q.db.Exec(ctx, stampGitOpsSourceSync, arg.ID, arg.LastSyncedAt, arg.LastSyncedSha)
	return err
}

const tombstoneGitOpsRegisteredCluster = `-- name: TombstoneGitOpsRegisteredCluster :exec
UPDATE gitops_registered_clusters
SET status        = 'tombstoned',
    tombstoned_at = $2,
    updated_at    = now()
WHERE cluster_id = $1
`

type TombstoneGitOpsRegisteredClusterParams struct {
	ClusterID    uuid.UUID          `json:"cluster_id"`
	TombstonedAt pgtype.Timestamptz `json:"tombstoned_at"`
}

// Sets status='tombstoned' + tombstoned_at=now. The reaper later picks
// the row up via ListExpiredTombstones.
func (q *Queries) TombstoneGitOpsRegisteredCluster(ctx context.Context, arg TombstoneGitOpsRegisteredClusterParams) error {
	_, err := q.db.Exec(ctx, tombstoneGitOpsRegisteredCluster, arg.ClusterID, arg.TombstonedAt)
	return err
}

const updateGitOpsSource = `-- name: UpdateGitOpsSource :one
UPDATE gitops_registration_sources
SET name                  = $2,
    repo_url              = $3,
    branch                = $4,
    path_prefix           = $5,
    auth_mode             = $6,
    auth_encrypted        = $7,
    sync_mode             = $8,
    sync_interval_seconds = $9,
    on_delete             = $10,
    enabled               = $11,
    updated_at            = now()
WHERE id = $1
RETURNING id, name, repo_url, branch, path_prefix, auth_mode, auth_encrypted,
          sync_mode, sync_interval_seconds, on_delete,
          last_synced_at, last_synced_sha, last_error, enabled,
          created_by, created_at, updated_at
`

type UpdateGitOpsSourceParams struct {
	ID                  uuid.UUID `json:"id"`
	Name                string    `json:"name"`
	RepoUrl             string    `json:"repo_url"`
	Branch              string    `json:"branch"`
	PathPrefix          string    `json:"path_prefix"`
	AuthMode            string    `json:"auth_mode"`
	AuthEncrypted       string    `json:"auth_encrypted"`
	SyncMode            string    `json:"sync_mode"`
	SyncIntervalSeconds int32     `json:"sync_interval_seconds"`
	OnDelete            string    `json:"on_delete"`
	Enabled             bool      `json:"enabled"`
}

func (q *Queries) UpdateGitOpsSource(ctx context.Context, arg UpdateGitOpsSourceParams) (GitopsRegistrationSource, error) {
	row := q.db.QueryRow(ctx, updateGitOpsSource,
		arg.ID,
		arg.Name,
		arg.RepoUrl,
		arg.Branch,
		arg.PathPrefix,
		arg.AuthMode,
		arg.AuthEncrypted,
		arg.SyncMode,
		arg.SyncIntervalSeconds,
		arg.OnDelete,
		arg.Enabled,
	)
	var i GitopsRegistrationSource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.PathPrefix,
		&i.AuthMode,
		&i.AuthEncrypted,
		&i.SyncMode,
		&i.SyncIntervalSeconds,
		&i.OnDelete,
		&i.LastSyncedAt,
		&i.LastSyncedSha,
		&i.LastError,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitOpsRegisteredCluster = `-- name: UpsertGitOpsRegisteredCluster :one
INSERT INTO gitops_registered_clusters (
    cluster_id, source_id, repo_path, last_yaml_sha, last_applied_at, status, tombstoned_at
) VALUES ($1, $2, $3, $4, now(), 'active', NULL)
ON CONFLICT (cluster_id) DO UPDATE
SET source_id       = EXCLUDED.source_id,
    repo_path       = EXCLUDED.repo_path,
    last_yaml_sha   = EXCLUDED.last_yaml_sha,
    last_applied_at = now(),
    status          = 'active',
    tombstoned_at   = NULL,
    updated_at      = now()
RETURNING cluster_id, source_id, repo_path, last_yaml_sha, last_applied_at,
          status, tombstoned_at, created_at, updated_at
`

type UpsertGitOpsRegisteredClusterParams struct {
	ClusterID   uuid.UUID `json:"cluster_id"`
	SourceID    uuid.UUID `json:"source_id"`
	RepoPath    string    `json:"repo_path"`
	LastYamlSha string    `json:"last_yaml_sha"`
}

// The sync worker calls this after a YAML's contents have been applied
// so subsequent ticks no-op when last_yaml_sha matches. ON CONFLICT
// promotes any tombstoned row back to active — that's the
// "YAML reappears" path under on_delete='tombstone'.
func (q *Queries) UpsertGitOpsRegisteredCluster(ctx context.Context, arg UpsertGitOpsRegisteredClusterParams) (GitopsRegisteredCluster, error) {
	row := q.db.QueryRow(ctx, upsertGitOpsRegisteredCluster,
		arg.ClusterID,
		arg.SourceID,
		arg.RepoPath,
		arg.LastYamlSha,
	)
	var i GitopsRegisteredCluster
	err := row.Scan(
		&i.ClusterID,
		&i.SourceID,
		&i.RepoPath,
		&i.LastYamlSha,
		&i.LastAppliedAt,
		&i.Status,
		&i.TombstonedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
