// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_sync.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGroupMappings = `-- name: CountGroupMappings :one
SELECT count(*) FROM identity_group_mappings
`

func (q *Queries) CountGroupMappings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMappings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupSyncClusterBindings = `-- name: CountGroupSyncClusterBindings :one
SELECT count(*) FROM cluster_role_bindings WHERE source = 'group_sync'
`

func (q *Queries) CountGroupSyncClusterBindings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupSyncClusterBindings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupSyncGlobalBindings = `-- name: CountGroupSyncGlobalBindings :one
SELECT count(*) FROM global_role_bindings WHERE source = 'group_sync'
`

func (q *Queries) CountGroupSyncGlobalBindings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupSyncGlobalBindings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupSyncProjectBindings = `-- name: CountGroupSyncProjectBindings :one
SELECT count(*) FROM project_role_bindings WHERE source = 'group_sync'
`

func (q *Queries) CountGroupSyncProjectBindings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupSyncProjectBindings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupMapping = `-- name: CreateGroupMapping :one

INSERT INTO identity_group_mappings (
    connector_id, group_name, scope, role_id, cluster_id, project_id
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, connector_id, group_name, scope, role_id, cluster_id, project_id, created_at, updated_at
`

type CreateGroupMappingParams struct {
	ConnectorID pgtype.UUID `json:"connector_id"`
	GroupName   string      `json:"group_name"`
	Scope       string      `json:"scope"`
	RoleID      uuid.UUID   `json:"role_id"`
	ClusterID   pgtype.UUID `json:"cluster_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
}

// Identity-group sync queries (migration 042). Drives the
// claims-to-role-binding mapping resolved on every SSO login + the
// admin CRUD endpoints under /api/v1/admin/group-mappings/.
// Admin endpoint POST. Caller is responsible for validating that
// scope/role_id/cluster_id/project_id agree before this call — the
// table's scope_matches CHECK constraint will reject mismatched rows.
func (q *Queries) CreateGroupMapping(ctx context.Context, arg CreateGroupMappingParams) (IdentityGroupMapping, error) {
	row := q.db.QueryRow(ctx, createGroupMapping,
		arg.ConnectorID,
		arg.GroupName,
		arg.Scope,
		arg.RoleID,
		arg.ClusterID,
		arg.ProjectID,
	)
	var i IdentityGroupMapping
	err := row.Scan(
		&i.ID,
		&i.ConnectorID,
		&i.GroupName,
		&i.Scope,
		&i.RoleID,
		&i.ClusterID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupSyncClusterBinding = `-- name: CreateGroupSyncClusterBinding :one
INSERT INTO cluster_role_bindings (user_id, "group", role_id, cluster_id, source)
VALUES ($1, '', $2, $3, 'group_sync')
ON CONFLICT (user_id, role_id, cluster_id) DO NOTHING
RETURNING id, user_id, "group", role_id, cluster_id, created_at, updated_at, source, namespace, group_sync_connector_id
`

type CreateGroupSyncClusterBindingParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	RoleID    uuid.UUID   `json:"role_id"`
	ClusterID uuid.UUID   `json:"cluster_id"`
}

func (q *Queries) CreateGroupSyncClusterBinding(ctx context.Context, arg CreateGroupSyncClusterBindingParams) (ClusterRoleBinding, error) {
	row := q.db.QueryRow(ctx, createGroupSyncClusterBinding, arg.UserID, arg.RoleID, arg.ClusterID)
	var i ClusterRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Group,
		&i.RoleID,
		&i.ClusterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.Namespace,
		&i.GroupSyncConnectorID,
	)
	return i, err
}

const createGroupSyncClusterBindingForConnector = `-- name: CreateGroupSyncClusterBindingForConnector :one
INSERT INTO cluster_role_bindings (user_id, "group", role_id, cluster_id, source, group_sync_connector_id)
VALUES ($1, '', $2, $3, 'group_sync', $4)
ON CONFLICT (user_id, role_id, cluster_id) DO NOTHING
RETURNING id, user_id, "group", role_id, cluster_id, created_at, updated_at, source, namespace, group_sync_connector_id
`

type CreateGroupSyncClusterBindingForConnectorParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	RoleID               uuid.UUID   `json:"role_id"`
	ClusterID            uuid.UUID   `json:"cluster_id"`
	GroupSyncConnectorID pgtype.UUID `json:"group_sync_connector_id"`
}

func (q *Queries) CreateGroupSyncClusterBindingForConnector(ctx context.Context, arg CreateGroupSyncClusterBindingForConnectorParams) (ClusterRoleBinding, error) {
	row := q.db.QueryRow(ctx, createGroupSyncClusterBindingForConnector,
		arg.UserID,
		arg.RoleID,
		arg.ClusterID,
		arg.GroupSyncConnectorID,
	)
	var i ClusterRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Group,
		&i.RoleID,
		&i.ClusterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.Namespace,
		&i.GroupSyncConnectorID,
	)
	return i, err
}

const createGroupSyncGlobalBinding = `-- name: CreateGroupSyncGlobalBinding :one
INSERT INTO global_role_bindings (user_id, "group", role_id, source)
VALUES ($1, '', $2, 'group_sync')
ON CONFLICT (user_id, role_id) DO NOTHING
RETURNING id, user_id, "group", role_id, created_at, updated_at, source, group_sync_connector_id
`

type CreateGroupSyncGlobalBindingParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID uuid.UUID   `json:"role_id"`
}

// Marks the source column with 'group_sync' on insert. ON CONFLICT
// DO NOTHING handles the idempotent re-sync case (manual binding
// on (user_id, role_id) wins; group_sync row stays absent).
func (q *Queries) CreateGroupSyncGlobalBinding(ctx context.Context, arg CreateGroupSyncGlobalBindingParams) (GlobalRoleBinding, error) {
	row := q.db.QueryRow(ctx, createGroupSyncGlobalBinding, arg.UserID, arg.RoleID)
	var i GlobalRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Group,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.GroupSyncConnectorID,
	)
	return i, err
}

const createGroupSyncGlobalBindingForConnector = `-- name: CreateGroupSyncGlobalBindingForConnector :one
INSERT INTO global_role_bindings (user_id, "group", role_id, source, group_sync_connector_id)
VALUES ($1, '', $2, 'group_sync', $3)
ON CONFLICT (user_id, role_id) DO NOTHING
RETURNING id, user_id, "group", role_id, created_at, updated_at, source, group_sync_connector_id
`

type CreateGroupSyncGlobalBindingForConnectorParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	RoleID               uuid.UUID   `json:"role_id"`
	GroupSyncConnectorID pgtype.UUID `json:"group_sync_connector_id"`
}

// Same idempotent insert as CreateGroupSyncGlobalBinding but stamps the
// granting connector so a later sync can scope its revocation diff.
func (q *Queries) CreateGroupSyncGlobalBindingForConnector(ctx context.Context, arg CreateGroupSyncGlobalBindingForConnectorParams) (GlobalRoleBinding, error) {
	row := q.db.QueryRow(ctx, createGroupSyncGlobalBindingForConnector, arg.UserID, arg.RoleID, arg.GroupSyncConnectorID)
	var i GlobalRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Group,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.GroupSyncConnectorID,
	)
	return i, err
}

const createGroupSyncProjectBinding = `-- name: CreateGroupSyncProjectBinding :one
INSERT INTO project_role_bindings (user_id, "group", role_id, project_id, source)
VALUES ($1, '', $2, $3, 'group_sync')
ON CONFLICT (user_id, role_id, project_id) DO NOTHING
RETURNING id, user_id, "group", role_id, project_id, created_at, updated_at, source, group_sync_connector_id
`

type CreateGroupSyncProjectBindingParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	RoleID    uuid.UUID   `json:"role_id"`
	ProjectID uuid.UUID   `json:"project_id"`
}

func (q *Queries) CreateGroupSyncProjectBinding(ctx context.Context, arg CreateGroupSyncProjectBindingParams) (ProjectRoleBinding, error) {
	row := q.db.QueryRow(ctx, createGroupSyncProjectBinding, arg.UserID, arg.RoleID, arg.ProjectID)
	var i ProjectRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Group,
		&i.RoleID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.GroupSyncConnectorID,
	)
	return i, err
}

const createGroupSyncProjectBindingForConnector = `-- name: CreateGroupSyncProjectBindingForConnector :one
INSERT INTO project_role_bindings (user_id, "group", role_id, project_id, source, group_sync_connector_id)
VALUES ($1, '', $2, $3, 'group_sync', $4)
ON CONFLICT (user_id, role_id, project_id) DO NOTHING
RETURNING id, user_id, "group", role_id, project_id, created_at, updated_at, source, group_sync_connector_id
`

type CreateGroupSyncProjectBindingForConnectorParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	RoleID               uuid.UUID   `json:"role_id"`
	ProjectID            uuid.UUID   `json:"project_id"`
	GroupSyncConnectorID pgtype.UUID `json:"group_sync_connector_id"`
}

func (q *Queries) CreateGroupSyncProjectBindingForConnector(ctx context.Context, arg CreateGroupSyncProjectBindingForConnectorParams) (ProjectRoleBinding, error) {
	row := q.db.QueryRow(ctx, createGroupSyncProjectBindingForConnector,
		arg.UserID,
		arg.RoleID,
		arg.ProjectID,
		arg.GroupSyncConnectorID,
	)
	var i ProjectRoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Group,
		&i.RoleID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.GroupSyncConnectorID,
	)
	return i, err
}

const deleteGroupMapping = `-- name: DeleteGroupMapping :exec
DELETE FROM identity_group_mappings WHERE id = $1
`

func (q *Queries) DeleteGroupMapping(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupMapping, id)
	return err
}

const deleteGroupSyncClusterBinding = `-- name: DeleteGroupSyncClusterBinding :exec
DELETE FROM cluster_role_bindings WHERE id = $1 AND source = 'group_sync'
`

func (q *Queries) DeleteGroupSyncClusterBinding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupSyncClusterBinding, id)
	return err
}

const deleteGroupSyncGlobalBinding = `-- name: DeleteGroupSyncGlobalBinding :exec
DELETE FROM global_role_bindings WHERE id = $1 AND source = 'group_sync'
`

// Belt-and-suspenders source check so a sync run can never delete a
// manual binding even if the caller picks the wrong ID.
func (q *Queries) DeleteGroupSyncGlobalBinding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupSyncGlobalBinding, id)
	return err
}

const deleteGroupSyncProjectBinding = `-- name: DeleteGroupSyncProjectBinding :exec
DELETE FROM project_role_bindings WHERE id = $1 AND source = 'group_sync'
`

func (q *Queries) DeleteGroupSyncProjectBinding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupSyncProjectBinding, id)
	return err
}

const getGroupMappingByID = `-- name: GetGroupMappingByID :one
SELECT id, connector_id, group_name, scope, role_id, cluster_id, project_id, created_at, updated_at FROM identity_group_mappings WHERE id = $1
`

func (q *Queries) GetGroupMappingByID(ctx context.Context, id uuid.UUID) (IdentityGroupMapping, error) {
	row := q.db.QueryRow(ctx, getGroupMappingByID, id)
	var i IdentityGroupMapping
	err := row.Scan(
		&i.ID,
		&i.ConnectorID,
		&i.GroupName,
		&i.Scope,
		&i.RoleID,
		&i.ClusterID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIDPGroups = `-- name: GetUserIDPGroups :one
SELECT user_id, connector_id, groups, synced_at FROM user_idp_groups WHERE user_id = $1
`

func (q *Queries) GetUserIDPGroups(ctx context.Context, userID uuid.UUID) (UserIdpGroup, error) {
	row := q.db.QueryRow(ctx, getUserIDPGroups, userID)
	var i UserIdpGroup
	err := row.Scan(
		&i.UserID,
		&i.ConnectorID,
		&i.Groups,
		&i.SyncedAt,
	)
	return i, err
}

const listGroupMappings = `-- name: ListGroupMappings :many
SELECT id, connector_id, group_name, scope, role_id, cluster_id, project_id, created_at, updated_at FROM identity_group_mappings
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListGroupMappingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin endpoint GET (paginated).
func (q *Queries) ListGroupMappings(ctx context.Context, arg ListGroupMappingsParams) ([]IdentityGroupMapping, error) {
	rows, err := q.db.Query(ctx, listGroupMappings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityGroupMapping{}
	for rows.Next() {
		var i IdentityGroupMapping
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorID,
			&i.GroupName,
			&i.Scope,
			&i.RoleID,
			&i.ClusterID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMappingsForConnector = `-- name: ListGroupMappingsForConnector :many
SELECT id, connector_id, group_name, scope, role_id, cluster_id, project_id, created_at, updated_at FROM identity_group_mappings
WHERE connector_id = $1 OR connector_id IS NULL
`

// Hot path. Used by SyncUserGroups on every successful SSO login.
// Returns rows whose connector_id is either the supplied UUID *or*
// NULL (the wildcard connector). The Go-side filter on group_name
// happens in the caller so we can batch a single round-trip against
// the user's slice — Postgres has no array-of-text-to-IN-clause
// shortcut that sqlc can express portably.
//
// NOTE: pgtype.UUID is the parameter type so the caller can pass an
// Invalid (NULL) value to mean "wildcard only", though the typical
// call has a Valid connector ID and gets both connector-scoped + NULL
// rows back in one read.
func (q *Queries) ListGroupMappingsForConnector(ctx context.Context, connectorID pgtype.UUID) ([]IdentityGroupMapping, error) {
	rows, err := q.db.Query(ctx, listGroupMappingsForConnector, connectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityGroupMapping{}
	for rows.Next() {
		var i IdentityGroupMapping
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorID,
			&i.GroupName,
			&i.Scope,
			&i.RoleID,
			&i.ClusterID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSyncClusterBindings = `-- name: ListGroupSyncClusterBindings :many
SELECT id, user_id, "group", role_id, cluster_id, created_at, updated_at, source, namespace, group_sync_connector_id FROM cluster_role_bindings WHERE user_id = $1 AND source = 'group_sync'
`

func (q *Queries) ListGroupSyncClusterBindings(ctx context.Context, userID pgtype.UUID) ([]ClusterRoleBinding, error) {
	rows, err := q.db.Query(ctx, listGroupSyncClusterBindings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClusterRoleBinding{}
	for rows.Next() {
		var i ClusterRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Group,
			&i.RoleID,
			&i.ClusterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.Namespace,
			&i.GroupSyncConnectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSyncClusterBindingsForConnector = `-- name: ListGroupSyncClusterBindingsForConnector :many
SELECT id, user_id, "group", role_id, cluster_id, created_at, updated_at, source, namespace, group_sync_connector_id FROM cluster_role_bindings
WHERE user_id = $1 AND source = 'group_sync'
  AND (group_sync_connector_id IS NOT DISTINCT FROM $2
       OR group_sync_connector_id IS NULL)
`

type ListGroupSyncClusterBindingsForConnectorParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	GroupSyncConnectorID pgtype.UUID `json:"group_sync_connector_id"`
}

func (q *Queries) ListGroupSyncClusterBindingsForConnector(ctx context.Context, arg ListGroupSyncClusterBindingsForConnectorParams) ([]ClusterRoleBinding, error) {
	rows, err := q.db.Query(ctx, listGroupSyncClusterBindingsForConnector, arg.UserID, arg.GroupSyncConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClusterRoleBinding{}
	for rows.Next() {
		var i ClusterRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Group,
			&i.RoleID,
			&i.ClusterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.Namespace,
			&i.GroupSyncConnectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSyncGlobalBindings = `-- name: ListGroupSyncGlobalBindings :many
SELECT id, user_id, "group", role_id, created_at, updated_at, source, group_sync_connector_id FROM global_role_bindings WHERE user_id = $1 AND source = 'group_sync'
`

// Enumerates the user's group_sync-managed global bindings so the
// sync loop can compute the revocation diff. Manual bindings are
// explicitly excluded.
func (q *Queries) ListGroupSyncGlobalBindings(ctx context.Context, userID pgtype.UUID) ([]GlobalRoleBinding, error) {
	rows, err := q.db.Query(ctx, listGroupSyncGlobalBindings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalRoleBinding{}
	for rows.Next() {
		var i GlobalRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Group,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.GroupSyncConnectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSyncGlobalBindingsForConnector = `-- name: ListGroupSyncGlobalBindingsForConnector :many

SELECT id, user_id, "group", role_id, created_at, updated_at, source, group_sync_connector_id FROM global_role_bindings
WHERE user_id = $1 AND source = 'group_sync'
  AND (group_sync_connector_id IS NOT DISTINCT FROM $2
       OR group_sync_connector_id IS NULL)
`

type ListGroupSyncGlobalBindingsForConnectorParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	GroupSyncConnectorID pgtype.UUID `json:"group_sync_connector_id"`
}

// Finding #3 (connector-scoped reconciliation). These mirror the
// ListGroupSync*Bindings queries above but additionally filter by the
// granting connector (migration 128's group_sync_connector_id). The
// reconciler must enumerate — and therefore only revoke — the bindings
// granted by the connector currently syncing, so a user entitled under
// multiple connectors doesn't lose one connector's roles on a login
// through another. IS NOT DISTINCT FROM makes a NULL (wildcard-connector /
// legacy) parameter match NULL-connector rows.
//
// Sweep-4 fix (wildcard/legacy over-retention): we ALSO enumerate
// NULL-connector rows on every sync (OR group_sync_connector_id IS NULL),
// regardless of the connector being synced. NULL provenance means
// "wildcard-owned or legacy pre-128 grant" — connector-agnostic — so it
// must be reconciled on every login. Without this, a wildcard grant
// stamped for connector A (or a legacy NULL row) is never revisited when
// the operator deletes the mapping and the user only logs in via
// connector B, so the (possibly admin) role is retained indefinitely.
// Bindings owned by a *named* connector stay scoped to that connector.
func (q *Queries) ListGroupSyncGlobalBindingsForConnector(ctx context.Context, arg ListGroupSyncGlobalBindingsForConnectorParams) ([]GlobalRoleBinding, error) {
	rows, err := q.db.Query(ctx, listGroupSyncGlobalBindingsForConnector, arg.UserID, arg.GroupSyncConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalRoleBinding{}
	for rows.Next() {
		var i GlobalRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Group,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.GroupSyncConnectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSyncProjectBindings = `-- name: ListGroupSyncProjectBindings :many
SELECT id, user_id, "group", role_id, project_id, created_at, updated_at, source, group_sync_connector_id FROM project_role_bindings WHERE user_id = $1 AND source = 'group_sync'
`

func (q *Queries) ListGroupSyncProjectBindings(ctx context.Context, userID pgtype.UUID) ([]ProjectRoleBinding, error) {
	rows, err := q.db.Query(ctx, listGroupSyncProjectBindings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectRoleBinding{}
	for rows.Next() {
		var i ProjectRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Group,
			&i.RoleID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.GroupSyncConnectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupSyncProjectBindingsForConnector = `-- name: ListGroupSyncProjectBindingsForConnector :many
SELECT id, user_id, "group", role_id, project_id, created_at, updated_at, source, group_sync_connector_id FROM project_role_bindings
WHERE user_id = $1 AND source = 'group_sync'
  AND (group_sync_connector_id IS NOT DISTINCT FROM $2
       OR group_sync_connector_id IS NULL)
`

type ListGroupSyncProjectBindingsForConnectorParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	GroupSyncConnectorID pgtype.UUID `json:"group_sync_connector_id"`
}

func (q *Queries) ListGroupSyncProjectBindingsForConnector(ctx context.Context, arg ListGroupSyncProjectBindingsForConnectorParams) ([]ProjectRoleBinding, error) {
	rows, err := q.db.Query(ctx, listGroupSyncProjectBindingsForConnector, arg.UserID, arg.GroupSyncConnectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectRoleBinding{}
	for rows.Next() {
		var i ProjectRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Group,
			&i.RoleID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.GroupSyncConnectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserIDPGroups = `-- name: UpsertUserIDPGroups :one
INSERT INTO user_idp_groups (user_id, connector_id, groups, synced_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    connector_id = EXCLUDED.connector_id,
    groups       = EXCLUDED.groups,
    synced_at    = EXCLUDED.synced_at
RETURNING user_id, connector_id, groups, synced_at
`

type UpsertUserIDPGroupsParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	ConnectorID pgtype.UUID     `json:"connector_id"`
	Groups      json.RawMessage `json:"groups"`
	SyncedAt    time.Time       `json:"synced_at"`
}

// Replace the user's group snapshot on every login. The synced_at
// timestamp drives the audit + "stale-claims" detection in the
// admin resync endpoint.
func (q *Queries) UpsertUserIDPGroups(ctx context.Context, arg UpsertUserIDPGroupsParams) (UserIdpGroup, error) {
	row := q.db.QueryRow(ctx, upsertUserIDPGroups,
		arg.UserID,
		arg.ConnectorID,
		arg.Groups,
		arg.SyncedAt,
	)
	var i UserIdpGroup
	err := row.Scan(
		&i.UserID,
		&i.ConnectorID,
		&i.Groups,
		&i.SyncedAt,
	)
	return i, err
}
