// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: heartbeats.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getClusterHealthTarget = `-- name: GetClusterHealthTarget :one
SELECT
    c.id,
    c.status,
    c.kubernetes_version,
    c.distribution,
    c.node_count,
    l.last_heartbeat
FROM clusters c
LEFT JOIN cluster_liveness l ON l.cluster_id = c.id
WHERE c.id = $1
  AND c.decommissioned_at IS NULL
`

type GetClusterHealthTargetRow struct {
	ID                uuid.UUID          `json:"id"`
	Status            string             `json:"status"`
	KubernetesVersion string             `json:"kubernetes_version"`
	Distribution      string             `json:"distribution"`
	NodeCount         int32              `json:"node_count"`
	LastHeartbeat     pgtype.Timestamptz `json:"last_heartbeat"`
}

func (q *Queries) GetClusterHealthTarget(ctx context.Context, clusterID uuid.UUID) (GetClusterHealthTargetRow, error) {
	row := q.db.QueryRow(ctx, getClusterHealthTarget, clusterID)
	var i GetClusterHealthTargetRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.KubernetesVersion,
		&i.Distribution,
		&i.NodeCount,
		&i.LastHeartbeat,
	)
	return i, err
}

const getClusterLiveness = `-- name: GetClusterLiveness :one
SELECT cluster_id, last_heartbeat, heartbeat_count, commands_pending, created_at, updated_at FROM cluster_liveness WHERE cluster_id = $1
`

func (q *Queries) GetClusterLiveness(ctx context.Context, clusterID uuid.UUID) (ClusterLiveness, error) {
	row := q.db.QueryRow(ctx, getClusterLiveness, clusterID)
	var i ClusterLiveness
	err := row.Scan(
		&i.ClusterID,
		&i.LastHeartbeat,
		&i.HeartbeatCount,
		&i.CommandsPending,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClusterHealthTargets = `-- name: ListClusterHealthTargets :many
SELECT
    c.id,
    c.status,
    c.kubernetes_version,
    c.distribution,
    c.node_count,
    l.last_heartbeat
FROM clusters c
LEFT JOIN cluster_liveness l ON l.cluster_id = c.id
WHERE c.decommissioned_at IS NULL
ORDER BY c.created_at DESC, c.id DESC
LIMIT $2 OFFSET $1
`

type ListClusterHealthTargetsParams struct {
	QueryOffset int32 `json:"query_offset"`
	QueryLimit  int32 `json:"query_limit"`
}

type ListClusterHealthTargetsRow struct {
	ID                uuid.UUID          `json:"id"`
	Status            string             `json:"status"`
	KubernetesVersion string             `json:"kubernetes_version"`
	Distribution      string             `json:"distribution"`
	NodeCount         int32              `json:"node_count"`
	LastHeartbeat     pgtype.Timestamptz `json:"last_heartbeat"`
}

func (q *Queries) ListClusterHealthTargets(ctx context.Context, arg ListClusterHealthTargetsParams) ([]ListClusterHealthTargetsRow, error) {
	rows, err := q.db.Query(ctx, listClusterHealthTargets, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterHealthTargetsRow{}
	for rows.Next() {
		var i ListClusterHealthTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.KubernetesVersion,
			&i.Distribution,
			&i.NodeCount,
			&i.LastHeartbeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClusterLivenessForClusters = `-- name: ListClusterLivenessForClusters :many
SELECT cluster_id, last_heartbeat, heartbeat_count, commands_pending, created_at, updated_at FROM cluster_liveness
WHERE cluster_id = ANY($1::uuid[])
`

func (q *Queries) ListClusterLivenessForClusters(ctx context.Context, clusterIds []uuid.UUID) ([]ClusterLiveness, error) {
	rows, err := q.db.Query(ctx, listClusterLivenessForClusters, clusterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClusterLiveness{}
	for rows.Next() {
		var i ClusterLiveness
		if err := rows.Scan(
			&i.ClusterID,
			&i.LastHeartbeat,
			&i.HeartbeatCount,
			&i.CommandsPending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAgentHeartbeat = `-- name: RecordAgentHeartbeat :one
WITH touched_connection AS (
    UPDATE agent_connections
    SET last_ping = statement_timestamp()
    WHERE agent_connections.id = $1
      AND agent_connections.cluster_id = $2
      AND agent_connections.status = 'connected'
    RETURNING agent_connections.id
), liveness AS (
    INSERT INTO cluster_liveness (
        cluster_id,
        last_heartbeat,
        heartbeat_count,
        commands_pending
    )
    SELECT
        $2,
        statement_timestamp(),
        1,
        EXISTS (
            SELECT 1
            FROM agent_lifecycle_operations op
            WHERE op.cluster_id = $2
              AND op.status IN ('pending', 'running')
        )
    FROM touched_connection
    ON CONFLICT (cluster_id) DO UPDATE SET
        last_heartbeat = EXCLUDED.last_heartbeat,
        heartbeat_count = cluster_liveness.heartbeat_count + 1,
        updated_at = EXCLUDED.last_heartbeat
    RETURNING commands_pending
), inventory AS (
    UPDATE clusters
    SET agent_version = COALESCE(NULLIF($3::text, ''), agent_version),
        kubernetes_version = COALESCE(NULLIF($4::text, ''), kubernetes_version),
        node_count = CASE WHEN $5::int > 0 THEN $5::int ELSE node_count END,
        distribution = COALESCE(NULLIF($6::text, ''), distribution)
    WHERE clusters.id = $2
      AND clusters.decommissioned_at IS NULL
      AND EXISTS (SELECT 1 FROM liveness)
      AND (
          clusters.agent_version IS DISTINCT FROM COALESCE(NULLIF($3::text, ''), clusters.agent_version)
          OR clusters.kubernetes_version IS DISTINCT FROM COALESCE(NULLIF($4::text, ''), clusters.kubernetes_version)
          OR clusters.node_count IS DISTINCT FROM CASE WHEN $5::int > 0 THEN $5::int ELSE clusters.node_count END
          OR clusters.distribution IS DISTINCT FROM COALESCE(NULLIF($6::text, ''), clusters.distribution)
      )
    RETURNING id
), health AS (
    INSERT INTO cluster_health_statuses (
        cluster_id,
        cpu_usage_percent,
        memory_usage_percent,
        pod_count,
        node_count,
        conditions
    )
    SELECT
        $2,
        $7,
        $8,
        $9,
        $5,
        $10
    FROM liveness
    ON CONFLICT (cluster_id) DO UPDATE SET
        cpu_usage_percent = EXCLUDED.cpu_usage_percent,
        memory_usage_percent = EXCLUDED.memory_usage_percent,
        pod_count = EXCLUDED.pod_count,
        node_count = EXCLUDED.node_count,
        conditions = EXCLUDED.conditions,
        last_check = statement_timestamp()
    RETURNING cluster_id
)
SELECT commands_pending FROM liveness
`

type RecordAgentHeartbeatParams struct {
	ConnectionID       uuid.UUID       `json:"connection_id"`
	ClusterID          uuid.UUID       `json:"cluster_id"`
	AgentVersion       string          `json:"agent_version"`
	KubernetesVersion  string          `json:"kubernetes_version"`
	NodeCount          int32           `json:"node_count"`
	Distribution       string          `json:"distribution"`
	CpuUsagePercent    float64         `json:"cpu_usage_percent"`
	MemoryUsagePercent float64         `json:"memory_usage_percent"`
	PodCount           int32           `json:"pod_count"`
	Conditions         json.RawMessage `json:"conditions"`
}

// Persist the ordinary heartbeat path in one round trip:
//  1. touch the authenticated connection row;
//  2. advance the narrow liveness row;
//  3. update wide cluster inventory only when it materially changed; and
//  4. refresh health in the same statement.
//
// A missing live connection returns no row. That prevents a superseded socket
// from advancing liveness after another replica has replaced its session.
func (q *Queries) RecordAgentHeartbeat(ctx context.Context, arg RecordAgentHeartbeatParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordAgentHeartbeat,
		arg.ConnectionID,
		arg.ClusterID,
		arg.AgentVersion,
		arg.KubernetesVersion,
		arg.NodeCount,
		arg.Distribution,
		arg.CpuUsagePercent,
		arg.MemoryUsagePercent,
		arg.PodCount,
		arg.Conditions,
	)
	var commands_pending bool
	err := row.Scan(&commands_pending)
	return commands_pending, err
}
