// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logging.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPipelineOutput = `-- name: AddPipelineOutput :exec

INSERT INTO logging_pipeline_outputs (logging_pipeline_id, logging_output_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPipelineOutputParams struct {
	LoggingPipelineID uuid.UUID `json:"logging_pipeline_id"`
	LoggingOutputID   uuid.UUID `json:"logging_output_id"`
}

// Pipeline <-> Output M2M
func (q *Queries) AddPipelineOutput(ctx context.Context, arg AddPipelineOutputParams) error {
	_, err := q.db.Exec(ctx, addPipelineOutput, arg.LoggingPipelineID, arg.LoggingOutputID)
	return err
}

const countLoggingOutputs = `-- name: CountLoggingOutputs :one
SELECT count(*) FROM logging_outputs
`

func (q *Queries) CountLoggingOutputs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLoggingOutputs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLoggingPipelines = `-- name: CountLoggingPipelines :one
SELECT count(*) FROM logging_pipelines
`

func (q *Queries) CountLoggingPipelines(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLoggingPipelines)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoggingOutput = `-- name: CreateLoggingOutput :one
INSERT INTO logging_outputs (name, output_type, configuration, cluster_id, enabled, created_by_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, output_type, configuration, cluster_id, enabled, created_by_id, created_at, updated_at
`

type CreateLoggingOutputParams struct {
	Name          string          `json:"name"`
	OutputType    string          `json:"output_type"`
	Configuration json.RawMessage `json:"configuration"`
	ClusterID     pgtype.UUID     `json:"cluster_id"`
	Enabled       bool            `json:"enabled"`
	CreatedByID   pgtype.UUID     `json:"created_by_id"`
}

func (q *Queries) CreateLoggingOutput(ctx context.Context, arg CreateLoggingOutputParams) (LoggingOutput, error) {
	row := q.db.QueryRow(ctx, createLoggingOutput,
		arg.Name,
		arg.OutputType,
		arg.Configuration,
		arg.ClusterID,
		arg.Enabled,
		arg.CreatedByID,
	)
	var i LoggingOutput
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OutputType,
		&i.Configuration,
		&i.ClusterID,
		&i.Enabled,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLoggingPipeline = `-- name: CreateLoggingPipeline :one
INSERT INTO logging_pipelines (name, cluster_id, namespaces, labels, filters, enabled, created_by_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, cluster_id, namespaces, labels, filters, enabled, created_by_id, created_at, updated_at
`

type CreateLoggingPipelineParams struct {
	Name        string          `json:"name"`
	ClusterID   uuid.UUID       `json:"cluster_id"`
	Namespaces  json.RawMessage `json:"namespaces"`
	Labels      json.RawMessage `json:"labels"`
	Filters     json.RawMessage `json:"filters"`
	Enabled     bool            `json:"enabled"`
	CreatedByID pgtype.UUID     `json:"created_by_id"`
}

func (q *Queries) CreateLoggingPipeline(ctx context.Context, arg CreateLoggingPipelineParams) (LoggingPipeline, error) {
	row := q.db.QueryRow(ctx, createLoggingPipeline,
		arg.Name,
		arg.ClusterID,
		arg.Namespaces,
		arg.Labels,
		arg.Filters,
		arg.Enabled,
		arg.CreatedByID,
	)
	var i LoggingPipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClusterID,
		&i.Namespaces,
		&i.Labels,
		&i.Filters,
		&i.Enabled,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLoggingOutput = `-- name: DeleteLoggingOutput :exec
DELETE FROM logging_outputs WHERE id = $1
`

func (q *Queries) DeleteLoggingOutput(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLoggingOutput, id)
	return err
}

const deleteLoggingPipeline = `-- name: DeleteLoggingPipeline :exec
DELETE FROM logging_pipelines WHERE id = $1
`

func (q *Queries) DeleteLoggingPipeline(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLoggingPipeline, id)
	return err
}

const getLoggingOutputByID = `-- name: GetLoggingOutputByID :one

SELECT id, name, output_type, configuration, cluster_id, enabled, created_by_id, created_at, updated_at FROM logging_outputs WHERE id = $1
`

// Logging Outputs
func (q *Queries) GetLoggingOutputByID(ctx context.Context, id uuid.UUID) (LoggingOutput, error) {
	row := q.db.QueryRow(ctx, getLoggingOutputByID, id)
	var i LoggingOutput
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OutputType,
		&i.Configuration,
		&i.ClusterID,
		&i.Enabled,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoggingPipelineByID = `-- name: GetLoggingPipelineByID :one

SELECT id, name, cluster_id, namespaces, labels, filters, enabled, created_by_id, created_at, updated_at FROM logging_pipelines WHERE id = $1
`

// Logging Pipelines
func (q *Queries) GetLoggingPipelineByID(ctx context.Context, id uuid.UUID) (LoggingPipeline, error) {
	row := q.db.QueryRow(ctx, getLoggingPipelineByID, id)
	var i LoggingPipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClusterID,
		&i.Namespaces,
		&i.Labels,
		&i.Filters,
		&i.Enabled,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledOutputsByCluster = `-- name: ListEnabledOutputsByCluster :many
SELECT id, name, output_type, configuration, cluster_id, enabled, created_by_id, created_at, updated_at FROM logging_outputs WHERE cluster_id = $1 AND enabled = true ORDER BY created_at DESC
`

func (q *Queries) ListEnabledOutputsByCluster(ctx context.Context, clusterID pgtype.UUID) ([]LoggingOutput, error) {
	rows, err := q.db.Query(ctx, listEnabledOutputsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoggingOutput{}
	for rows.Next() {
		var i LoggingOutput
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OutputType,
			&i.Configuration,
			&i.ClusterID,
			&i.Enabled,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPipelinesByCluster = `-- name: ListEnabledPipelinesByCluster :many
SELECT id, name, cluster_id, namespaces, labels, filters, enabled, created_by_id, created_at, updated_at FROM logging_pipelines WHERE cluster_id = $1 AND enabled = true ORDER BY created_at DESC
`

func (q *Queries) ListEnabledPipelinesByCluster(ctx context.Context, clusterID uuid.UUID) ([]LoggingPipeline, error) {
	rows, err := q.db.Query(ctx, listEnabledPipelinesByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoggingPipeline{}
	for rows.Next() {
		var i LoggingPipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClusterID,
			&i.Namespaces,
			&i.Labels,
			&i.Filters,
			&i.Enabled,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoggingOutputs = `-- name: ListLoggingOutputs :many
SELECT id, name, output_type, configuration, cluster_id, enabled, created_by_id, created_at, updated_at FROM logging_outputs ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListLoggingOutputsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLoggingOutputs(ctx context.Context, arg ListLoggingOutputsParams) ([]LoggingOutput, error) {
	rows, err := q.db.Query(ctx, listLoggingOutputs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoggingOutput{}
	for rows.Next() {
		var i LoggingOutput
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OutputType,
			&i.Configuration,
			&i.ClusterID,
			&i.Enabled,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoggingPipelines = `-- name: ListLoggingPipelines :many
SELECT id, name, cluster_id, namespaces, labels, filters, enabled, created_by_id, created_at, updated_at FROM logging_pipelines ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListLoggingPipelinesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLoggingPipelines(ctx context.Context, arg ListLoggingPipelinesParams) ([]LoggingPipeline, error) {
	rows, err := q.db.Query(ctx, listLoggingPipelines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoggingPipeline{}
	for rows.Next() {
		var i LoggingPipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClusterID,
			&i.Namespaces,
			&i.Labels,
			&i.Filters,
			&i.Enabled,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutputsByCluster = `-- name: ListOutputsByCluster :many
SELECT id, name, output_type, configuration, cluster_id, enabled, created_by_id, created_at, updated_at FROM logging_outputs WHERE cluster_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListOutputsByClusterParams struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListOutputsByCluster(ctx context.Context, arg ListOutputsByClusterParams) ([]LoggingOutput, error) {
	rows, err := q.db.Query(ctx, listOutputsByCluster, arg.ClusterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoggingOutput{}
	for rows.Next() {
		var i LoggingOutput
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OutputType,
			&i.Configuration,
			&i.ClusterID,
			&i.Enabled,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutputsForPipeline = `-- name: ListOutputsForPipeline :many
SELECT lo.id, lo.name, lo.output_type, lo.configuration, lo.cluster_id, lo.enabled, lo.created_by_id, lo.created_at, lo.updated_at FROM logging_outputs lo
INNER JOIN logging_pipeline_outputs lpo ON lo.id = lpo.logging_output_id
WHERE lpo.logging_pipeline_id = $1
`

func (q *Queries) ListOutputsForPipeline(ctx context.Context, loggingPipelineID uuid.UUID) ([]LoggingOutput, error) {
	rows, err := q.db.Query(ctx, listOutputsForPipeline, loggingPipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoggingOutput{}
	for rows.Next() {
		var i LoggingOutput
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OutputType,
			&i.Configuration,
			&i.ClusterID,
			&i.Enabled,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByCluster = `-- name: ListPipelinesByCluster :many
SELECT id, name, cluster_id, namespaces, labels, filters, enabled, created_by_id, created_at, updated_at FROM logging_pipelines WHERE cluster_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPipelinesByClusterParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListPipelinesByCluster(ctx context.Context, arg ListPipelinesByClusterParams) ([]LoggingPipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByCluster, arg.ClusterID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoggingPipeline{}
	for rows.Next() {
		var i LoggingPipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClusterID,
			&i.Namespaces,
			&i.Labels,
			&i.Filters,
			&i.Enabled,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesForOutput = `-- name: ListPipelinesForOutput :many
SELECT lp.id, lp.name, lp.cluster_id, lp.namespaces, lp.labels, lp.filters, lp.enabled, lp.created_by_id, lp.created_at, lp.updated_at FROM logging_pipelines lp
INNER JOIN logging_pipeline_outputs lpo ON lp.id = lpo.logging_pipeline_id
WHERE lpo.logging_output_id = $1
`

func (q *Queries) ListPipelinesForOutput(ctx context.Context, loggingOutputID uuid.UUID) ([]LoggingPipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesForOutput, loggingOutputID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoggingPipeline{}
	for rows.Next() {
		var i LoggingPipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClusterID,
			&i.Namespaces,
			&i.Labels,
			&i.Filters,
			&i.Enabled,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePipelineOutput = `-- name: RemovePipelineOutput :exec
DELETE FROM logging_pipeline_outputs WHERE logging_pipeline_id = $1 AND logging_output_id = $2
`

type RemovePipelineOutputParams struct {
	LoggingPipelineID uuid.UUID `json:"logging_pipeline_id"`
	LoggingOutputID   uuid.UUID `json:"logging_output_id"`
}

func (q *Queries) RemovePipelineOutput(ctx context.Context, arg RemovePipelineOutputParams) error {
	_, err := q.db.Exec(ctx, removePipelineOutput, arg.LoggingPipelineID, arg.LoggingOutputID)
	return err
}

const updateLoggingOutput = `-- name: UpdateLoggingOutput :one
UPDATE logging_outputs SET
    name = $2,
    output_type = $3,
    configuration = $4,
    enabled = $5
WHERE id = $1
RETURNING id, name, output_type, configuration, cluster_id, enabled, created_by_id, created_at, updated_at
`

type UpdateLoggingOutputParams struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	OutputType    string          `json:"output_type"`
	Configuration json.RawMessage `json:"configuration"`
	Enabled       bool            `json:"enabled"`
}

func (q *Queries) UpdateLoggingOutput(ctx context.Context, arg UpdateLoggingOutputParams) (LoggingOutput, error) {
	row := q.db.QueryRow(ctx, updateLoggingOutput,
		arg.ID,
		arg.Name,
		arg.OutputType,
		arg.Configuration,
		arg.Enabled,
	)
	var i LoggingOutput
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OutputType,
		&i.Configuration,
		&i.ClusterID,
		&i.Enabled,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoggingPipeline = `-- name: UpdateLoggingPipeline :one
UPDATE logging_pipelines SET
    name = $2,
    namespaces = $3,
    labels = $4,
    filters = $5,
    enabled = $6
WHERE id = $1
RETURNING id, name, cluster_id, namespaces, labels, filters, enabled, created_by_id, created_at, updated_at
`

type UpdateLoggingPipelineParams struct {
	ID         uuid.UUID       `json:"id"`
	Name       string          `json:"name"`
	Namespaces json.RawMessage `json:"namespaces"`
	Labels     json.RawMessage `json:"labels"`
	Filters    json.RawMessage `json:"filters"`
	Enabled    bool            `json:"enabled"`
}

func (q *Queries) UpdateLoggingPipeline(ctx context.Context, arg UpdateLoggingPipelineParams) (LoggingPipeline, error) {
	row := q.db.QueryRow(ctx, updateLoggingPipeline,
		arg.ID,
		arg.Name,
		arg.Namespaces,
		arg.Labels,
		arg.Filters,
		arg.Enabled,
	)
	var i LoggingPipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClusterID,
		&i.Namespaces,
		&i.Labels,
		&i.Filters,
		&i.Enabled,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
