// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentConnection struct {
	ID             uuid.UUID          `json:"id"`
	ClusterID      uuid.UUID          `json:"cluster_id"`
	AgentID        string             `json:"agent_id"`
	SessionID      string             `json:"session_id"`
	ConnectedAt    time.Time          `json:"connected_at"`
	DisconnectedAt pgtype.Timestamptz `json:"disconnected_at"`
	LastPing       pgtype.Timestamptz `json:"last_ping"`
	Status         string             `json:"status"`
	ChannelName    string             `json:"channel_name"`
	PodName        string             `json:"pod_name"`
	NodeName       string             `json:"node_name"`
	AgentVersion   string             `json:"agent_version"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type AlertEvent struct {
	ID               uuid.UUID          `json:"id"`
	RuleID           uuid.UUID          `json:"rule_id"`
	ClusterID        pgtype.UUID        `json:"cluster_id"`
	Status           string             `json:"status"`
	Message          string             `json:"message"`
	Details          json.RawMessage    `json:"details"`
	FiredAt          time.Time          `json:"fired_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	AcknowledgedByID pgtype.UUID        `json:"acknowledged_by_id"`
	AcknowledgedAt   pgtype.Timestamptz `json:"acknowledged_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type AlertRule struct {
	ID              uuid.UUID       `json:"id"`
	Name            string          `json:"name"`
	ClusterID       pgtype.UUID     `json:"cluster_id"`
	RuleType        string          `json:"rule_type"`
	Configuration   json.RawMessage `json:"configuration"`
	Severity        string          `json:"severity"`
	Enabled         bool            `json:"enabled"`
	CooldownMinutes int32           `json:"cooldown_minutes"`
	CreatedByID     pgtype.UUID     `json:"created_by_id"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type AlertRuleChannel struct {
	AlertRuleID           uuid.UUID `json:"alert_rule_id"`
	NotificationChannelID uuid.UUID `json:"notification_channel_id"`
}

type AlertSilence struct {
	ID          uuid.UUID   `json:"id"`
	RuleID      pgtype.UUID `json:"rule_id"`
	ClusterID   pgtype.UUID `json:"cluster_id"`
	Reason      string      `json:"reason"`
	StartsAt    time.Time   `json:"starts_at"`
	EndsAt      time.Time   `json:"ends_at"`
	CreatedByID pgtype.UUID `json:"created_by_id"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type ApiToken struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Name             string             `json:"name"`
	TokenHash        string             `json:"token_hash"`
	Prefix           string             `json:"prefix"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	IsRevoked        bool               `json:"is_revoked"`
	Scopes           json.RawMessage    `json:"scopes"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	AllowedCidrs     string             `json:"allowed_cidrs"`
	LastSeenRemoteIp string             `json:"last_seen_remote_ip"`
}

type ArgocdApplication struct {
	ID                   uuid.UUID          `json:"id"`
	ArgocdInstanceID     uuid.UUID          `json:"argocd_instance_id"`
	Name                 string             `json:"name"`
	Project              string             `json:"project"`
	RepoUrl              string             `json:"repo_url"`
	Path                 string             `json:"path"`
	TargetRevision       string             `json:"target_revision"`
	DestinationCluster   string             `json:"destination_cluster"`
	DestinationNamespace string             `json:"destination_namespace"`
	SyncStatus           string             `json:"sync_status"`
	HealthStatus         string             `json:"health_status"`
	LastSynced           pgtype.Timestamptz `json:"last_synced"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type ArgocdInstance struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	ClusterID          uuid.UUID          `json:"cluster_id"`
	ApiUrl             string             `json:"api_url"`
	AuthTokenEncrypted string             `json:"auth_token_encrypted"`
	VerifySsl          bool               `json:"verify_ssl"`
	IsHealthy          bool               `json:"is_healthy"`
	LastSync           pgtype.Timestamptz `json:"last_sync"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type ArgocdManagedCluster struct {
	ID                uuid.UUID       `json:"id"`
	ArgocdInstanceID  uuid.UUID       `json:"argocd_instance_id"`
	ClusterID         uuid.UUID       `json:"cluster_id"`
	ClusterSecretName string          `json:"cluster_secret_name"`
	ServerUrl         string          `json:"server_url"`
	Labels            json.RawMessage `json:"labels"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type ArgocdOperation struct {
	ID            uuid.UUID          `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetKey     string             `json:"target_key"`
	OperationType string             `json:"operation_type"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage  string             `json:"error_message"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	Revision      string             `json:"revision"`
	Message       string             `json:"message"`
	OperationID   string             `json:"operation_id"`
	Phase         string             `json:"phase"`
	PollAttempts  int32              `json:"poll_attempts"`
	LastPolledAt  pgtype.Timestamptz `json:"last_polled_at"`
}

type ArgocdOperationEvent struct {
	ID          uuid.UUID       `json:"id"`
	OperationID uuid.UUID       `json:"operation_id"`
	Level       string          `json:"level"`
	Stage       string          `json:"stage"`
	Message     string          `json:"message"`
	Detail      json.RawMessage `json:"detail"`
	CreatedAt   time.Time       `json:"created_at"`
}

type AuditArchive struct {
	ID                uuid.UUID       `json:"id"`
	CreatedAt         time.Time       `json:"created_at"`
	SchemaVersion     string          `json:"schema_version"`
	UserID            pgtype.UUID     `json:"user_id"`
	ActorAuthMethod   string          `json:"actor_auth_method"`
	Action            string          `json:"action"`
	ResourceType      string          `json:"resource_type"`
	ResourceID        string          `json:"resource_id"`
	ResourceName      string          `json:"resource_name"`
	HttpMethod        string          `json:"http_method"`
	Path              string          `json:"path"`
	StatusCode        int32           `json:"status_code"`
	DurationMs        int64           `json:"duration_ms"`
	RequestID         string          `json:"request_id"`
	IpAddress         *netip.Addr     `json:"ip_address"`
	UserAgent         string          `json:"user_agent"`
	Detail            json.RawMessage `json:"detail"`
	Source            string          `json:"source"`
	CorrelationID     string          `json:"correlation_id"`
	ArchivedClusterID pgtype.UUID     `json:"archived_cluster_id"`
	ArchivedAt        time.Time       `json:"archived_at"`
}

type AuditLog struct {
	ID              uuid.UUID       `json:"id"`
	CreatedAt       time.Time       `json:"created_at"`
	SchemaVersion   string          `json:"schema_version"`
	UserID          pgtype.UUID     `json:"user_id"`
	ActorAuthMethod string          `json:"actor_auth_method"`
	Action          string          `json:"action"`
	ResourceType    string          `json:"resource_type"`
	ResourceID      string          `json:"resource_id"`
	ResourceName    string          `json:"resource_name"`
	HttpMethod      string          `json:"http_method"`
	Path            string          `json:"path"`
	StatusCode      int32           `json:"status_code"`
	DurationMs      int64           `json:"duration_ms"`
	RequestID       string          `json:"request_id"`
	IpAddress       *netip.Addr     `json:"ip_address"`
	UserAgent       string          `json:"user_agent"`
	Detail          json.RawMessage `json:"detail"`
	Source          string          `json:"source"`
	CorrelationID   string          `json:"correlation_id"`
	// ActionClass classifies the row as mutation / read / auth / system.
	// Added in migration 063 to support read-side audit filtering.
	ActionClass string `json:"action_class"`
}

type AuditLogDefault struct {
	ID              uuid.UUID       `json:"id"`
	CreatedAt       time.Time       `json:"created_at"`
	SchemaVersion   string          `json:"schema_version"`
	UserID          pgtype.UUID     `json:"user_id"`
	ActorAuthMethod string          `json:"actor_auth_method"`
	Action          string          `json:"action"`
	ResourceType    string          `json:"resource_type"`
	ResourceID      string          `json:"resource_id"`
	ResourceName    string          `json:"resource_name"`
	HttpMethod      string          `json:"http_method"`
	Path            string          `json:"path"`
	StatusCode      int32           `json:"status_code"`
	DurationMs      int64           `json:"duration_ms"`
	RequestID       string          `json:"request_id"`
	IpAddress       *netip.Addr     `json:"ip_address"`
	UserAgent       string          `json:"user_agent"`
	Detail          json.RawMessage `json:"detail"`
}

type Backup struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	StorageID          uuid.UUID          `json:"storage_id"`
	BackupType         string             `json:"backup_type"`
	Status             string             `json:"status"`
	FilePath           string             `json:"file_path"`
	FileSizeBytes      int64              `json:"file_size_bytes"`
	DatabaseTables     json.RawMessage    `json:"database_tables"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage       string             `json:"error_message"`
	CreatedByID        pgtype.UUID        `json:"created_by_id"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	ClusterID          pgtype.UUID        `json:"cluster_id"`
	VeleroBackupName   string             `json:"velero_backup_name"`
	VeleroNamespace    string             `json:"velero_namespace"`
	IncludedNamespaces json.RawMessage    `json:"included_namespaces"`
	ExcludedNamespaces json.RawMessage    `json:"excluded_namespaces"`
	PollAttempts       int32              `json:"poll_attempts"`
	LastPolledAt       pgtype.Timestamptz `json:"last_polled_at"`
}

type BackupDrillResult struct {
	ID            uuid.UUID          `json:"id"`
	StartedAt     time.Time          `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Status        string             `json:"status"`
	BackupKey     string             `json:"backup_key"`
	SchemaVersion pgtype.Int4        `json:"schema_version"`
	ErrorMessage  string             `json:"error_message"`
	CreatedAt     time.Time          `json:"created_at"`
}

type BackupSchedule struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	StorageID          uuid.UUID       `json:"storage_id"`
	BackupType         string          `json:"backup_type"`
	CronExpression     string          `json:"cron_expression"`
	RetentionCount     int32           `json:"retention_count"`
	Enabled            bool            `json:"enabled"`
	LastBackupID       pgtype.UUID     `json:"last_backup_id"`
	CreatedByID        pgtype.UUID     `json:"created_by_id"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ClusterID          pgtype.UUID     `json:"cluster_id"`
	VeleroNamespace    string          `json:"velero_namespace"`
	VeleroScheduleName string          `json:"velero_schedule_name"`
	IncludedNamespaces json.RawMessage `json:"included_namespaces"`
	ExcludedNamespaces json.RawMessage `json:"excluded_namespaces"`
	Ttl                string          `json:"ttl"`
}

type BackupStorageConfig struct {
	ID                   uuid.UUID   `json:"id"`
	Name                 string      `json:"name"`
	StorageType          string      `json:"storage_type"`
	Bucket               string      `json:"bucket"`
	Prefix               string      `json:"prefix"`
	Region               string      `json:"region"`
	EndpointUrl          string      `json:"endpoint_url"`
	AccessKey            string      `json:"access_key"`
	SecretKey            string      `json:"secret_key"`
	IsDefault            bool        `json:"is_default"`
	CreatedByID          pgtype.UUID `json:"created_by_id"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	ClusterID            pgtype.UUID `json:"cluster_id"`
	VeleroNamespace      string      `json:"velero_namespace"`
	BslName              string      `json:"bsl_name"`
	EncryptedCredentials string      `json:"encrypted_credentials"`
}

type CatalogOperation struct {
	ID            uuid.UUID          `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetKey     string             `json:"target_key"`
	OperationType string             `json:"operation_type"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage  string             `json:"error_message"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type CatalogOperationEvent struct {
	ID          uuid.UUID       `json:"id"`
	OperationID uuid.UUID       `json:"operation_id"`
	Level       string          `json:"level"`
	Stage       string          `json:"stage"`
	Message     string          `json:"message"`
	Detail      json.RawMessage `json:"detail"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Cluster struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	Status            string             `json:"status"`
	ApiServerUrl      string             `json:"api_server_url"`
	CaCertificate     string             `json:"ca_certificate"`
	Environment       string             `json:"environment"`
	Region            string             `json:"region"`
	Provider          string             `json:"provider"`
	Labels            json.RawMessage    `json:"labels"`
	Annotations       json.RawMessage    `json:"annotations"`
	Distribution      string             `json:"distribution"`
	AgentVersion      string             `json:"agent_version"`
	LastHeartbeat     pgtype.Timestamptz `json:"last_heartbeat"`
	KubernetesVersion string             `json:"kubernetes_version"`
	NodeCount         int32              `json:"node_count"`
	CreatedByID       pgtype.UUID        `json:"created_by_id"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	IsLocal           bool               `json:"is_local"`
	DecommissionedAt  pgtype.Timestamptz `json:"decommissioned_at"`
}

type ClusterAgentToken struct {
	ID         uuid.UUID          `json:"id"`
	ClusterID  uuid.UUID          `json:"cluster_id"`
	Token      string             `json:"token"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type ClusterCondition struct {
	ID                 uuid.UUID `json:"id"`
	ClusterID          uuid.UUID `json:"cluster_id"`
	Type               string    `json:"type"`
	Status             string    `json:"status"`
	Reason             string    `json:"reason"`
	Message            string    `json:"message"`
	LastTransitionTime time.Time `json:"last_transition_time"`
	LastProbeTime      time.Time `json:"last_probe_time"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type ClusterDecommission struct {
	ID            uuid.UUID          `json:"id"`
	ClusterID     uuid.UUID          `json:"cluster_id"`
	Status        string             `json:"status"`
	Phases        json.RawMessage    `json:"phases"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	LastError     string             `json:"last_error"`
	Attempts      int32              `json:"attempts"`
	RequestedByID pgtype.UUID        `json:"requested_by_id"`
	ClusterName   string             `json:"cluster_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type ClusterHealthStatus struct {
	ID                 uuid.UUID       `json:"id"`
	ClusterID          uuid.UUID       `json:"cluster_id"`
	CpuUsagePercent    float64         `json:"cpu_usage_percent"`
	MemoryUsagePercent float64         `json:"memory_usage_percent"`
	PodCount           int32           `json:"pod_count"`
	NodeCount          int32           `json:"node_count"`
	Conditions         json.RawMessage `json:"conditions"`
	LastCheck          time.Time       `json:"last_check"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type ClusterMonitoringConfig struct {
	ID                      uuid.UUID          `json:"id"`
	ClusterID               uuid.UUID          `json:"cluster_id"`
	BackendID               uuid.UUID          `json:"backend_id"`
	ClusterLabel            string             `json:"cluster_label"`
	ClusterLabelValue       string             `json:"cluster_label_value"`
	ScrapeIntervalSeconds   int32              `json:"scrape_interval_seconds"`
	Retention               string             `json:"retention"`
	StackNamespace          string             `json:"stack_namespace"`
	PrometheusReleaseName   string             `json:"prometheus_release_name"`
	ThanosSidecarEnabled    bool               `json:"thanos_sidecar_enabled"`
	Status                  string             `json:"status"`
	LastHealthyAt           pgtype.Timestamptz `json:"last_healthy_at"`
	CreatedByID             pgtype.UUID        `json:"created_by_id"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
	StorageConfigID         pgtype.UUID        `json:"storage_config_id"`
	ObjectStorageSecretName string             `json:"object_storage_secret_name"`
	StorageClass            string             `json:"storage_class"`
	StorageSize             string             `json:"storage_size"`
	LastAppliedSpecHash     string             `json:"last_applied_spec_hash"`
	LastObservedStatus      string             `json:"last_observed_status"`
	LastObservedRevision    int32              `json:"last_observed_revision"`
	LastObservedAt          pgtype.Timestamptz `json:"last_observed_at"`
	LastDriftDetectedAt     pgtype.Timestamptz `json:"last_drift_detected_at"`
}

type ClusterRegistrationPolicy struct {
	ClusterID         uuid.UUID   `json:"cluster_id"`
	TokenRotationDays int32       `json:"token_rotation_days"`
	SourceTemplateID  pgtype.UUID `json:"source_template_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}

type ClusterRegistrationToken struct {
	ID        uuid.UUID `json:"id"`
	ClusterID uuid.UUID `json:"cluster_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	IsUsed    bool      `json:"is_used"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ClusterTemplate is migration-049's operator-defined "Production Web App"
// style template. spec is JSONB; the handler validates the shape at
// write time so a future schema evolution doesn't require an ALTER TABLE.
type ClusterTemplate struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Spec        json.RawMessage `json:"spec"`
	CreatedBy   pgtype.UUID     `json:"created_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// ClusterTemplateApplication tracks "which template is bound to this
// cluster, and how did the most recent apply go?". One row per cluster
// (cluster_id is the PK). spec_snapshot is the template body at the time
// of the last apply — drift detection compares the live state to this.
type ClusterTemplateApplication struct {
	ClusterID    uuid.UUID          `json:"cluster_id"`
	TemplateID   uuid.UUID          `json:"template_id"`
	Status       string             `json:"status"`
	SpecSnapshot json.RawMessage    `json:"spec_snapshot"`
	LastError    string             `json:"last_error"`
	AppliedAt    pgtype.Timestamptz `json:"applied_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type ClusterRegistryConfig struct {
	ID                 uuid.UUID          `json:"id"`
	ClusterID          uuid.UUID          `json:"cluster_id"`
	PrivateRegistryUrl string             `json:"private_registry_url"`
	RegistryUsername   string             `json:"registry_username"`
	RegistryPassword   string             `json:"registry_password"`
	Insecure           bool               `json:"insecure"`
	CaBundle           string             `json:"ca_bundle"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	Namespaces         json.RawMessage    `json:"namespaces"`
	InjectDefaultSa    bool               `json:"inject_default_sa"`
	SecretName         string             `json:"secret_name"`
	LastAppliedAt      pgtype.Timestamptz `json:"last_applied_at"`
	LastApplyError     string             `json:"last_apply_error"`
}

type ClusterRole struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	Rules       json.RawMessage `json:"rules"`
	IsBuiltin   bool            `json:"is_builtin"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	DisplayName string          `json:"display_name"`
}

type ClusterRoleBinding struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Group     string      `json:"group"`
	RoleID    uuid.UUID   `json:"role_id"`
	ClusterID uuid.UUID   `json:"cluster_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	Source    string      `json:"source"`
}

type ClusterSecurityPolicy struct {
	ID           uuid.UUID          `json:"id"`
	ClusterID    uuid.UUID          `json:"cluster_id"`
	TemplateID   uuid.UUID          `json:"template_id"`
	AppliedAt    pgtype.Timestamptz `json:"applied_at"`
	SyncStatus   string             `json:"sync_status"`
	ErrorMessage string             `json:"error_message"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type ClusterTool struct {
	ID                uuid.UUID       `json:"id"`
	Slug              string          `json:"slug"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Icon              string          `json:"icon"`
	Category          string          `json:"category"`
	Charts            json.RawMessage `json:"charts"`
	VersionConstraint string          `json:"version_constraint"`
	DefaultNamespace  string          `json:"default_namespace"`
	IsBuiltin         bool            `json:"is_builtin"`
	IsEnabled         bool            `json:"is_enabled"`
	HelmChartID       pgtype.UUID     `json:"helm_chart_id"`
	Presets           json.RawMessage `json:"presets"`
	ServiceName       string          `json:"service_name"`
	ServicePort       pgtype.Int4     `json:"service_port"`
	ServicePath       string          `json:"service_path"`
	SubServices       json.RawMessage `json:"sub_services"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type ControlPlaneAlert struct {
	ID               uuid.UUID          `json:"id"`
	Controller       string             `json:"controller"`
	ConditionType    string             `json:"condition_type"`
	Status           string             `json:"status"`
	Message          string             `json:"message"`
	Detail           json.RawMessage    `json:"detail"`
	FiredAt          time.Time          `json:"fired_at"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	AcknowledgedByID pgtype.UUID        `json:"acknowledged_by_id"`
	AcknowledgedAt   pgtype.Timestamptz `json:"acknowledged_at"`
}

type ControlPlanePolicy struct {
	ID                               uuid.UUID `json:"id"`
	Name                             string    `json:"name"`
	MonitoringQueueDepthThreshold    int32     `json:"monitoring_queue_depth_threshold"`
	ArgocdQueueDepthThreshold        int32     `json:"argocd_queue_depth_threshold"`
	ToolsQueueDepthThreshold         int32     `json:"tools_queue_depth_threshold"`
	CatalogQueueDepthThreshold       int32     `json:"catalog_queue_depth_threshold"`
	MonitoringStaleRunningThreshold  int32     `json:"monitoring_stale_running_threshold"`
	ArgocdStaleRunningThreshold      int32     `json:"argocd_stale_running_threshold"`
	ToolsStaleRunningThreshold       int32     `json:"tools_stale_running_threshold"`
	CatalogStaleRunningThreshold     int32     `json:"catalog_stale_running_threshold"`
	MonitoringRecentFailureThreshold int32     `json:"monitoring_recent_failure_threshold"`
	ArgocdRecentFailureThreshold     int32     `json:"argocd_recent_failure_threshold"`
	ToolsRecentFailureThreshold      int32     `json:"tools_recent_failure_threshold"`
	CatalogRecentFailureThreshold    int32     `json:"catalog_recent_failure_threshold"`
	RecentFailureWindowMinutes       int32     `json:"recent_failure_window_minutes"`
	CreatedAt                        time.Time `json:"created_at"`
	UpdatedAt                        time.Time `json:"updated_at"`
}

type ControlPlaneSilence struct {
	ID            uuid.UUID   `json:"id"`
	Controller    string      `json:"controller"`
	ConditionType string      `json:"condition_type"`
	Reason        string      `json:"reason"`
	StartsAt      time.Time   `json:"starts_at"`
	EndsAt        time.Time   `json:"ends_at"`
	CreatedByID   pgtype.UUID `json:"created_by_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type DexConnector struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Type        string          `json:"type"`
	DisplayName string          `json:"display_name"`
	Config      json.RawMessage `json:"config"`
	Enabled     bool            `json:"enabled"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type DexSetting struct {
	ID            uuid.UUID       `json:"id"`
	IssuerUrl     string          `json:"issuer_url"`
	ClusterID     pgtype.UUID     `json:"cluster_id"`
	Namespace     string          `json:"namespace"`
	ReleaseName   string          `json:"release_name"`
	ConfigmapName string          `json:"configmap_name"`
	PublicClients json.RawMessage `json:"public_clients"`
	Expiry        json.RawMessage `json:"expiry"`
	Extra         json.RawMessage `json:"extra"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type GlobalRole struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	Rules       json.RawMessage `json:"rules"`
	IsBuiltin   bool            `json:"is_builtin"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	DisplayName string          `json:"display_name"`
}

type GlobalRoleBinding struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Group     string      `json:"group"`
	RoleID    uuid.UUID   `json:"role_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	Source    string      `json:"source"`
}

type HelmChart struct {
	ID           uuid.UUID       `json:"id"`
	RepositoryID uuid.UUID       `json:"repository_id"`
	Name         string          `json:"name"`
	DisplayName  string          `json:"display_name"`
	Description  string          `json:"description"`
	IconUrl      string          `json:"icon_url"`
	HomeUrl      string          `json:"home_url"`
	Category     string          `json:"category"`
	Keywords     json.RawMessage `json:"keywords"`
	Maintainers  json.RawMessage `json:"maintainers"`
	Deprecated   bool            `json:"deprecated"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type HelmChartVersion struct {
	ID                uuid.UUID          `json:"id"`
	ChartID           uuid.UUID          `json:"chart_id"`
	Version           string             `json:"version"`
	AppVersion        string             `json:"app_version"`
	Digest            string             `json:"digest"`
	Urls              json.RawMessage    `json:"urls"`
	ValuesSchema      json.RawMessage    `json:"values_schema"`
	DefaultValues     string             `json:"default_values"`
	Readme            string             `json:"readme"`
	CreatedAtUpstream pgtype.Timestamptz `json:"created_at_upstream"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type HelmRepository struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Url          string             `json:"url"`
	RepoType     string             `json:"repo_type"`
	Description  string             `json:"description"`
	IsDefault    bool               `json:"is_default"`
	AuthType     string             `json:"auth_type"`
	AuthConfig   json.RawMessage    `json:"auth_config"`
	Enabled      bool               `json:"enabled"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	CreatedByID  pgtype.UUID        `json:"created_by_id"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type InstalledChart struct {
	ID             uuid.UUID   `json:"id"`
	ClusterID      uuid.UUID   `json:"cluster_id"`
	ChartVersionID pgtype.UUID `json:"chart_version_id"`
	ReleaseName    string      `json:"release_name"`
	Namespace      string      `json:"namespace"`
	ValuesOverride string      `json:"values_override"`
	Status         string      `json:"status"`
	Revision       int32       `json:"revision"`
	Notes          string      `json:"notes"`
	InstalledByID  pgtype.UUID `json:"installed_by_id"`
	RequestID      pgtype.UUID `json:"request_id"`
	ToolSlug       pgtype.Text `json:"tool_slug"`
	PresetUsed     pgtype.Text `json:"preset_used"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type JwtRevocation struct {
	Jti       string    `json:"jti"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	RevokedAt time.Time `json:"revoked_at"`
	Reason    string    `json:"reason"`
}

type LoggingOperation struct {
	ID            uuid.UUID          `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetKey     string             `json:"target_key"`
	OperationType string             `json:"operation_type"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage  string             `json:"error_message"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type LoggingOperationEvent struct {
	ID          uuid.UUID       `json:"id"`
	OperationID uuid.UUID       `json:"operation_id"`
	Level       string          `json:"level"`
	Stage       string          `json:"stage"`
	Message     string          `json:"message"`
	Detail      json.RawMessage `json:"detail"`
	CreatedAt   time.Time       `json:"created_at"`
}

type LoggingOutput struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	OutputType    string          `json:"output_type"`
	Configuration json.RawMessage `json:"configuration"`
	ClusterID     pgtype.UUID     `json:"cluster_id"`
	Enabled       bool            `json:"enabled"`
	CreatedByID   pgtype.UUID     `json:"created_by_id"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type LoggingPipeline struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	ClusterID   uuid.UUID       `json:"cluster_id"`
	Namespaces  json.RawMessage `json:"namespaces"`
	Labels      json.RawMessage `json:"labels"`
	Filters     json.RawMessage `json:"filters"`
	Enabled     bool            `json:"enabled"`
	CreatedByID pgtype.UUID     `json:"created_by_id"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type LoggingPipelineOutput struct {
	LoggingPipelineID uuid.UUID `json:"logging_pipeline_id"`
	LoggingOutputID   uuid.UUID `json:"logging_output_id"`
}

type MonitoringBackend struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	BackendType        string          `json:"backend_type"`
	QueryUrl           string          `json:"query_url"`
	AlertmanagerUrl    string          `json:"alertmanager_url"`
	TenantID           string          `json:"tenant_id"`
	AuthType           string          `json:"auth_type"`
	AuthConfig         json.RawMessage `json:"auth_config"`
	DefaultStepSeconds int32           `json:"default_step_seconds"`
	TimeoutSeconds     int32           `json:"timeout_seconds"`
	IsDefault          bool            `json:"is_default"`
	CreatedByID        pgtype.UUID     `json:"created_by_id"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type MonitoringOperation struct {
	ID            uuid.UUID          `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetKey     string             `json:"target_key"`
	OperationType string             `json:"operation_type"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage  string             `json:"error_message"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type MonitoringOperationEvent struct {
	ID          uuid.UUID       `json:"id"`
	OperationID uuid.UUID       `json:"operation_id"`
	Level       string          `json:"level"`
	Stage       string          `json:"stage"`
	Message     string          `json:"message"`
	Detail      json.RawMessage `json:"detail"`
	CreatedAt   time.Time       `json:"created_at"`
}

type NotificationChannel struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	ChannelType   string          `json:"channel_type"`
	Configuration json.RawMessage `json:"configuration"`
	Enabled       bool            `json:"enabled"`
	CreatedByID   pgtype.UUID     `json:"created_by_id"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type PlatformConfiguration struct {
	ID               int32              `json:"id"`
	ServerUrl        string             `json:"server_url"`
	PlatformName     string             `json:"platform_name"`
	TelemetryEnabled bool               `json:"telemetry_enabled"`
	BootstrappedAt   pgtype.Timestamptz `json:"bootstrapped_at"`
	InstanceID       uuid.UUID          `json:"instance_id"`
	// DefaultClusterTemplateID is migration-074's auto-attach default.
	// When Valid, the cluster Create handler records a
	// cluster_template_applications row pointing at this template so the
	// sprint-049 apply worker installs the baseline (trivy-operator,
	// kube-state-metrics, node-exporter, fluent-bit, cert-manager) on
	// every newly-registered cluster. ON DELETE SET NULL in the FK so
	// removing the template gracefully degrades to "no auto-attach".
	DefaultClusterTemplateID pgtype.UUID `json:"default_cluster_template_id"`
}

type PlatformSetting struct {
	Key         string          `json:"key"`
	Value       json.RawMessage `json:"value"`
	Description string          `json:"description"`
	UpdatedBy   pgtype.UUID     `json:"updated_by"`
	UpdatedAt   time.Time       `json:"updated_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

type PodSecurityTemplate struct {
	ID                   uuid.UUID       `json:"id"`
	Name                 string          `json:"name"`
	Description          string          `json:"description"`
	IsDefault            bool            `json:"is_default"`
	EnforceLevel         string          `json:"enforce_level"`
	EnforceVersion       string          `json:"enforce_version"`
	AuditLevel           string          `json:"audit_level"`
	AuditVersion         string          `json:"audit_version"`
	WarnLevel            string          `json:"warn_level"`
	WarnVersion          string          `json:"warn_version"`
	ExemptUsernames      json.RawMessage `json:"exempt_usernames"`
	ExemptRuntimeClasses json.RawMessage `json:"exempt_runtime_classes"`
	ExemptNamespaces     json.RawMessage `json:"exempt_namespaces"`
	CreatedByID          pgtype.UUID     `json:"created_by_id"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

type Project struct {
	ID                       uuid.UUID       `json:"id"`
	Name                     string          `json:"name"`
	DisplayName              string          `json:"display_name"`
	Description              string          `json:"description"`
	ClusterID                uuid.UUID       `json:"cluster_id"`
	Namespaces               json.RawMessage `json:"namespaces"`
	ResourceQuota            json.RawMessage `json:"resource_quota"`
	CreatedByID              pgtype.UUID     `json:"created_by_id"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
	LimitRange               json.RawMessage `json:"limit_range"`
	NetworkPolicyMode        string          `json:"network_policy_mode"`
	PodSecurityProfile       string          `json:"pod_security_profile"`
	ResourceQuotaCpuLimit    string          `json:"resource_quota_cpu_limit"`
	ResourceQuotaMemoryLimit string          `json:"resource_quota_memory_limit"`
	ResourceQuotaPodCount    int32           `json:"resource_quota_pod_count"`
	QuotaPlan                string          `json:"quota_plan"`
	QuotaOverrides           json.RawMessage `json:"quota_overrides"`
}

type ProjectNamespace struct {
	ProjectID          uuid.UUID          `json:"project_id"`
	ClusterID          uuid.UUID          `json:"cluster_id"`
	Namespace          string             `json:"namespace"`
	LastReconciledAt   pgtype.Timestamptz `json:"last_reconciled_at"`
	LastReconcileError string             `json:"last_reconcile_error"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type ProjectRole struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	Rules       json.RawMessage `json:"rules"`
	IsBuiltin   bool            `json:"is_builtin"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	DisplayName string          `json:"display_name"`
}

type ProjectRoleBinding struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Group     string      `json:"group"`
	RoleID    uuid.UUID   `json:"role_id"`
	ProjectID uuid.UUID   `json:"project_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	Source    string      `json:"source"`
}

// IdentityGroupMapping is the row shape for identity_group_mappings.
// Mapping an external IdP group name to one or more RBAC role bindings;
// resolved on every SSO login by internal/auth.SyncUserGroups.
type IdentityGroupMapping struct {
	ID          uuid.UUID   `json:"id"`
	ConnectorID pgtype.UUID `json:"connector_id"`
	GroupName   string      `json:"group_name"`
	Scope       string      `json:"scope"`
	RoleID      uuid.UUID   `json:"role_id"`
	ClusterID   pgtype.UUID `json:"cluster_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

// UserIdpGroup is the row shape for user_idp_groups — the per-user
// snapshot of the groups slice last claimed by the IdP. Persisted so
// admin-triggered re-sync can run without fresh claims.
type UserIdpGroup struct {
	UserID      uuid.UUID       `json:"user_id"`
	ConnectorID pgtype.UUID     `json:"connector_id"`
	Groups      json.RawMessage `json:"groups"`
	SyncedAt    time.Time       `json:"synced_at"`
}

// UserTotpEnrollment is the row shape for user_totp_enrollments — the
// per-user TOTP secret (Fernet-encrypted) plus the metadata surfaced
// in /auth/totp/status. Migration 043.
type UserTotpEnrollment struct {
	UserID          uuid.UUID          `json:"user_id"`
	SecretEncrypted string             `json:"secret_encrypted"`
	Label           string             `json:"label"`
	ConfirmedAt     time.Time          `json:"confirmed_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

// UserTotpRecoveryCode is one of N one-time-use recovery codes for a
// TOTP-enrolled user. Only the sha256 hash of the displayed code is
// stored; the literal is shown once at enrollment. Migration 043.
type UserTotpRecoveryCode struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type RestoreOperation struct {
	ID                 uuid.UUID          `json:"id"`
	BackupID           uuid.UUID          `json:"backup_id"`
	Status             string             `json:"status"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage       string             `json:"error_message"`
	InitiatedByID      pgtype.UUID        `json:"initiated_by_id"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	ClusterID          pgtype.UUID        `json:"cluster_id"`
	VeleroNamespace    string             `json:"velero_namespace"`
	VeleroRestoreName  string             `json:"velero_restore_name"`
	IncludedNamespaces json.RawMessage    `json:"included_namespaces"`
	NamespaceMapping   json.RawMessage    `json:"namespace_mapping"`
	PollAttempts       int32              `json:"poll_attempts"`
	LastPolledAt       pgtype.Timestamptz `json:"last_polled_at"`
}

type SecurityScanResult struct {
	ID              uuid.UUID          `json:"id"`
	ClusterID       uuid.UUID          `json:"cluster_id"`
	ScanType        string             `json:"scan_type"`
	Status          string             `json:"status"`
	Summary         json.RawMessage    `json:"summary"`
	Results         json.RawMessage    `json:"results"`
	StartedAt       time.Time          `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	InitiatedByID   pgtype.UUID        `json:"initiated_by_id"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	ClusterScanName string             `json:"cluster_scan_name"`
	Passed          int32              `json:"passed"`
	Failed          int32              `json:"failed"`
	Warned          int32              `json:"warned"`
	Skipped         int32              `json:"skipped"`
	Findings        json.RawMessage    `json:"findings"`
}

type SsoConfiguration struct {
	ID                    uuid.UUID       `json:"id"`
	Provider              string          `json:"provider"`
	IsEnabled             bool            `json:"is_enabled"`
	DisplayName           string          `json:"display_name"`
	Config                json.RawMessage `json:"config"`
	ClientID              string          `json:"client_id"`
	ClientSecretEncrypted string          `json:"client_secret_encrypted"`
	AllowedOrganizations  json.RawMessage `json:"allowed_organizations"`
	AllowedDomains        json.RawMessage `json:"allowed_domains"`
	AutoCreateUsers       bool            `json:"auto_create_users"`
	DefaultGlobalRoleID   pgtype.UUID     `json:"default_global_role_id"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

// SsoSession is the row shape for sso_sessions — single sign-out
// (SLO) tracking from migration 054. One row per active Astronomer
// JWT issued via an upstream OIDC handshake. The Logout handler joins
// this against the access JWT's JTI to mint the RP-initiated logout
// redirect URL. The upstream_id_token is Fernet-encrypted at rest.
type SsoSession struct {
	Jti                      string    `json:"jti"`
	UserID                   uuid.UUID `json:"user_id"`
	ProviderName             string    `json:"provider_name"`
	UpstreamIdTokenEncrypted string    `json:"upstream_id_token_encrypted"`
	EndSessionEndpoint       string    `json:"end_session_endpoint"`
	ExpiresAt                time.Time `json:"expires_at"`
	CreatedAt                time.Time `json:"created_at"`
}

type ToolOperation struct {
	ID            uuid.UUID          `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetKey     string             `json:"target_key"`
	OperationType string             `json:"operation_type"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage  string             `json:"error_message"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type ToolOperationEvent struct {
	ID          uuid.UUID       `json:"id"`
	OperationID uuid.UUID       `json:"operation_id"`
	Level       string          `json:"level"`
	Stage       string          `json:"stage"`
	Message     string          `json:"message"`
	Detail      json.RawMessage `json:"detail"`
	CreatedAt   time.Time       `json:"created_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	Username            string             `json:"username"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Password            string             `json:"password"`
	IsActive            bool               `json:"is_active"`
	IsStaff             bool               `json:"is_staff"`
	IsSuperuser         bool               `json:"is_superuser"`
	LastLogin           pgtype.Timestamptz `json:"last_login"`
	DateJoined          time.Time          `json:"date_joined"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	MustChangePassword  bool               `json:"must_change_password"`
	FailedLoginCount    int32              `json:"failed_login_count"`
	FailedLoginAt       pgtype.Timestamptz `json:"failed_login_at"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	LockedReason        string             `json:"locked_reason"`
	TokensInvalidatedAt pgtype.Timestamptz `json:"tokens_invalidated_at"`
	QuotaPlan           string             `json:"quota_plan"`
	QuotaOverrides      json.RawMessage    `json:"quota_overrides"`
}

type WorkloadOperation struct {
	ID            uuid.UUID          `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetKey     string             `json:"target_key"`
	OperationType string             `json:"operation_type"`
	Payload       json.RawMessage    `json:"payload"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage  string             `json:"error_message"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type WorkloadOperationEvent struct {
	ID          uuid.UUID       `json:"id"`
	OperationID uuid.UUID       `json:"operation_id"`
	Level       string          `json:"level"`
	Stage       string          `json:"stage"`
	Message     string          `json:"message"`
	Detail      json.RawMessage `json:"detail"`
	CreatedAt   time.Time       `json:"created_at"`
}

// SmtpSettings is the singleton row carrying SMTP host/port/from/auth
// for the email delivery worker. Migration 047. password_encrypted is
// Fernet-encrypted under auth.Encryptor.
type SmtpSettings struct {
	ID                uuid.UUID `json:"id"`
	Enabled           bool      `json:"enabled"`
	Host              string    `json:"host"`
	Port              int32     `json:"port"`
	Username          string    `json:"username"`
	PasswordEncrypted string    `json:"password_encrypted"`
	FromAddress       string    `json:"from_address"`
	FromName          string    `json:"from_name"`
	AuthMechanism     string    `json:"auth_mechanism"`
	Encryption        string    `json:"encryption"`
	RequireTls        bool      `json:"require_tls"`
	TimeoutSeconds    int32     `json:"timeout_seconds"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

// EmailMessage records every email the platform has tried (or skipped
// while SMTP was disabled). The dispatcher worker drains queued rows;
// the admin audit view reads from here. Migration 047.
type EmailMessage struct {
	ID        uuid.UUID          `json:"id"`
	ToAddress string             `json:"to_address"`
	CcAddress string             `json:"cc_address"`
	Subject   string             `json:"subject"`
	Template  string             `json:"template"`
	BodyText  string             `json:"body_text"`
	BodyHtml  string             `json:"body_html"`
	UserID    pgtype.UUID        `json:"user_id"`
	Status    string             `json:"status"`
	Attempts  int32              `json:"attempts"`
	LastError string             `json:"last_error"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// PasswordResetToken backs the password-reset flow. The literal token
// is sent in the email link only; we store hex(sha256(token)) and a
// snapshot of the user's password hash so a successful password change
// invalidates every outstanding link. Migration 047.
type PasswordResetToken struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	TokenHash           string             `json:"token_hash"`
	PasswordHashAtIssue string             `json:"password_hash_at_issue"`
	ExpiresAt           time.Time          `json:"expires_at"`
	UsedAt              pgtype.Timestamptz `json:"used_at"`
	CreatedAt           time.Time          `json:"created_at"`
}

// WebhookSubscription is migration-048's operator-managed outbound
// webhook config. secret_encrypted is Fernet-encrypted under
// auth.Encryptor (same key set as smtp_settings.password_encrypted).
type WebhookSubscription struct {
	ID              uuid.UUID       `json:"id"`
	Name            string          `json:"name"`
	Url             string          `json:"url"`
	SecretEncrypted string          `json:"secret_encrypted"`
	EventFilters    json.RawMessage `json:"event_filters"`
	PayloadTemplate string          `json:"payload_template"`
	ExtraHeaders    json.RawMessage `json:"extra_headers"`
	Enabled         bool            `json:"enabled"`
	MaxRetries      int32           `json:"max_retries"`
	TimeoutSeconds  int32           `json:"timeout_seconds"`
	CreatedBy       pgtype.UUID     `json:"created_by"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

// WebhookDelivery is one POST attempt for a (subscription, event) pair.
// Migration 048. The dispatcher reads queued/failed rows and ships them
// to the subscription URL; status transitions to delivered/dropped.
type WebhookDelivery struct {
	ID             uuid.UUID          `json:"id"`
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	EventName      string             `json:"event_name"`
	EventID        string             `json:"event_id"`
	Payload        json.RawMessage    `json:"payload"`
	PayloadSize    int32              `json:"payload_size"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   string             `json:"response_body"`
	LastError      string             `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

// SiemForwarder is migration-055's operator-managed external SIEM sink.
// auth_encrypted is the Fernet ciphertext of the JSON auth blob ({token,
// username, password}) under auth.Encryptor — same key set as
// webhook_subscriptions.secret_encrypted.
type SiemForwarder struct {
	ID              uuid.UUID       `json:"id"`
	Name            string          `json:"name"`
	Transport       string          `json:"transport"`
	Endpoint        string          `json:"endpoint"`
	AuthEncrypted   string          `json:"auth_encrypted"`
	EventFilters    json.RawMessage `json:"event_filters"`
	Format          string          `json:"format"`
	TlsSkipVerify   bool            `json:"tls_skip_verify"`
	CaCertPem       string          `json:"ca_cert_pem"`
	BatchSize       int32           `json:"batch_size"`
	FlushIntervalMs int32           `json:"flush_interval_ms"`
	TimeoutSeconds  int32           `json:"timeout_seconds"`
	Enabled         bool            `json:"enabled"`
	CreatedBy       pgtype.UUID     `json:"created_by"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

// SiemForwardQueue is one queued event row destined for a forwarder.
// Migration 055. The dispatcher batches up to forwarder.batch_size of
// these per tick and DELETEs them on a successful send. attempts is
// bumped on every failure; rows that cross the retry cap (100) are
// dropped and the forwarder's dropped_total counter is incremented.
type SiemForwardQueue struct {
	ID          int64           `json:"id"`
	ForwarderID uuid.UUID       `json:"forwarder_id"`
	EventName   string          `json:"event_name"`
	Payload     json.RawMessage `json:"payload"`
	Severity    string          `json:"severity"`
	Attempts    int32           `json:"attempts"`
	CreatedAt   time.Time       `json:"created_at"`
}

// SiemForwarderStatus is the per-forwarder health + lag row updated by
// the dispatcher on every tick. The admin status endpoint reads it
// without scanning the queue table.
type SiemForwarderStatus struct {
	ForwarderID     uuid.UUID          `json:"forwarder_id"`
	LastSentAt      pgtype.Timestamptz `json:"last_sent_at"`
	LastError       string             `json:"last_error"`
	QueueDepth      int32              `json:"queue_depth"`
	DroppedTotal    int64              `json:"dropped_total"`
	DispatchedTotal int64              `json:"dispatched_total"`
	UpdatedAt       time.Time          `json:"updated_at"`
}
