// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitoring.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getClusterMonitoringConfig = `-- name: GetClusterMonitoringConfig :one
SELECT id, cluster_id, backend_id, cluster_label, cluster_label_value, scrape_interval_seconds, retention, stack_namespace, prometheus_release_name, thanos_sidecar_enabled, status, last_healthy_at, created_by_id, created_at, updated_at, storage_config_id, object_storage_secret_name, storage_class, storage_size, last_applied_spec_hash, last_observed_status, last_observed_revision, last_observed_at, last_drift_detected_at FROM cluster_monitoring_configs WHERE cluster_id = $1
`

func (q *Queries) GetClusterMonitoringConfig(ctx context.Context, clusterID uuid.UUID) (ClusterMonitoringConfig, error) {
	row := q.db.QueryRow(ctx, getClusterMonitoringConfig, clusterID)
	var i ClusterMonitoringConfig
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.BackendID,
		&i.ClusterLabel,
		&i.ClusterLabelValue,
		&i.ScrapeIntervalSeconds,
		&i.Retention,
		&i.StackNamespace,
		&i.PrometheusReleaseName,
		&i.ThanosSidecarEnabled,
		&i.Status,
		&i.LastHealthyAt,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageConfigID,
		&i.ObjectStorageSecretName,
		&i.StorageClass,
		&i.StorageSize,
		&i.LastAppliedSpecHash,
		&i.LastObservedStatus,
		&i.LastObservedRevision,
		&i.LastObservedAt,
		&i.LastDriftDetectedAt,
	)
	return i, err
}

const getClusterMonitoringContext = `-- name: GetClusterMonitoringContext :one
SELECT
    cmc.id AS cluster_config_id,
    cmc.cluster_id,
    cmc.backend_id,
    cmc.cluster_label,
    cmc.cluster_label_value,
    cmc.scrape_interval_seconds,
    cmc.retention,
    cmc.stack_namespace,
    cmc.prometheus_release_name,
    cmc.thanos_sidecar_enabled,
    cmc.storage_config_id,
    cmc.object_storage_secret_name,
    cmc.storage_class,
    cmc.storage_size,
    cmc.last_applied_spec_hash,
    cmc.last_observed_status,
    cmc.last_observed_revision,
    cmc.last_observed_at,
    cmc.last_drift_detected_at,
    cmc.status,
    cmc.last_healthy_at,
    mb.name AS backend_name,
    mb.backend_type,
    mb.query_url,
    mb.alertmanager_url,
    mb.tenant_id,
    mb.auth_type,
    mb.auth_config,
    -- Migration 146: the credential half of the pair. Selected here because
    -- alert evaluation and the cluster-metrics handler build a monitoring
    -- client straight off this joined row; without it they would authenticate
    -- with the stripped projection.
    mb.auth_config_encrypted,
    mb.default_step_seconds,
    mb.timeout_seconds
FROM cluster_monitoring_configs cmc
INNER JOIN monitoring_backends mb ON mb.id = cmc.backend_id
WHERE cmc.cluster_id = $1
`

type GetClusterMonitoringContextRow struct {
	ClusterConfigID         uuid.UUID          `json:"cluster_config_id"`
	ClusterID               uuid.UUID          `json:"cluster_id"`
	BackendID               uuid.UUID          `json:"backend_id"`
	ClusterLabel            string             `json:"cluster_label"`
	ClusterLabelValue       string             `json:"cluster_label_value"`
	ScrapeIntervalSeconds   int32              `json:"scrape_interval_seconds"`
	Retention               string             `json:"retention"`
	StackNamespace          string             `json:"stack_namespace"`
	PrometheusReleaseName   string             `json:"prometheus_release_name"`
	ThanosSidecarEnabled    bool               `json:"thanos_sidecar_enabled"`
	StorageConfigID         pgtype.UUID        `json:"storage_config_id"`
	ObjectStorageSecretName string             `json:"object_storage_secret_name"`
	StorageClass            string             `json:"storage_class"`
	StorageSize             string             `json:"storage_size"`
	LastAppliedSpecHash     string             `json:"last_applied_spec_hash"`
	LastObservedStatus      string             `json:"last_observed_status"`
	LastObservedRevision    int32              `json:"last_observed_revision"`
	LastObservedAt          pgtype.Timestamptz `json:"last_observed_at"`
	LastDriftDetectedAt     pgtype.Timestamptz `json:"last_drift_detected_at"`
	Status                  string             `json:"status"`
	LastHealthyAt           pgtype.Timestamptz `json:"last_healthy_at"`
	BackendName             string             `json:"backend_name"`
	BackendType             string             `json:"backend_type"`
	QueryUrl                string             `json:"query_url"`
	AlertmanagerUrl         string             `json:"alertmanager_url"`
	TenantID                string             `json:"tenant_id"`
	AuthType                string             `json:"auth_type"`
	AuthConfig              json.RawMessage    `json:"auth_config"`
	AuthConfigEncrypted     string             `json:"auth_config_encrypted"`
	DefaultStepSeconds      int32              `json:"default_step_seconds"`
	TimeoutSeconds          int32              `json:"timeout_seconds"`
}

func (q *Queries) GetClusterMonitoringContext(ctx context.Context, clusterID uuid.UUID) (GetClusterMonitoringContextRow, error) {
	row := q.db.QueryRow(ctx, getClusterMonitoringContext, clusterID)
	var i GetClusterMonitoringContextRow
	err := row.Scan(
		&i.ClusterConfigID,
		&i.ClusterID,
		&i.BackendID,
		&i.ClusterLabel,
		&i.ClusterLabelValue,
		&i.ScrapeIntervalSeconds,
		&i.Retention,
		&i.StackNamespace,
		&i.PrometheusReleaseName,
		&i.ThanosSidecarEnabled,
		&i.StorageConfigID,
		&i.ObjectStorageSecretName,
		&i.StorageClass,
		&i.StorageSize,
		&i.LastAppliedSpecHash,
		&i.LastObservedStatus,
		&i.LastObservedRevision,
		&i.LastObservedAt,
		&i.LastDriftDetectedAt,
		&i.Status,
		&i.LastHealthyAt,
		&i.BackendName,
		&i.BackendType,
		&i.QueryUrl,
		&i.AlertmanagerUrl,
		&i.TenantID,
		&i.AuthType,
		&i.AuthConfig,
		&i.AuthConfigEncrypted,
		&i.DefaultStepSeconds,
		&i.TimeoutSeconds,
	)
	return i, err
}

const getDefaultMonitoringBackend = `-- name: GetDefaultMonitoringBackend :one
SELECT id, name, backend_type, query_url, alertmanager_url, tenant_id, auth_type, auth_config, default_step_seconds, timeout_seconds, is_default, created_by_id, created_at, updated_at, auth_config_encrypted FROM monitoring_backends
WHERE is_default = true OR name = 'default'
ORDER BY is_default DESC, created_at ASC
LIMIT 1
`

func (q *Queries) GetDefaultMonitoringBackend(ctx context.Context) (MonitoringBackend, error) {
	row := q.db.QueryRow(ctx, getDefaultMonitoringBackend)
	var i MonitoringBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BackendType,
		&i.QueryUrl,
		&i.AlertmanagerUrl,
		&i.TenantID,
		&i.AuthType,
		&i.AuthConfig,
		&i.DefaultStepSeconds,
		&i.TimeoutSeconds,
		&i.IsDefault,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthConfigEncrypted,
	)
	return i, err
}

const listMonitoringBackendsWithLegacyAuthConfig = `-- name: ListMonitoringBackendsWithLegacyAuthConfig :many
SELECT id, name, backend_type, query_url, alertmanager_url, tenant_id, auth_type, auth_config, default_step_seconds, timeout_seconds, is_default, created_by_id, created_at, updated_at, auth_config_encrypted FROM monitoring_backends
WHERE auth_config_encrypted = ''
  AND auth_config IS NOT NULL
  AND jsonb_typeof(auth_config) = 'object'
  AND EXISTS (
        SELECT 1
        FROM jsonb_object_keys(auth_config) AS config_key
        WHERE config_key <> ALL (ARRAY[
            'operationPolicies', 'sharedThanos', 'sharedAlertmanager',
            'sharedGrafana', 'sharedLoki', 'sharedAlertingAssets', 'status'
        ])
      )
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListMonitoringBackendsWithLegacyAuthConfigParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Rows that still hold their credential as plaintext JSONB, for the
// security:migrate_plaintext_credentials sweep. Empty ciphertext is the only
// marker of a pre-146 row.
//
// The EXISTS clause is what makes "returned by this query" mean "has something
// to seal", and it must stay in exact step with monitoring.HasAuthConfigSecret:
// at least one key OUTSIDE the non-secret allow-list. A looser predicate
// (auth_config <> '{}') also matches rows the sweep can never seal — a backend
// whose auth_config is nothing but {"operationPolicies":{...}}, which is the
// common case for an unauthenticated in-cluster Prometheus. Those rows never
// leave the result set, so a full page of them ahead of a credentialed row
// would make the sweep re-read the same page forever and never reach it.
//
// jsonb_typeof guards jsonb_object_keys, which errors on a non-object.
func (q *Queries) ListMonitoringBackendsWithLegacyAuthConfig(ctx context.Context, arg ListMonitoringBackendsWithLegacyAuthConfigParams) ([]MonitoringBackend, error) {
	rows, err := q.db.Query(ctx, listMonitoringBackendsWithLegacyAuthConfig, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringBackend{}
	for rows.Next() {
		var i MonitoringBackend
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BackendType,
			&i.QueryUrl,
			&i.AlertmanagerUrl,
			&i.TenantID,
			&i.AuthType,
			&i.AuthConfig,
			&i.DefaultStepSeconds,
			&i.TimeoutSeconds,
			&i.IsDefault,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthConfigEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sealMonitoringBackendAuthConfig = `-- name: SealMonitoringBackendAuthConfig :exec
UPDATE monitoring_backends
   SET auth_config_encrypted = $2,
       auth_config = $3
 WHERE id = $1
   AND auth_config_encrypted = ''
`

type SealMonitoringBackendAuthConfigParams struct {
	ID                  uuid.UUID       `json:"id"`
	AuthConfigEncrypted string          `json:"auth_config_encrypted"`
	AuthConfig          json.RawMessage `json:"auth_config"`
}

// Compare-and-set on the empty ciphertext: the server and the dedicated worker
// both run the sealing task, and the loser of a race must not overwrite a
// freshly-sealed envelope with a re-encryption of the document it read before
// the winner stripped it.
func (q *Queries) SealMonitoringBackendAuthConfig(ctx context.Context, arg SealMonitoringBackendAuthConfigParams) error {
	_, err := q.db.Exec(ctx, sealMonitoringBackendAuthConfig, arg.ID, arg.AuthConfigEncrypted, arg.AuthConfig)
	return err
}

const upsertClusterMonitoringConfig = `-- name: UpsertClusterMonitoringConfig :one
INSERT INTO cluster_monitoring_configs (
    cluster_id,
    backend_id,
    cluster_label,
    cluster_label_value,
    scrape_interval_seconds,
    retention,
    stack_namespace,
    prometheus_release_name,
    thanos_sidecar_enabled,
    storage_config_id,
    object_storage_secret_name,
    storage_class,
    storage_size,
    last_applied_spec_hash,
    last_observed_status,
    last_observed_revision,
    last_observed_at,
    last_drift_detected_at,
    status,
    last_healthy_at,
    created_by_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
ON CONFLICT (cluster_id) DO UPDATE SET
    backend_id = EXCLUDED.backend_id,
    cluster_label = EXCLUDED.cluster_label,
    cluster_label_value = EXCLUDED.cluster_label_value,
    scrape_interval_seconds = EXCLUDED.scrape_interval_seconds,
    retention = EXCLUDED.retention,
    stack_namespace = EXCLUDED.stack_namespace,
    prometheus_release_name = EXCLUDED.prometheus_release_name,
    thanos_sidecar_enabled = EXCLUDED.thanos_sidecar_enabled,
    storage_config_id = EXCLUDED.storage_config_id,
    object_storage_secret_name = EXCLUDED.object_storage_secret_name,
    storage_class = EXCLUDED.storage_class,
    storage_size = EXCLUDED.storage_size,
    last_applied_spec_hash = EXCLUDED.last_applied_spec_hash,
    last_observed_status = EXCLUDED.last_observed_status,
    last_observed_revision = EXCLUDED.last_observed_revision,
    last_observed_at = EXCLUDED.last_observed_at,
    last_drift_detected_at = EXCLUDED.last_drift_detected_at,
    status = EXCLUDED.status,
    last_healthy_at = EXCLUDED.last_healthy_at,
    updated_at = now()
RETURNING id, cluster_id, backend_id, cluster_label, cluster_label_value, scrape_interval_seconds, retention, stack_namespace, prometheus_release_name, thanos_sidecar_enabled, status, last_healthy_at, created_by_id, created_at, updated_at, storage_config_id, object_storage_secret_name, storage_class, storage_size, last_applied_spec_hash, last_observed_status, last_observed_revision, last_observed_at, last_drift_detected_at
`

type UpsertClusterMonitoringConfigParams struct {
	ClusterID               uuid.UUID          `json:"cluster_id"`
	BackendID               uuid.UUID          `json:"backend_id"`
	ClusterLabel            string             `json:"cluster_label"`
	ClusterLabelValue       string             `json:"cluster_label_value"`
	ScrapeIntervalSeconds   int32              `json:"scrape_interval_seconds"`
	Retention               string             `json:"retention"`
	StackNamespace          string             `json:"stack_namespace"`
	PrometheusReleaseName   string             `json:"prometheus_release_name"`
	ThanosSidecarEnabled    bool               `json:"thanos_sidecar_enabled"`
	StorageConfigID         pgtype.UUID        `json:"storage_config_id"`
	ObjectStorageSecretName string             `json:"object_storage_secret_name"`
	StorageClass            string             `json:"storage_class"`
	StorageSize             string             `json:"storage_size"`
	LastAppliedSpecHash     string             `json:"last_applied_spec_hash"`
	LastObservedStatus      string             `json:"last_observed_status"`
	LastObservedRevision    int32              `json:"last_observed_revision"`
	LastObservedAt          pgtype.Timestamptz `json:"last_observed_at"`
	LastDriftDetectedAt     pgtype.Timestamptz `json:"last_drift_detected_at"`
	Status                  string             `json:"status"`
	LastHealthyAt           pgtype.Timestamptz `json:"last_healthy_at"`
	CreatedByID             pgtype.UUID        `json:"created_by_id"`
}

func (q *Queries) UpsertClusterMonitoringConfig(ctx context.Context, arg UpsertClusterMonitoringConfigParams) (ClusterMonitoringConfig, error) {
	row := q.db.QueryRow(ctx, upsertClusterMonitoringConfig,
		arg.ClusterID,
		arg.BackendID,
		arg.ClusterLabel,
		arg.ClusterLabelValue,
		arg.ScrapeIntervalSeconds,
		arg.Retention,
		arg.StackNamespace,
		arg.PrometheusReleaseName,
		arg.ThanosSidecarEnabled,
		arg.StorageConfigID,
		arg.ObjectStorageSecretName,
		arg.StorageClass,
		arg.StorageSize,
		arg.LastAppliedSpecHash,
		arg.LastObservedStatus,
		arg.LastObservedRevision,
		arg.LastObservedAt,
		arg.LastDriftDetectedAt,
		arg.Status,
		arg.LastHealthyAt,
		arg.CreatedByID,
	)
	var i ClusterMonitoringConfig
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.BackendID,
		&i.ClusterLabel,
		&i.ClusterLabelValue,
		&i.ScrapeIntervalSeconds,
		&i.Retention,
		&i.StackNamespace,
		&i.PrometheusReleaseName,
		&i.ThanosSidecarEnabled,
		&i.Status,
		&i.LastHealthyAt,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageConfigID,
		&i.ObjectStorageSecretName,
		&i.StorageClass,
		&i.StorageSize,
		&i.LastAppliedSpecHash,
		&i.LastObservedStatus,
		&i.LastObservedRevision,
		&i.LastObservedAt,
		&i.LastDriftDetectedAt,
	)
	return i, err
}

const upsertDefaultMonitoringBackend = `-- name: UpsertDefaultMonitoringBackend :one
WITH clear_default AS (
    UPDATE monitoring_backends SET is_default = false WHERE is_default = true AND name <> 'default'
)
INSERT INTO monitoring_backends (
    name,
    backend_type,
    query_url,
    alertmanager_url,
    tenant_id,
    auth_type,
    auth_config,
    auth_config_encrypted,
    default_step_seconds,
    timeout_seconds,
    is_default,
    created_by_id
)
VALUES ('default', $1, $2, $3, $4, $5, $6, $7, $8, $9, true, $10)
ON CONFLICT (name) DO UPDATE SET
    backend_type = EXCLUDED.backend_type,
    query_url = EXCLUDED.query_url,
    alertmanager_url = EXCLUDED.alertmanager_url,
    tenant_id = EXCLUDED.tenant_id,
    auth_type = EXCLUDED.auth_type,
    auth_config = EXCLUDED.auth_config,
    auth_config_encrypted = EXCLUDED.auth_config_encrypted,
    default_step_seconds = EXCLUDED.default_step_seconds,
    timeout_seconds = EXCLUDED.timeout_seconds,
    is_default = true,
    updated_at = now()
RETURNING id, name, backend_type, query_url, alertmanager_url, tenant_id, auth_type, auth_config, default_step_seconds, timeout_seconds, is_default, created_by_id, created_at, updated_at, auth_config_encrypted
`

type UpsertDefaultMonitoringBackendParams struct {
	BackendType         string          `json:"backend_type"`
	QueryUrl            string          `json:"query_url"`
	AlertmanagerUrl     string          `json:"alertmanager_url"`
	TenantID            string          `json:"tenant_id"`
	AuthType            string          `json:"auth_type"`
	AuthConfig          json.RawMessage `json:"auth_config"`
	AuthConfigEncrypted string          `json:"auth_config_encrypted"`
	DefaultStepSeconds  int32           `json:"default_step_seconds"`
	TimeoutSeconds      int32           `json:"timeout_seconds"`
	CreatedByID         pgtype.UUID     `json:"created_by_id"`
}

// auth_config and auth_config_encrypted are two halves of ONE value (migration
// 146) and this statement always writes both. Every caller builds its params
// through handler.sealMonitoringBackendAuthConfig / tasks.sealMonitoringBackendAuthConfig,
// which set the pair together from a RESOLVED document — a writer that set the
// projection without the envelope would silently drop the credential during an
// unrelated config edit.
func (q *Queries) UpsertDefaultMonitoringBackend(ctx context.Context, arg UpsertDefaultMonitoringBackendParams) (MonitoringBackend, error) {
	row := q.db.QueryRow(ctx, upsertDefaultMonitoringBackend,
		arg.BackendType,
		arg.QueryUrl,
		arg.AlertmanagerUrl,
		arg.TenantID,
		arg.AuthType,
		arg.AuthConfig,
		arg.AuthConfigEncrypted,
		arg.DefaultStepSeconds,
		arg.TimeoutSeconds,
		arg.CreatedByID,
	)
	var i MonitoringBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BackendType,
		&i.QueryUrl,
		&i.AlertmanagerUrl,
		&i.TenantID,
		&i.AuthType,
		&i.AuthConfig,
		&i.DefaultStepSeconds,
		&i.TimeoutSeconds,
		&i.IsDefault,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthConfigEncrypted,
	)
	return i, err
}
