// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformConfig = `-- name: GetPlatformConfig :one
SELECT id, server_url, platform_name, telemetry_enabled, bootstrapped_at FROM platform_configuration WHERE id = 1
`

func (q *Queries) GetPlatformConfig(ctx context.Context) (PlatformConfiguration, error) {
	row := q.db.QueryRow(ctx, getPlatformConfig)
	var i PlatformConfiguration
	err := row.Scan(
		&i.ID,
		&i.ServerUrl,
		&i.PlatformName,
		&i.TelemetryEnabled,
		&i.BootstrappedAt,
	)
	return i, err
}

const upsertPlatformConfig = `-- name: UpsertPlatformConfig :one
INSERT INTO platform_configuration (id, server_url, platform_name, telemetry_enabled, bootstrapped_at)
VALUES (1, $1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    server_url = EXCLUDED.server_url,
    platform_name = EXCLUDED.platform_name,
    telemetry_enabled = EXCLUDED.telemetry_enabled,
    bootstrapped_at = EXCLUDED.bootstrapped_at
RETURNING id, server_url, platform_name, telemetry_enabled, bootstrapped_at
`

type UpsertPlatformConfigParams struct {
	ServerUrl        string             `json:"server_url"`
	PlatformName     string             `json:"platform_name"`
	TelemetryEnabled bool               `json:"telemetry_enabled"`
	BootstrappedAt   pgtype.Timestamptz `json:"bootstrapped_at"`
}

func (q *Queries) UpsertPlatformConfig(ctx context.Context, arg UpsertPlatformConfigParams) (PlatformConfiguration, error) {
	row := q.db.QueryRow(ctx, upsertPlatformConfig,
		arg.ServerUrl,
		arg.PlatformName,
		arg.TelemetryEnabled,
		arg.BootstrappedAt,
	)
	var i PlatformConfiguration
	err := row.Scan(
		&i.ID,
		&i.ServerUrl,
		&i.PlatformName,
		&i.TelemetryEnabled,
		&i.BootstrappedAt,
	)
	return i, err
}
