// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: siem.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSIEMQueueByForwarder = `-- name: CountSIEMQueueByForwarder :one
SELECT count(*) FROM siem_forward_queue WHERE forwarder_id = $1
`

func (q *Queries) CountSIEMQueueByForwarder(ctx context.Context, forwarderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSIEMQueueByForwarder, forwarderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSIEMForwarder = `-- name: CreateSIEMForwarder :one
INSERT INTO siem_forwarders (
    name, transport, endpoint, auth_encrypted, event_filters, format,
    tls_skip_verify, ca_cert_pem, batch_size, flush_interval_ms,
    timeout_seconds, enabled, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, name, transport, endpoint, auth_encrypted, event_filters, format,
          tls_skip_verify, ca_cert_pem, batch_size, flush_interval_ms,
          timeout_seconds, enabled, created_by, created_at, updated_at
`

type CreateSIEMForwarderParams struct {
	Name            string          `json:"name"`
	Transport       string          `json:"transport"`
	Endpoint        string          `json:"endpoint"`
	AuthEncrypted   string          `json:"auth_encrypted"`
	EventFilters    json.RawMessage `json:"event_filters"`
	Format          string          `json:"format"`
	TlsSkipVerify   bool            `json:"tls_skip_verify"`
	CaCertPem       string          `json:"ca_cert_pem"`
	BatchSize       int32           `json:"batch_size"`
	FlushIntervalMs int32           `json:"flush_interval_ms"`
	TimeoutSeconds  int32           `json:"timeout_seconds"`
	Enabled         bool            `json:"enabled"`
	CreatedBy       pgtype.UUID     `json:"created_by"`
}

func (q *Queries) CreateSIEMForwarder(ctx context.Context, arg CreateSIEMForwarderParams) (SiemForwarder, error) {
	row := q.db.QueryRow(ctx, createSIEMForwarder,
		arg.Name,
		arg.Transport,
		arg.Endpoint,
		arg.AuthEncrypted,
		arg.EventFilters,
		arg.Format,
		arg.TlsSkipVerify,
		arg.CaCertPem,
		arg.BatchSize,
		arg.FlushIntervalMs,
		arg.TimeoutSeconds,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i SiemForwarder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Endpoint,
		&i.AuthEncrypted,
		&i.EventFilters,
		&i.Format,
		&i.TlsSkipVerify,
		&i.CaCertPem,
		&i.BatchSize,
		&i.FlushIntervalMs,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSIEMForwarder = `-- name: DeleteSIEMForwarder :exec
DELETE FROM siem_forwarders WHERE id = $1
`

func (q *Queries) DeleteSIEMForwarder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSIEMForwarder, id)
	return err
}

const deleteSIEMQueueByIDs = `-- name: DeleteSIEMQueueByIDs :exec
DELETE FROM siem_forward_queue WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteSIEMQueueByIDs(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, deleteSIEMQueueByIDs, ids)
	return err
}

const deleteSIEMQueueOlderThan = `-- name: DeleteSIEMQueueOlderThan :execrows
DELETE FROM siem_forward_queue WHERE created_at < $1
`

func (q *Queries) DeleteSIEMQueueOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	tag, err := q.db.Exec(ctx, deleteSIEMQueueOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

const enqueueSIEMEvent = `-- name: EnqueueSIEMEvent :one
INSERT INTO siem_forward_queue (
    forwarder_id, event_name, payload, severity
) VALUES ($1, $2, $3, $4)
RETURNING id, forwarder_id, event_name, payload, severity, attempts, created_at
`

type EnqueueSIEMEventParams struct {
	ForwarderID uuid.UUID       `json:"forwarder_id"`
	EventName   string          `json:"event_name"`
	Payload     json.RawMessage `json:"payload"`
	Severity    string          `json:"severity"`
}

func (q *Queries) EnqueueSIEMEvent(ctx context.Context, arg EnqueueSIEMEventParams) (SiemForwardQueue, error) {
	row := q.db.QueryRow(ctx, enqueueSIEMEvent,
		arg.ForwarderID,
		arg.EventName,
		arg.Payload,
		arg.Severity,
	)
	var i SiemForwardQueue
	err := row.Scan(
		&i.ID,
		&i.ForwarderID,
		&i.EventName,
		&i.Payload,
		&i.Severity,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getSIEMForwarder = `-- name: GetSIEMForwarder :one
SELECT id, name, transport, endpoint, auth_encrypted, event_filters, format,
       tls_skip_verify, ca_cert_pem, batch_size, flush_interval_ms,
       timeout_seconds, enabled, created_by, created_at, updated_at
FROM siem_forwarders WHERE id = $1
`

func (q *Queries) GetSIEMForwarder(ctx context.Context, id uuid.UUID) (SiemForwarder, error) {
	row := q.db.QueryRow(ctx, getSIEMForwarder, id)
	var i SiemForwarder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Endpoint,
		&i.AuthEncrypted,
		&i.EventFilters,
		&i.Format,
		&i.TlsSkipVerify,
		&i.CaCertPem,
		&i.BatchSize,
		&i.FlushIntervalMs,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSIEMForwarderByName = `-- name: GetSIEMForwarderByName :one
SELECT id, name, transport, endpoint, auth_encrypted, event_filters, format,
       tls_skip_verify, ca_cert_pem, batch_size, flush_interval_ms,
       timeout_seconds, enabled, created_by, created_at, updated_at
FROM siem_forwarders WHERE name = $1
`

func (q *Queries) GetSIEMForwarderByName(ctx context.Context, name string) (SiemForwarder, error) {
	row := q.db.QueryRow(ctx, getSIEMForwarderByName, name)
	var i SiemForwarder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Endpoint,
		&i.AuthEncrypted,
		&i.EventFilters,
		&i.Format,
		&i.TlsSkipVerify,
		&i.CaCertPem,
		&i.BatchSize,
		&i.FlushIntervalMs,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSIEMForwarderStatus = `-- name: GetSIEMForwarderStatus :one
SELECT forwarder_id, last_sent_at, last_error, queue_depth, dropped_total,
       dispatched_total, updated_at
FROM siem_forwarder_status WHERE forwarder_id = $1
`

func (q *Queries) GetSIEMForwarderStatus(ctx context.Context, forwarderID uuid.UUID) (SiemForwarderStatus, error) {
	row := q.db.QueryRow(ctx, getSIEMForwarderStatus, forwarderID)
	var i SiemForwarderStatus
	err := row.Scan(
		&i.ForwarderID,
		&i.LastSentAt,
		&i.LastError,
		&i.QueueDepth,
		&i.DroppedTotal,
		&i.DispatchedTotal,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSIEMQueueAttempts = `-- name: IncrementSIEMQueueAttempts :exec
UPDATE siem_forward_queue
SET attempts = attempts + 1
WHERE id = ANY($1::bigint[])
`

func (q *Queries) IncrementSIEMQueueAttempts(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, incrementSIEMQueueAttempts, ids)
	return err
}

const listEnabledSIEMForwarders = `-- name: ListEnabledSIEMForwarders :many
SELECT id, name, transport, endpoint, auth_encrypted, event_filters, format,
       tls_skip_verify, ca_cert_pem, batch_size, flush_interval_ms,
       timeout_seconds, enabled, created_by, created_at, updated_at
FROM siem_forwarders WHERE enabled = true ORDER BY created_at ASC
`

func (q *Queries) ListEnabledSIEMForwarders(ctx context.Context) ([]SiemForwarder, error) {
	rows, err := q.db.Query(ctx, listEnabledSIEMForwarders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiemForwarder{}
	for rows.Next() {
		var i SiemForwarder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Transport,
			&i.Endpoint,
			&i.AuthEncrypted,
			&i.EventFilters,
			&i.Format,
			&i.TlsSkipVerify,
			&i.CaCertPem,
			&i.BatchSize,
			&i.FlushIntervalMs,
			&i.TimeoutSeconds,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOldestSIEMQueue = `-- name: ListOldestSIEMQueue :many
SELECT id FROM siem_forward_queue
WHERE forwarder_id = $1
ORDER BY id ASC
LIMIT $2
`

type ListOldestSIEMQueueParams struct {
	ForwarderID uuid.UUID `json:"forwarder_id"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListOldestSIEMQueue(ctx context.Context, arg ListOldestSIEMQueueParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOldestSIEMQueue, arg.ForwarderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSIEMForwarders = `-- name: ListSIEMForwarders :many
SELECT id, name, transport, endpoint, auth_encrypted, event_filters, format,
       tls_skip_verify, ca_cert_pem, batch_size, flush_interval_ms,
       timeout_seconds, enabled, created_by, created_at, updated_at
FROM siem_forwarders ORDER BY created_at DESC
`

func (q *Queries) ListSIEMForwarders(ctx context.Context) ([]SiemForwarder, error) {
	rows, err := q.db.Query(ctx, listSIEMForwarders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiemForwarder{}
	for rows.Next() {
		var i SiemForwarder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Transport,
			&i.Endpoint,
			&i.AuthEncrypted,
			&i.EventFilters,
			&i.Format,
			&i.TlsSkipVerify,
			&i.CaCertPem,
			&i.BatchSize,
			&i.FlushIntervalMs,
			&i.TimeoutSeconds,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSIEMQueueBatch = `-- name: ListSIEMQueueBatch :many
SELECT id, forwarder_id, event_name, payload, severity, attempts, created_at
FROM siem_forward_queue
WHERE forwarder_id = $1
ORDER BY id ASC
LIMIT $2
`

type ListSIEMQueueBatchParams struct {
	ForwarderID uuid.UUID `json:"forwarder_id"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListSIEMQueueBatch(ctx context.Context, arg ListSIEMQueueBatchParams) ([]SiemForwardQueue, error) {
	rows, err := q.db.Query(ctx, listSIEMQueueBatch, arg.ForwarderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiemForwardQueue{}
	for rows.Next() {
		var i SiemForwardQueue
		if err := rows.Scan(
			&i.ID,
			&i.ForwarderID,
			&i.EventName,
			&i.Payload,
			&i.Severity,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSIEMQueueExhausted = `-- name: ListSIEMQueueExhausted :many
SELECT id, forwarder_id, event_name, payload, severity, attempts, created_at
FROM siem_forward_queue
WHERE forwarder_id = $1 AND attempts >= $2
ORDER BY id ASC
LIMIT $3
`

type ListSIEMQueueExhaustedParams struct {
	ForwarderID uuid.UUID `json:"forwarder_id"`
	Attempts    int32     `json:"attempts"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListSIEMQueueExhausted(ctx context.Context, arg ListSIEMQueueExhaustedParams) ([]SiemForwardQueue, error) {
	rows, err := q.db.Query(ctx, listSIEMQueueExhausted, arg.ForwarderID, arg.Attempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiemForwardQueue{}
	for rows.Next() {
		var i SiemForwardQueue
		if err := rows.Scan(
			&i.ID,
			&i.ForwarderID,
			&i.EventName,
			&i.Payload,
			&i.Severity,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSIEMForwarder = `-- name: UpdateSIEMForwarder :one
UPDATE siem_forwarders
SET name              = $2,
    transport         = $3,
    endpoint          = $4,
    auth_encrypted    = $5,
    event_filters     = $6,
    format            = $7,
    tls_skip_verify   = $8,
    ca_cert_pem       = $9,
    batch_size        = $10,
    flush_interval_ms = $11,
    timeout_seconds   = $12,
    enabled           = $13,
    updated_at        = now()
WHERE id = $1
RETURNING id, name, transport, endpoint, auth_encrypted, event_filters, format,
          tls_skip_verify, ca_cert_pem, batch_size, flush_interval_ms,
          timeout_seconds, enabled, created_by, created_at, updated_at
`

type UpdateSIEMForwarderParams struct {
	ID              uuid.UUID       `json:"id"`
	Name            string          `json:"name"`
	Transport       string          `json:"transport"`
	Endpoint        string          `json:"endpoint"`
	AuthEncrypted   string          `json:"auth_encrypted"`
	EventFilters    json.RawMessage `json:"event_filters"`
	Format          string          `json:"format"`
	TlsSkipVerify   bool            `json:"tls_skip_verify"`
	CaCertPem       string          `json:"ca_cert_pem"`
	BatchSize       int32           `json:"batch_size"`
	FlushIntervalMs int32           `json:"flush_interval_ms"`
	TimeoutSeconds  int32           `json:"timeout_seconds"`
	Enabled         bool            `json:"enabled"`
}

func (q *Queries) UpdateSIEMForwarder(ctx context.Context, arg UpdateSIEMForwarderParams) (SiemForwarder, error) {
	row := q.db.QueryRow(ctx, updateSIEMForwarder,
		arg.ID,
		arg.Name,
		arg.Transport,
		arg.Endpoint,
		arg.AuthEncrypted,
		arg.EventFilters,
		arg.Format,
		arg.TlsSkipVerify,
		arg.CaCertPem,
		arg.BatchSize,
		arg.FlushIntervalMs,
		arg.TimeoutSeconds,
		arg.Enabled,
	)
	var i SiemForwarder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Endpoint,
		&i.AuthEncrypted,
		&i.EventFilters,
		&i.Format,
		&i.TlsSkipVerify,
		&i.CaCertPem,
		&i.BatchSize,
		&i.FlushIntervalMs,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSIEMForwarderStatus = `-- name: UpsertSIEMForwarderStatus :exec
INSERT INTO siem_forwarder_status (
    forwarder_id, last_sent_at, last_error, queue_depth,
    dropped_total, dispatched_total, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (forwarder_id) DO UPDATE
SET last_sent_at      = COALESCE(EXCLUDED.last_sent_at, siem_forwarder_status.last_sent_at),
    last_error        = EXCLUDED.last_error,
    queue_depth       = EXCLUDED.queue_depth,
    dropped_total     = siem_forwarder_status.dropped_total + EXCLUDED.dropped_total,
    dispatched_total  = siem_forwarder_status.dispatched_total + EXCLUDED.dispatched_total,
    updated_at        = now()
`

type UpsertSIEMForwarderStatusParams struct {
	ForwarderID     uuid.UUID          `json:"forwarder_id"`
	LastSentAt      pgtype.Timestamptz `json:"last_sent_at"`
	LastError       string             `json:"last_error"`
	QueueDepth      int32              `json:"queue_depth"`
	DroppedTotal    int64              `json:"dropped_total"`
	DispatchedTotal int64              `json:"dispatched_total"`
}

func (q *Queries) UpsertSIEMForwarderStatus(ctx context.Context, arg UpsertSIEMForwarderStatusParams) error {
	_, err := q.db.Exec(ctx, upsertSIEMForwarderStatus,
		arg.ForwarderID,
		arg.LastSentAt,
		arg.LastError,
		arg.QueueDepth,
		arg.DroppedTotal,
		arg.DispatchedTotal,
	)
	return err
}
