// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, theme, table_density, landing_route, time_format, favorites, created_at, updated_at, pinned_clusters, rows_per_page, date_format, starred_types FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.TableDensity,
		&i.LandingRoute,
		&i.TimeFormat,
		&i.Favorites,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinnedClusters,
		&i.RowsPerPage,
		&i.DateFormat,
		&i.StarredTypes,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (
    user_id, theme, table_density, landing_route, time_format, favorites, pinned_clusters,
    rows_per_page, date_format, starred_types
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10
)
ON CONFLICT (user_id) DO UPDATE SET
    theme = EXCLUDED.theme,
    table_density = EXCLUDED.table_density,
    landing_route = EXCLUDED.landing_route,
    time_format = EXCLUDED.time_format,
    favorites = EXCLUDED.favorites,
    pinned_clusters = EXCLUDED.pinned_clusters,
    rows_per_page = EXCLUDED.rows_per_page,
    date_format = EXCLUDED.date_format,
    starred_types = EXCLUDED.starred_types,
    updated_at = now()
RETURNING user_id, theme, table_density, landing_route, time_format, favorites, created_at, updated_at, pinned_clusters, rows_per_page, date_format, starred_types
`

type UpsertUserPreferencesParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	Theme          string          `json:"theme"`
	TableDensity   string          `json:"table_density"`
	LandingRoute   string          `json:"landing_route"`
	TimeFormat     string          `json:"time_format"`
	Favorites      json.RawMessage `json:"favorites"`
	PinnedClusters json.RawMessage `json:"pinned_clusters"`
	RowsPerPage    int32           `json:"rows_per_page"`
	DateFormat     string          `json:"date_format"`
	StarredTypes   json.RawMessage `json:"starred_types"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.TableDensity,
		arg.LandingRoute,
		arg.TimeFormat,
		arg.Favorites,
		arg.PinnedClusters,
		arg.RowsPerPage,
		arg.DateFormat,
		arg.StarredTypes,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.TableDensity,
		&i.LandingRoute,
		&i.TimeFormat,
		&i.Favorites,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PinnedClusters,
		&i.RowsPerPage,
		&i.DateFormat,
		&i.StarredTypes,
	)
	return i, err
}
