// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault_connections.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVaultConnection = `-- name: CreateVaultConnection :one
INSERT INTO vault_connections (
    name, description, addr, auth_method, auth_encrypted, namespace,
    tls_skip_verify, ca_cert_pem, default_mount, enabled, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, description, addr, auth_method, auth_encrypted, namespace,
          tls_skip_verify, ca_cert_pem, default_mount, enabled,
          cached_token_expires_at, last_health_at, last_health_ok, last_error,
          created_by, created_at, updated_at
`

type CreateVaultConnectionParams struct {
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	Addr          string      `json:"addr"`
	AuthMethod    string      `json:"auth_method"`
	AuthEncrypted string      `json:"auth_encrypted"`
	Namespace     string      `json:"namespace"`
	TlsSkipVerify bool        `json:"tls_skip_verify"`
	CaCertPem     string      `json:"ca_cert_pem"`
	DefaultMount  string      `json:"default_mount"`
	Enabled       bool        `json:"enabled"`
	CreatedBy     pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateVaultConnection(ctx context.Context, arg CreateVaultConnectionParams) (VaultConnection, error) {
	row := q.db.QueryRow(ctx, createVaultConnection,
		arg.Name,
		arg.Description,
		arg.Addr,
		arg.AuthMethod,
		arg.AuthEncrypted,
		arg.Namespace,
		arg.TlsSkipVerify,
		arg.CaCertPem,
		arg.DefaultMount,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i VaultConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Addr,
		&i.AuthMethod,
		&i.AuthEncrypted,
		&i.Namespace,
		&i.TlsSkipVerify,
		&i.CaCertPem,
		&i.DefaultMount,
		&i.Enabled,
		&i.CachedTokenExpiresAt,
		&i.LastHealthAt,
		&i.LastHealthOk,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVaultConnection = `-- name: DeleteVaultConnection :exec
DELETE FROM vault_connections WHERE id = $1
`

func (q *Queries) DeleteVaultConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVaultConnection, id)
	return err
}

const getProjectDefaultVaultConnection = `-- name: GetProjectDefaultVaultConnection :one
SELECT default_vault_connection_id FROM projects WHERE id = $1
`

// Returns the (possibly NULL) default_vault_connection_id pointer. Caller
// decides whether to chase the FK; this just answers "is a default set?".
func (q *Queries) GetProjectDefaultVaultConnection(ctx context.Context, id uuid.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getProjectDefaultVaultConnection, id)
	var default_vault_connection_id pgtype.UUID
	err := row.Scan(&default_vault_connection_id)
	return default_vault_connection_id, err
}

const getVaultConnectionByID = `-- name: GetVaultConnectionByID :one
SELECT id, name, description, addr, auth_method, auth_encrypted, namespace,
       tls_skip_verify, ca_cert_pem, default_mount, enabled,
       cached_token_expires_at, last_health_at, last_health_ok, last_error,
       created_by, created_at, updated_at
FROM vault_connections
WHERE id = $1
`

func (q *Queries) GetVaultConnectionByID(ctx context.Context, id uuid.UUID) (VaultConnection, error) {
	row := q.db.QueryRow(ctx, getVaultConnectionByID, id)
	var i VaultConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Addr,
		&i.AuthMethod,
		&i.AuthEncrypted,
		&i.Namespace,
		&i.TlsSkipVerify,
		&i.CaCertPem,
		&i.DefaultMount,
		&i.Enabled,
		&i.CachedTokenExpiresAt,
		&i.LastHealthAt,
		&i.LastHealthOk,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVaultConnectionByName = `-- name: GetVaultConnectionByName :one
SELECT id, name, description, addr, auth_method, auth_encrypted, namespace,
       tls_skip_verify, ca_cert_pem, default_mount, enabled,
       cached_token_expires_at, last_health_at, last_health_ok, last_error,
       created_by, created_at, updated_at
FROM vault_connections
WHERE name = $1
`

func (q *Queries) GetVaultConnectionByName(ctx context.Context, name string) (VaultConnection, error) {
	row := q.db.QueryRow(ctx, getVaultConnectionByName, name)
	var i VaultConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Addr,
		&i.AuthMethod,
		&i.AuthEncrypted,
		&i.Namespace,
		&i.TlsSkipVerify,
		&i.CaCertPem,
		&i.DefaultMount,
		&i.Enabled,
		&i.CachedTokenExpiresAt,
		&i.LastHealthAt,
		&i.LastHealthOk,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVaultConnections = `-- name: ListVaultConnections :many

SELECT id, name, description, addr, auth_method, auth_encrypted, namespace,
       tls_skip_verify, ca_cert_pem, default_mount, enabled,
       cached_token_expires_at, last_health_at, last_health_ok, last_error,
       created_by, created_at, updated_at
FROM vault_connections
ORDER BY name ASC
`

// Vault connections CRUD (migration 067).
//
// Hand-edited SQL paired with the hand-authored sqlc shim in
// internal/db/sqlc/vault_connections.sql.go (sqlc CLI not available
// in agent worktrees; same pattern cloud_credentials uses). Keep this
// file byte-compatible with what sqlc would emit so a future
// `make sqlc` is a no-op.
func (q *Queries) ListVaultConnections(ctx context.Context) ([]VaultConnection, error) {
	rows, err := q.db.Query(ctx, listVaultConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultConnection{}
	for rows.Next() {
		var i VaultConnection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Addr,
			&i.AuthMethod,
			&i.AuthEncrypted,
			&i.Namespace,
			&i.TlsSkipVerify,
			&i.CaCertPem,
			&i.DefaultMount,
			&i.Enabled,
			&i.CachedTokenExpiresAt,
			&i.LastHealthAt,
			&i.LastHealthOk,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectDefaultVaultConnection = `-- name: SetProjectDefaultVaultConnection :exec
UPDATE projects
SET default_vault_connection_id = $2,
    updated_at = now()
WHERE id = $1
`

type SetProjectDefaultVaultConnectionParams struct {
	ID                       uuid.UUID   `json:"id"`
	DefaultVaultConnectionID pgtype.UUID `json:"default_vault_connection_id"`
}

func (q *Queries) SetProjectDefaultVaultConnection(ctx context.Context, arg SetProjectDefaultVaultConnectionParams) error {
	_, err := q.db.Exec(ctx, setProjectDefaultVaultConnection, arg.ID, arg.DefaultVaultConnectionID)
	return err
}

const updateVaultConnection = `-- name: UpdateVaultConnection :one
UPDATE vault_connections
SET description     = $2,
    addr            = $3,
    auth_method     = $4,
    auth_encrypted  = $5,
    namespace       = $6,
    tls_skip_verify = $7,
    ca_cert_pem     = $8,
    default_mount   = $9,
    enabled         = $10,
    updated_at      = now()
WHERE id = $1
RETURNING id, name, description, addr, auth_method, auth_encrypted, namespace,
          tls_skip_verify, ca_cert_pem, default_mount, enabled,
          cached_token_expires_at, last_health_at, last_health_ok, last_error,
          created_by, created_at, updated_at
`

type UpdateVaultConnectionParams struct {
	ID            uuid.UUID `json:"id"`
	Description   string    `json:"description"`
	Addr          string    `json:"addr"`
	AuthMethod    string    `json:"auth_method"`
	AuthEncrypted string    `json:"auth_encrypted"`
	Namespace     string    `json:"namespace"`
	TlsSkipVerify bool      `json:"tls_skip_verify"`
	CaCertPem     string    `json:"ca_cert_pem"`
	DefaultMount  string    `json:"default_mount"`
	Enabled       bool      `json:"enabled"`
}

func (q *Queries) UpdateVaultConnection(ctx context.Context, arg UpdateVaultConnectionParams) (VaultConnection, error) {
	row := q.db.QueryRow(ctx, updateVaultConnection,
		arg.ID,
		arg.Description,
		arg.Addr,
		arg.AuthMethod,
		arg.AuthEncrypted,
		arg.Namespace,
		arg.TlsSkipVerify,
		arg.CaCertPem,
		arg.DefaultMount,
		arg.Enabled,
	)
	var i VaultConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Addr,
		&i.AuthMethod,
		&i.AuthEncrypted,
		&i.Namespace,
		&i.TlsSkipVerify,
		&i.CaCertPem,
		&i.DefaultMount,
		&i.Enabled,
		&i.CachedTokenExpiresAt,
		&i.LastHealthAt,
		&i.LastHealthOk,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVaultConnectionHealth = `-- name: UpdateVaultConnectionHealth :exec
UPDATE vault_connections
SET last_health_at = now(),
    last_health_ok = $2,
    last_error     = $3,
    updated_at     = now()
WHERE id = $1
`

type UpdateVaultConnectionHealthParams struct {
	ID           uuid.UUID `json:"id"`
	LastHealthOk bool      `json:"last_health_ok"`
	LastError    string    `json:"last_error"`
}

func (q *Queries) UpdateVaultConnectionHealth(ctx context.Context, arg UpdateVaultConnectionHealthParams) error {
	_, err := q.db.Exec(ctx, updateVaultConnectionHealth, arg.ID, arg.LastHealthOk, arg.LastError)
	return err
}
