apiVersion: v1
kind: ConfigMap
metadata:
  name: astronomer-config
  namespace: astronomer
  labels:
    app.kubernetes.io/name: astronomer
data:
  DATABASE_URL: "postgres://astronomer:astronomer@astronomer-postgres:5432/astronomer?sslmode=disable"
  REDIS_URL: "redis://astronomer-redis:6379/0"
  ENV: "development"
  DEBUG: "true"
  LOG_LEVEL: "info"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://astronomer.localtest.me"
  AGENT_IMAGE_REPOSITORY: "astronomer-go-agent"
  AGENT_IMAGE_TAG: "dev"
