apiVersion: v1
kind: Service
metadata:
  name: astronomer-server
  namespace: astronomer
  labels:
    app.kubernetes.io/name: astronomer
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/name: astronomer
    app.kubernetes.io/component: server
