{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "astronomer.fullname" . }}-frontend
  labels:
    {{- include "astronomer.componentLabels" (dict "context" . "component" "frontend") | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "astronomer.componentSelectorLabels" (dict "context" . "component" "frontend") | nindent 6 }}
{{- end }}
