-- Control-plane (etcd) DR snapshot registry (migration 125).
--
-- Every query here targets the control_plane_snapshots table. The Go
-- bodies are generated by sqlc into internal/db/sqlc/; reference them as
-- q.<Name> (e.g. q.CreateControlPlaneSnapshot).

-- name: CreateControlPlaneSnapshot :one
INSERT INTO control_plane_snapshots (
    cluster_id, name, status, location, requested_by_id
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, cluster_id, name, status, location, size_bytes,
          requested_by_id, error, created_at, completed_at;

-- name: GetControlPlaneSnapshotByID :one
SELECT id, cluster_id, name, status, location, size_bytes,
       requested_by_id, error, created_at, completed_at
FROM control_plane_snapshots
WHERE id = $1;

-- name: ListControlPlaneSnapshotsByCluster :many
SELECT id, cluster_id, name, status, location, size_bytes,
       requested_by_id, error, created_at, completed_at
FROM control_plane_snapshots
WHERE cluster_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3;

-- name: CountControlPlaneSnapshotsByCluster :one
SELECT COUNT(*)::bigint FROM control_plane_snapshots WHERE cluster_id = $1;

-- name: GetLatestControlPlaneSnapshotByCluster :one
SELECT id, cluster_id, name, status, location, size_bytes,
       requested_by_id, error, created_at, completed_at
FROM control_plane_snapshots
WHERE cluster_id = $1
ORDER BY created_at DESC
LIMIT 1;

-- name: MarkControlPlaneSnapshotStatus :exec
UPDATE control_plane_snapshots
SET status = $2,
    error  = $3
WHERE id = $1;

-- name: MarkControlPlaneSnapshotSucceeded :exec
UPDATE control_plane_snapshots
SET status       = 'succeeded',
    size_bytes   = $2,
    error        = '',
    completed_at = now()
WHERE id = $1;

-- name: MarkControlPlaneSnapshotFailed :exec
UPDATE control_plane_snapshots
SET status       = 'failed',
    error        = $2,
    completed_at = now()
WHERE id = $1;

-- name: ListRunningControlPlaneSnapshots :many
-- In-flight rows across all clusters, oldest-first, so the sweep can poll
-- each snapshot Job to completion and move it off 'running'. Only 'running'
-- rows qualify: a row reaches 'running' ONLY after its Job POST succeeds, so
-- the Job provably existed — this avoids racing a 'pending' row whose Job is
-- still being applied (a premature GET would 404 and wrongly fail it).
SELECT id, cluster_id, name, status, location, size_bytes,
       requested_by_id, error, created_at, completed_at
FROM control_plane_snapshots
WHERE status = 'running'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2;

-- name: PruneControlPlaneSnapshots :exec
-- Retention: keep the newest $2 rows for the cluster, delete the rest.
-- Only terminal rows are eligible so an in-flight snapshot is never
-- reaped out from under the poller.
DELETE FROM control_plane_snapshots c
WHERE c.cluster_id = $1
  AND c.status IN ('succeeded', 'failed')
  AND c.id NOT IN (
      SELECT s.id FROM control_plane_snapshots s
      WHERE s.cluster_id = $1
      ORDER BY s.created_at DESC
      LIMIT $2
  );
