package charliequalification

import (
	"bufio"
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"net"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

const (
	defaultProofTimeout = 60 * time.Second
	defaultProofPoll    = time.Second
	defaultNoCallDwell  = 10 * time.Second
	maxExpiryWait       = 90 * time.Second
)

// ApprovalFixture binds a live qualification scenario to one pre-provisioned,
// centrally signed approval. Request IDs are operator-created idempotency
// identifiers, never generated by the driver after the fixture is loaded.
type ApprovalFixture struct {
	ApprovalID      string `json:"approval_id"`
	ActionID        string `json:"action_id,omitempty"`
	Capability      string `json:"capability"`
	DecisionRequest string `json:"decision_request_id,omitempty"`
	ReplayRequest   string `json:"replay_request_id,omitempty"`
}

// SessionStimulus creates one fresh, private, single-resource session and sends
// one exact user message through Astronomer's existing authenticated product
// API. Stable client IDs make every mutation idempotent and auditable.
type SessionStimulus struct {
	ClientSessionID string `json:"client_session_id"`
	ClientMessageID string `json:"client_message_id"`
	AbortRequestID  string `json:"abort_request_id"`
	Intent          string `json:"intent"`
	ResourceType    string `json:"resource_type"`
	ResourceID      string `json:"resource_id"`
	Message         string `json:"message"`
}

// ActionFixture binds the exact capability expected after the fresh-session
// stimulus. The action ID is discovered only from the SSE event bound to the
// message receipt's exact turn; Charlie action IDs cannot be known before a
// real engine turn exists.
type ActionFixture struct {
	Capability string          `json:"capability"`
	Stimulus   SessionStimulus `json:"stimulus"`
}

// EventActionFixture binds unattended automation to a product event. The
// service session is created by the trigger dispatcher; no browser identity
// creates the session or sends an instruction.
type EventActionFixture struct {
	Capability     string `json:"capability"`
	TaskID         string `json:"task_id"`
	AbortRequestID string `json:"abort_request_id"`
}

type PendingApprovalFixture struct {
	Capability string          `json:"capability"`
	Stimulus   SessionStimulus `json:"stimulus"`
}

// VersionedRAGFixture proves one real route invocation against a uniquely
// identifiable corrected document revision. Markers are non-secret canaries
// that the operator placed in the selected product-version documentation.
type VersionedRAGFixture struct {
	Stimulus                SessionStimulus `json:"stimulus"`
	CorrectedRevisionMarker string          `json:"corrected_revision_marker"`
	ProductVersionMarker    string          `json:"product_version_marker"`
	CitationID              string          `json:"citation_id"`
	CitationTitle           string          `json:"citation_title"`
	CitationSource          string          `json:"citation_source"`
}

// GeneralAnswerFixture proves that the same product route can answer a
// non-product question without inventing a citation when retrieval finds no
// applicable product material.
type GeneralAnswerFixture struct {
	Stimulus             SessionStimulus `json:"stimulus"`
	ExpectedAnswerMarker string          `json:"expected_answer_marker"`
}

// AlertDeliveryFixture binds an alert scenario to one real, already-created
// Astronomer finding and delivery. It contains no notification content.
type AlertDeliveryFixture struct {
	FindingID             string `json:"finding_id"`
	DeliveryID            string `json:"delivery_id"`
	ExpectedBlockCode     string `json:"expected_block_code"`
	ExpectedWorkflowState string `json:"expected_workflow_state"`
}

// LiveFixtures is intentionally scenario-specific. Reusing one unconstrained
// identifier across scenarios could allow an earlier side effect to masquerade
// as proof for a later scenario.
type LiveFixtures struct {
	ApprovalExpiry          ApprovalFixture        `json:"approval_expiry"`
	ApprovalOnce            ApprovalFixture        `json:"approval_once"`
	ApprovalReject          ApprovalFixture        `json:"approval_reject"`
	AutoAllowlistedSuccess  EventActionFixture     `json:"auto_allowlisted_success"`
	AutoNonallowlisted      PendingApprovalFixture `json:"auto_nonallowlisted_approval"`
	LeaderKillFailover      ActionFixture          `json:"leader_kill_failover"`
	VersionedRAGGrounded    VersionedRAGFixture    `json:"versioned_rag_grounded"`
	GeneralAnswer           GeneralAnswerFixture   `json:"general_answer"`
	DiagnosisAlert          AlertDeliveryFixture   `json:"diagnosis_alert"`
	ApprovalPendingAlert    AlertDeliveryFixture   `json:"approval_pending_alert"`
	ApprovalRejectedAlert   AlertDeliveryFixture   `json:"approval_rejected_alert"`
	ApprovalExpiredAlert    AlertDeliveryFixture   `json:"approval_expired_alert"`
	BlockedAutoAlert        AlertDeliveryFixture   `json:"blocked_auto_alert"`
	FailedPreconditionAlert AlertDeliveryFixture   `json:"failed_precondition_alert"`
	FailedVerificationAlert AlertDeliveryFixture   `json:"failed_verification_alert"`
}

type LiveConfig struct {
	AstronomerURL         string
	AdminToken            string
	ApproverToken         string
	DeniedToken           string
	MetricSources         []MetricSource
	CounterMetrics        map[string]string
	Fixtures              LiveFixtures
	AllowHTTP             bool
	HTTPClient            *http.Client
	AgentScaler           AgentScaler
	IsolationObserver     IsolationObserver
	LeaderFailover        *KubernetesLeaderFailoverTarget
	EventStimulus         EventStimulus
	InfrastructureCommand string
	ProofTimeout          time.Duration
	ProofPoll             time.Duration
	NoCallDwell           time.Duration
}

// MetricSource binds one scrape endpoint to only its own optional bearer.
// Charlie central's qualification credential must never be forwarded to an
// Astronomer metrics listener (or vice versa).
type MetricSource struct {
	URL   string
	Token string
}

type metricEndpoint struct {
	url   *url.URL
	token string
}

type LiveDriver struct {
	base              *url.URL
	adminToken        string
	approverToken     string
	deniedToken       string
	metricSources     []metricEndpoint
	counterMetrics    map[string]string
	fixtures          LiveFixtures
	client            *http.Client
	agentScaler       AgentScaler
	isolationObserver IsolationObserver
	leaderFailover    leaderFailoverTarget
	eventStimulus     EventStimulus
	infrastructure    infrastructureQualificationOperator
	proofTimeout      time.Duration
	proofPoll         time.Duration
	noCallDwell       time.Duration
	scenarioMu        sync.Mutex
}

func NewLiveDriver(config LiveConfig) (*LiveDriver, error) {
	base, err := safeOperatorURL(config.AstronomerURL, config.AllowHTTP)
	if err != nil || strings.TrimSpace(config.AdminToken) == "" {
		return nil, errors.New("live driver requires a safe Astronomer URL and admin token")
	}
	metrics := make([]metricEndpoint, 0, len(config.MetricSources))
	seenMetricURLs := make(map[string]struct{}, len(config.MetricSources))
	for _, source := range config.MetricSources {
		parsed, parseErr := safeOperatorURL(source.URL, config.AllowHTTP)
		if parseErr != nil {
			return nil, fmt.Errorf("invalid metrics URL")
		}
		if _, duplicate := seenMetricURLs[parsed.String()]; duplicate {
			return nil, fmt.Errorf("duplicate metrics URL")
		}
		seenMetricURLs[parsed.String()] = struct{}{}
		metrics = append(metrics, metricEndpoint{url: parsed, token: strings.TrimSpace(source.Token)})
	}
	mapping := defaultCounterMetrics()
	for key, name := range config.CounterMetrics {
		if !metricNamePattern.MatchString(name) || (!contains(runtimeKeys, key) && !contains(downstreamKeys, key)) {
			return nil, fmt.Errorf("invalid counter metric mapping")
		}
		mapping[key] = name
	}
	client := config.HTTPClient
	if client == nil {
		client = &http.Client{
			Timeout:       30 * time.Second,
			Transport:     &http.Transport{TLSClientConfig: &tls.Config{MinVersion: tls.VersionTLS12}},
			CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse },
		}
	}
	proofTimeout, proofPoll, noCallDwell := config.ProofTimeout, config.ProofPoll, config.NoCallDwell
	if proofTimeout == 0 {
		proofTimeout = defaultProofTimeout
	}
	if proofPoll == 0 {
		proofPoll = defaultProofPoll
	}
	if noCallDwell == 0 {
		noCallDwell = defaultNoCallDwell
	}
	if proofTimeout < proofPoll || proofTimeout > 2*time.Minute || proofPoll < time.Millisecond || proofPoll > 10*time.Second || noCallDwell < time.Millisecond || noCallDwell > 2*time.Minute {
		return nil, errors.New("live proof timing is outside its safe bound")
	}
	var leaderFailover leaderFailoverTarget
	if config.LeaderFailover != nil {
		leaderFailover = config.LeaderFailover
	}
	var infrastructure infrastructureQualificationOperator
	if strings.TrimSpace(config.InfrastructureCommand) != "" {
		infrastructure, err = NewCommandInfrastructureOperator(config.InfrastructureCommand)
		if err != nil {
			return nil, err
		}
	}
	return &LiveDriver{
		base: base, adminToken: strings.TrimSpace(config.AdminToken), approverToken: strings.TrimSpace(config.ApproverToken), deniedToken: strings.TrimSpace(config.DeniedToken),
		metricSources: metrics, counterMetrics: mapping, fixtures: config.Fixtures,
		client: client, agentScaler: config.AgentScaler, isolationObserver: config.IsolationObserver, leaderFailover: leaderFailover, eventStimulus: config.EventStimulus, infrastructure: infrastructure,
		proofTimeout: proofTimeout, proofPoll: proofPoll, noCallDwell: noCallDwell,
	}, nil
}

func safeOperatorURL(raw string, allowHTTP bool) (*url.URL, error) {
	parsed, err := url.Parse(strings.TrimSpace(raw))
	httpLoopbackAllowed := allowHTTP && parsed.Scheme == "http" && netLoopback(parsed.Hostname())
	if err != nil || parsed.Hostname() == "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" || (parsed.Scheme != "https" && !httpLoopbackAllowed) {
		return nil, errors.New("URL must use HTTPS without credentials, query, or fragment")
	}
	return parsed, nil
}

func netLoopback(host string) bool {
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}

func defaultCounterMetrics() map[string]string {
	return map[string]string{
		"model_calls": "charlie_model_usage_total", "rag_queries": "charlie_rag_queries_total",
		"sessions": "charlie_sessions_created_total", "mcp_calls": "astronomer_charlie_mcp_calls_total",
		"tool_calls": "astronomer_charlie_actions_total", "work_claims": "charlie_agent_work_claims_total",
		"evidence_calls": "charlie_evidence_calls_total", "trigger_dispatches": "astronomer_charlie_trigger_events_total",
		"finding_dispatches": "charlie_findings_dispatched_total",
		"tunnel":             "astronomer_charlie_downstream_boundary_calls_total",
		"proxy":              "astronomer_charlie_downstream_boundary_calls_total",
		"kubernetes":         "astronomer_charlie_downstream_boundary_calls_total",
		"exec":               "astronomer_charlie_downstream_boundary_calls_total",
		"logs":               "astronomer_charlie_downstream_boundary_calls_total",
		"helm":               "astronomer_charlie_downstream_boundary_calls_total",
	}
}

func (d *LiveDriver) Counters(ctx context.Context) (CounterSet, error) {
	if len(d.metricSources) == 0 {
		return CounterSet{}, errors.New("metrics URLs are not configured")
	}
	samples := make([]metricSample, 0)
	for _, endpoint := range d.metricSources {
		request, _ := http.NewRequestWithContext(ctx, http.MethodGet, endpoint.url.String(), nil)
		request.Header.Set("Accept", "text/plain")
		if endpoint.token != "" {
			request.Header.Set("Authorization", "Bearer "+endpoint.token)
		}
		response, err := d.client.Do(request)
		if err != nil {
			return CounterSet{}, errors.New("metrics unavailable")
		}
		limited := &io.LimitedReader{R: response.Body, N: (16 << 20) + 1}
		parsed, parseErr := parsePrometheus(limited)
		_ = response.Body.Close()
		if response.StatusCode != http.StatusOK || parseErr != nil || limited.N == 0 {
			return CounterSet{}, errors.New("metrics invalid")
		}
		samples = append(samples, parsed...)
	}
	result := CounterSet{Runtime: map[string]uint64{}, Downstream: map[string]uint64{}}
	for _, key := range runtimeKeys {
		value, found := sumMetric(samples, d.counterMetrics[key], nil)
		if !found {
			return CounterSet{}, fmt.Errorf("required runtime counter %s is absent", key)
		}
		result.Runtime[key] = value
	}
	selectors := map[string]func(map[string]string) bool{
		"tunnel": func(v map[string]string) bool {
			return v["entrypoint"] == "tunnel_message" || v["entrypoint"] == "tunnel_broadcast" || v["entrypoint"] == "remote_dialer"
		},
		"proxy":      func(v map[string]string) bool { return v["entrypoint"] == "kubernetes_proxy" },
		"kubernetes": func(v map[string]string) bool { return v["operation"] == "kubernetes" },
		"exec":       func(v map[string]string) bool { return v["operation"] == "exec" },
		"logs":       func(v map[string]string) bool { return v["operation"] == "logs" },
		"helm":       func(v map[string]string) bool { return v["operation"] == "helm" },
	}
	for _, key := range downstreamKeys {
		metric := d.counterMetrics[key]
		value, found := sumMetric(samples, metric, selectors[key])
		if !found {
			// A newly started process may not have emitted a sample yet. The
			// metric family itself must still be present before zero is accepted.
			if !metricFamilyPresent(samples, metric) {
				return CounterSet{}, errors.New("downstream boundary metric is absent")
			}
		}
		result.Downstream[key] = value
	}
	return result, nil
}

func (d *LiveDriver) Run(ctx context.Context, request ScenarioRequest) ScenarioResult {
	// The public Hook already serializes scenario requests, but the driver is a
	// separately constructible type. Keep destructive mode transitions safe even
	// when a test harness or future caller invokes it directly.
	d.scenarioMu.Lock()
	defer d.scenarioMu.Unlock()
	switch request.Scenario {
	case "feature_false":
		return d.featureFalse(ctx, request.Scenario)
	case "unactivated":
		return d.unactivated(ctx, request)
	case "central_disabled":
		return d.centralDisabled(ctx, request.Scenario)
	case "emergency_disabled":
		return d.emergencyDisabled(ctx, request.Scenario)
	case "read_denial":
		return d.readDenial(ctx, request.Scenario)
	case "approval_expiry":
		return d.approvalExpiry(ctx, request.Scenario)
	case "approval_once":
		return d.approvalOnce(ctx, request.Scenario)
	case "approval_replay":
		return d.approvalReplay(ctx, request.Scenario)
	case "approval_reject":
		return d.approvalReject(ctx, request.Scenario)
	case "auto_allowlisted_success":
		return d.autoAllowlistedSuccess(ctx, request.Scenario)
	case "auto_nonallowlisted_approval":
		return d.autoNonallowlistedApproval(ctx, request.Scenario)
	case "versioned_rag_grounded":
		return d.versionedRAGGrounded(ctx, request.Scenario)
	case "general_answer":
		return d.generalAnswer(ctx, request.Scenario)
	case "discovery_mixed_catalog":
		return d.discoveryQualification(ctx, request.Scenario, "mixed_catalog")
	case "malformed_discovery":
		return d.discoveryQualification(ctx, request.Scenario, "malformed_catalog")
	case "diagnosis_alert", "approval_pending_alert", "approval_rejected_alert", "approval_expired_alert",
		"blocked_auto_alert", "failed_precondition_alert", "failed_verification_alert":
		return d.alertDeliveryQualification(ctx, request.Scenario)
	case "leader_kill_failover", "clean_install", "isolation_matrix", "resilience_matrix", "upgrade_rollback":
		if request.Scenario == "leader_kill_failover" && d.leaderFailover != nil {
			return d.leaderKillFailover(ctx, request)
		}
		return d.infrastructureQualification(ctx, request)
	default:
		return Unsupported(request.Scenario)
	}
}

type approvalProof struct {
	ID         string    `json:"id"`
	State      string    `json:"state"`
	Eligible   bool      `json:"eligible"`
	Capability string    `json:"capability"`
	Target     string    `json:"target"`
	ExpiresAt  time.Time `json:"expiresAt"`
}

type approvalListEnvelope struct {
	Data struct {
		Items []approvalProof `json:"items"`
	} `json:"data"`
}

type approvalDecisionEnvelope struct {
	Data struct {
		Approval approvalProof `json:"approval"`
	} `json:"data"`
}

type operationEnvelope struct {
	Data struct {
		OperationID  string `json:"operation_id"`
		Capability   string `json:"capability"`
		State        string `json:"state"`
		ResultStatus string `json:"result_status"`
	} `json:"data"`
}

type sessionCreateEnvelope struct {
	Data struct {
		Session struct {
			ID string `json:"id"`
		} `json:"session"`
		Replayed bool `json:"replayed"`
	} `json:"data"`
}

type messageReceipt struct {
	SessionID  string    `json:"session_id"`
	TurnID     string    `json:"turn_id"`
	AcceptedAt time.Time `json:"accepted_at"`
}

type sessionListItem struct {
	ID                   string `json:"id"`
	ClientSessionID      string `json:"client_session_id"`
	ResourceScopeSummary string `json:"resource_scope_summary"`
	State                string `json:"state"`
	Visibility           string `json:"visibility"`
	Source               string `json:"source"`
}

type sessionListEnvelope struct {
	Data struct {
		Sessions []sessionListItem `json:"sessions"`
	} `json:"data"`
}

type triggerEventItem struct {
	ID           string `json:"id"`
	EventType    string `json:"event_type"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	State        string `json:"state"`
}

type triggerEventListEnvelope struct {
	Data struct {
		Items []triggerEventItem `json:"items"`
	} `json:"data"`
}

var (
	fixtureIDPattern         = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$`)
	fixtureCapabilityPattern = regexp.MustCompile(`^[a-z][a-z0-9._:-]{0,127}$`)
)

// Real streaming providers may emit one bounded event per small text delta.
// The byte-limited reader remains the primary memory bound; this secondary
// event-count bound prevents an otherwise valid response from being rejected
// merely because it was split into more than 256 deltas.
const maxQualificationStreamEvents = 4096

func (d *LiveDriver) approvalExpiry(ctx context.Context, scenario string) (result ScenarioResult) {
	fixture := d.fixtures.ApprovalExpiry
	if d.approverToken == "" || !d.validApprovalFixture(fixture, false, true, false) {
		return Unsupported(scenario)
	}
	original, before, ok := d.beginAuthorityProof(ctx, "approval")
	if !ok {
		return Unsupported(scenario)
	}
	defer d.finishAuthorityProof(&result, scenario, original, before, 0)

	approval, found, err := d.findApproval(ctx, fixture.ApprovalID)
	if err != nil || !found || !approvalMatches(approval, fixture) {
		return Unsupported(scenario)
	}
	wait := time.Until(approval.ExpiresAt.UTC()) + 250*time.Millisecond
	if wait <= 250*time.Millisecond || wait > maxExpiryWait || waitContext(ctx, wait) != nil || time.Now().UTC().Before(approval.ExpiresAt.UTC()) {
		return Unsupported(scenario)
	}
	status, decisionErr := d.decideApproval(ctx, fixture, fixture.DecisionRequest, "approve")
	if decisionErr == nil || (status != http.StatusForbidden && status != http.StatusConflict) {
		return Unsupported(scenario)
	}
	if current, present, listErr := d.findApproval(ctx, fixture.ApprovalID); listErr != nil || present && current.State == "pending" {
		return Unsupported(scenario)
	}
	if !d.observeProductCallDelta(ctx, before, 0, d.noCallDwell) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "approval_expired", "product_calls_zero")
}

func (d *LiveDriver) approvalOnce(ctx context.Context, scenario string) (result ScenarioResult) {
	fixture := d.fixtures.ApprovalOnce
	if d.approverToken == "" || !d.validApprovalFixture(fixture, true, true, true) {
		return Unsupported(scenario)
	}
	original, before, ok := d.beginAuthorityProof(ctx, "approval")
	if !ok {
		return Unsupported(scenario)
	}
	defer d.finishAuthorityProof(&result, scenario, original, before, 1)

	approval, found, err := d.findApproval(ctx, fixture.ApprovalID)
	if err != nil || !found || !approvalMatches(approval, fixture) {
		return Unsupported(scenario)
	}
	decision, status, err := d.approveExact(ctx, fixture, fixture.DecisionRequest)
	if err != nil || status != http.StatusOK || decision.ID != fixture.ApprovalID || decision.State != "approved" || decision.Capability != fixture.Capability {
		return Unsupported(scenario)
	}
	if !d.waitForOperation(ctx, fixture.ActionID, fixture.Capability, before, 1) {
		return Unsupported(scenario)
	}
	// A lost response may be retried with the exact same idempotency tuple. It
	// must return the committed decision without dispatching the action twice.
	replayed, status, err := d.approveExact(ctx, fixture, fixture.DecisionRequest)
	if err != nil || status != http.StatusOK || replayed.ID != fixture.ApprovalID || replayed.State != "approved" || !d.observeProductCallDelta(ctx, before, 1, d.noCallDwell) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "approval_consumed_once", "product_call_once")
}

func (d *LiveDriver) approvalReplay(ctx context.Context, scenario string) (result ScenarioResult) {
	fixture := d.fixtures.ApprovalOnce
	if d.approverToken == "" || !d.validApprovalFixture(fixture, true, true, true) {
		return Unsupported(scenario)
	}
	original, before, ok := d.beginAuthorityProof(ctx, "approval")
	if !ok {
		return Unsupported(scenario)
	}
	defer d.finishAuthorityProof(&result, scenario, original, before, 0)
	if !d.operationSucceeded(ctx, fixture.ActionID, fixture.Capability) {
		return Unsupported(scenario)
	}
	status, err := d.decideApproval(ctx, fixture, fixture.ReplayRequest, "approve")
	if err == nil || status != http.StatusConflict || !d.observeProductCallDelta(ctx, before, 0, d.noCallDwell) || !d.operationSucceeded(ctx, fixture.ActionID, fixture.Capability) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "approval_replay_denied", "additional_product_calls_zero")
}

func (d *LiveDriver) approvalReject(ctx context.Context, scenario string) (result ScenarioResult) {
	fixture := d.fixtures.ApprovalReject
	if d.approverToken == "" || !d.validApprovalFixture(fixture, false, true, false) {
		return Unsupported(scenario)
	}
	original, before, ok := d.beginAuthorityProof(ctx, "approval")
	if !ok {
		return Unsupported(scenario)
	}
	defer d.finishAuthorityProof(&result, scenario, original, before, 0)
	approval, found, err := d.findApproval(ctx, fixture.ApprovalID)
	if err != nil || !found || !approvalMatches(approval, fixture) {
		return Unsupported(scenario)
	}
	decision, status, err := d.rejectExact(ctx, fixture)
	if err != nil || status != http.StatusOK || decision.ID != fixture.ApprovalID || decision.State != "denied" || decision.Capability != fixture.Capability {
		return Unsupported(scenario)
	}
	if current, present, listErr := d.findApproval(ctx, fixture.ApprovalID); listErr != nil || present && current.State == "pending" || !d.observeProductCallDelta(ctx, before, 0, d.noCallDwell) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "approval_rejected", "product_calls_zero")
}

func (d *LiveDriver) autoAllowlistedSuccess(ctx context.Context, scenario string) (result ScenarioResult) {
	fixture := d.fixtures.AutoAllowlistedSuccess
	if d.approverToken == "" || d.eventStimulus == nil || !validEventActionFixture(fixture) {
		return Unsupported(scenario)
	}
	original, before, ok := d.beginAuthorityProof(ctx, "auto")
	if !ok {
		return Unsupported(scenario)
	}
	if d.eventSessionExists(ctx, fixture.TaskID) || d.eventStimulus.PublishTerminalQueueFailure(ctx, fixture.TaskID) != nil {
		d.finishAuthorityProof(&result, scenario, original, before, 0)
		return Unsupported(scenario)
	}
	localSessionID, eventID, ok := d.waitForEventSession(ctx, fixture.TaskID)
	if !ok || !d.verifyDispatchedQueueEvent(ctx, eventID, fixture.TaskID) {
		d.finishAuthorityProof(&result, scenario, original, before, 0)
		return Unsupported(scenario)
	}
	defer d.finishAutomaticProof(&result, scenario, original, before, 1, localSessionID, fixture.AbortRequestID)
	actionID, ok := d.discoverEventActionFromEvents(ctx, localSessionID, fixture.Capability)
	if !ok || !d.waitForOperation(ctx, actionID, fixture.Capability, before, 1) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "event_bound_service_session", "allowlisted_action_succeeded", "product_call_once")
}

func (d *LiveDriver) autoNonallowlistedApproval(ctx context.Context, scenario string) (result ScenarioResult) {
	fixture := d.fixtures.AutoNonallowlisted
	if d.approverToken == "" || !fixtureCapabilityPattern.MatchString(fixture.Capability) || !validStimulus(fixture.Stimulus) {
		return Unsupported(scenario)
	}
	original, before, ok := d.beginAuthorityProof(ctx, "auto")
	if !ok {
		return Unsupported(scenario)
	}
	prior, err := d.listApprovals(ctx)
	if err != nil {
		d.finishAuthorityProof(&result, scenario, original, before, 0)
		return Unsupported(scenario)
	}
	localSessionID, err := d.createFixtureSession(ctx, fixture.Stimulus)
	if err != nil {
		d.finishAuthorityProof(&result, scenario, original, before, 0)
		return Unsupported(scenario)
	}
	defer d.finishAutomaticProof(&result, scenario, original, before, 0, localSessionID, fixture.Stimulus.AbortRequestID)
	if _, err = d.sendStimulus(ctx, localSessionID, fixture.Stimulus); err != nil || !d.waitForNewApproval(ctx, fixture, prior, before) || !d.observeProductCallDelta(ctx, before, 0, d.noCallDwell) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "approval_pending", "product_calls_zero")
}

func (d *LiveDriver) versionedRAGGrounded(ctx context.Context, scenario string) (result ScenarioResult) {
	fixture := d.fixtures.VersionedRAGGrounded
	if d.approverToken == "" || !validVersionedRAGFixture(fixture) || !d.fixtureIDsAreIsolated() {
		return Unsupported(scenario)
	}
	original, err := d.qualificationBaseline(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	before, err := d.Counters(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	localSessionID, err := d.createFixtureSession(ctx, fixture.Stimulus)
	if err != nil {
		return Unsupported(scenario)
	}
	defer d.finishAnswerProof(&result, scenario, original, before, localSessionID, fixture.Stimulus.AbortRequestID, 2, 1)
	receipt, err := d.sendStimulus(ctx, localSessionID, fixture.Stimulus)
	if err != nil || !d.waitForTurnCompletion(ctx, localSessionID, receipt.TurnID) {
		return Unsupported(scenario)
	}
	answer, ok := d.waitForSingleAssistantAnswer(ctx, localSessionID)
	if !ok || !strings.Contains(answer.Content, fixture.CorrectedRevisionMarker) || !strings.Contains(answer.Content, fixture.ProductVersionMarker) ||
		!hasExactCitation(answer.Citations, fixture.CitationID, fixture.CitationTitle, fixture.CitationSource) ||
		!d.waitForAnswerCounterDelta(ctx, before, 2, 1) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "real_generation", "real_embedding", "corrected_revision", "version_selected", "grounded_citation")
}

func (d *LiveDriver) generalAnswer(ctx context.Context, scenario string) (result ScenarioResult) {
	fixture := d.fixtures.GeneralAnswer
	if d.approverToken == "" || !validGeneralAnswerFixture(fixture) || !d.fixtureIDsAreIsolated() {
		return Unsupported(scenario)
	}
	original, err := d.qualificationBaseline(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	before, err := d.Counters(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	localSessionID, err := d.createFixtureSession(ctx, fixture.Stimulus)
	if err != nil {
		return Unsupported(scenario)
	}
	// The production route is retrieval-aware even for a general question: one
	// query embedding plus one generation call proves the intended RAG
	// passthrough instead of silently exercising a retrieval-disabled route.
	defer d.finishAnswerProof(&result, scenario, original, before, localSessionID, fixture.Stimulus.AbortRequestID, 2, 1)
	receipt, err := d.sendStimulus(ctx, localSessionID, fixture.Stimulus)
	if err != nil || !d.waitForTurnCompletion(ctx, localSessionID, receipt.TurnID) {
		return Unsupported(scenario)
	}
	answer, ok := d.waitForSingleAssistantAnswer(ctx, localSessionID)
	if !ok || !strings.Contains(answer.Content, fixture.ExpectedAnswerMarker) || len(answer.Citations) != 0 ||
		!d.waitForAnswerCounterDelta(ctx, before, 2, 1) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "real_generation", "general_answer", "no_fabricated_citation")
}

func (d *LiveDriver) beginAuthorityProof(ctx context.Context, mode string) (statusEnvelope, CounterSet, bool) {
	original, err := d.qualificationBaseline(ctx)
	if err != nil || !d.fixtureIDsAreIsolated() {
		return statusEnvelope{}, CounterSet{}, false
	}
	before, err := d.Counters(ctx)
	if err != nil {
		return statusEnvelope{}, CounterSet{}, false
	}
	if err = d.enterAuthorityMode(ctx, original, mode); err != nil {
		_ = d.restoreMode(original)
		return statusEnvelope{}, CounterSet{}, false
	}
	return original, before, true
}

func (d *LiveDriver) finishAuthorityProof(result *ScenarioResult, scenario string, original statusEnvelope, before CounterSet, toolDelta uint64) {
	if d.restoreMode(original) != nil {
		*result = Unsupported(scenario)
		return
	}
	verifyCtx, cancel := context.WithTimeout(context.Background(), 35*time.Second)
	defer cancel()
	if !d.observeProductCallDelta(verifyCtx, before, toolDelta, 0) {
		*result = Unsupported(scenario)
	}
}

func (d *LiveDriver) enterAuthorityMode(ctx context.Context, original statusEnvelope, desired string) error {
	if desired != "approval" && desired != "auto" {
		return errors.New("qualification authority mode is invalid")
	}
	// Mode changes reconcile through the deployment controller and may return a
	// transient conflict even after the requested revision was accepted. Treat
	// the converged authoritative state as proof; never treat the PATCH response
	// itself as proof that a higher authority mode is active.
	_, _ = d.setMode(ctx, desired, original.Data.Mode.Revision, false)
	current, err := d.waitForStatus(ctx, func(status statusEnvelope) bool {
		return status.Data.Mode.Requested == desired && status.Data.Mode.Authoritative == desired &&
			!status.Data.Mode.EmergencyDisabled && strings.TrimSpace(status.Data.Mode.DisclosureDigest) != ""
	})
	if err != nil {
		return errors.New("qualification authority mode was not verified")
	}
	if !current.Data.Connection.DisclosureAcknowledged || current.Data.Connection.DisclosureDigest != current.Data.Mode.DisclosureDigest {
		_, _ = d.api(ctx, http.MethodPatch, "/api/v1/admin/charlie/mode/", d.adminToken, map[string]any{"acknowledge_disclosure_digest": current.Data.Mode.DisclosureDigest}, nil)
		current, err = d.waitForStatus(ctx, func(status statusEnvelope) bool {
			return status.Data.Mode.Requested == desired && status.Data.Mode.Authoritative == desired &&
				!status.Data.Mode.EmergencyDisabled && status.Data.Connection.DisclosureAcknowledged &&
				status.Data.Connection.DisclosureDigest == status.Data.Mode.DisclosureDigest
		})
	}
	if err != nil || current.Data.Mode.Requested != desired || current.Data.Mode.Authoritative != desired || current.Data.Mode.EmergencyDisabled || !current.Data.Connection.DisclosureAcknowledged || current.Data.Connection.DisclosureDigest != current.Data.Mode.DisclosureDigest {
		return errors.New("qualification authority disclosure was not acknowledged")
	}
	if !d.waitForAgentMetrics(ctx, int(current.Data.Agent.DesiredReplicas)) {
		return errors.New("qualification agents did not converge on the authority mode")
	}
	return nil
}

func (d *LiveDriver) findApproval(ctx context.Context, approvalID string) (approvalProof, bool, error) {
	items, err := d.listApprovals(ctx)
	if err != nil {
		return approvalProof{}, false, err
	}
	var found approvalProof
	count := 0
	for _, item := range items {
		if item.ID == approvalID {
			found, count = item, count+1
		}
	}
	if count > 1 {
		return approvalProof{}, false, errors.New("qualification approval identifier is ambiguous")
	}
	return found, count == 1, nil
}

func (d *LiveDriver) listApprovals(ctx context.Context) ([]approvalProof, error) {
	var response approvalListEnvelope
	if _, err := d.api(ctx, http.MethodGet, "/api/v1/charlie/approvals/", d.approverToken, nil, &response); err != nil {
		return nil, err
	}
	if len(response.Data.Items) > 200 {
		return nil, errors.New("qualification approval list exceeded its bound")
	}
	return response.Data.Items, nil
}

func (d *LiveDriver) approveExact(ctx context.Context, fixture ApprovalFixture, requestID string) (approvalProof, int, error) {
	var response approvalDecisionEnvelope
	status, err := d.api(ctx, http.MethodPost, approvalDecisionPath(fixture.ApprovalID), d.approverToken,
		map[string]any{"request_id": requestID, "decision": "approve", "rationale": "bounded live qualification action"}, &response)
	return response.Data.Approval, status, err
}

func (d *LiveDriver) rejectExact(ctx context.Context, fixture ApprovalFixture) (approvalProof, int, error) {
	var response approvalDecisionEnvelope
	status, err := d.api(ctx, http.MethodPost, approvalDecisionPath(fixture.ApprovalID), d.approverToken,
		map[string]any{"request_id": fixture.DecisionRequest, "decision": "reject", "rationale": "rejected by live qualification fixture"}, &response)
	return response.Data.Approval, status, err
}

func (d *LiveDriver) decideApproval(ctx context.Context, fixture ApprovalFixture, requestID, decision string) (int, error) {
	return d.api(ctx, http.MethodPost, approvalDecisionPath(fixture.ApprovalID), d.approverToken,
		map[string]any{"request_id": requestID, "decision": decision, "rationale": "bounded live qualification decision"}, nil)
}

func approvalDecisionPath(id string) string {
	return "/api/v1/charlie/approvals/" + url.PathEscape(id) + "/decision/"
}

func (d *LiveDriver) getOperation(ctx context.Context, actionID string, output *operationEnvelope) (int, error) {
	return d.api(ctx, http.MethodGet, "/api/v1/charlie/operations/"+url.PathEscape(actionID), d.approverToken, nil, output)
}

func (d *LiveDriver) createFixtureSession(ctx context.Context, stimulus SessionStimulus) (string, error) {
	var response sessionCreateEnvelope
	status, err := d.api(ctx, http.MethodPost, "/api/v1/charlie/sessions/", d.approverToken, map[string]any{
		"client_session_id": stimulus.ClientSessionID, "intent": stimulus.Intent,
		"resources": []map[string]string{{"type": stimulus.ResourceType, "id": stimulus.ResourceID, "required_verb": "read"}},
	}, &response)
	localID, parseErr := uuid.Parse(response.Data.Session.ID)
	if err != nil || status != http.StatusCreated || response.Data.Replayed || parseErr != nil || localID == uuid.Nil {
		return "", errors.New("qualification session was not created fresh")
	}
	return localID.String(), nil
}

func (d *LiveDriver) sendStimulus(ctx context.Context, localSessionID string, stimulus SessionStimulus) (messageReceipt, error) {
	var receipt messageReceipt
	status, err := d.api(ctx, http.MethodPost, "/api/v1/charlie/sessions/"+url.PathEscape(localSessionID)+"/messages/", d.approverToken,
		map[string]any{"client_message_id": stimulus.ClientMessageID, "message": stimulus.Message}, &receipt)
	now := time.Now().UTC()
	// The bridge receipt carries Charlie's opaque central session ID. Astronomer
	// deliberately addresses the browser session with a different local UUID,
	// so the receipt identity must be bounded and non-empty rather than equal to
	// the product-local route parameter.
	if err != nil || status != http.StatusAccepted || !validFixtureID(receipt.SessionID) || !validFixtureID(receipt.TurnID) ||
		receipt.AcceptedAt.IsZero() || receipt.AcceptedAt.Before(now.Add(-5*time.Minute)) || receipt.AcceptedAt.After(now.Add(time.Minute)) {
		return messageReceipt{}, errors.New("qualification stimulus was not accepted")
	}
	return receipt, nil
}

func (d *LiveDriver) abortFixtureSession(ctx context.Context, localSessionID, requestID string) error {
	status, err := d.api(ctx, http.MethodPost, "/api/v1/charlie/sessions/"+url.PathEscape(localSessionID)+"/abort/", d.approverToken,
		map[string]any{"request_id": requestID}, nil)
	if err != nil || status != http.StatusNoContent {
		return errors.New("qualification session cleanup was not confirmed")
	}
	return nil
}

func (d *LiveDriver) finishAutomaticProof(result *ScenarioResult, scenario string, original statusEnvelope, before CounterSet, toolDelta uint64, localSessionID, abortRequestID string) {
	cleanupCtx, cancel := context.WithTimeout(context.Background(), 35*time.Second)
	abortErr := d.abortFixtureSession(cleanupCtx, localSessionID, abortRequestID)
	cancel()
	d.finishAuthorityProof(result, scenario, original, before, toolDelta)
	if abortErr != nil {
		*result = Unsupported(scenario)
	}
}

type streamedActionEvent struct {
	TurnID   string `json:"turn_id"`
	ActionID string `json:"action_id"`
	Type     string `json:"type"`
	Data     struct {
		Data struct {
			Capability string `json:"capability"`
		} `json:"data"`
	} `json:"data"`
}

type historyCitation struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Source string `json:"source"`
}

type historyItem struct {
	ItemID    string            `json:"item_id"`
	Kind      string            `json:"kind"`
	Content   string            `json:"redacted_content"`
	Citations []historyCitation `json:"citations,omitempty"`
}

type historyEnvelope struct {
	Data []historyItem `json:"data"`
}

func (d *LiveDriver) waitForTurnCompletion(ctx context.Context, localSessionID, turnID string) bool {
	streamCtx, cancel := context.WithTimeout(ctx, d.proofTimeout)
	defer cancel()
	endpoint := d.base.ResolveReference(&url.URL{Path: "/api/v1/charlie/sessions/" + localSessionID + "/events/"})
	request, err := http.NewRequestWithContext(streamCtx, http.MethodGet, endpoint.String(), nil)
	if err != nil {
		return false
	}
	request.Header.Set("Authorization", "Bearer "+d.approverToken)
	request.Header.Set("Accept", "text/event-stream")
	response, err := d.client.Do(request)
	if err != nil {
		return false
	}
	defer func() { _ = response.Body.Close() }()
	if response.StatusCode != http.StatusOK || !strings.HasPrefix(strings.ToLower(response.Header.Get("Content-Type")), "text/event-stream") {
		return false
	}
	limited := &io.LimitedReader{R: response.Body, N: (1 << 20) + 1}
	scanner := bufio.NewScanner(limited)
	scanner.Buffer(make([]byte, 16<<10), 256<<10)
	eventName := ""
	dataLines := make([]string, 0, 2)
	events := 0
	process := func() (bool, bool) {
		if len(dataLines) == 0 {
			eventName = ""
			return false, true
		}
		events++
		if events > maxQualificationStreamEvents {
			return false, false
		}
		var event streamedActionEvent
		if json.Unmarshal([]byte(strings.Join(dataLines, "\n")), &event) != nil {
			return false, false
		}
		dataLines = dataLines[:0]
		if eventName != "" && event.Type != "" && eventName != event.Type {
			return false, false
		}
		typeName := event.Type
		if typeName == "" {
			typeName = eventName
		}
		eventName = ""
		if event.TurnID != "" && event.TurnID != turnID {
			return false, false
		}
		switch typeName {
		case "turn.completed":
			return true, event.TurnID == turnID
		case "turn.failed", "turn.aborted", "charlie.error":
			return true, false
		default:
			return false, true
		}
	}
	for scanner.Scan() {
		line := scanner.Text()
		switch {
		case line == "":
			done, valid := process()
			if done || !valid {
				return done && valid
			}
		case strings.HasPrefix(line, "event:"):
			eventName = strings.TrimSpace(strings.TrimPrefix(line, "event:"))
		case strings.HasPrefix(line, "data:"):
			dataLines = append(dataLines, strings.TrimPrefix(strings.TrimPrefix(line, "data:"), " "))
		case strings.HasPrefix(line, "id:"):
			eventID := strings.TrimSpace(strings.TrimPrefix(line, "id:"))
			if len(eventID) > 128 || strings.ContainsRune(eventID, '\x00') {
				return false
			}
		case strings.HasPrefix(line, ":"):
		default:
			return false
		}
	}
	return false
}

func (d *LiveDriver) waitForSingleAssistantAnswer(ctx context.Context, localSessionID string) (historyItem, bool) {
	deadline := time.Now().Add(d.proofTimeout)
	for {
		var response historyEnvelope
		_, err := d.api(ctx, http.MethodGet, "/api/v1/charlie/sessions/"+url.PathEscape(localSessionID)+"/history/", d.approverToken, nil, &response)
		history := response.Data
		if err == nil && len(history) <= 100 {
			var answer historyItem
			userCount, assistantCount := 0, 0
			valid := true
			for _, item := range history {
				if !validFixtureID(item.ItemID) || len([]byte(item.Content)) > 32768 || len(item.Citations) > 16 {
					valid = false
					break
				}
				switch item.Kind {
				case "user_message":
					userCount++
				case "assistant_message":
					assistantCount++
					answer = item
				case "finding_evidence":
				default:
					valid = false
				}
				for _, citation := range item.Citations {
					if !validFixtureID(citation.ID) || strings.TrimSpace(citation.Title) == "" || strings.TrimSpace(citation.Source) == "" || len([]byte(citation.Title)) > 1024 || len([]byte(citation.Source)) > 2048 {
						valid = false
					}
				}
			}
			if valid && userCount == 1 && assistantCount == 1 && strings.TrimSpace(answer.Content) != "" {
				return answer, true
			}
			if !valid || userCount > 1 || assistantCount > 1 {
				return historyItem{}, false
			}
		}
		if !time.Now().Before(deadline) || waitContext(ctx, d.proofPoll) != nil {
			return historyItem{}, false
		}
	}
}

func hasExactCitation(citations []historyCitation, id, title, source string) bool {
	for _, citation := range citations {
		if citation.ID == id && citation.Title == title && citation.Source == source {
			return true
		}
	}
	return false
}

func (d *LiveDriver) waitForAnswerCounterDelta(ctx context.Context, before CounterSet, modelCalls, ragQueries uint64) bool {
	deadline := time.Now().Add(d.proofTimeout)
	for {
		after, err := d.Counters(ctx)
		if err == nil && exactAnswerCounterDelta(before, after, modelCalls, ragQueries) {
			return true
		}
		if err != nil || countersExceededAnswerDelta(before, after, modelCalls, ragQueries) || !time.Now().Before(deadline) || waitContext(ctx, d.proofPoll) != nil {
			return false
		}
	}
}

func exactAnswerCounterDelta(before, after CounterSet, modelCalls, ragQueries uint64) bool {
	if !completeCounters(before) || !completeCounters(after) || !sameCounterMap(before.Downstream, after.Downstream) {
		return false
	}
	for _, key := range runtimeKeys {
		expected := uint64(0)
		switch key {
		case "model_calls":
			expected = modelCalls
		case "rag_queries":
			expected = ragQueries
		case "sessions":
			expected = 1
		case "work_claims":
			// One accepted explicit message creates exactly one agent turn and
			// therefore exactly one durable work claim.
			expected = 1
		}
		if after.Runtime[key] < before.Runtime[key] || after.Runtime[key]-before.Runtime[key] != expected {
			return false
		}
	}
	return true
}

func countersExceededAnswerDelta(before, after CounterSet, modelCalls, ragQueries uint64) bool {
	if !completeCounters(before) || !completeCounters(after) || !sameCounterMap(before.Downstream, after.Downstream) {
		return true
	}
	for _, key := range runtimeKeys {
		maximum := uint64(0)
		switch key {
		case "model_calls":
			maximum = modelCalls
		case "rag_queries":
			maximum = ragQueries
		case "sessions":
			maximum = 1
		case "work_claims":
			maximum = 1
		}
		if after.Runtime[key] < before.Runtime[key] || after.Runtime[key]-before.Runtime[key] > maximum {
			return true
		}
	}
	return false
}

func (d *LiveDriver) finishAnswerProof(result *ScenarioResult, scenario string, original statusEnvelope, before CounterSet, localSessionID, abortRequestID string, modelCalls, ragQueries uint64) {
	cleanupCtx, cancel := context.WithTimeout(context.Background(), 35*time.Second)
	defer cancel()
	if d.abortFixtureSession(cleanupCtx, localSessionID, abortRequestID) != nil || d.restoreMode(original) != nil ||
		!d.waitForAnswerCounterDelta(cleanupCtx, before, modelCalls, ragQueries) {
		*result = Unsupported(scenario)
	}
}

func (d *LiveDriver) eventSessionExists(ctx context.Context, taskID string) bool {
	_, _, found := d.findEventSession(ctx, taskID)
	return found
}

func (d *LiveDriver) waitForEventSession(ctx context.Context, taskID string) (string, string, bool) {
	deadline := time.Now().Add(d.proofTimeout)
	for {
		localID, eventID, found := d.findEventSession(ctx, taskID)
		if found {
			return localID, eventID, true
		}
		if !time.Now().Before(deadline) || waitContext(ctx, d.proofPoll) != nil {
			return "", "", false
		}
	}
}

func (d *LiveDriver) findEventSession(ctx context.Context, taskID string) (string, string, bool) {
	var response sessionListEnvelope
	status, err := d.apiQuery(ctx, http.MethodGet, "/api/v1/charlie/sessions/", url.Values{"offset": {"0"}, "limit": {"100"}}, d.approverToken, nil, &response)
	if err != nil || status != http.StatusOK || len(response.Data.Sessions) > 100 {
		return "", "", false
	}
	wantScope := "workflow:" + qualificationQueueTaskType + ":" + taskID
	localID, eventID := "", ""
	for _, session := range response.Data.Sessions {
		if session.ResourceScopeSummary != wantScope {
			continue
		}
		_, sessionIDErr := uuid.Parse(session.ClientSessionID)
		if !validFixtureID(session.ID) || sessionIDErr != nil || session.Source != "event" || session.Visibility != "incident" ||
			(session.State != "active" && session.State != "waiting_approval") || localID != "" {
			return "", "", false
		}
		localID, eventID = session.ID, session.ClientSessionID
	}
	return localID, eventID, localID != ""
}

func (d *LiveDriver) verifyDispatchedQueueEvent(ctx context.Context, eventID, taskID string) bool {
	var response triggerEventListEnvelope
	status, err := d.apiQuery(ctx, http.MethodGet, "/api/v1/admin/charlie/trigger-events/", url.Values{"state": {"dispatched"}, "offset": {"0"}, "limit": {"100"}}, d.adminToken, nil, &response)
	if err != nil || status != http.StatusOK || len(response.Data.Items) > 100 {
		return false
	}
	matches := 0
	for _, event := range response.Data.Items {
		if event.ID == eventID && event.EventType == "queue_terminal_failure" && event.ResourceType == "workflow" &&
			event.ResourceID == qualificationQueueTaskType+":"+taskID && event.State == "dispatched" {
			matches++
		}
	}
	return matches == 1
}

// Event-created sessions have no browser message receipt, so the exact turn is
// learned from the first action event and every subsequent action must remain
// bound to that same turn until its terminal event.
func (d *LiveDriver) discoverEventActionFromEvents(ctx context.Context, localSessionID, capability string) (string, bool) {
	streamCtx, cancel := context.WithTimeout(ctx, d.proofTimeout)
	defer cancel()
	endpoint := d.base.ResolveReference(&url.URL{Path: "/api/v1/charlie/sessions/" + localSessionID + "/events/"})
	request, err := http.NewRequestWithContext(streamCtx, http.MethodGet, endpoint.String(), nil)
	if err != nil {
		return "", false
	}
	request.Header.Set("Authorization", "Bearer "+d.approverToken)
	request.Header.Set("Accept", "text/event-stream")
	response, err := d.client.Do(request)
	if err != nil {
		return "", false
	}
	defer func() { _ = response.Body.Close() }()
	if response.StatusCode != http.StatusOK || !strings.HasPrefix(strings.ToLower(response.Header.Get("Content-Type")), "text/event-stream") {
		return "", false
	}
	limited := &io.LimitedReader{R: response.Body, N: (1 << 20) + 1}
	scanner := bufio.NewScanner(limited)
	scanner.Buffer(make([]byte, 16<<10), 256<<10)
	eventName, dataLines, actionID, turnID := "", make([]string, 0, 2), "", ""
	events := 0
	process := func() (bool, bool) {
		if len(dataLines) == 0 {
			eventName = ""
			return false, true
		}
		events++
		if events > maxQualificationStreamEvents {
			return false, false
		}
		var event streamedActionEvent
		if json.Unmarshal([]byte(strings.Join(dataLines, "\n")), &event) != nil {
			return false, false
		}
		dataLines = dataLines[:0]
		if eventName != "" && event.Type != "" && eventName != event.Type {
			return false, false
		}
		terminalType := event.Type
		if terminalType == "" {
			terminalType = eventName
		}
		eventName = ""
		if event.ActionID != "" {
			eventCapability := strings.TrimSpace(event.Data.Data.Capability)
			if !validFixtureID(event.ActionID) || !validFixtureID(event.TurnID) || eventCapability != capability ||
				(actionID != "" && event.ActionID != actionID) || (turnID != "" && event.TurnID != turnID) {
				return false, false
			}
			actionID, turnID = event.ActionID, event.TurnID
		}
		if turnID != "" && event.TurnID == turnID && (terminalType == "turn.failed" || terminalType == "turn.aborted") {
			return true, false
		}
		if turnID != "" && event.TurnID == turnID && terminalType == "turn.completed" {
			return true, actionID != ""
		}
		return false, true
	}
	for scanner.Scan() {
		line := scanner.Text()
		switch {
		case line == "":
			done, valid := process()
			if done || !valid {
				return actionID, done && valid
			}
		case strings.HasPrefix(line, "event:"):
			eventName = strings.TrimSpace(strings.TrimPrefix(line, "event:"))
		case strings.HasPrefix(line, "data:"):
			dataLines = append(dataLines, strings.TrimPrefix(strings.TrimPrefix(line, "data:"), " "))
		case strings.HasPrefix(line, "id:"):
			eventID := strings.TrimSpace(strings.TrimPrefix(line, "id:"))
			if len(eventID) > 128 || strings.ContainsRune(eventID, '\x00') {
				return "", false
			}
		case strings.HasPrefix(line, ":"):
		default:
			return "", false
		}
	}
	return "", false
}

func (d *LiveDriver) operationSucceeded(ctx context.Context, actionID, capability string) bool {
	var response operationEnvelope
	status, err := d.getOperation(ctx, actionID, &response)
	return err == nil && status == http.StatusOK && response.Data.OperationID == actionID && response.Data.Capability == capability && response.Data.State == "succeeded" && response.Data.ResultStatus == "succeeded"
}

func (d *LiveDriver) waitForOperation(ctx context.Context, actionID, capability string, before CounterSet, expected uint64) bool {
	deadline := time.Now().Add(d.proofTimeout)
	for {
		if d.operationSucceeded(ctx, actionID, capability) && d.observeProductCallDelta(ctx, before, expected, 0) {
			return true
		}
		current, err := d.Counters(ctx)
		if err != nil || current.Runtime["tool_calls"] < before.Runtime["tool_calls"] || current.Runtime["tool_calls"]-before.Runtime["tool_calls"] > expected || !sameCounterMap(before.Downstream, current.Downstream) || !time.Now().Before(deadline) {
			return false
		}
		if waitContext(ctx, d.proofPoll) != nil {
			return false
		}
	}
}

func (d *LiveDriver) waitForNewApproval(ctx context.Context, fixture PendingApprovalFixture, prior []approvalProof, before CounterSet) bool {
	priorIDs := make(map[string]struct{}, len(prior))
	for _, item := range prior {
		if !validFixtureID(item.ID) {
			return false
		}
		priorIDs[item.ID] = struct{}{}
	}
	expectedTarget := fixture.Stimulus.ResourceType + ":" + fixture.Stimulus.ResourceID
	deadline := time.Now().Add(d.proofTimeout)
	for {
		items, err := d.listApprovals(ctx)
		newItems := make([]approvalProof, 0, 1)
		for _, item := range items {
			if _, existed := priorIDs[item.ID]; !existed {
				newItems = append(newItems, item)
			}
		}
		if err == nil && len(newItems) == 1 {
			item := newItems[0]
			if validFixtureID(item.ID) && item.State == "pending" && item.Eligible && item.Capability == fixture.Capability && item.Target == expectedTarget && item.ExpiresAt.After(time.Now().UTC()) && d.observeProductCallDelta(ctx, before, 0, 0) {
				return true
			}
			return false
		}
		if err == nil && len(newItems) > 1 {
			return false
		}
		current, counterErr := d.Counters(ctx)
		if err != nil || counterErr != nil || current.Runtime["tool_calls"] != before.Runtime["tool_calls"] || !sameCounterMap(before.Downstream, current.Downstream) || !time.Now().Before(deadline) {
			return false
		}
		if waitContext(ctx, d.proofPoll) != nil {
			return false
		}
	}
}

func (d *LiveDriver) observeProductCallDelta(ctx context.Context, before CounterSet, expected uint64, dwell time.Duration) bool {
	if dwell > 0 && waitContext(ctx, dwell) != nil {
		return false
	}
	after, err := d.Counters(ctx)
	if err != nil || after.Runtime["tool_calls"] < before.Runtime["tool_calls"] || !sameCounterMap(before.Downstream, after.Downstream) {
		return false
	}
	return after.Runtime["tool_calls"]-before.Runtime["tool_calls"] == expected
}

func waitContext(ctx context.Context, duration time.Duration) error {
	if duration <= 0 {
		return nil
	}
	timer := time.NewTimer(duration)
	defer timer.Stop()
	select {
	case <-timer.C:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

func approvalMatches(approval approvalProof, fixture ApprovalFixture) bool {
	return approval.ID == fixture.ApprovalID && approval.State == "pending" && approval.Eligible && approval.Capability == fixture.Capability && approval.ExpiresAt.After(time.Now().UTC())
}

func (d *LiveDriver) validApprovalFixture(fixture ApprovalFixture, requireAction, requireDecision, requireReplay bool) bool {
	if !validFixtureID(fixture.ApprovalID) || !fixtureCapabilityPattern.MatchString(fixture.Capability) || requireAction && !validFixtureID(fixture.ActionID) {
		return false
	}
	decision, decisionErr := uuid.Parse(fixture.DecisionRequest)
	replay, replayErr := uuid.Parse(fixture.ReplayRequest)
	if requireDecision && (decisionErr != nil || decision == uuid.Nil) || !requireDecision && fixture.DecisionRequest != "" {
		return false
	}
	if requireReplay && (replayErr != nil || replay == uuid.Nil || replay == decision) || !requireReplay && fixture.ReplayRequest != "" {
		return false
	}
	return true
}

func validActionFixture(fixture ActionFixture) bool {
	return fixtureCapabilityPattern.MatchString(fixture.Capability) && validStimulus(fixture.Stimulus)
}

func validVersionedRAGFixture(fixture VersionedRAGFixture) bool {
	return validStimulus(fixture.Stimulus) && validFixtureMarker(fixture.CorrectedRevisionMarker) && validFixtureMarker(fixture.ProductVersionMarker) &&
		fixture.CorrectedRevisionMarker != fixture.ProductVersionMarker && validFixtureID(fixture.CitationID) &&
		validFixtureText(fixture.CitationTitle, 1024) && validFixtureText(fixture.CitationSource, 2048)
}

func validGeneralAnswerFixture(fixture GeneralAnswerFixture) bool {
	return validStimulus(fixture.Stimulus) && validFixtureMarker(fixture.ExpectedAnswerMarker)
}

func validEventActionFixture(fixture EventActionFixture) bool {
	taskID, taskErr := uuid.Parse(fixture.TaskID)
	abortID, abortErr := uuid.Parse(fixture.AbortRequestID)
	return fixtureCapabilityPattern.MatchString(fixture.Capability) && taskErr == nil && abortErr == nil && taskID != uuid.Nil && abortID != uuid.Nil && taskID != abortID
}

func validFixtureMarker(value string) bool {
	return validFixtureText(value, 256) && len([]byte(strings.TrimSpace(value))) >= 8
}

func validFixtureText(value string, maximum int) bool {
	trimmed := strings.TrimSpace(value)
	return trimmed == value && trimmed != "" && len([]byte(value)) <= maximum && !strings.ContainsAny(value, "\x00\r\n")
}

func validStimulus(stimulus SessionStimulus) bool {
	sessionID, sessionErr := uuid.Parse(stimulus.ClientSessionID)
	messageID, messageErr := uuid.Parse(stimulus.ClientMessageID)
	abortID, abortErr := uuid.Parse(stimulus.AbortRequestID)
	message := strings.TrimSpace(stimulus.Message)
	intent := strings.TrimSpace(stimulus.Intent)
	return sessionErr == nil && sessionID != uuid.Nil && messageErr == nil && messageID != uuid.Nil && abortErr == nil && abortID != uuid.Nil && sessionID != messageID && sessionID != abortID && messageID != abortID &&
		intent != "" && len([]byte(stimulus.Intent)) <= 255 && validFixtureID(stimulus.ResourceType) && validFixtureID(stimulus.ResourceID) && message != "" && len([]byte(stimulus.Message)) <= 1024
}

func validFixtureID(value string) bool {
	return fixtureIDPattern.MatchString(value)
}

func (d *LiveDriver) fixtureIDsAreIsolated() bool {
	seenApprovals := map[string]struct{}{}
	for _, fixture := range []ApprovalFixture{d.fixtures.ApprovalExpiry, d.fixtures.ApprovalOnce, d.fixtures.ApprovalReject} {
		if fixture.ApprovalID == "" {
			continue
		}
		if _, duplicate := seenApprovals[fixture.ApprovalID]; duplicate {
			return false
		}
		seenApprovals[fixture.ApprovalID] = struct{}{}
	}
	seenRequests := map[string]struct{}{}
	for _, requestID := range []string{
		d.fixtures.ApprovalExpiry.DecisionRequest,
		d.fixtures.ApprovalOnce.DecisionRequest,
		d.fixtures.ApprovalOnce.ReplayRequest,
		d.fixtures.ApprovalReject.DecisionRequest,
		d.fixtures.AutoAllowlistedSuccess.TaskID,
		d.fixtures.AutoAllowlistedSuccess.AbortRequestID,
		d.fixtures.AutoNonallowlisted.Stimulus.ClientSessionID,
		d.fixtures.AutoNonallowlisted.Stimulus.ClientMessageID,
		d.fixtures.AutoNonallowlisted.Stimulus.AbortRequestID,
		d.fixtures.LeaderKillFailover.Stimulus.ClientSessionID,
		d.fixtures.LeaderKillFailover.Stimulus.ClientMessageID,
		d.fixtures.LeaderKillFailover.Stimulus.AbortRequestID,
		d.fixtures.VersionedRAGGrounded.Stimulus.ClientSessionID,
		d.fixtures.VersionedRAGGrounded.Stimulus.ClientMessageID,
		d.fixtures.VersionedRAGGrounded.Stimulus.AbortRequestID,
		d.fixtures.GeneralAnswer.Stimulus.ClientSessionID,
		d.fixtures.GeneralAnswer.Stimulus.ClientMessageID,
		d.fixtures.GeneralAnswer.Stimulus.AbortRequestID,
	} {
		if requestID == "" {
			continue
		}
		if _, duplicate := seenRequests[requestID]; duplicate {
			return false
		}
		seenRequests[requestID] = struct{}{}
	}
	seenResources := map[string]struct{}{}
	for _, stimulus := range []SessionStimulus{
		d.fixtures.AutoNonallowlisted.Stimulus,
		d.fixtures.LeaderKillFailover.Stimulus,
		d.fixtures.VersionedRAGGrounded.Stimulus,
		d.fixtures.GeneralAnswer.Stimulus,
	} {
		if stimulus.ResourceType == "" && stimulus.ResourceID == "" {
			continue
		}
		resource := stimulus.ResourceType + ":" + stimulus.ResourceID
		if _, duplicate := seenResources[resource]; duplicate {
			return false
		}
		seenResources[resource] = struct{}{}
	}
	return true
}

type settingEnvelope struct {
	Data struct {
		Value     json.RawMessage `json:"value"`
		IsDefault bool            `json:"is_default"`
	} `json:"data"`
}

func (d *LiveDriver) featureFalse(ctx context.Context, scenario string) (result ScenarioResult) {
	originalMode, err := d.qualificationBaseline(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	baselineCounters, err := d.Counters(ctx)
	if err != nil || !completeCounters(baselineCounters) {
		return Unsupported(scenario)
	}
	if d.isolationObserver == nil {
		return Unsupported(scenario)
	}
	preparedObservation, err := d.isolationObserver.Prepare(ctx, IsolationColdFeatureDisabled)
	if err != nil {
		return Unsupported(scenario)
	}
	var original settingEnvelope
	if _, err = d.api(ctx, http.MethodGet, "/api/v1/admin/settings/feature.charlie/", d.adminToken, nil, &original); err != nil {
		return Unsupported(scenario)
	}
	defer func() {
		cleanupCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		cleanupCounters, counterErr := d.Counters(cleanupCtx)
		settingErr := d.restoreFeatureSetting(cleanupCtx, original)
		baselineErr := d.restoreBaseline(originalMode, cleanupCounters)
		if counterErr != nil || settingErr != nil || baselineErr != nil {
			markCleanupFailed(&result, scenario)
		}
	}()
	var applied settingEnvelope
	_, applyErr := d.api(ctx, http.MethodPut, "/api/v1/admin/settings/feature.charlie/", d.adminToken, map[string]any{"value": false}, &applied)
	if applyErr != nil || string(applied.Data.Value) != "false" {
		return Unsupported(scenario)
	}
	quietCounters, counterErr := d.Counters(ctx)
	if counterErr != nil || !completeCounters(quietCounters) {
		return Unsupported(scenario)
	}
	observation, observeErr := preparedObservation.Observe(ctx, d.noCallDwell)
	if observeErr != nil || !coldIsolationProved(observation, IsolationColdFeatureDisabled) || !d.countersUnchanged(ctx, quietCounters) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "state_applied", "process_absent", "listener_absent", "timer_absent", "dns_packets_zero", "tcp_packets_zero", "udp_packets_zero", "runtime_counters_unchanged", "downstream_counters_unchanged")
}

func (d *LiveDriver) restoreFeatureSetting(ctx context.Context, original settingEnvelope) error {
	var lastErr error
	for attempt := 0; attempt < 3; attempt++ {
		if original.Data.IsDefault {
			_, lastErr = d.api(ctx, http.MethodDelete, "/api/v1/admin/settings/feature.charlie/", d.adminToken, nil, nil)
		} else {
			_, lastErr = d.api(ctx, http.MethodPut, "/api/v1/admin/settings/feature.charlie/", d.adminToken, map[string]any{"value": original.Data.Value}, nil)
		}
		if lastErr == nil {
			var current settingEnvelope
			if _, lastErr = d.api(ctx, http.MethodGet, "/api/v1/admin/settings/feature.charlie/", d.adminToken, nil, &current); lastErr == nil &&
				current.Data.IsDefault == original.Data.IsDefault && string(current.Data.Value) == string(original.Data.Value) {
				return nil
			}
			if lastErr == nil {
				lastErr = errors.New("restored value did not match the original")
			}
		}
	}
	return fmt.Errorf("restore Charlie feature setting: %w", lastErr)
}

type statusEnvelope struct {
	Data struct {
		Connection struct {
			Connected              bool   `json:"connected"`
			CentralVersion         string `json:"central_version"`
			DisclosureAcknowledged bool   `json:"disclosure_acknowledged"`
			DisclosureDigest       string `json:"disclosure_digest"`
		} `json:"connection"`
		Mode struct {
			Requested         string `json:"requested"`
			Authoritative     string `json:"authoritative"`
			Revision          int64  `json:"revision"`
			EmergencyDisabled bool   `json:"emergency_disabled"`
			DisclosureDigest  string `json:"disclosure_digest"`
		} `json:"mode"`
		Agent struct {
			DesiredReplicas int32  `json:"desired_replicas"`
			ReadyReplicas   int32  `json:"ready_replicas"`
			LeaderReplica   string `json:"leader_replica"`
			FencingEpoch    int64  `json:"fencing_epoch"`
			AgentVersion    string `json:"agent_version"`
			ChartDigest     string `json:"chart_digest"`
			ImageDigest     string `json:"image_digest"`
			Replicas        []struct {
				Ordinal    int    `json:"ordinal"`
				InstanceID string `json:"instance_id"`
				Role       string `json:"role"`
				State      string `json:"state"`
			} `json:"replicas"`
		} `json:"agent"`
	} `json:"data"`
}

func (d *LiveDriver) status(ctx context.Context) (statusEnvelope, error) {
	var value statusEnvelope
	_, err := d.api(ctx, http.MethodGet, "/api/v1/admin/charlie/status/", d.adminToken, nil, &value)
	return value, err
}

func (d *LiveDriver) unactivated(ctx context.Context, request ScenarioRequest) (result ScenarioResult) {
	scenario := request.Scenario
	original, err := d.qualificationBaseline(ctx)
	if err != nil || d.agentScaler == nil {
		return Unsupported(scenario)
	}
	versionMatches := request.Candidate.Version != "" && original.Data.Agent.AgentVersion == request.Candidate.Version
	digestMatches := request.Candidate.AgentImageDigest != "" && original.Data.Agent.ImageDigest == request.Candidate.AgentImageDigest
	if !versionMatches && !digestMatches {
		return Unsupported(scenario)
	}
	baselineCounters, err := d.Counters(ctx)
	if err != nil || !completeCounters(baselineCounters) {
		return Unsupported(scenario)
	}
	replicas, err := d.agentScaler.Replicas(ctx)
	if err != nil || replicas < 1 {
		return Unsupported(scenario)
	}
	if d.isolationObserver == nil {
		return Unsupported(scenario)
	}
	preparedObservation, err := d.isolationObserver.Prepare(ctx, IsolationColdConnectionDisabled)
	if err != nil {
		return Unsupported(scenario)
	}
	defer func() {
		cleanupCtx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()
		cleanupCounters, counterErr := d.Counters(cleanupCtx)
		scaleErr := d.agentScaler.Scale(cleanupCtx, replicas)
		var readyErr error
		if scaleErr == nil {
			readyErr = d.agentScaler.WaitReady(cleanupCtx, replicas)
		}
		baselineErr := d.restoreBaseline(original, cleanupCounters)
		finalReplicas, replicasErr := d.agentScaler.Replicas(cleanupCtx)
		if counterErr != nil || scaleErr != nil || readyErr != nil || baselineErr != nil || replicasErr != nil || finalReplicas != replicas {
			markCleanupFailed(&result, scenario)
		}
	}()
	if d.agentScaler.Scale(ctx, 0) != nil {
		return Unsupported(scenario)
	}
	if d.agentScaler.WaitReady(ctx, 0) != nil {
		return Unsupported(scenario)
	}
	quietCounters, counterErr := d.Counters(ctx)
	if counterErr != nil || !completeCounters(quietCounters) {
		return Unsupported(scenario)
	}
	observation, observeErr := preparedObservation.Observe(ctx, d.noCallDwell)
	if observeErr != nil || !coldIsolationProved(observation, IsolationColdConnectionDisabled) || !d.countersUnchanged(ctx, quietCounters) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "state_applied", "process_absent", "listener_absent", "timer_absent", "dns_packets_zero", "tcp_packets_zero", "udp_packets_zero", "runtime_counters_unchanged", "downstream_counters_unchanged")
}

func (d *LiveDriver) centralDisabled(ctx context.Context, scenario string) (result ScenarioResult) {
	original, err := d.qualificationBaseline(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	baselineCounters, err := d.Counters(ctx)
	if err != nil || !completeCounters(baselineCounters) {
		return Unsupported(scenario)
	}
	if d.isolationObserver == nil {
		return Unsupported(scenario)
	}
	preparedObservation, err := d.isolationObserver.Prepare(ctx, IsolationOperationalWireDisabled)
	if err != nil {
		return Unsupported(scenario)
	}
	defer func() {
		cleanupCtx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()
		cleanupCounters, counterErr := d.Counters(cleanupCtx)
		baselineErr := d.restoreBaseline(original, cleanupCounters)
		if counterErr != nil || baselineErr != nil {
			markCleanupFailed(&result, scenario)
		}
	}()
	_, _ = d.setMode(ctx, "disabled", original.Data.Mode.Revision, false)
	_, statusErr := d.waitForStatus(ctx, func(status statusEnvelope) bool {
		return !status.Data.Mode.EmergencyDisabled && status.Data.Mode.Requested == "disabled" && status.Data.Mode.Authoritative == "disabled"
	})
	if statusErr != nil {
		return Unsupported(scenario)
	}
	result = isolationScenarioResult(scenario, true, false, false)
	if !d.waitForAgentMetrics(ctx, int(original.Data.Agent.DesiredReplicas)) {
		return result
	}
	quietCounters, counterErr := d.Counters(ctx)
	if counterErr != nil || !completeCounters(quietCounters) {
		return result
	}
	observation, observeErr := preparedObservation.Observe(ctx, d.noCallDwell)
	controlOnly := observeErr == nil && controlProtocolOnly(observation)
	countersUnchanged := controlOnly && d.countersUnchanged(ctx, quietCounters)
	return isolationScenarioResult(scenario, true, controlOnly, countersUnchanged)
}

func (d *LiveDriver) emergencyDisabled(ctx context.Context, scenario string) (result ScenarioResult) {
	original, err := d.qualificationBaseline(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	baselineCounters, err := d.Counters(ctx)
	if err != nil || !completeCounters(baselineCounters) {
		return Unsupported(scenario)
	}
	if d.isolationObserver == nil {
		return Unsupported(scenario)
	}
	preparedObservation, err := d.isolationObserver.Prepare(ctx, IsolationOperationalWireDisabled)
	if err != nil {
		return Unsupported(scenario)
	}
	defer func() {
		cleanupCtx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()
		cleanupCounters, counterErr := d.Counters(cleanupCtx)
		baselineErr := d.restoreBaseline(original, cleanupCounters)
		if counterErr != nil || baselineErr != nil {
			markCleanupFailed(&result, scenario)
		}
	}()
	_, _ = d.setMode(ctx, "disabled", original.Data.Mode.Revision, true)
	_, err = d.waitForStatus(ctx, func(status statusEnvelope) bool {
		return status.Data.Mode.EmergencyDisabled && status.Data.Mode.Authoritative == "disabled"
	})
	if err != nil {
		return Unsupported(scenario)
	}
	result = isolationScenarioResult(scenario, true, false, false)
	if !d.waitForAgentMetrics(ctx, int(original.Data.Agent.DesiredReplicas)) {
		return result
	}
	quietCounters, counterErr := d.Counters(ctx)
	if counterErr != nil || !completeCounters(quietCounters) {
		return result
	}
	observation, observeErr := preparedObservation.Observe(ctx, d.noCallDwell)
	controlOnly := observeErr == nil && controlProtocolOnly(observation)
	countersUnchanged := controlOnly && d.countersUnchanged(ctx, quietCounters)
	return isolationScenarioResult(scenario, true, controlOnly, countersUnchanged)
}

func isolationScenarioResult(scenario string, stateApplied, controlOnly, countersUnchanged bool) ScenarioResult {
	return ScenarioResult{
		Scenario: scenario,
		Passed:   stateApplied && controlOnly && countersUnchanged,
		Assertions: []Assertion{
			{Name: "state_applied", Passed: stateApplied},
			{Name: "control_protocol_only", Passed: controlOnly},
			{Name: "runtime_counters_unchanged", Passed: countersUnchanged},
			{Name: "downstream_counters_unchanged", Passed: countersUnchanged},
		},
	}
}

func markCleanupFailed(result *ScenarioResult, scenario string) {
	if result.Scenario == "" {
		*result = Unsupported(scenario)
		return
	}
	result.Passed = false
}

type modeEnvelope struct {
	Data struct {
		Requested         string `json:"requested"`
		Authoritative     string `json:"authoritative"`
		Revision          int64  `json:"revision"`
		EmergencyDisabled bool   `json:"emergency_disabled"`
	} `json:"data"`
}

func (d *LiveDriver) setMode(ctx context.Context, mode string, revision int64, emergency bool) (modeEnvelope, error) {
	var result modeEnvelope
	_, err := d.api(ctx, http.MethodPatch, "/api/v1/admin/charlie/mode/", d.adminToken, map[string]any{"mode": mode, "revision": revision, "emergency_disable": emergency}, &result)
	return result, err
}

func (d *LiveDriver) qualificationBaseline(ctx context.Context) (statusEnvelope, error) {
	status, err := d.status(ctx)
	if err != nil || !status.Data.Connection.Connected || status.Data.Mode.EmergencyDisabled || status.Data.Mode.Requested != "read_only" || status.Data.Mode.Authoritative != "read_only" || !status.Data.Connection.DisclosureAcknowledged || strings.TrimSpace(status.Data.Mode.DisclosureDigest) == "" || status.Data.Connection.DisclosureDigest != status.Data.Mode.DisclosureDigest {
		return statusEnvelope{}, errors.New("qualification requires an acknowledged read-only baseline")
	}
	return status, nil
}

func (d *LiveDriver) restoreMode(original statusEnvelope) error {
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	current, err := d.status(ctx)
	if err != nil {
		return err
	}
	if current.Data.Mode.EmergencyDisabled {
		if _, err = d.setMode(ctx, "disabled", current.Data.Mode.Revision, false); err != nil {
			return err
		}
		current, err = d.waitForStatus(ctx, func(status statusEnvelope) bool {
			return !status.Data.Mode.EmergencyDisabled
		})
		if err != nil {
			return errors.New("emergency latch cleanup failed")
		}
	}
	modeTransitioned := false
	if current.Data.Mode.Requested != original.Data.Mode.Requested || current.Data.Mode.Authoritative != original.Data.Mode.Authoritative {
		if _, err = d.setMode(ctx, original.Data.Mode.Requested, current.Data.Mode.Revision, false); err != nil {
			return err
		}
		modeTransitioned = true
	}
	restored := current
	if modeTransitioned {
		restored, err = d.waitForStatus(ctx, func(status statusEnvelope) bool {
			return restorationCoreMatches(status, original)
		})
	}
	if err != nil || !restorationCoreMatches(restored, original) {
		return errors.New("Charlie mode cleanup did not restore disclosure baseline")
	}
	if _, err = d.api(ctx, http.MethodPatch, "/api/v1/admin/charlie/mode/", d.adminToken, map[string]any{"acknowledge_disclosure_digest": original.Data.Connection.DisclosureDigest}, nil); err != nil {
		return err
	}
	final, err := d.status(ctx)
	if err != nil || final.Data.Mode.EmergencyDisabled || final.Data.Mode.Requested != original.Data.Mode.Requested || final.Data.Mode.Authoritative != original.Data.Mode.Authoritative || final.Data.Mode.DisclosureDigest != original.Data.Mode.DisclosureDigest || final.Data.Connection.DisclosureDigest != original.Data.Connection.DisclosureDigest || final.Data.Connection.Connected != original.Data.Connection.Connected || final.Data.Connection.DisclosureAcknowledged != original.Data.Connection.DisclosureAcknowledged || final.Data.Agent.DesiredReplicas != original.Data.Agent.DesiredReplicas || final.Data.Agent.ReadyReplicas != original.Data.Agent.ReadyReplicas {
		return errors.New("Charlie mode cleanup did not restore baseline")
	}
	return nil
}

func restorationCoreMatches(current, original statusEnvelope) bool {
	return !current.Data.Mode.EmergencyDisabled &&
		current.Data.Mode.Requested == original.Data.Mode.Requested && current.Data.Mode.Authoritative == original.Data.Mode.Authoritative &&
		current.Data.Mode.DisclosureDigest == original.Data.Mode.DisclosureDigest && current.Data.Connection.DisclosureDigest == original.Data.Connection.DisclosureDigest &&
		current.Data.Connection.Connected == original.Data.Connection.Connected &&
		current.Data.Agent.DesiredReplicas == original.Data.Agent.DesiredReplicas && current.Data.Agent.ReadyReplicas == original.Data.Agent.ReadyReplicas
}

func (d *LiveDriver) waitForStatus(ctx context.Context, accept func(statusEnvelope) bool) (statusEnvelope, error) {
	for {
		current, err := d.status(ctx)
		if err == nil && accept(current) {
			return current, nil
		}
		timer := time.NewTimer(d.proofPoll)
		select {
		case <-ctx.Done():
			timer.Stop()
			return statusEnvelope{}, ctx.Err()
		case <-timer.C:
		}
	}
}

func (d *LiveDriver) restoreBaseline(original statusEnvelope, counters CounterSet) error {
	if err := d.restoreMode(original); err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	after, err := d.Counters(ctx)
	if err != nil || !cleanupTransitionSafe(counters, after) {
		return errors.New("Charlie cleanup counters contained non-control work")
	}
	if !d.countersUnchanged(ctx, after) {
		return errors.New("Charlie cleanup counters did not match baseline")
	}
	return nil
}

func cleanupTransitionSafe(before, after CounterSet) bool {
	if !completeCounters(before) || !completeCounters(after) {
		return false
	}
	for _, key := range runtimeKeys {
		if key == "work_claims" {
			continue
		}
		if before.Runtime[key] != after.Runtime[key] {
			return false
		}
	}
	beforeClaims, afterClaims := before.Runtime["work_claims"], after.Runtime["work_claims"]
	if afterClaims < beforeClaims || afterClaims-beforeClaims > 4 {
		return false
	}
	return sameCounterKeys(before.Downstream, after.Downstream, downstreamKeys)
}

func (d *LiveDriver) waitForAgentMetrics(ctx context.Context, replicas int) bool {
	// A mode-ceiling change rolls the agent StatefulSet asynchronously. Give the
	// controller a bounded opportunity to observe the new template before
	// accepting a ready count, then require both readiness and complete metrics.
	stabilization := 5 * d.proofPoll
	if stabilization > 5*time.Second {
		stabilization = 5 * time.Second
	}
	timer := time.NewTimer(stabilization)
	select {
	case <-ctx.Done():
		timer.Stop()
		return false
	case <-timer.C:
	}
	if d.agentScaler != nil && d.agentScaler.WaitReady(ctx, replicas) != nil {
		return false
	}
	deadline := time.Now().Add(d.proofTimeout)
	for {
		counters, err := d.Counters(ctx)
		if err == nil && completeCounters(counters) {
			return true
		}
		if time.Now().After(deadline) {
			return false
		}
		poll := time.NewTimer(d.proofPoll)
		select {
		case <-ctx.Done():
			poll.Stop()
			return false
		case <-poll.C:
		}
	}
}

func (d *LiveDriver) countersUnchanged(ctx context.Context, before CounterSet) bool {
	if !completeCounters(before) {
		return false
	}
	deadline := time.Now().Add(d.noCallDwell)
	for {
		after, err := d.Counters(ctx)
		if err != nil || !completeCounters(after) || !sameCounterKeys(before.Runtime, after.Runtime, runtimeKeys) || !sameCounterKeys(before.Downstream, after.Downstream, downstreamKeys) {
			return false
		}
		remaining := time.Until(deadline)
		if remaining <= 0 {
			return true
		}
		wait := d.proofPoll
		if wait > remaining {
			wait = remaining
		}
		timer := time.NewTimer(wait)
		select {
		case <-ctx.Done():
			timer.Stop()
			return false
		case <-timer.C:
		}
	}
}

func (d *LiveDriver) readDenial(ctx context.Context, scenario string) ScenarioResult {
	if d.deniedToken == "" {
		return Unsupported(scenario)
	}
	before, err := d.Counters(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	status, requestErr := d.api(ctx, http.MethodGet, "/api/v1/charlie/sessions/", d.deniedToken, nil, nil)
	after, counterErr := d.Counters(ctx)
	if counterErr != nil || status != http.StatusForbidden || requestErr == nil || after.Runtime["tool_calls"] != before.Runtime["tool_calls"] || !sameCounterMap(before.Downstream, after.Downstream) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "authorization_denied", "product_calls_zero")
}

type discoveryQualificationEnvelope struct {
	Data struct {
		Scenario          string   `json:"scenario"`
		CandidateEnabled  bool     `json:"candidate_enabled"`
		AcceptedCount     int      `json:"accepted_count"`
		RejectedCount     int      `json:"rejected_count"`
		AcceptedNames     []string `json:"accepted_names"`
		DisclosureDigest  string   `json:"disclosure_digest"`
		CatalogBound      bool     `json:"catalog_bound"`
		MalformedRejected bool     `json:"malformed_rejected"`
	} `json:"data"`
}

func (d *LiveDriver) discoveryQualification(ctx context.Context, scenario, fixedCase string) ScenarioResult {
	before, err := d.Counters(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	var response discoveryQualificationEnvelope
	status, err := d.api(ctx, http.MethodPost, "/api/v1/admin/charlie/qualification/discovery/", d.adminToken, map[string]string{"scenario": fixedCase}, &response)
	proof := response.Data
	if err != nil || status != http.StatusOK || proof.Scenario != fixedCase || !proof.MalformedRejected {
		return Unsupported(scenario)
	}
	if fixedCase == "mixed_catalog" {
		if !proof.CandidateEnabled || proof.AcceptedCount != 2 || proof.RejectedCount != 1 || !proof.CatalogBound ||
			!regexp.MustCompile(`^[a-f0-9]{64}$`).MatchString(proof.DisclosureDigest) ||
			len(proof.AcceptedNames) != 2 || proof.AcceptedNames[0] != "astronomer.installation.summary" || proof.AcceptedNames[1] != "astronomer.management.workload_restart" {
			return Unsupported(scenario)
		}
		if !d.countersUnchanged(ctx, before) {
			return Unsupported(scenario)
		}
		return Passed(scenario, "valid_capability_retained", "malformed_capability_rejected", "catalog_bound")
	}
	if proof.CandidateEnabled || proof.AcceptedCount != 0 || proof.RejectedCount != 1 || proof.CatalogBound || proof.DisclosureDigest != "" || len(proof.AcceptedNames) != 0 || !d.countersUnchanged(ctx, before) {
		return Unsupported(scenario)
	}
	return Passed(scenario, "discovery_rejected", "integration_disabled", "product_calls_zero")
}

type alertDeliveryEnvelope struct {
	Data struct {
		FindingID            string `json:"finding_id"`
		FindingBlockCode     string `json:"finding_block_code"`
		FindingWorkflowState string `json:"finding_workflow_state"`
		DeliveryCount        int    `json:"delivery_count"`
		DedupeValid          bool   `json:"dedupe_valid"`
		Deliveries           []struct {
			DeliveryID       string     `json:"delivery_id"`
			FindingID        string     `json:"finding_id"`
			DeliveryKind     string     `json:"delivery_kind"`
			Status           string     `json:"status"`
			TemplateIdentity string     `json:"template_identity"`
			DeepLinkValid    bool       `json:"deep_link_valid"`
			ContentFree      bool       `json:"content_free"`
			AttemptCount     int32      `json:"attempt_count"`
			MaximumAttempts  int32      `json:"maximum_attempts"`
			CreatedAt        time.Time  `json:"created_at"`
			UpdatedAt        time.Time  `json:"updated_at"`
			DeliveredAt      *time.Time `json:"delivered_at"`
		} `json:"deliveries"`
	} `json:"data"`
}

func (d *LiveDriver) alertFixture(scenario string) AlertDeliveryFixture {
	switch scenario {
	case "diagnosis_alert":
		return d.fixtures.DiagnosisAlert
	case "approval_pending_alert":
		return d.fixtures.ApprovalPendingAlert
	case "approval_rejected_alert":
		return d.fixtures.ApprovalRejectedAlert
	case "approval_expired_alert":
		return d.fixtures.ApprovalExpiredAlert
	case "blocked_auto_alert":
		return d.fixtures.BlockedAutoAlert
	case "failed_precondition_alert":
		return d.fixtures.FailedPreconditionAlert
	case "failed_verification_alert":
		return d.fixtures.FailedVerificationAlert
	default:
		return AlertDeliveryFixture{}
	}
}

func (d *LiveDriver) alertDeliveryQualification(ctx context.Context, scenario string) ScenarioResult {
	fixture := d.alertFixture(scenario)
	findingID, findingErr := uuid.Parse(fixture.FindingID)
	deliveryID, deliveryErr := uuid.Parse(fixture.DeliveryID)
	if findingErr != nil || deliveryErr != nil || findingID == uuid.Nil || deliveryID == uuid.Nil || strings.TrimSpace(fixture.ExpectedBlockCode) == "" || strings.TrimSpace(fixture.ExpectedWorkflowState) == "" {
		return Unsupported(scenario)
	}
	before, err := d.Counters(ctx)
	if err != nil {
		return Unsupported(scenario)
	}
	var first, second alertDeliveryEnvelope
	query := url.Values{"finding_id": []string{findingID.String()}}
	if status, callErr := d.apiQuery(ctx, http.MethodGet, "/api/v1/admin/charlie/alert-deliveries/", query, d.adminToken, nil, &first); callErr != nil || status != http.StatusOK || !validAlertDeliveryProof(first, fixture) {
		return Unsupported(scenario)
	}
	if !d.countersUnchanged(ctx, before) {
		return Unsupported(scenario)
	}
	if status, callErr := d.apiQuery(ctx, http.MethodGet, "/api/v1/admin/charlie/alert-deliveries/", query, d.adminToken, nil, &second); callErr != nil || status != http.StatusOK || !validAlertDeliveryProof(second, fixture) || !sameAlertDeliveryProof(first, second) {
		return Unsupported(scenario)
	}
	if !d.countersUnchanged(ctx, before) {
		return Unsupported(scenario)
	}
	names := []string{"one_alert", "valid_deep_link", "content_free"}
	if scenario == "failed_verification_alert" {
		if fixture.ExpectedBlockCode != "verification_failed" {
			return Unsupported(scenario)
		}
		names = append(names, "block_code_verification_failed")
	}
	return Passed(scenario, names...)
}

func validAlertDeliveryProof(value alertDeliveryEnvelope, fixture AlertDeliveryFixture) bool {
	proof := value.Data
	if proof.FindingID != fixture.FindingID || proof.FindingBlockCode != fixture.ExpectedBlockCode || proof.FindingWorkflowState != fixture.ExpectedWorkflowState || proof.DeliveryCount != 1 || !proof.DedupeValid || len(proof.Deliveries) != 1 {
		return false
	}
	delivery := proof.Deliveries[0]
	deliveredAtValid := delivery.DeliveredAt == nil || (!delivery.DeliveredAt.IsZero() && !delivery.DeliveredAt.Before(delivery.CreatedAt))
	return delivery.DeliveryID == fixture.DeliveryID && delivery.FindingID == fixture.FindingID && delivery.DeliveryKind == "initial" &&
		delivery.TemplateIdentity == "charlie.finding.initial/v1" && delivery.DeepLinkValid && delivery.ContentFree &&
		delivery.AttemptCount >= 0 && delivery.MaximumAttempts >= 1 && delivery.MaximumAttempts <= 20 && delivery.AttemptCount <= delivery.MaximumAttempts &&
		!delivery.CreatedAt.IsZero() && !delivery.UpdatedAt.IsZero() && !delivery.UpdatedAt.Before(delivery.CreatedAt) &&
		deliveredAtValid && contains([]string{"queued", "delivering", "retry", "delivered", "suppressed", "dead"}, delivery.Status)
}

func sameAlertDeliveryProof(a, b alertDeliveryEnvelope) bool {
	left, right := a.Data, b.Data
	if left.FindingID != right.FindingID || left.FindingBlockCode != right.FindingBlockCode || left.FindingWorkflowState != right.FindingWorkflowState || left.DeliveryCount != right.DeliveryCount || left.DedupeValid != right.DedupeValid || len(left.Deliveries) != 1 || len(right.Deliveries) != 1 {
		return false
	}
	l, r := left.Deliveries[0], right.Deliveries[0]
	return l.DeliveryID == r.DeliveryID && l.FindingID == r.FindingID && l.DeliveryKind == r.DeliveryKind && l.Status == r.Status && l.TemplateIdentity == r.TemplateIdentity && l.DeepLinkValid == r.DeepLinkValid && l.ContentFree == r.ContentFree && l.AttemptCount == r.AttemptCount && l.MaximumAttempts == r.MaximumAttempts && l.CreatedAt.Equal(r.CreatedAt) && l.UpdatedAt.Equal(r.UpdatedAt) && sameOptionalTime(l.DeliveredAt, r.DeliveredAt)
}

func sameOptionalTime(a, b *time.Time) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	return a.Equal(*b)
}

func sameCounterMap(before, after map[string]uint64) bool {
	return sameCounterKeys(before, after, downstreamKeys)
}

func sameCounterKeys(before, after map[string]uint64, keys []string) bool {
	for _, key := range keys {
		if before[key] != after[key] {
			return false
		}
	}
	return true
}

func (d *LiveDriver) api(ctx context.Context, method, path, token string, body any, output any) (int, error) {
	return d.apiQuery(ctx, method, path, nil, token, body, output)
}

func (d *LiveDriver) apiQuery(ctx context.Context, method, path string, query url.Values, token string, body any, output any) (int, error) {
	endpoint := d.base.ResolveReference(&url.URL{Path: path, RawQuery: query.Encode()})
	var reader io.Reader
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return 0, err
		}
		reader = bytes.NewReader(encoded)
	}
	request, err := http.NewRequestWithContext(ctx, method, endpoint.String(), reader)
	if err != nil {
		return 0, err
	}
	request.Header.Set("Authorization", "Bearer "+token)
	request.Header.Set("Accept", "application/json")
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	response, err := d.client.Do(request)
	if err != nil {
		return 0, errors.New("Astronomer API unavailable")
	}
	defer func() { _ = response.Body.Close() }()
	contents, readErr := io.ReadAll(io.LimitReader(response.Body, (1<<20)+1))
	if readErr != nil || len(contents) > 1<<20 {
		return response.StatusCode, errors.New("Astronomer API response exceeded its bound")
	}
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return response.StatusCode, fmt.Errorf("Astronomer API returned HTTP %d", response.StatusCode)
	}
	if output != nil {
		decoder := json.NewDecoder(bytes.NewReader(contents))
		if err := decoder.Decode(output); err != nil {
			return response.StatusCode, errors.New("Astronomer API response invalid")
		}
		if decoder.Decode(&struct{}{}) != io.EOF {
			return response.StatusCode, errors.New("Astronomer API response contains trailing data")
		}
	}
	return response.StatusCode, nil
}

type metricSample struct {
	name   string
	labels map[string]string
	value  uint64
}

var metricNamePattern = regexp.MustCompile(`^[a-zA-Z_:][a-zA-Z0-9_:]*$`)
var samplePattern = regexp.MustCompile(`^([a-zA-Z_:][a-zA-Z0-9_:]*)(?:\{([^}]*)\})?\s+([^\s]+)`)
var labelPattern = regexp.MustCompile(`([a-zA-Z_][a-zA-Z0-9_]*)="((?:\\.|[^"])*)"`)

func parsePrometheus(reader io.Reader) ([]metricSample, error) {
	scanner := bufio.NewScanner(reader)
	scanner.Buffer(make([]byte, 64<<10), 1<<20)
	result := []metricSample{}
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		match := samplePattern.FindStringSubmatch(line)
		if match == nil {
			continue
		}
		value, err := strconv.ParseFloat(match[3], 64)
		if err != nil || value < 0 || value > 9_007_199_254_740_991 || math.Trunc(value) != value {
			continue
		}
		labels := map[string]string{}
		for _, item := range labelPattern.FindAllStringSubmatch(match[2], -1) {
			labels[item[1]] = item[2]
		}
		result = append(result, metricSample{name: match[1], labels: labels, value: uint64(value)})
	}
	return result, scanner.Err()
}

func sumMetric(samples []metricSample, name string, include func(map[string]string) bool) (uint64, bool) {
	var total uint64
	found := false
	for _, sample := range samples {
		if sample.name == name && (include == nil || include(sample.labels)) {
			if total > 9_007_199_254_740_991-sample.value {
				return 0, false
			}
			total += sample.value
			found = true
		}
	}
	return total, found
}
func metricFamilyPresent(samples []metricSample, name string) bool {
	for _, s := range samples {
		if s.name == name {
			return true
		}
	}
	return false
}
func contains[T comparable](values []T, wanted T) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}
