-- 141 only ADDS the `proxy` verb where the catalog already intended it (032
-- seeds pods:proxy, 098 seeds services:proxy), so the rows it touches end up
-- byte-identical to a fresh install's. Stripping the verb on the way down
-- would therefore corrupt roles that shipped with it — 032/098's own downs
-- delete their rows outright, which is the symmetric behaviour here only if we
-- can tell "we added this" from "032 seeded it", and we cannot.
--
-- Rolling back the code re-widens the proxy subresource to the target's generic
-- read/update verb, at which point `pods:proxy` / `services:proxy` are inert
-- again exactly as they were before this migration. Leaving them in place is
-- the safe direction: no role gains anything the pre-141 catalog did not
-- already grant on a fresh install.
SELECT 1;
