-- Give chart-repository credentials a Fernet envelope (P1, security).
--
-- `helm_repositories.auth_config` has been bare JSONB since 001. It is the
-- only place a private ChartMuseum / Artifactory / Nexus / OCI registry
-- credential is kept, and every one of them — username, password, bearer
-- token — has been sitting in the clear in the platform database, in
-- `pg_dump` output, and in every backup taken of either. Migration 144 named
-- this explicitly and deliberately left it alone; this is that follow-up.
--
-- The shape is the one ~8 other tables in this schema already use for exactly
-- this (`*_encrypted TEXT NOT NULL DEFAULT ''` holding a Fernet token — see
-- 020 backup_storage_configs, 043 user_totp_enrollments, 047 smtp_settings,
-- 048 webhook_subscriptions, 095 cluster_registry_configs, 134 dex_settings).
-- Choosing a sibling TEXT column rather than re-typing auth_config in place is
-- what makes the upgrade survivable, and it is also what makes the column
-- sweepable: cmd/keyrotate rewrites ciphertext columns, and its build-time
-- completeness guard (cmd/keyrotate/coverage_test.go) only recognises a column
-- whose name contains "encrypted" and whose type is TEXT/BYTEA/VARCHAR. A
-- Fernet token hidden inside JSONB would be invisible to that guard and would
-- become permanently undecryptable on the next key rotation.
--
-- Split of responsibility between the two columns after this migration:
--
--   auth_config_encrypted  Fernet token over the COMPLETE auth_config JSON
--                          document, including the secret fields. Authoritative
--                          whenever it is non-empty.
--   auth_config            the non-secret projection of the same document —
--                          username, charts, allow_catalog. Secret-valued keys
--                          (password / token / bearer / secret / client_secret /
--                          access_token / refresh_token) are removed from it,
--                          not blanked, so no secret-shaped value survives in
--                          the clear anywhere in this table.
--
-- Readers disambiguate on the COLUMN, never on the bytes: a non-empty
-- auth_config_encrypted means "decrypt this"; an empty one means "this row
-- predates the envelope, auth_config is still the whole document". There is no
-- Fernet-vs-JSON sniffing heuristic to get wrong, and no ambiguity for a row
-- whose plaintext JSON happens to start with 'g'.
--
-- ── The upgrade window ─────────────────────────────────────────────────────
--
-- A migration cannot call the Go Fernet encryptor, so this file cannot convert
-- existing rows; it only adds the column. Existing rows therefore keep working
-- unchanged (auth_config_encrypted = '' → auth_config is authoritative) until
-- the already-registered `security:migrate_plaintext_credentials` task
-- (internal/worker/tasks/plaintext_credential_migration.go, @every 6h in both
-- the server and the dedicated worker) seals them: it encrypts the document
-- into auth_config_encrypted and strips the secret keys from auth_config, with
-- a CAS on auth_config_encrypted = '' so two schedulers cannot clobber each
-- other. That task is where the two other legacy-plaintext credential columns
-- in this schema (backup_storage_configs.access_key/secret_key,
-- cluster_registry_configs.registry_password) are already converted, so this
-- adds a third case to an existing mechanism rather than inventing one.
--
-- The transition therefore ends at most 6h after upgrade, or immediately for
-- any repository an operator saves through the API in the meantime — the
-- create/update handlers seal on every write. It never ends on a deployment
-- with no ASTRONOMER_ENCRYPTION_KEY, which is a supported development
-- configuration only: config.ValidateProductionSecurity already refuses to
-- start a production server without a working encryptor.
--
-- ── What this deliberately does NOT do ─────────────────────────────────────
--
-- It does not UPDATE, re-type or drop auth_config. Every existing row keeps
-- its exact current contents and keeps authenticating against its repository
-- across the upgrade. Encrypting on the write path while leaving the read path
-- unable to read a pre-upgrade row is the failure mode that turns a security
-- fix into an outage, and it is why 144 declined to do this inline.
--
-- It does not add NOT NULL/CHECK constraints coupling the two columns. During
-- the window both "sealed" (encrypted non-empty, secrets stripped) and "legacy"
-- (encrypted empty, secrets inline) are valid states, and a constraint that
-- admitted only one of them would either reject the pre-seal state or reject
-- the post-seal state depending on which way it was written.
--
-- It does not fix monitoring_backends.auth_config (002_monitoring.up.sql:9),
-- which is the SAME finding in the same shape: bare `JSONB NOT NULL DEFAULT
-- '{}'`, written by an operator-facing handler (UpdateBackendConfig), and read
-- as a live credential by internal/monitoring/prometheus.go to authenticate to
-- Thanos/Prometheus/Alertmanager. It is named here so it cannot be lost, not
-- excused.
--
-- It is a separate unit of work rather than a wider blast radius on this one
-- because that column is not only a credential. It doubles as an operator
-- config bag — `operationPolicies` (retry/rollback) and
-- `sharedAlertingAssets.hashes` — and at least four handler and worker paths
-- do a read-modify-write on it to update those non-secret keys
-- (internal/handler/monitoring.go, internal/handler/alerting.go,
-- internal/worker/tasks/monitoring_reconcile.go,
-- internal/worker/tasks/alert_evaluation.go). Every one of those becomes a
-- resolve → mutate → re-seal, and any one of them missed silently drops the
-- monitoring credential on an unrelated policy edit. Bundling that risk into
-- this migration would make both changes harder to review and to revert, and
-- the failure mode is exactly the half-done encryption this file is written to
-- avoid. helm_repositories has no such mixed-use readers, which is why it can
-- be done cleanly on its own.
--
-- It does not encrypt the non-secret fields out of reach. charts,
-- allow_catalog and username stay readable in auth_config on purpose: the
-- catalog API surfaces them (redacted) so the UI can show which charts an OCI
-- repository is pinned to and whether a credential is configured at all, and
-- making that require a successful decrypt would mean a key problem also
-- blanks the repository list.

ALTER TABLE helm_repositories
    ADD COLUMN IF NOT EXISTS auth_config_encrypted TEXT NOT NULL DEFAULT '';
