-- Reverse of 145: drop the chart-repository credential envelope.
--
-- This is lossy and it is lossy on purpose. Once the sealing task has run, the
-- secret fields live ONLY in auth_config_encrypted; auth_config holds the
-- non-secret projection. Dropping the column discards those credentials, and a
-- repository that had a password will fall back to unauthenticated fetches and
-- start reporting 401s in last_sync_error until an operator re-enters it.
--
-- The alternative — decrypting back into auth_config on the way down — is not
-- available here: a migration has no access to the Fernet key, so it cannot
-- reverse the transform it did not perform. Re-entering the credential is the
-- documented rollback step; it is a small, visible, per-repository action,
-- whereas silently writing something wrong into auth_config would be neither.
--
-- Rolling back the CODE alone (without this migration) is safe ONLY for rows
-- the sealing task has not yet touched. security:migrate_plaintext_credentials
-- runs @every 6h, so that window is short: once a row is sealed its auth_config
-- has the secret keys REMOVED, and an older binary — which knows only that
-- column — sends no credential at all. Every private chart repository then
-- syncs unauthenticated, and the only operator-visible signal is 401s
-- accumulating in last_sync_error. After sealing, a code-only rollback means
-- re-entering the credentials, or dropping the column via this migration and
-- re-entering them; there is no version of it that recovers them by itself.
--
-- Do not edit chart-repository credentials mid-rollout while both binaries are
-- live. An old pod's UpdateHelmRepository does not touch auth_config_encrypted,
-- so a password changed through an old pod lands in auth_config while new pods
-- keep decrypting the stale envelope: the change appears to have been accepted
-- and has not taken effect.

ALTER TABLE helm_repositories DROP COLUMN IF EXISTS auth_config_encrypted;
