-- Give the monitoring-backend credential a Fernet envelope (P1, security).
--
-- `monitoring_backends.auth_config` has been bare JSONB since 002. It holds
-- the bearer token or basic-auth password this platform uses to authenticate
-- to Thanos / Prometheus / Alertmanager (internal/monitoring/prometheus.go is
-- the live reader), and it has been sitting in the clear in the platform
-- database, in `pg_dump` output, and in every backup taken of either.
--
-- This is the same finding migration 145 fixed for helm_repositories, named in
-- 145's own "does NOT do" block and in docs/secret-column-inventory.md as
-- deliberately deferred. This is that follow-up, and it uses the identical
-- shape: a sibling `*_encrypted TEXT NOT NULL DEFAULT ''` holding a Fernet
-- token, the shape ~9 other tables in this schema already use (020
-- backup_storage_configs, 043 user_totp_enrollments, 047 smtp_settings, 048
-- webhook_subscriptions, 095 cluster_registry_configs, 134 dex_settings, 145
-- helm_repositories).
--
-- A sibling TEXT column rather than re-typing auth_config in place is what
-- makes the upgrade survivable, and it is also the only shape cmd/keyrotate's
-- completeness guard (cmd/keyrotate/coverage_test.go) can see: it recognises a
-- column whose name contains "encrypted" and whose type is TEXT/BYTEA/VARCHAR.
-- A Fernet token hidden inside the existing JSONB would be invisible to that
-- guard and would become permanently undecryptable on the next key rotation.
--
-- ── Split of responsibility between the two columns ────────────────────────
--
--   auth_config_encrypted  Fernet token over the COMPLETE auth_config JSON
--                          document, including the credential. Authoritative
--                          whenever it is non-empty.
--   auth_config            the non-secret projection of the same document.
--
-- The projection is an ALLOW-LIST, the opposite direction from 145. 145 could
-- strip a deny-list of secret key names because helm_repositories.auth_config
-- IS a credential with a couple of known non-secret extras. This column is the
-- inverse: a fixed set of structural keys written by this codebase, wrapped
-- around an unbounded operator-authored credential portion (the request DTO
-- takes `authConfig` as free-form JSON and stores whatever arrives). A
-- deny-list would leak any key an operator names something we did not think of.
--
-- The five keys that stay in the clear, and every Go reader of each:
--
--   operationPolicies     retry/auto-rollback policy —
--                         resolveAutoRollbackPolicy, resolveMaxRetryAttempts,
--                         monitoringBackendPayload (handler/monitoring.go)
--   sharedThanos          shared Thanos deploy metadata + status —
--                         sharedThanosMetadata (handler/monitoring.go),
--                         reconcileMonitoringBackend (worker),
--                         syncSharedAlertingAssets (handler/alerting.go)
--   sharedAlertmanager    shared Alertmanager deploy metadata + status —
--                         sharedAlertmanagerMetadata (handler/monitoring.go)
--   sharedAlertingAssets  rendered rule/routing/silence ConfigMap hashes —
--                         GetSharedThanosStatus, GetSharedAlertmanagerStatus
--   status                backend health — the monitoring summary
--
-- Everything else is a credential and is sealed. Nothing SQL-queries into this
-- column: the only three statements over it are `SELECT *`,
-- `SELECT mb.auth_config` and `auth_config = EXCLUDED.auth_config`. There is
-- no `->>`, no `@>`, and no expression index, so moving the credential keys
-- out of the projection cannot break a query — only a Go reader, and those are
-- listed above. (Contrast helm_repositories, where the sealing sweep's own
-- predicate does `auth_config ->> secret_key`, which is why 145's split had to
-- be expressible in SQL key-by-key.)
--
-- Readers disambiguate on the COLUMN, never on the bytes: a non-empty
-- auth_config_encrypted means "decrypt this"; an empty one means "this row
-- predates the envelope, auth_config is still the whole document". There is no
-- Fernet-vs-JSON sniffing heuristic to get wrong.
--
-- ── The upgrade window ─────────────────────────────────────────────────────
--
-- A migration cannot call the Go Fernet encryptor, so this file cannot convert
-- existing rows; it only adds the column. Existing rows keep working unchanged
-- (auth_config_encrypted = '' → auth_config is authoritative) until the
-- already-registered `security:migrate_plaintext_credentials` task
-- (internal/worker/tasks/plaintext_credential_migration.go, @every 6h in both
-- the server and the dedicated worker) seals them. That task already converts
-- backup_storage_configs, cluster_registry_configs and (since 145)
-- helm_repositories; this adds a fourth case to an existing mechanism rather
-- than inventing one. The CAS on auth_config_encrypted = '' keeps the two
-- schedulers from clobbering each other.
--
-- The transition therefore ends at most 6h after upgrade, or immediately when
-- an operator saves the backend through the API. It never ends on a deployment
-- with no ASTRONOMER_ENCRYPTION_KEY, which is a supported development
-- configuration only: config.ValidateProductionSecurity already refuses to
-- start a production server without a working encryptor.
--
-- ── What this deliberately does NOT do ─────────────────────────────────────
--
-- It does not UPDATE, re-type or drop auth_config. Every existing row keeps
-- its exact current contents and keeps authenticating across the upgrade.
-- Encrypting on the write path while leaving the read path unable to read a
-- pre-upgrade row is the failure mode that turns a security fix into an
-- outage.
--
-- It does not add NOT NULL/CHECK constraints coupling the two columns. During
-- the window both "sealed" (encrypted non-empty, credential stripped out of
-- the projection) and "legacy" (encrypted empty, credential inline) are valid
-- states, and a constraint admitting only one of them would reject the other.
--
-- It does not split internal/handler/monitoring.go, whose 3.9k lines carry
-- five of the sites this change touches. That file badly wants splitting and
-- is tracked separately; mixing a file move into a credential change would
-- make it impossible to review either.
--
-- It does not change what the monitoring:read API returns. GetBackendConfig
-- already answered with the non-secret projection plus the key NAMES; those key
-- names now come from the resolved document instead of the raw column, so the
-- "configured, not disclosed" signal survives sealing. The ciphertext is never
-- rendered into a response.
--
-- It DOES change one thing on the write path, and this is the part to review.
-- The PUT/POST response used to echo the caller's authConfig back unredacted,
-- which was safe only because the handler was a pure writer: the document it
-- rendered was exactly what the caller had just sent. Making it a
-- read-modify-write broke that — the rendered document became the caller's
-- input MERGED OVER THE STORED ONE, so a request that omitted authConfig
-- rendered the stored credential, turning monitoring:update and
-- monitoring:create into ways to READ a credential the holder was never given.
-- There is now one redaction shared by every response and no write variant.
-- The operator-visible cost is nil: operationPolicies and the credential key
-- names are still returned, so a successful save does not read as a dropped
-- credential.
--
-- It does not encrypt the config bag out of reach. The five keys above stay
-- readable so a key problem degrades authentication only, rather than also
-- blanking the shared-stack status pages and the retry policy the operation
-- reconciler needs to decide whether to roll back.

ALTER TABLE monitoring_backends
    ADD COLUMN IF NOT EXISTS auth_config_encrypted TEXT NOT NULL DEFAULT '';
