package charlie

// CapabilitySource is the only subsystem an Astronomer MCP adapter may read or
// mutate. No value represents a downstream tunnel or downstream Kubernetes API.
type CapabilitySource string

const (
	SourceAstronomerDatabase   CapabilitySource = "astronomer_database"
	SourceAstronomerServer     CapabilitySource = "astronomer_server_telemetry"
	SourceManagementKubernetes CapabilitySource = "management_kubernetes"
	SourceManagementArgo       CapabilitySource = "management_argocd"
	SourceManagementQueue      CapabilitySource = "management_queue"
)

type CapabilityDescriptor struct {
	Name             string
	Description      string
	SchemaVersion    string
	Effect           Effect
	Risk             string
	TargetBounds     string
	Impact           string
	Reversibility    string
	Rollback         string
	Source           CapabilitySource
	RBACResource     string
	RBACVerb         string
	AcceptedFields   []string
	MaxResponseBytes int
	TimeoutSeconds   int
	// Destructive is a product-owned catalog fact, never a model-supplied risk
	// label. Destructive or irreversible operations are denied in every Charlie
	// mode; v1 intentionally publishes none.
	Destructive          bool
	AutoEligible         bool
	Idempotent           bool
	RequiresPrecondition bool
	RequiresVerification bool
	ManagedTargetAccess  bool
}

func ReadCapabilityCatalog() []CapabilityDescriptor {
	const max = 64 << 10
	return []CapabilityDescriptor{
		readDesc("astronomer.system.health",
			"Bounded concurrent management-plane health assessment across installation, Kubernetes runtime, database, Redis, queues, agent fleet, tunnels, backups, TLS, alerting, Argo CD, Charlie, and security posture. Use this once as the first tool for broad health/status requests, then run only targeted follow-up tools for degraded checks.",
			SourceAstronomerServer, "*", nil, max),
		readDesc("astronomer.installation.summary",
			"Installation identity: installation_id, platform name, astronomer_version, chart_version, namespace, release, kubernetes_version, kubernetes_distribution, and management component health. Use for 'what version of k8s/astronomer are we running'.",
			SourceAstronomerServer, "settings", nil, max),
		readDesc("astronomer.installation.readiness",
			"Boolean readiness of management plane: database, schema version/dirty, queues, and component ready/available counts.",
			SourceAstronomerServer, "settings", nil, max),
		readDesc("astronomer.installation.configuration",
			"Read allowlisted non-secret configuration keys only (keys array). Never returns credentials or raw env.",
			SourceAstronomerDatabase, "settings", []string{"keys"}, max),
		readDesc("astronomer.management.workloads",
			"List Astronomer-owned Deployments and StatefulSets in the install namespace with desired/ready/available replicas, pod restart/OOM/unready counts. Not a full-cluster list.",
			SourceManagementKubernetes, "workloads", []string{"page", "page_size"}, max),
		readDesc("astronomer.management.workload_get",
			"Get one owned workload by workload=deployment|statefulset/<name> including replica and pod health summary.",
			SourceManagementKubernetes, "workloads", []string{"workload"}, max),
		readDesc("astronomer.management.pods",
			"List Astronomer-owned Pods with phase, ready, restarts, node, containers, and owner workload. Optional component prefix filter and phase filter. Prefer this for 'what pods are running / crashlooping'.",
			SourceManagementKubernetes, "workloads", []string{"component", "phase", "page", "page_size"}, max),
		readDesc("astronomer.management.rollout_status",
			"Rollout status for one owned deployment or statefulset: desired/ready/updated/available, generation lag, progressing/available conditions, and whether the rollout is complete or stuck.",
			SourceManagementKubernetes, "workloads", []string{"workload"}, max),
		readDesc("astronomer.management.events",
			"Recent Kubernetes Warning/Normal events for owned components. Filter by component name, since duration, and limit.",
			SourceManagementKubernetes, "workloads", []string{"component", "since", "limit"}, max),
		readDesc("astronomer.management.pod_logs",
			"Bounded redacted log tail for one owned pod and container (default 200 lines, hard size bound). Returns requested/returned line counts and a truncation marker; newest evidence is retained when compaction is required. Requires pod and container names from pods/workloads tools first.",
			SourceManagementKubernetes, "logging", []string{"pod", "container", "lines"}, max),
		readDesc("astronomer.management.nodes",
			"Management-plane nodes: server_version, kubelet_version, OS, architecture, capacity, and Ready/pressure conditions.",
			SourceManagementKubernetes, "nodes", nil, max),
		readDesc("astronomer.management.storage",
			"Owned PersistentVolumeClaims phase, capacity, and access modes in the install namespace.",
			SourceManagementKubernetes, "storage", nil, max),
		readDesc("astronomer.management.network",
			"Owned Services and NetworkPolicies in the install namespace (ports, types, selectors).",
			SourceManagementKubernetes, "network_policies", nil, max),
		readDesc("astronomer.management.resource_usage",
			"Astronomer-owned management pod CPU and memory usage, requests, limits, restart counts, and node placement. Live usage is marked unavailable when metrics-server cannot be read.",
			SourceManagementKubernetes, "monitoring", []string{"component", "page", "page_size"}, max),
		readDesc("astronomer.management.jobs",
			"List Astronomer-owned management Jobs and CronJobs with schedules, suspension, active/succeeded/failed counts, conditions, and latest scheduling time.",
			SourceManagementKubernetes, "workloads", []string{"status", "page", "page_size"}, max),
		readDesc("astronomer.management.job_get",
			"Inspect one Astronomer-owned management Job or CronJob by kind/name with lifecycle conditions and bounded pod summary; job environment and secret values are withheld.",
			SourceManagementKubernetes, "workloads", []string{"job"}, max),
		readDesc("astronomer.management.daemonsets",
			"List Astronomer-owned management DaemonSets with desired/current/ready/available/unavailable scheduling and rollout generation state.",
			SourceManagementKubernetes, "workloads", nil, max),
		readDesc("astronomer.management.availability",
			"Management-plane availability controls: HorizontalPodAutoscalers and PodDisruptionBudgets in the Astronomer namespace with safe scaling and disruption status.",
			SourceManagementKubernetes, "workloads", nil, max),
		readDesc("astronomer.management.ingress",
			"Management-plane Ingress and EndpointSlice readiness metadata including hosts, TLS presence, addresses, endpoint readiness, ports, and fixed backend references; no secret material is returned. EndpointSlice permission/API failures are reported as a fixed partial-visibility code without discarding ingress inventory.",
			SourceManagementKubernetes, "ingresses", nil, max),
		readDesc("astronomer.database.health",
			"Postgres health for the Astronomer database (connectivity, size, recovery state).",
			SourceAstronomerServer, "monitoring", nil, max),
		readDesc("astronomer.database.performance",
			"Postgres connection, transaction, lock-wait, replication-lag, database-size, and pool-saturation diagnostics from fixed management-plane queries. SQL text and query parameters are never returned.",
			SourceAstronomerServer, "monitoring", nil, max),
		readDesc("astronomer.redis.health",
			"Management Redis connectivity, command latency, memory pressure, eviction, persistence, replication-role, and client-health metrics from a fixed safe field allowlist. Keys and values are never read.",
			SourceAstronomerServer, "monitoring", nil, max),
		readDesc("astronomer.runtime.http_health",
			"Astronomer server HTTP request totals by status class, in-flight request count, and aggregate request duration from bounded in-process metrics without request paths, headers, or bodies.",
			SourceAstronomerServer, "monitoring", nil, max),
		readDesc("astronomer.runtime.process_health",
			"Astronomer server process CPU, resident memory, heap, goroutine, file-descriptor, garbage-collection, and uptime metrics from the in-process Prometheus registry.",
			SourceAstronomerServer, "monitoring", nil, max),
		readDesc("astronomer.security.key_status",
			"Global-administrator live key-rotation posture for Astronomer encryption and JWT signing keys, including loaded-key counts and development-sentinel identifiers. Key material is never returned.",
			SourceAstronomerServer, "*", nil, max),
		readDesc("astronomer.delivery.summary",
			"Global-administrator aggregate of management-plane outbound delivery health across email, webhook, SIEM, and notification channels, including queue depth and terminal failures without message bodies, recipients, endpoints, or credentials.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.delivery.email_health",
			"SMTP configuration posture and email-dispatch lifecycle counts, attempts, and queue age. Addresses, subjects, bodies, usernames, passwords, and raw errors are withheld.",
			SourceAstronomerDatabase, "settings", nil, max),
		readDesc("astronomer.delivery.webhook_health",
			"Webhook subscription and delivery health with enabled, encrypted-secret, insecure-transport, queue, failure, and retry counts. URLs, headers, payloads, response bodies, and raw errors are withheld.",
			SourceAstronomerDatabase, "settings", nil, max),
		readDesc("astronomer.delivery.siem_health",
			"SIEM forwarder health with transport, queue, dispatch, drop, credential, and TLS-posture counts. Endpoints, authentication, certificates, event payloads, and raw errors are withheld.",
			SourceAstronomerDatabase, "audit_logs", nil, max),
		readDesc("astronomer.logging.health",
			"Logging configuration health with output and pipeline counts, enabled state, and controller backlog summary; configuration documents and credentials are withheld.",
			SourceAstronomerDatabase, "logging", nil, max),
		readDesc("astronomer.monitoring.health",
			"Monitoring and dashboard data-source posture with backend types, default selection, endpoint presence, credential sealing, TLS verification, and alert evaluation counts; queries and credentials are withheld.",
			SourceAstronomerDatabase, "monitoring", nil, max),
		readDesc("astronomer.identity.health",
			"Global-administrator management identity health across local accounts, SSO, Dex connectors/runtime generations, group mappings, and SCIM token use. User identities, claims, token values, and connector configuration are withheld.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.authentication.health",
			"Global-administrator authentication-session and account-recovery posture, including active/expired SSO sessions, TOTP enrollment and recovery-code coverage, and password-reset token lifecycle. Identities, tokens, labels, providers, and secret material are withheld.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.rbac.health",
			"Management-plane RBAC inventory and integrity counts for global, cluster-metadata, and project scopes, including user/group bindings and invalid subject state without identities or permission documents.",
			SourceAstronomerDatabase, "rbac", nil, max),
		readDesc("astronomer.security.posture",
			"Global-administrator management-plane security posture covering credential sealing, account hardening, token expiry, Vault health, TLS verification exceptions, and compliance baseline state without exposing secrets or security documents.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.external_integrations.health",
			"Global-administrator credential-integration posture for project cloud credentials and Vault connections, including provider, sealing, materialization, drift/failure, health, and TLS-verification counts. Credential names, targets, endpoints, and values are withheld.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.governance.health",
			"Global-administrator management governance posture covering maintenance policy, deferred work, quota enforcement, compliance baselines, read-audit policy, alert inhibition, and network-policy template counts without policy documents or selectors.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.policy_engine.health",
			"Control-plane policy-engine posture with configured thresholds, active silences, alert lifecycle, and stale silence counts. Reasons, messages, detail documents, and user identities are withheld.",
			SourceAstronomerDatabase, "alerts", nil, max),
		readDesc("astronomer.templates.health",
			"Global-administrator template and baseline reconciliation posture across cluster, pod-security, network-policy, and compliance templates. Specifications, selectors, namespaces, cluster targets, and raw errors are withheld.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.configuration.overview",
			"Registered platform-setting overrides with key, JSON type, update time, and safe scalar value or configured/size metadata. Secret-like and content-bearing strings are never returned.",
			SourceAstronomerDatabase, "settings", nil, max),
		readDesc("astronomer.tenancy.summary",
			"Global-administrator management tenancy inventory for users, projects, cluster registration metadata, environments, lifecycle states, and quota-plan assignment. It does not inspect managed Kubernetes resources.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.registration.health",
			"Astronomer-owned cluster-registration, decommission, and agent-lifecycle workflow health with state, age, and retry aggregates. It never queries managed Kubernetes or returns manifests, credentials, operation specifications, or raw errors.",
			SourceAstronomerDatabase, "agents", nil, max),
		readDesc("astronomer.fleet_operations.health",
			"Management-side fleet-operation orchestration health with operation/target state, backlog, age, and concurrency aggregates. It only reads Astronomer records and cannot inspect or act on managed Kubernetes.",
			SourceAstronomerDatabase, "fleet_operations", nil, max),
		readDesc("astronomer.gitops.health",
			"GitOps registration-source health with source, sync, stale, error-category, and registered-cluster counts. Repository paths, branches, credentials, and source documents are withheld.",
			SourceAstronomerDatabase, "settings", nil, max),
		readDesc("astronomer.extensions.health",
			"UI extension registry posture with compatibility, enabled, and signed-bundle verification counts. Manifests, bundle locations, checksums, and extension content are withheld.",
			SourceAstronomerDatabase, "settings", nil, max),
		readDesc("astronomer.alerting.health",
			"Management alerting posture with rule, channel, firing, acknowledged, resolved, and unbound-rule counts. Alert messages, channel configuration, and event detail are withheld.",
			SourceAstronomerDatabase, "alerts", nil, max),
		readDesc("astronomer.catalog.health",
			"Astronomer catalog ingestion and inventory health with repository sync, chart/version hydration, deprecation, curation, installed-state, and rating counts. Repository paths, chart contents, values, readmes, credentials, and managed-cluster identities are withheld.",
			SourceAstronomerDatabase, "catalog", nil, max),
		readDesc("astronomer.reconciliation.health",
			"Management reconciler bookkeeping health for repair jobs and idempotency records, including status, staleness, failure totals, and orphaned operation references. Scopes, keys, response documents, metadata, and raw errors are withheld.",
			SourceAstronomerDatabase, "monitoring", nil, max),
		readDesc("astronomer.dashboard.health",
			"Management dashboard widget and Prometheus data-source posture with type, scope, enablement, credential, and TLS-verification counts; widget specifications and URLs are withheld.",
			SourceAstronomerDatabase, "monitoring", nil, max),
		readDesc("astronomer.platform.inventory",
			"Global-administrator bounded count inventory across the Astronomer management plane so Charlie can identify configured domains and choose a specific diagnostic tool. It returns no record contents or secrets.",
			SourceAstronomerDatabase, "*", nil, max),
		readDesc("astronomer.charlie.runtime_health",
			"Product-local Charlie bridge health covering connection mode/disclosure/credential posture, sessions, approvals, receipts, triggers, findings, alert delivery, and automation-policy counts without prompts, results, or secret material.",
			SourceAstronomerDatabase, "charlie", nil, max),
		readDesc("astronomer.queue.health",
			"Background job queue health and readiness.",
			SourceManagementQueue, "monitoring", nil, max),
		readDesc("astronomer.queue.failed_tasks",
			"Paged list of failed background tasks with types; use before queue.retry_task.",
			SourceManagementQueue, "monitoring", []string{"page", "page_size", "task_type"}, max),
		readDesc("astronomer.queue.tasks",
			"Paged management-plane task inventory for one state (pending by default, active, scheduled, retry, or archived). Returns safe task identity, type purpose when known, retry counters, timing, and failure category; never payload values or raw errors. Use this to explain queue depth and identify what queued work represents.",
			SourceManagementQueue, "monitoring", []string{"state", "queue", "task_type", "page", "page_size"}, max),
		readDesc("astronomer.queue.task_get",
			"Detailed safe metadata for one management-plane task by task_id: queue/type/state, known purpose, retry/timing/orphan status, payload field names and byte count, and fixed failure category. Never returns payload values, headers, or raw error strings.",
			SourceManagementQueue, "monitoring", []string{"task_id"}, max),
		readDesc("astronomer.task_outbox.summary",
			"Summarize Astronomer's durable task-delivery outbox by lifecycle state, including stalled and dead-letter counts. This is database-owned management-plane state and never returns task payload values.",
			SourceAstronomerDatabase, "monitoring", nil, max),
		readDesc("astronomer.task_outbox.list",
			"List durable task-outbox records with safe task type, queue, delivery state, attempts, timing, payload field names, byte count, and fixed failure category. Payload values and raw errors are withheld.",
			SourceAstronomerDatabase, "monitoring", []string{"status", "task_type", "page", "page_size"}, max),
		readDesc("astronomer.task_outbox.get",
			"Inspect one durable task-outbox record by UUID and correlate its delivery attempts with the management queue. Returns payload field names only, never values or raw errors.",
			SourceAstronomerDatabase, "monitoring", []string{"outbox_id"}, max),
		readDesc("astronomer.scheduler.health",
			"Summarize durable delivery, deferred-operation, and controller-operation scheduling health, including oldest pending age and fixed failure categories without operation payload values.",
			SourceAstronomerDatabase, "monitoring", nil, max),
		readDesc("astronomer.controllers.summary",
			"Summarize Astronomer control-plane controller alerts and operation backlogs across catalog, Argo CD, tools, monitoring, logging, and workload reconcilers.",
			SourceAstronomerDatabase, "alerts", nil, max),
		readDesc("astronomer.controllers.alerts",
			"List bounded control-plane controller alerts with controller, condition, state, acknowledgement, timing, and sanitized failure category. Raw detail and potentially sensitive messages are withheld.",
			SourceAstronomerDatabase, "alerts", []string{"status", "controller", "page", "page_size"}, max),
		readDesc("astronomer.catalog.operations",
			"List durable catalog-controller operations with target identity, lifecycle state, attempt count, payload field names, timing, and fixed failure category; payload values and raw errors are withheld.",
			SourceAstronomerDatabase, "catalog", []string{"status", "page", "page_size"}, max),
		readDesc("astronomer.catalog.operation_get",
			"Inspect one durable catalog-controller operation and its sanitized event timeline by operation UUID without returning payload values or raw event messages.",
			SourceAstronomerDatabase, "catalog", []string{"record_id"}, max),
		readDesc("astronomer.argocd.operations",
			"List durable Astronomer Argo CD controller operations with lifecycle and safe diagnostic metadata. This reads product-owned records and never queries or mutates a managed cluster.",
			SourceAstronomerDatabase, "argocd", []string{"status", "page", "page_size"}, max),
		readDesc("astronomer.argocd.operation_get",
			"Inspect one Astronomer-owned Argo CD operation and sanitized event timeline. Manifests, repository credentials, managed-cluster resources, payload values, and raw messages are withheld.",
			SourceAstronomerDatabase, "argocd", []string{"record_id"}, max),
		readDesc("astronomer.tools.operations",
			"List durable tool-controller operations recorded by Astronomer with safe lifecycle metadata only; no managed-cluster request or operation payload values are returned.",
			SourceAstronomerDatabase, "catalog", []string{"status", "page", "page_size"}, max),
		readDesc("astronomer.tools.operation_get",
			"Inspect one Astronomer-owned tool operation and sanitized event timeline without exposing managed-cluster contents, operation payload values, or raw messages.",
			SourceAstronomerDatabase, "catalog", []string{"record_id"}, max),
		readDesc("astronomer.monitoring.operations",
			"List durable monitoring-controller operations recorded by Astronomer with safe lifecycle metadata and no query credentials, payload values, or managed-cluster access.",
			SourceAstronomerDatabase, "monitoring", []string{"status", "page", "page_size"}, max),
		readDesc("astronomer.monitoring.operation_get",
			"Inspect one Astronomer-owned monitoring operation and sanitized event timeline without exposing backend credentials, operation payload values, or raw messages.",
			SourceAstronomerDatabase, "monitoring", []string{"record_id"}, max),
		readDesc("astronomer.logging.operations",
			"List durable logging-controller operations recorded by Astronomer with safe lifecycle metadata and no output credentials, payload values, or managed-cluster access.",
			SourceAstronomerDatabase, "logging", []string{"status", "page", "page_size"}, max),
		readDesc("astronomer.logging.operation_get",
			"Inspect one Astronomer-owned logging operation and sanitized event timeline without exposing log contents, output credentials, payload values, or raw messages.",
			SourceAstronomerDatabase, "logging", []string{"record_id"}, max),
		readDesc("astronomer.workloads.operations",
			"List durable workload-controller operations recorded by Astronomer with safe lifecycle metadata only and no managed-cluster Kubernetes request or payload values.",
			SourceAstronomerDatabase, "workloads", []string{"status", "page", "page_size"}, max),
		readDesc("astronomer.workloads.operation_get",
			"Inspect one Astronomer-owned workload operation and sanitized event timeline without querying managed-cluster Kubernetes or returning operation payload values or raw messages.",
			SourceAstronomerDatabase, "workloads", []string{"record_id"}, max),
		readDesc("astronomer.argocd.self_management_status",
			"Argo CD self-management Application sync/health status for the Astronomer install.",
			SourceManagementArgo, "argocd", nil, max),
		readDesc("astronomer.migrations.status",
			"Schema migration version, dirty flag, and expected version.",
			SourceAstronomerDatabase, "settings", nil, max),
		readDesc("astronomer.backups.status",
			"Management-plane backup/drill status summaries (no credentials).",
			SourceAstronomerDatabase, "backups", nil, max),
		readDesc("astronomer.tls.status",
			"TLS certificate status for management endpoints.",
			SourceAstronomerServer, "security", nil, max),
		readDesc("astronomer.observability.health",
			"Bounded observability via fixed query_template enum: availability|latency|errors|saturation and optional range 5m|15m|1h|6h. Not free-form PromQL.",
			SourceAstronomerServer, "monitoring", []string{"query_template", "range"}, max),
		readDesc("astronomer.alert.list",
			"List product alerts filtered by status/severity with paging.",
			SourceAstronomerDatabase, "alerts", []string{"status", "severity", "page", "page_size"}, max),
		readDesc("astronomer.alert.get",
			"Get one product alert by alert_id UUID: severity, status, summary fields, and timestamps (no raw secrets).",
			SourceAstronomerDatabase, "alerts", []string{"alert_id"}, max),
		readDesc("astronomer.audit.recent_changes",
			"Recent product audit changes (resource_type/resource_id/since/limit). Content-bounded; not full log dumps.",
			SourceAstronomerDatabase, "audit_logs", []string{"resource_type", "resource_id", "since", "limit"}, max),
		readDesc("astronomer.audit.search",
			"Search the management-plane audit trail by exact resource, action, result class, source, correlation ID, and bounded lookback with pagination. Detail JSON, actors, paths, IPs, user agents, and managed-cluster evidence are withheld.",
			SourceAstronomerDatabase, "audit_logs", []string{"resource_type", "resource_id", "action", "action_class", "result", "source", "correlation_id", "since", "page", "page_size"}, max),
		readDesc("astronomer.catalog.repositories",
			"Configured Astronomer Helm catalog repositories with safe scheme/host endpoint, type, enabled/default/project scope, authentication presence, last attempt/success, and fixed failure category. Credentials, URL paths/query/userinfo, auth configuration, and raw errors are withheld. Correlate this with catalog:sync queue failures.",
			SourceAstronomerDatabase, "catalog", []string{"page", "page_size"}, max),
		readDesc("astronomer.agent_fleet.summary",
			"Fleet-wide agent connection summary (connected/stale counts). Uses management-plane database telemetry only; never proxies into customer clusters.",
			SourceAstronomerDatabase, "agents", []string{"stale_after_seconds"}, max),
		readDesc("astronomer.agent_fleet.list",
			"List registered cluster agents with environment/region/state filters.",
			SourceAstronomerDatabase, "agents", []string{"environment", "region", "state", "page", "page_size"}, max),
		readDesc("astronomer.agent_fleet.get",
			"One cluster agent record by cluster_id (identity, versions, connection state).",
			SourceAstronomerDatabase, "agents", []string{"cluster_id"}, max),
		readDesc("astronomer.agent_fleet.connection_history",
			"Connection history for one cluster agent (disconnects, auth errors).",
			SourceAstronomerDatabase, "agents", []string{"cluster_id", "since", "limit"}, max),
		readDesc("astronomer.agent_fleet.upgrade_status",
			"Agent upgrade desired vs installed state for one cluster_id.",
			SourceAstronomerDatabase, "agents", []string{"cluster_id"}, max),
		readDesc("astronomer.agent_fleet.ingestion_health",
			"Agent ingestion/command pipeline health for one cluster_id (audit/metrics/state ingestion).",
			SourceAstronomerDatabase, "agents", []string{"cluster_id"}, max),
		readDesc("astronomer.tunnel.health",
			"Management tunnel hub health and ownership.",
			SourceAstronomerServer, "agents", nil, max),
		readDesc("astronomer.tunnel.replica_distribution",
			"Tunnel replica distribution across server replicas.",
			SourceAstronomerServer, "agents", nil, max),
		readDesc("astronomer.tunnel.recent_errors",
			"Recent tunnel errors with optional connection_id filter.",
			SourceAstronomerServer, "agents", []string{"since", "limit", "connection_id"}, max),
	}
}

func WriteCapabilityCatalog() []CapabilityDescriptor {
	return []CapabilityDescriptor{
		writeDescWithTimeout("astronomer.management.workload_restart",
			"Restart one mutable management Deployment (server|worker|frontend). Use when the user asks to restart a management component. resource_id must be a session-scoped resource id from product context (default install scope is 'local'); workload=deployment/<name>; operation_id=any fresh opaque correlator (product replaces it with the trusted action id). Never ask the user for tool names or these ids.",
			SourceManagementKubernetes, "workloads", []string{"resource_id", "workload", "operation_id"}, false, 120),
		writeDescWithTimeout("astronomer.management.workload_rollout",
			"Trigger a rollout restart of one mutable management Deployment. resource_id=session-scoped id (default 'local'); workload=deployment/<name>; operation_id=any fresh opaque correlator.",
			SourceManagementKubernetes, "workloads", []string{"resource_id", "workload", "operation_id"}, false, 120),
		writeDesc("astronomer.management.workload_scale",
			"Scale a mutable management Deployment to replicas in [2,20]. Use when the user asks to scale a management workload. resource_id=session-scoped id from product context (default install scope is 'local'); workload=deployment/<name> e.g. deployment/astronomer-worker; replicas=N; operation_id=any fresh opaque correlator (product binds trusted action id). Do not ask the user for resource_id or operation_id.",
			SourceManagementKubernetes, "workloads", []string{"resource_id", "workload", "replicas", "operation_id"}, false),
		writeDesc("astronomer.argocd.self_management_sync",
			"Request Argo CD sync of the self-management Application with exact human approval. A sync can change the running Astronomer revision, so v1 never admits it as unattended automation. resource_id=session-scoped id (default 'local'); application name; operation_id=any fresh opaque correlator.",
			SourceManagementArgo, "argocd", []string{"resource_id", "application", "operation_id"}, false),
		writeDesc("astronomer.queue.retry_task",
			"Retry one failed allowlisted queue task by task_id (auto-eligible when mode=auto and centrally allowlisted). resource_id=session-scoped id; task_id from failed_tasks; operation_id=any fresh opaque correlator.",
			SourceManagementQueue, "monitoring", []string{"resource_id", "task_id", "operation_id"}, true),
		writeDesc("astronomer.task_outbox.retry_delivery",
			"Requeue one failed or dead durable task-delivery record by outbox_id. Approval is always required; delivered, pending, and in-flight records are refused. resource_id=session-scoped id and operation_id is a fresh opaque correlator.",
			SourceAstronomerDatabase, "monitoring", []string{"resource_id", "outbox_id", "operation_id"}, false),
		writeDesc("astronomer.management.run_job",
			"Run an owned CronJob-derived maintenance Job: management-plane-backup or restore-drill. resource_id=session-scoped id (default 'local'); job enum; operation_id=any fresh opaque correlator.",
			SourceManagementKubernetes, "workloads", []string{"resource_id", "job", "operation_id"}, false),
		writeDescWithTimeout("astronomer.tunnel.restart_component",
			"Restart tunnel-related management component server|worker. resource_id=session-scoped id; component; operation_id=any fresh opaque correlator.",
			SourceManagementKubernetes, "agents", []string{"resource_id", "component", "operation_id"}, false, 120),
	}
}

func readDesc(name, description string, source CapabilitySource, resource string, fields []string, maxBytes int) CapabilityDescriptor {
	return CapabilityDescriptor{
		Name: name, Description: description, SchemaVersion: "1",
		Effect: EffectRead, Risk: "low", TargetBounds: "astronomer_management_plane_only", Impact: "none",
		Reversibility: "not_applicable", Rollback: "not_applicable", Source: source, RBACResource: resource,
		RBACVerb: "read", AcceptedFields: fields, MaxResponseBytes: maxBytes, TimeoutSeconds: 10,
	}
}

func writeDesc(name, description string, source CapabilitySource, resource string, fields []string, auto bool) CapabilityDescriptor {
	return CapabilityDescriptor{
		Name: name, Description: description, SchemaVersion: "1",
		Effect: EffectWrite, Risk: "medium", TargetBounds: "allowlisted_astronomer_management_component_only",
		Impact: "bounded_management_plane_change", Reversibility: "adapter_declared", Rollback: "stop_and_operator_reconcile",
		Source: source, RBACResource: resource,
		RBACVerb: "update", AcceptedFields: fields, MaxResponseBytes: 64 << 10,
		TimeoutSeconds: 30, Destructive: false, AutoEligible: auto, Idempotent: true,
		RequiresPrecondition: true, RequiresVerification: true,
	}
}

func writeDescWithTimeout(name, description string, source CapabilitySource, resource string, fields []string, auto bool, timeoutSeconds int) CapabilityDescriptor {
	descriptor := writeDesc(name, description, source, resource, fields, auto)
	descriptor.TimeoutSeconds = timeoutSeconds
	return descriptor
}
