- op: add
  path: /metadata/labels/pod-security.kubernetes.io~1enforce
  value: restricted
- op: add
  path: /metadata/labels/pod-security.kubernetes.io~1audit
  value: restricted
- op: add
  path: /metadata/labels/pod-security.kubernetes.io~1warn
  value: restricted
- op: add
  path: /metadata/labels/pod-security.kubernetes.io~1enforce-version
  value: v1.33
- op: add
  path: /metadata/labels/pod-security.kubernetes.io~1audit-version
  value: v1.33
- op: replace
  path: /metadata/labels/pod-security.kubernetes.io~1warn-version
  value: v1.33
